### ISSUE TITLE
Speaking with Fists Fisticuffs fighting style

### ISSUE THREAD

**Issue by Dragon5e** [Sklore/HL_DD_5e_Colab#1002]
Fisticuffs c5CFisticf

foreach pick in hero from BaseWep where "IsWeapon.wUnarmed"
eachpick.field[wAttBonus].value += 0
eachpick.field[wDamBonus].value += 2
nexteach

Added this from looking at those tattoos. Place in eval.

**Comment by Fenris447** [comment]
Donezo. Will be in release 3.5
