### ISSUE TITLE
Werebear AC

### ISSUE THREAD

**Issue by Dragon5e** [Sklore/HL_DD_5e_Colab#1005]
I did check to see if the were get a bonus to AC in hybrid/animal form. After looking at raWBeShape this line 
  hero.child[mNatural].field[arAC].value = 1 did not quite work for the werebear monk I tried. Think the problem might be the AC calc of Nat armor + DEX. Any other AC calc will stop that. I thought about comment out that line and add this 
~Add +1 to hybrid/animal form
hero.childfound[ArmorClass].field[Bonus].value += 1

It did not add a 1 in human form but did in hybrid/animal form. Checked with monk AC and also leather armor and shield.

**Comment by Dragon5e** [comment]
Didn't check the other wereraces but the bonus should work the same way. Heh didn't care to try a wererat.

**Comment by Fenris447** [comment]
Did you add monk levels to the existing werebear? I'm not sure it's supposed to work like that either way. Though this is spurring me to update/fix all the were____ creatures. I'm also going to check and see if we have adjustments for applying lycantrhopy to actual PC's.

**Comment by Fenris447** [comment]
I'm unsure whether the natural armor should really stack with other armors, or if it should be treated as a different calculation and therefore a different option from other armor calcs. Your way makes it stack; the original way didn't,

I'm going to leave the original the way it is. But I have built adjustments to add each type of lycanthropy to a character, and it uses your way.
