### ISSUE TITLE
Orphaned minions

### ISSUE THREAD

**Issue by Dragon5e** [Sklore/HL_DD_5e_Colab#1007]
COM_5ePack_TOB is full of orphaned minion. I take it they're minion tags that is pointing to minions that no longer exist. I found out by trying to pull a copy and it could not find it.

**Comment by Fenris447** [comment]
They're actually not orphaned. They are for anyone who bought the Tome of Beasts data file from LWD. I have it, and just tested these minions to see they're working as intended.
