### ISSUE TITLE
Genie warlock 9th level spell

### ISSUE THREAD

**Issue by Dragon5e** [Sklore/HL_DD_5e_Colab#1010]
I'd been reading articles on the Genie Warlock and it seem that all genie warlocks do get the 9th level spell wish.

simple fix 
doneif (islinkage[table] = 0)

      perform linkage[table].assign[ClsAllowSp.spDeteEvil]
      perform linkage[table].assign[ClsAllowSp.sp5CPhantF]
      perform linkage[table].assign[ClsAllowSp.spCreaFood]
      perform linkage[table].assign[ClsAllowSp.spPhanKill]
      perform linkage[table].assign[ClsAllowSp.spCreation]
      perform linkage[table].assign[ClsAllowSp.spWish]
followed by the rest of the eval script

**Comment by Dragon5e** [comment]
I have a small request here. Stuff can be stored in it so can we make it a container?

**Comment by Fenris447** [comment]
Forgot to comment on the Genie's Vessel thing. Done. :D
