### ISSUE TITLE
Add Inertial Armor adjustment for Psionic Handbook?

### ISSUE THREAD

**Issue by Dragon5e** [Sklore/HL_DD_5e_Colab#1015]
I adapted mage armor to do the inertial armor adjustment for Psionic Handbook. 
>   <thing id="pInAr" name="Inertial Armor" description="This set your base AC to 14 + Dex if you are wearing no armor and you gain resistance to force." compset="InPlay" summary="AC 14 + DEX" uniqueness="unique">
    <fieldval field="pDuration" value="8 Hours"/>
    <usesource source="5eHBPsiHCP"/>
    <tag group="SpInfo" tag="spMageArmo" name="Mage Armor" abbrev="Mage Armor"/>
    <tag group="Helper" tag="AdjInfo" name="Adjustment Information" abbrev="Adjustment Information"/>
    <tag group="Helper" tag="NoIncr" name="NoIncr" abbrev="NoIncr"/>
    <tag group="OthAdjCat" tag="UserBot3rd" name="User 3rd Bottom Group" abbrev="User 3rd Bottom Group"/>
    <eval phase="PreAttr" index="2"><![CDATA[     doneif (hero.tagcount[Hero.EquipArmor] <> 0)
     perform hero.assign[DamageRes.dtForce]]]></eval>
    <eval phase="PreAttr"><![CDATA[
      ~ If we're not enabled, get out now
      doneif (field[pIsOn].value = 0)
      doneif (hero.tagcount[Hero.EquipArmor] <> 0)
~      hero.childfound[ArmorClass].field[tACBase].value = 13
      #baseac[4,"Inertial Armor"]]]></eval>
    </thing>

**Comment by Fenris447** [comment]
I couldn't find anything for this in the Psionics Handbook. Did you mean the Mystic UA? Inertial Armor is in there. I set up an adjustment for that, and will include it in 3.5.
