### ISSUE TITLE
Mage armor keep stacking with other base ac

### ISSUE THREAD

**Issue by Dragon5e** [Sklore/HL_DD_5e_Colab#1017]
Changed the mage armor to include base ac properly. 

[
[custom.txt](https://github.com/Sklore/HL_DD_5e_Colab/files/6679771/custom.txt)
](url)

**Comment by Dragon5e** [comment]
Mage armor kept stacking with other base ac so I see thing like 11 base AC + mage armor = 14 base AC. Also mage armor stack with natural armor when it shouldn't. Think part of the problem is that there's no CALC AC Natural code. If there was the program could compare Nat AC + dex to Base AC + dex like it does with other kind of AC.

**Comment by Fenris447** [comment]
I think I have this fixed. I have it now set to add an ability that itself has a full AC calculation. This should alleviate a lot of the issues with it stacking with other things. I'm trying to comprehensively address all these AC issues together in the next release.
