### ISSUE TITLE
Dragonborn 2 dragonhide feat 

### ISSUE THREAD

**Issue by Dragon5e** [Sklore/HL_DD_5e_Colab#1018]
The base AC one want to stack with mage armor and the bonus +1 one really should do it for unarmored PC. 
[custom.txt](https://github.com/Sklore/HL_DD_5e_Colab/files/6679782/custom.txt)

**Comment by Dragon5e** [comment]
Also sent in the fix for Mage Armor. Now the Base AC feat will properly compare to mage armor adjustment.

**Comment by Fenris447** [comment]
I've fixed this the same way I did Mage Armor in issue #1017. Expect it next release.
