### ISSUE TITLE
Request to add magic robes. 

### ISSUE THREAD

**Issue by Dragon5e** [Sklore/HL_DD_5e_Colab#1020]
I created magic robes +1 ,+2 and +3 robes. dunno why the all the unarmored wearers don't have armors, I'm aware of the power of free bonuses so I made all of these to be base armor of 11, 12, and 13. 
[custom.txt](https://github.com/Sklore/HL_DD_5e_Colab/files/6679792/custom.txt)

**Comment by Fenris447** [comment]
This is basically a homebrew request, as simple as it may be. But since it's so simple, I'll probably squeeze it into release 3.4.

**Comment by Fenris447** [comment]
I've added these in as part of the next release. They'll be available under the "Various Homebrew Options" source.
