### ISSUE TITLE
Tortle natural AC implementation is a problem

### ISSUE THREAD

**Issue by Dragon5e** [Sklore/HL_DD_5e_Colab#1021]
The problem with Tortle  implmentation of 10 + 7 natural AC is that it can stack with mage armor. I fixed mage armor but this affect every base AC. They all stack with Tortle. 10 + 7 natural AC + say inertial armor 14 base ac gives 14 + 7 -21. Not kosher I don't think. I can't figure out a better way except to request an CALC AC of Nat Armor so I can specify  the AC should be Dex + Nat armor in the options. After thinking about it I set Tortle AC to be base 17. No way to specify that it's natural now but it stop all that stacking with base AC. 
[custom.txt](https://github.com/Sklore/HL_DD_5e_Colab/files/6679802/custom.txt)
This show what I mean about mage armor stacking with NPC Tortle nat ac.
![image](https://user-images.githubusercontent.com/84625721/122627738-0ba54c00-d077-11eb-8120-ce3fd696a1af.png)

**Comment by Fenris447** [comment]
I think I've got this fixed in the revised Tortle for MPMotMM. It uses the standard AC calcs, and disallows the use of any armor. Together with the fix to Mage Armor in #1017, we should be good.
