### ISSUE TITLE
Joining as a contributor

### ISSUE THREAD

**Issue by digitalshadowhawk** [Sklore/HL_DD_5e_Colab#1024]
I've recently made the switch from Pathfinder to 5e, and use HeroLab, so figured I'd at least try to give back to the community. I initially took a crack at Van Richten's Guide, but missed that fenris had already been working on it, so submitted what I have that wasn't completed yet, but I think for now I'll stick to work on the Unearthed Arcana sources, as they're a bit of a mess, are missing several releases, and are somewhat inconsistent in the Unique ID naming conventions.

**Comment by Fenris447** [comment]
I've been away for quite a bit (personal stuff) but I'm getting caught back up on my VRGtR work. I'm really excited to take a look at your work on the Dark Gifts! And if you are willing to get the UA stuff done, that would be amazing. Especially the stuff that's looking at a release, like the Dragon and Multiverse things. If you need any help, let me know.
