### ISSUE TITLE
Artificer Cantrip spell-list incomplete

### ISSUE THREAD

**Issue by MyWorldNetwork** [Sklore/HL_DD_5e_Colab#1032]
The cantrip 'Fire Bolt' is not included despite being a spell available to Artificers

**Comment by Fenris447** [comment]
Ah I think this might be a product of a fix I made that replaces the old version of FireBolt with a new one. I'll get the fix up in the next release.

**Comment by MyWorldNetwork** [comment]
Glad to be of service, kinda!

Is there anything I can do as a short term fix until the next release or am I best just to wait?

**Comment by Fenris447** [comment]
You definitely helped by reporting it! I would have had no idea, and now I know to watch for this in future, similar situations. 

There are two different workarounds you can choose from:

1. Go to the Adjustments tab and add the one titled "Add Single Spell to Class/Race." Select Artificer from the first drop-down, and Fire Bolt from the second. That'll add it back into your spell list.
2. Open the Editor, and open the PHB - Spells.user file. Go to Class->Spell->Fire Bolt. Click the Classes button, find Artificer, check it, and click OK. Click the "Test Now!" button at the top left, and save the modified PHB Spells file.

**Comment by MyWorldNetwork** [comment]
#1 works just fine. #2, which i tried at first, results in;
![image](https://user-images.githubusercontent.com/14790507/140192726-20c462a7-8ba9-4cf0-b2ad-44efd83ae3f4.png)
