### ISSUE TITLE
Error Replacing 3rd level Clockwork Magic Spell with 'Counterspell'

### ISSUE THREAD

**Issue by Lurker37** [Sklore/HL_DD_5e_Colab#1033]
If you try to select Counterspell as a replacement spell for a 3rd level Clockwork Magic spell, there is an error and the full spell list is displayed instead of just the replacement spells chosen.

![ClkWrkSplCounterspellError](https://user-images.githubusercontent.com/38503303/140538746-a9266cdc-7fa6-478a-a6e4-35143e59698d.png)
![ClkWrkSplCounterspellErrorSpellList](https://user-images.githubusercontent.com/38503303/140538963-6c8575cd-f875-4c99-8468-4c5ee2ede2b3.png)

Steps to reproduce.

Create a 6th level Sorcerer with the "Clockwork Soul" Sorcerous Origin 

Go to the Clockwork Spells tab

Select 'Known' on the dropdown for all spells except the last one (3 - Protection from Energy)

For 'Protection from Energy', select 'Replaced' in the dropdown. A second dropdown appears.

From the second dropdown, select 'Counterspell'

Click on 'Add new Replacement Clockwork Spells (1 Left)'

You get the error message " Syntax error in dynamic 'candidate' tag expression"

A popup list of all spells of all levels form Sorceror, Warlock and Wizard appears.

Instead of a popup list of the replacement spells you selected, you get the full spell list.

Almost any spell selected from this list, of any level, will show up on the Sorcerer Spells tab as a clockwork spell. The exceptions are "Counterspell" and "Mage's Private Sanctum", neither of which will appear on the Sorcerer Spells tab at all. 

Expected Result: There is no error, the popup list only displays the replacement spells you have selected, and selecting them from this list causes them to show on the Sorcerer Spells tab as clockwork spells.

The same error occurs when replacing a 4th level spell with "Mage's Private Sanctum".

**Comment by Fenris447** [comment]
This was a really interesting one, but I think I got it solved. Counterspell is one of the spells that was originally in the 5e SRD pack from Lone Wolf, but was replaced by another version in the Community Pack. Though the replacement is total for almost everything, the code used for this feature pulls both the thingid for the original version and the replacement. Putting both of those into the spell-choosing code without any special separator causes the error.

I have a fix that'll account for these replacements, as this won't be limited to Counterspell, but _any and all_ replaced spells either now or if/when they're replaced in the future.

So thanks for the report! I learned something and it helps future-proof a lot!
