### ISSUE TITLE
TCoE: Druidic Warrior ranger subclass

### ISSUE THREAD

**Issue by d3caf** [Sklore/HL_DD_5e_Colab#1036]
I'm not seeing Druidic Warrior as an option for a ranger subclass. Am I missing it somewhere? I didn't see it in the source either. I'd be happy to work on adding it if that'd be helpful.

**Comment by Fenris447** [comment]
Wow. I have no idea how I missed this, as I was positive I had added that. There's already a version from UA, so it'll be a relatively easy add for me to put in the TCoE version.

**Comment by Fenris447** [comment]
Added. Will be in the next release. Thanks again for the catch!
