### ISSUE TITLE
DMG: Necklace of Prayer Beads

### ISSUE THREAD

**Issue by SilverbackPrime** [Sklore/HL_DD_5e_Colab#1037]
Something is off with how the item calculates the number of available beads when set to max value.

When the item is set to 3, 4, or 5 beads in the Magic Item tab, then the user is able to select the proper number of beads in the Necklace configuration tab.

However, if the item is set to 6 beads in the Magic Item tab, then the user is unable to select **_any_** number of beads greater than 0 in the Necklace configuration tab without a validation error.

See below screenshots for the results of each setting for the necklace:

![Necklace_of_Prayer_Beads_6](https://user-images.githubusercontent.com/6117007/145422411-03ec95a9-9f68-48b7-a26a-ae4d43f035ea.png)
![Necklace_of_Prayer_Beads_5](https://user-images.githubusercontent.com/6117007/145422425-b3b132f8-b2d1-4a20-bee1-17febf81cb11.png)
![Necklace_of_Prayer_Beads_4](https://user-images.githubusercontent.com/6117007/145422438-a142d99a-1ea0-43ed-80cb-662be6dd6d1a.png)
![Necklace_of_Prayer_Beads_3](https://user-images.githubusercontent.com/6117007/145422457-b69a793b-6a72-4f7f-a7b0-75d3fc12f223.png)
.

**Comment by Fenris447** [comment]
I found this issue. Looks like I made a dumb. Thanks for reporting it! The fix will be included in the next release.

If you want to fix it in the mean time, you can open it in the editor. It's the file: COM_5ePack_DMG - Equipment.user. Go to the General -> Configurable tab, select the Necklace, and click the Eval Scripts button. Change "    elseif (focus.field[usrIndex].value = 4) then" to "    elseif (focus.field[usrIndex].value = 3) then"

Save that, click Test Now, and you should be good to go.
