### ISSUE TITLE
Linguist Feat's +1 INT looks weird.

### ISSUE THREAD

**Issue by Fenris447** [Sklore/HL_DD_5e_Colab#1043]
Making issue for tracking purposes. Fix is in the thread. Review similar feats for the same issue.

http://forums.wolflair.com/showthread.php?t=66792

**Comment by asvaldson** [comment]
PHB Feats with the same Effect
Heavily Armored - It's targeting .field[Bonus] instead of .field[aStartMod]
Keen Mind - Same script string as Linguist

**Comment by Fenris447** [comment]
Thanks for the help! I checked virtually every other feat in the pack (release and UA, no 3rd-party ones) and made sure they're all clean. Fix is uploaded for next release.
