### ISSUE TITLE
No Flaws, Bonds, Ideals or Traits with SCAG Backgrounds

### ISSUE THREAD

**Issue by OregonPinkRose** [Sklore/HL_DD_5e_Colab#106]
There are no Flaws, Bonds, Ideals, or Traits linked to the SCAG Backgrounds.
The only choice is for a custom one.

**Comment by Sklore** [comment]
They are there. 

Do you have the PHB Community Pack enabled? Because the SCAG backgrounds make use of the PHB Flaws, Bonds Ideals and Personality Traits you need to enable both packs in order to see all the options.

**Comment by OregonPinkRose** [comment]
Oh, interesting. Sorry. I'm working on filling in some place holder material, and must not have had the PHB Background file loaded at the time. Good to know.
