### ISSUE TITLE
Validation error for Call to the Wave

### ISSUE THREAD

**Issue by steggy53** [Sklore/HL_DD_5e_Colab#1060]
The Water Genasi racial trait Call to the Wave throws a validation error that the character can't cast a spell over 0th level.

Deleting the bootstrap from Call to the Wave in the racial special tab, and adding the innate spell to the Water Genasi subrace seems to fix the validation error.

**Comment by Fenris447** [comment]
Okay, looks like it was just Fire and Water Genasi that had this issue. I've got it fixed, along with a host of Source issues I found along the way.
