### ISSUE TITLE
Eldritch Adept does not boost stat

### ISSUE THREAD

**Issue by Dragon5e** [Sklore/HL_DD_5e_Colab#1064]
f5CEldAdp does not boost stat so I copied the code from Fey Touched to make it work.

      ~ If we're disabled, do nothing & 
      doneif (tagis[Helper.Disable] = 1)

      if (field[usrIndex].value = 0) then
        hero.child[aINT].field[aStartMod].value += 1
        perform hero.childfound[cfg5CFeyTch].assign[StandardDC.aINT]
      elseif (field[usrIndex].value = 1) then
        hero.child[aWIS].field[aStartMod].value += 1
        perform hero.childfound[cfg5CFeyTch].assign[StandardDC.aWIS]
      elseif (field[usrIndex].value = 2) then
        hero.child[aCHA].field[aStartMod].value += 1
        perform hero.childfound[cfg5CFeyTch].assign[StandardDC.aCHA]
      endif

**Comment by Fenris447** [comment]
There's nothing in the feat's description that says it's supposed to boost the stat.
