### ISSUE TITLE
Ring of Swimming

### ISSUE THREAD

**Issue by Dragon5e** [Sklore/HL_DD_5e_Colab#1066]
There's any number of items in magic tab with no movement speed coded. It is quite difficult. For one I'm not sure if the ring tab in editor can even recognize equipped tag. As I click on the equipped pick in inventory it display swim speed when ring is toggled off and vice versa. However you go to adjustments and add a speed, it correctly display the swim speed. The Speed, Special adjustment cannot adjust the swim speed. However the Haste Adjustment can.  I'm getting a headache here. I'll list the code here. Gonna need to figure this out before I can tackle things like Gloves of Arachnidia.

[COM+5ePack-Custom.user.txt](https://github.com/Sklore/HL_DD_5e_Colab/files/8931263/COM%2B5ePack-Custom.user.txt)

**Comment by Dragon5e** [comment]
I see what some of the issue is. I loaded the original code in, irS5CSwim. It bootstraps the swim speed in. It work but it share the same flaky behavior on equipping the ring. I'm not sure what's going on with the ring tab in editor.

**Comment by Dragon5e** [comment]
After experimenting more I discover bootstraps speed cannot be adjusted by speed adjustments. Only thing that can seem to be the haste adjustment.

**Comment by Dragon5e** [comment]
<thing id="pAllSpeed" name="All Speed, Special Bonus" description="Select this adjustment to modify all  of the character&apos;s special movement rates, such as flight or swimming by bonus movement. Put the desired bonus in Duration and it will add to it. ." compset="InPlay">
    <fieldval field="pMinimum" value="0"/>
    <fieldval field="pDuration" value="0"/>
    <tag group="Helper" tag="AdjInfo"/>
    <eval phase="PostAttr" priority="10000"><![CDATA[      ~ If we're not enabled, get out now
      doneif (field[pIsOn].value = 0)

      ~ Apply the speed
if (#value[xBurrow] > 0) then
        #value[xBurrow] += field[pAdjust].value + field[pDuration].text
endif  
if (#value[xClimb] > 0) then
        #value[xClimb] += field[pAdjust].value + field[pDuration].text
endif  
if (#value[xFly] > 0) then
        #value[xFly] += field[pAdjust].value + field[pDuration].text
endif  
if (#value[xSwim] > 0) then
      #value[xSwim] += field[pAdjust].value + field[pDuration].text
endif]]></eval>
    </thing>

**Comment by Dragon5e** [comment]
Bit of a clarification here. Bonus from longstrider or monk either go in pAdjust or pDuration. Swim speed from ring get boosted by the total amount of boost in this adjustment. The speed boost adjustment as found in adjustment menu is not likely to affect ring of swimming.

**Comment by Fenris447** [comment]
You're running into a problem with Hero Lab and how it handles implementing items' code when attuned and/or equipped. It's the top of our known issues page: https://github.com/Sklore/HL_DD_5e_Colab/wiki/7.-Known-Issues

Also, you don't have to click pAdjust 40 times. You can click the actual number and type in the number you want. Unless you're on an iPad; I have no idea if you can do it there.

I'll get the ring itself fixed to just provide the 40 ft. swim speed. Adjustments are great, but we want to keep things as simple as possible for the end user.

**Comment by Fenris447** [comment]
Oh, I just checked the ring and it's working fine (aside from the regular issue with equipping items). All the player has to do to get the swim speed to work once equipping the ring is just change anything else on the character. It kicks Hero Lab into processing the whole character again, and applies the swim speed properly.
