### ISSUE TITLE
Whew now I can show the custom background that can also give a feat

### ISSUE THREAD

**Issue by Dragon5e** [Sklore/HL_DD_5e_Colab#1070]
Considering that 5E now has Dragonlance 5e that can give a feat on backgrounds. There's also Baldur Gate 3 loosely based on 5e and a mod grant feats in background. The program just don't allow giving any feats at level 1 but they found a way with backgrounds. 
[custom.txt](https://github.com/Sklore/HL_DD_5e_Colab/files/8934627/custom.txt)

**Comment by Fenris447** [comment]
This is helpful, but is technically homebrew, since there's nothing official for _5e_ that says custom backgrounds automatically get a feat. So I'm shelving it. But hang onto it, so you'll have a route to add it for OneD&D.
