### ISSUE TITLE
Slippers of Spider Climbing

### ISSUE THREAD

**Issue by Dragon5e** [Sklore/HL_DD_5e_Colab#1074]
A small change. I added in the climb speed.
[custom.txt](https://github.com/Sklore/HL_DD_5e_Colab/files/8969983/custom.txt)

**Comment by Fenris447** [comment]
Another good catch. I did use my go-to scripting for adding special speed equivalent to walking (as yours would override an existing, faster climbing speed):

`     hero.childfound[xClimb].field[abValue].value = maximum(hero.childfound[Speed].field[tSpeedMod].value,hero.childfound[xClimb].field[abValue].value)`

It runs at Final 10001.
