### ISSUE TITLE
Tortle natural AC

### ISSUE THREAD

**Issue by Dragon5e** [Sklore/HL_DD_5e_Colab#1075]
The racial special ra5CMPTrtNAr look really unusual to me. It had AC Calc 7 + 2 dex + 5 shield -2 unarmored AC. I swapped in the code from the other one you had. ra5CNaArTo.
[custom.txt](https://github.com/Sklore/HL_DD_5e_Colab/files/8971868/custom.txt)

**Comment by Dragon5e** [comment]
Decide to look at the NPC Tortles.
r5CTortl
r5CTortleR
r5CTorDruR
r5CTorDr
Not sure if it's my files or not. I updated all these with racial bootstrap ra5CNaArTo. The AC is now correct but with an oddity. It show 7 + 2 DEX - 2 unarmored defense. Which is weird because the 2 of the players Tortle do not display this behavior. Think I'm missing some interaction somewhere.

**Comment by Fenris447** [comment]
So the reason the MPMotM Tortle works the way it does is the way HLC handles AC calculations. When it's set as a standard AC Calc ability, HLC treats that as an _option_. If they have a high DEX, that can override the Natural Armor calculation. The way this Tortle's AC is written means that cannot happen. So instead we have to manually calculate out the AC, subtracting the DEX.
