### ISSUE TITLE
Bug Report - Clockwork Sorcerer

### ISSUE THREAD

**Issue by asvaldson** [Sklore/HL_DD_5e_Colab#1078]
The Description for Clockwork Magic states you can switch spells for a divination or enchantment spell, but the official material says 

Clockwork Magic
TCE p68
[–]
1st-level Clockwork Soul feature

You learn additional spells when you reach certain levels in this class, as shown on the Clockwork Spells table. Each of these spells counts as a sorcerer spell for you, but it doesn't count against the number of sorcerer spells you know.

Whenever you gain a sorcerer level, you can replace one spell you gained from this feature with another spell of the same level. The new spell must be an [**abjuration or a transmutation spell from the sorcerer, warlock, or wizard spell list**](https://5e.tools/spells.html#blankhash,flstclass:sorcerer=1~warlock=1~wizard=1,flstschool:a=1~t=1,flstlevel:1=1~2=1~3=1~4=1~5=1).

**Comment by Fenris447** [comment]
I checked and the feature is *functioning* properly. It was just a typo in the description. It'll be fixed for the next patch.
