### ISSUE TITLE
Finally adjusted Fist Wraps and Brass Knuckles 

### ISSUE THREAD

**Issue by Dragon5e** [Sklore/HL_DD_5e_Colab#1079]
For the longest time I could not see why Fist Wraps and Brass Knuckles could not be buffed as the unarmed strike in store was. Yes I added one to store to make it easy on me to add to a minion. What I learned is I cannot extend the original name of wraps and knuckles. I had to use their new name to use in extend.
[custom.txt](https://github.com/Sklore/HL_DD_5e_Colab/files/9015478/custom.txt)

**Comment by Dragon5e** [comment]
Fist Wraps and Brass Knuckles now look like all unarmed strikes and natural weapons  After thinking about it made the Brass Knuckles Finesse as that what it take for a rogue to sneak attack with it.

**Comment by Fenris447** [comment]
Without access to the actual text, I can't verify or test any of this. Are the weapons considered Natural weapons? If not, adding the BaseNatWep tag isn't appropriate. And I also don't see why we need the custom Unarmed Strike weapon. None of the effects you mention in its description (Hex, Hunter's Mark, Divine Strike) actually modify weapons in Hero Lab. So there's no need for a separate Unarmed Strike "weapon" to be added.

Like a lot of the stuff you submit, I see where you're going and somewhat how you're thinking, but it doesn't align with how other, similar Things are done in the pack.

It also comes down to this being 3rd Party content, which I'm not actively supporting.
