### ISSUE TITLE
Created a Warding Bond issue

### ISSUE THREAD

**Issue by Dragon5e** [Sklore/HL_DD_5e_Colab#1083]
Putting in +1 to AC and save was easy. Putting in all damage resistances was a bit harder.
[custom.txt](https://github.com/Sklore/HL_DD_5e_Colab/files/9035168/custom.txt)

**Comment by Fenris447** [comment]
Good stuff! This is definitely the kind of spell (one with multiple effects) that deserves its own Adjustment. I'll get it in.

Also, a tip for you if you're ever making other spell adjustments; I use the SpInfo.____ tag for these. It will automatically include the designated spell's full description in the Adjustment's description, so you don't have to copy/paste or retype it all.
