### ISSUE TITLE
Gloves of Thievery

### ISSUE THREAD

**Issue by Dragon5e** [Sklore/HL_DD_5e_Colab#1084]
Removed the attunement code from this item io5CGloThi in the eval script. It now work as normal.

**Comment by Dragon5e** [comment]
Hmm after looking at it online, it seems the gloves boost sleight of hand +5 and also a +5 to dex checks to pick locks. I included the code.
[custom.txt](https://github.com/Sklore/HL_DD_5e_Colab/files/9035746/custom.txt)

**Comment by Fenris447** [comment]
Added the code for the Sleight of Hand fix. Thanks!
