### ISSUE TITLE
Devil Sight is now its own sense. 

### ISSUE THREAD

**Issue by Dragon5e** [Sklore/HL_DD_5e_Colab#1088]
The forums talked about appending text to darkvision. Tried it and boy problems. For one regular darkvision disappeared and secondly goggle of nights expanded that thing to 180 foot. While Devil Sight include aspects of darkvision it is its own sense. Ok why don't I copy darkvision and make it Devil Sight. Had to simplify it as I could not include the tags but Devil Sight show up now.
[custom.txt](https://github.com/Sklore/HL_DD_5e_Colab/files/9050229/custom.txt)

**Comment by Dragon5e** [comment]
After looking at this online. Devil Sight has no interaction at all with dim light. Darkvision does. If you have both senses you can see normally in all lighting conditions.

**Comment by Fenris447** [comment]
This is another instance where it's fine if you want to treat it as a separate sense, but that's not how the rules are as-written.
