### ISSUE TITLE
Hide of the Feral Guardian i5CHdFrlG

### ISSUE THREAD

**Issue by Dragon5e** [Sklore/HL_DD_5e_Colab#1089]
Thought it was hide so the AC should be basically 2 armor not 1? I looked at various online sites and they all displayed studded leather. Considering that and hide have 2 armor that's fine with me. I looked at the gizmo and saw it had mLeather so I changed it to mStudLeath.

**Comment by Fenris447** [comment]
Great catch! I'm updating this for the next release.
