### ISSUE TITLE
Swords bard c5CBrdBlaF

### ISSUE THREAD

**Issue by Dragon5e** [Sklore/HL_DD_5e_Colab#1092]
I add situational text to Blade Flourish to display +1d6 situationally . After another thought copied the code for bardic inspiration and put here Scratch that didn't work but made my own script. The text display situationally for armor Defensive Flourish.

[custom.txt](https://github.com/Sklore/HL_DD_5e_Colab/files/9099262/custom.txt)

**Comment by Dragon5e** [comment]
Oops forgot about level 14 Master Flourish. simpel matter to add. This code include it
[custom.txt](https://github.com/Sklore/HL_DD_5e_Colab/files/9098789/custom.txt)
.

**Comment by Fenris447** [comment]
This is a little bit _too_ situational to merit situational text. Situational text is really not used for features where "if you choose to spend something you can add this" situations.
