### ISSUE TITLE
Gift of the Metallic Dragons f5CGftMetDrg

### ISSUE THREAD

**Issue by Dragon5e** [Sklore/HL_DD_5e_Colab#1093]
This was not increasing the stats at all. I looked at the Dragonhide feats and used that.
[custom.txt](https://github.com/Sklore/HL_DD_5e_Colab/files/9125132/custom.txt)

**Comment by Dragon5e** [comment]
Added situation AC text to Protective wings
[custom.txt](https://github.com/Sklore/HL_DD_5e_Colab/files/9126290/custom.txt)

**Comment by Fenris447** [comment]
The Gift of the Metallic Dragon does not increase any stats.
