### ISSUE TITLE
Arcane Deflection War Mage c5CWizArDe

### ISSUE THREAD

**Issue by Dragon5e** [Sklore/HL_DD_5e_Colab#1094]
Added situation text to Arcane Deflection on AC and saves.
[custom.txt](https://github.com/Sklore/HL_DD_5e_Colab/files/9126295/custom.txt)

**Comment by Fenris447** [comment]
This is similar to the Swords Bard issue you raised. It's not really what we use Situational Text for. As another example of something that is an active choice to add, we'd have to add a situational +5 to AC for anyone with the Shield spell.
