### ISSUE TITLE
Jump movement mode

### ISSUE THREAD

**Issue by Dragon5e** [Sklore/HL_DD_5e_Colab#1095]
I played around with the Harengon. I could not figure how how to add jump as a movement mode. I looked at swimming and modified it to Jump. One of the reason is that I believe a monk fast movement which apply to swim and flight should also apply to jump. 
[custom.txt](https://github.com/Sklore/HL_DD_5e_Colab/files/9222274/custom.txt)

**Comment by Fenris447** [comment]
Jumping is not an alternative mode of movement. It's a neat idea, but this is the sort of thing that is up to the player to figure out at the table.
