### ISSUE TITLE
D&D 5.5e or 6e playtesting document

### ISSUE THREAD

**Issue by Dragon5e** [Sklore/HL_DD_5e_Colab#1100]
https://thekindgm.com/2022/09/02/unearthed-arcana-one-dd-character-origins-analysis/ talked about the upcoming D&D 5.5 or 6e. It give a iink to Dndbeyond where you can sign in and get the pdf to read. I figure the coders would want a look at the proposed changes to get an idea of possible change to the community code. Also posted in the community hero lab forum. I do not know if you need to maintain 2 versions or not.

**Comment by Fenris447** [comment]
Oh believe me, I've looked at it. It's...going to be very difficult to fully implement. At least not in a way that is a pleasant, simple experience for the end user. I'm gonna close this since it's not technically an issue with the pack. But believe me, I'm pouring over everything they put out.
