### ISSUE TITLE
COM-5ePack_MTOF - Races.user: Sheyanna Flaxenstrand

### ISSUE THREAD

**Issue by Enforcer84** [Sklore/HL_DD_5e_Colab#1104]
The gnome goddess is checked bot elf and gnome pantheons and lacks the deity category number (15)

fixed Here:
`<thing id="dei5CSheya" name="Sheyanna Flaxenstrand" compset="Deity" uniqueness="unique">
    <fieldval field="deiPortfol" value="love, beauty, passion"/>
    <fieldval field="deiSymbol" value="Two silver goblets"/>
    <usesource source="5eMTOFCP"/>
    <tag group="AlignTemp" tag="ChaotGood"/>
    <tag group="SuggDomain" tag="c5CClrLig"/>
    <tag group="DeityCat" tag="5CGnomish"/>
    <tag group="explicit" tag="15"/>
    </thing>`

**Comment by Fenris447** [comment]
Fixed and will be in 3.8 (hopefully very, very soon). Thanks for the find!
