### ISSUE TITLE
Contributor offer

### ISSUE THREAD

**Issue by whoblitzell** [Sklore/HL_DD_5e_Colab#1107]
I work with C#, XML and SQL (Transact and Oracle) and I'm very into 5th ed. I'd love to help contribute in any way that I can. Please let me know.

**Comment by lProvosl** [comment]
I'm looking for help with some Dark Sun stuff.

**Comment by Fenris447** [comment]
Anyone is always welcome to try their hand at making stuff for the pack. If there's ever a piece of content you want to create, just make an issue saying what you're tackling.
