### ISSUE TITLE
Gem Dragonbon not auto spekaing draconinc

### ISSUE THREAD

**Issue by Catman74** [Sklore/HL_DD_5e_Colab#1108]
OK all dragon born speak draconic as a racial feature. However the community pack does not put that in automatically for gem dragonborn. That really needs to be fixed please. Thank you!

**Comment by Fenris447** [comment]
As surprising as it may be, the Dragonborn in Fizban's Treasury of Dragons (including the Gem ones) do not automatically get Draconic as a language. They all follow the new lineage-style of Race choices, where everyone automatically gets Common and one other language of the player's choice.
