### ISSUE TITLE
Request: 5e Arcanis Campaign Guide

### ISSUE THREAD

**Issue by NidomeUK** [Sklore/HL_DD_5e_Colab#1110]
Would like to see this added. Willing to give it a go myself if no-one is up for doing it and would appreciate pointers for best way to tackle it.

**Comment by Fenris447** [comment]
Hey Nidome. Sorry for the incredibly late reply. I'll refer you to [this page](https://github.com/Sklore/HL_DD_5e_Colab/wiki/6.-Homebrew-Requests) that outlines 3rd-party content requests for the Community Pack.

That said, you're always welcome to take a swing at it yourself. I regularly check the LWD 5e forum and offer whatever knowledge I have to anyone trying to create their own content.
