### ISSUE TITLE
Backgrounds still not quite right.

### ISSUE THREAD

**Issue by OregonPinkRose** [Sklore/HL_DD_5e_Colab#115]
If I could fix it I would.

Uninstalled. Clean re-install of D&D SRD and Community Pack.
No alterations on my part.

All PHB Backgrounds work, but the following SCAG do not have Flaws, Bonds, etc.
City Watch
Clan Crafter
Cloistered Scholar
Courtier
Inheritor
Investigator
Knight of the Order
Mercenary Veteran
Urban Bounty Hunter
Uthgardt Tribe Member
Waterdhavian Noble

What's odd is that the following SCAG Backgrounds work just fine.
Faction Agent
Far Traveller
Guild Artisan
Guild Merchant
Noble Knight

**Comment by Sklore** [comment]
Are you sure you have the PHB and SCAG source enabled? I've tested all of these and they all work. 

![2016-02-29 11_53_17-hero lab - test - test_1](https://cloud.githubusercontent.com/assets/8046697/13383581/af3629d6-dedb-11e5-8c97-e691371a139d.jpg)

**Comment by OregonPinkRose** [comment]
First question: Is there a cache or are files saved somewhere else besides the Hero Lab install folder?

If not, here are the screenshots I have for settings for a new Portfolio.
![hlsettings](https://cloud.githubusercontent.com/assets/17410871/13386694/1a9e7fa2-de64-11e5-8841-378ccb91b6b1.png)

And this is what shows up for the Mercenary:
![hlmerc](https://cloud.githubusercontent.com/assets/17410871/13386699/28af125a-de64-11e5-998f-163edaa7cd2d.png)

**Comment by Sklore** [comment]
Try delete all the *,user folders from here and re-download. 

C:\ProgramData\Hero Lab\data\5e

**Comment by OregonPinkRose** [comment]
I deleted the whole Hero Lab folder and restarted.
And the Hero Lab Folder in Documents.
Same problem.

Happy to trouble-shoot anything you can think of.
But if I'm the only one having issues, it doesn't make sense.

**Comment by Sklore** [comment]
I'll delete my version and see what happens. I know this is fixed as it was an absolute PITA to do ;)

**Comment by Sklore** [comment]
Ok apologies, it is fixed just not in the public release. 
Download this:
https://github.com/Sklore/HL_DD_5e_Colab/archive/master.zip

Copy the contents of the folder to:
C:\ProgramData\Hero Lab\data\5e

And that should sort it. I'll talk to shadow about getting the next release ready.

**Comment by OregonPinkRose** [comment]
That did it.

**Comment by Sklore** [comment]
Closing as this is resolved and scheduled for release in the next release.
