### ISSUE TITLE
Two SCAG Backgrounds missing sources.

### ISSUE THREAD

**Issue by OregonPinkRose** [Sklore/HL_DD_5e_Colab#116]
The following SCAG Backgrounds are missing their source.

Clan Crafter
Cloistered Scholar

**Comment by Sklore** [comment]
What error message are you getting? These appear to be working ok based on my testing. 
![2016-02-29 12_34_24-hero lab - test - test_1](https://cloud.githubusercontent.com/assets/8046697/13383997/de3c9abc-dee0-11e5-8edb-992b0a32fded.jpg)

**Comment by OregonPinkRose** [comment]
Looking at the code, it appears that Crafter and Scholar are missing the following lines:
    <usesource source="5eSCAGCP"/>
    <tag group="ProductId" tag="Wizards"/>
in between the StartGear and the ProfSkills Tags.

When added in, it seems to fix it.

**Comment by grandchefpanda** [comment]
Checked it is in the last version of github

**Comment by OregonPinkRose** [comment]
In theory, I added the `<tag group="ProductId" tag="Wizards"/>` so this can be closed.

**Comment by Sklore** [comment]
Did you push these changes into Master? When you push a change add a hashtag and the issue number in a comment: Example: #116. 

This way your push links to the issue. Makes it easy to keep track of whats happened and why.
