### ISSUE TITLE
Rogue - 1/2 of correct ability score adjustments

### ISSUE THREAD

**Issue by Killanath** [Sklore/HL_DD_5e_Colab#119]
The Rogue class is only giving one ability score adjustment at the appropriate levels when it should be giving two.

**Comment by grandchefpanda** [comment]
Can't reproduce, Are you sure you are using the last version of Herolab with the last SRD version. Also if it is on the default Rogue class, it's more likely a Herolab bug. Can you post a screenshot.

**Comment by Sklore** [comment]
The community pack is only responsible for adding the Arcane Trickster and Assassin Roguish Archetypes. Please see this post for instructions on logging issues with the Core 5E SRF pack directly to Lone Wolf. 

http://forums.wolflair.com/showthread.php?t=54821
