### ISSUE TITLE
Implementing the Piercer Monster

### ISSUE THREAD

**Issue by grandchefpanda** [Sklore/HL_DD_5e_Colab#126]
I have implemented the piercer #125 but can't find a way to
1) remove the reach 5ft in the statblock of Drop action
2) change "one creature" target to "one creature directly underneath the piercer" of Drop action

**Comment by shadowchemosh** [comment]
1) On the natural attack you can change the wReach to 0 and that will cause it print:
**Drop. Melee Weapon Attack: +3 to hit, reach 0 ft., one creature.**

2) Sigh I can tell by the design who coded this logic into HL and it was not Aaron.  This is using a "Final Script" to make the word "One creature" and without access to the skeletal files it can't be changed.  Even worse is the tag group AttackTarg.? is not dynamic preventing us from creating our own.  Which is stupid.

We can try and put in a bug report about issue 2 to make this be a) a text field we could set in a script or b) at least make the AttackTarg.? tag group to be dynamic allowing us to add custom tags with a description of "one creature directly underneath".  I will see about putting in a bug report...

**Comment by shadowchemosh** [comment]
1) I see from the forums you don't like the idea of it saying 0 Reach.  But currently I see now way around this.  They are "generating" the text at the time the statblock is being generated.  They are not doing it before in a field we can change.

2) I have reported this issue to LW and will see what they say...

**Comment by grandchefpanda** [comment]
Thanks for reporting the issue, because I can't do it, all my issue report to LW are lost.

**Comment by grandchefpanda** [comment]
Mind Flayer same issue with target

**Comment by shadowchemosh** [comment]
I have been told this is "fixed".  They won't say "how its fixed".  Will see when the next update is dropped what it does.

**Comment by grandchefpanda** [comment]
Great, we need this also for the Winged kobold

**Comment by grandchefpanda** [comment]
corrected
