### ISSUE TITLE
Step by Step requested

### ISSUE THREAD

**Issue by OregonPinkRose** [Sklore/HL_DD_5e_Colab#129]
I'm sure this isn't where this should go but I can't find a way to message a person.
I would be very interested in a step by step, on how to download a file, make changes, and upload the file again.
I really don't want to learn everything about Github and programming.
But I know enough about editing, code and cutting and pasting, that I feel I can help in a small way, if I know how to do it.
I can easily change the numbers for entries in backgrounds, and can add the missing sources. 
I just don't know how to get and post the files and record the changes.
So if someone will take the time, to give me a step by step, I'm sure I can repay the time with editorial changes and fixing typos, and eventually filling in some of those place holders.

**Comment by grandchefpanda** [comment]
Small bugs and typo, just report it. 
If you have for example implemented the complete death domain from the DMG, the best way it to put what you've added in a user file then change the extension of your user file with the extension .txt and drag and drop in a message like this one and we can import it.

**Comment by grandchefpanda** [comment]
You can also copy paste tags, but not a complete user file as it will not be accepted by github.

**Comment by Sklore** [comment]
If your interested @OregonPinkRose I'm happy to give you contributor access so you can fix bugs directly which will then be release to the public. This applies to anyone who is keen to help.

**Comment by shadowchemosh** [comment]
@OregonPinkRose I have a document that I put together for Pathfinder GitHub that walks a person through setting up SourceTree on Windows to gain access to GitHub.  Its the tool I use.  That is different than how Sklore uses GitHub.

Here is the link.  Of course replace any URL's in the document to THIS repository. =)
http://www.shadowsoftware.net/herolab/d20pfsrd/GitHub_Community_Setup.pdf

Just offering something to help that is already done.

**Comment by Sklore** [comment]
The premise is the same, i just use the web client as I work from multiple locations (one of which does not appreciate foreign applications being installed). 

I might try your method tonight though Shadow. I suspect it will be more efficient.

**Comment by shadowchemosh** [comment]
I just meant that if you put together a step by step guide Sklore it would be different because you use a different method.  Really at the end of the day its a really nice feature that multiple ways are allowed to use GitHub.  That makes it really nice!

In addition GitHub is REALLY big and used by allot of people.  Meaning google searches are your friend and can even find "videos" that show how GitHub works and Git logic also.  Its one of the reasons I moved over to it because it was so heavily supported by others and finding help is easier...

**Comment by Sklore** [comment]
I'm really liking the ability to publish the Log Issue button. My career has revolved around the management of national IT service desks so having a simple way for end-users to log faults and then have visibility on the progress of their issue is awesome.

**Comment by shadowchemosh** [comment]
OMG that I totally agree with.  My job site has multiple "bug/support" ticket systems and none of them are linked.  Its a nightmare track a support issue vs the work.  Not including tracking issues/changes in a 3,000+ hour project with a half-dozen programmers making changes. =(

Sorry for the off topic messages. =)

**Comment by OregonPinkRose** [comment]
I got to page 8 of your guide.but when I hit OK, I get the below error.
```
git -c diff.mnemonicprefix=false -c core.quotepath=false fetch origin
From https://github.com/Sklore/HL_DD_5e_Colab
 * [new branch]      CraigG-Changes -> origin/CraigG-Changes
 * [new branch]      Gcp-Changes -> origin/Gcp-Changes
 * [new branch]      JoshP-Fix  -> origin/JoshP-Fix
 * [new branch]      KevinS-Changes -> origin/KevinS-Changes

 * [new branch]      master     -> origin/master


```



 * [new tag]         v1.0       -> v1.0
 * [new tag]         v1.1       -> v1.1



git -c diff.mnemonicprefix=false -c core.quotepath=false pull origin master
From https://github.com/Sklore/HL_DD_5e_Colab
 * branch            master     -> FETCH_HEAD


error: The following untracked working tree files would be overwritten by merge:
	COM_5ePack - Helper Things.user
	COM_5ePack - Procedures Validate.user

	COM_5ePack - Procedures.user
	COM_5ePack - Release Notes.user
	COM_5ePack - Tags.1st
	COM_5ePack_BOLS5e.-.Spells.user
	COM_5ePack_PHB - Adjustments.user
	COM_5ePack_PHB - Backgrounds.user
	COM_5ePack_PHB - Classes.user
	COM_5ePack_PHB - Deities.user
	COM_5ePack_PHB - Feats.user
	COM_5ePack_PHB - Races.user
	COM_5ePack_PHB - Spells.user
	COM_5ePack_PHB - Weapons.user

	COM_5ePack_ROT - All.user
	COM_5ePack_SCAG - Backgrounds.user
	COM_5ePack_SCAG - Classes.user
	COM_5ePack_SCAG - Spells.user
	COM_5ePack_TNRCToS - Spells.user

	COM_Source_001 - Community Packs.1st
	COM_Source_100 - 5e Pack.1st
	COM_Source_110 - Players Handbook.1st
	COM_Source_110 - Sourcebooks.1st

	COM_Source_110 - Third Party Publishing.1st
	COM_Source_110 - Tyranny of Dragons.1st
Please move or remove them before you can merge.
Aborting

**Comment by shadowchemosh** [comment]
Looks like you setup SourceTree to point to where you already have this Pack installed.  You should really setup a new 5e Game System to point GitHub too.  Otherwise you will a) get the above issues or more when you update from the .hl file and try and update from GitHub.

This is why on page 4 of the document I show how setup a "new" Pathfinder game folder or in this case a 5e game folder. =)

**Comment by shadowchemosh** [comment]
![gamesystems](https://cloud.githubusercontent.com/assets/7717785/13420395/7afee282-df4b-11e5-846a-eff0276b1d19.jpg)
In example this is what I see when I start HL.  Notice I have tons of the "same" system folders.  This make it much easier to keep all my stuff separate. =)

**Comment by OregonPinkRose** [comment]
```
On the above window press the “Change...” button so that you can setup a NEW fresh folder.
I recommend an easy to remember folder name. In example if this was to support the 3PP
Pack I would name the folder “pathfinder_Pack_3PP”. Once changed to your new folder
name press the “Start Import” button to load the latest Pathfinder files.
```
I made a folder called "My5e" in the data folder. Then When I did "Start Import" it loaded all the .1st and .user files from the Community pack.

**Comment by shadowchemosh** [comment]
Your not loading the community pack from the .hl file.  You are loading the 5e game system from Lone Wolf.  So delete your My5E folder and start again this time double clicking on the 5e.hl file from Lone Wolf not the 5e pack from the community.

That will install all new game system folder that is clean.  Then you will be able to do the pull from GitHub into a clean fresh game folder. =)

**Comment by OregonPinkRose** [comment]
Ok, I tried one.
Thank you for the help.
I feel useful now.

**Comment by Sklore** [comment]
Do you edit in this application or do you still use the likes of Notepad++?

**Comment by OregonPinkRose** [comment]
I clicked the Open in Explorer, then open the file in Notepad++, then when I save it shows up in SourceTree and then I commit it.
Did I do it right?
I didn't find a way to change it in the application.

**Comment by grandchefpanda** [comment]
You have done right, but after you have to push your commits to the server. You can do multiple commits, it is changing things on your local computer and all will go at the same time when you push.

**Comment by grandchefpanda** [comment]
I prefer to do the pushes on a separate branch, then I go on github, I do a pull request to merge the master branch in my branch, then I merge by updated branch in the master branch. With that I'm sure that I won't erase anything that others have done on master.

**Comment by shadowchemosh** [comment]
Correct. What grandchefpanda says is the "best" way.  Its just a little confusing if you have never worked with a repository before.  I tried to show my Pathfinder editors and it just went bad. =(  Hence why the documented I made only talks about committing to master.

@OregonPinkRose you don't have to use notepad as you pulled the user files down into where HL expects them to be.  So feel free in HL to start the editor and use it make changes.  No need to work at the XML level at all.  I do like half and half but the editor is very nice for doing fast thing and not memorizing tag names. =)

**Comment by IrondrakeX** [comment]
I've been getting all of the class text from the PHB put back into my local copies of the PHB files.  Is this something we are wanting to publish as well?  My concern is that when I get updates, all of my text will be overwritten with "Placeholder" if I don't push it out first.  I'm going to go over the GitHub guide but I'm pretty new to this.

**Comment by shadowchemosh** [comment]
You can't publish the text for classes or anything outside of the SRD.  If you totally re-write the text to be in your own words that is fine.  But you can not legally copy/paste the text.  If you do then WotC will have the legal right to come after us all.  So that is BAD!

The text I have entered I re-worded to be in my own words using ONLY mechanical words like bonus to hit or proficiency in poison.

@IrondrakeX if you modified the files that start with COM_ those files are overwritten each time you install the new community file.  The only way I can think of adding text without having issue is writing scripts to overwrite everything.  Which is going to be allot of CPU overhead eventually.

See this post I did on the forums about it:
http://forums.wolflair.com/showthread.php?p=224502&highlight=%23appenddesc#post224502

**Comment by Sklore** [comment]
We wish we could but ultimately it is not possible. WOTC are still sending out C&D's as evident here.

https://www.reddit.com/r/monsteraday/comments/464vle/monsteraday_compendium_going_down/

Ultimately we are only using the names and mechanics. All fluff text, descriptions, etc needs to be paraphrased.

**Comment by grandchefpanda** [comment]
And what about monsters name ?

**Comment by Sklore** [comment]
I met with LW who met with their IP Lawyer. The recommendation is that we should be OK to use the name but cannot include the fluff text. Text needs to be min 20% different. I have basically been sourcing descriptions and stuff from external Wiki's. We have to remember that while they may not have released the info under the 5e SRD, there's a high chance that content already exists for the same things elsewhere in the internet. So that's saving a lot of time. 

If a C&D is received then we will have to change the names which really shouldn't take too long it will just be annoying for the end-users.

**Comment by grandchefpanda** [comment]
I was worried also for the gods name. Thanks for the update.

**Comment by Sklore** [comment]
The God's names are freely available on the internet and the descriptions used have been taken from Wiki's.

**Comment by Sethvir** [comment]
Ok, I have two questions.  1) Has anyone done the Elemental Evil Player's Guide? and 2) I am working on updating the Book of Lost Spells to fix text formatting and some cleanup of the conversions in various fields as well as the En5ider material, where and how do I push my updates up?

**Comment by Sethvir** [comment]
I have my github account to pull from the Master in Source Tree, but working with the Pathfinder material, I just pushed up to the master.  Here it looks like we are doing something slightly different.

**Comment by Sklore** [comment]
Should work the same. 

I personally create a new branch in the GitHub web gui. From the new branch i select the file i want to edit. Click edit. Copy and Paste the updated documents contents over the original. Save and merge the branch. 

No ones started the EE stuff yet so it would be great to have some focus on it.

**Comment by Sethvir** [comment]
I needed it for one of the En5ider articles, so I ended up building it.  But since it's not SRD, we have to change the text of the spells don't we?

**Comment by Sklore** [comment]
I have been thinking about the BOLS. Its not a WOTC product but it appears some of it is copyrighted to Frog Good Games so yes we do likely need to change the fluff text or even just remove it leaving just the names and mechanics. Better to be safe than given a C&D...

**Comment by Sethvir** [comment]
I was more referencing the Elemental Evil PG with the fluff text, but if we need to do something similar with BOLS, I can work on that too.  It's only 706 spells?  LOL

**Comment by Sklore** [comment]
Just delete the fluff text. Leave the mechanics. I found the PHB spells to be rather simple in that regard. 

EE belongs to WOTC so we definitely need to be careful to para-phrase the copyright material.

**Comment by Sklore** [comment]
Looking through the BOLS most of it appears to be cut down already to just mechanics. Given alot of the spells have being updated from previous editions they probably did that to avoid their own copy right issues. Given then we should we ok.

**Comment by Sklore** [comment]
Closing this out.
