### ISSUE TITLE
Silver Weapons?

### ISSUE THREAD

**Issue by shadowchemosh** [Sklore/HL_DD_5e_Colab#130]
http://forums.wolflair.com/showthread.php?t=55182

The above post talked about wanting to make Sliver weapons.  I did see that Sliver weapons are in the SRD so this could be a LW issue.  But I could add logic that would allow for turning any weapon into a silver weapon.  The only issue would be can you make a +1 Silver Dagger in 5e?  It seems right now based on LW logic that can't happen.  The way the gizmo's are defined you could make a Silver Dagger or a +1 Dagger but not a +1 Silver Dagger..

Is it worth making a helper thing that would allow for turning any weapon silver.  Or should I just put in a LW bug report?  Or do both?

Thoughts?  Anyone?

**Comment by Sklore** [comment]
The thing with 5e is they have really gone with an open rule-set. As far as i know there's no reason you couldn't make a silver spoon in game if you really wanted to. 

I think this would be a useful option to have.

**Comment by shadowchemosh** [comment]
Added a way to make any weapon/ammo into a silver or magic silver weapon.  Hopefully that covers all the different methods in 5e. =)
