### ISSUE TITLE
Aarakocra - Weapon Damage Issue

### ISSUE THREAD

**Issue by Sklore** [Sklore/HL_DD_5e_Colab#132]
Ok no idea how to do this or if I should even try to fix it. 

Aarakocra has the following listing under Javelin. 

**MM Entry:** javelin. Melee or Ranged Weapon Attack: +4 to hit, reach 5 ft. or range 30/120 ft ., one target. Hit: 5 (1d6 + 2) piercing damage.

The +4 to attack should apply on ranged attack (+2 prof and +2 dex). 
The +4 to attack should not apply on melee attacks (+2 prof). 

The +2 to damage should apply on ranged attacks (+2 dex).
The +2 to damage should not apply on melee attacks (+0 str). 

Technically this should list the weapon twice. Ranged and Melee. 

**PHB:** javelin 5 sp 1d6 piercing 2 lb. Thrown (range 30/120)
**Current Output:** +2 3 (1d6) piercing
**Desired Output:** +4 5 (1d6+2) piercing

It looks like Hero Labs is more mathematically correct than the PHB?

The +2 to attack can be added with an adjustment but this would need to be done manually?

Am i over thinking this?

**Comment by MortierC** [comment]
Dont forget Aarakocra as a correction in the errata:
Aarakocra (p. 12). Languages: added Aarakocra.
http://media.wizards.com/2015/downloads/dnd/MM_Errata.pdf

If you look at the errata, there is a lot of corrections about wrong value, if you let herolab calculate, usually the calculated value from Herolab is the errata.

**Comment by MortierC** [comment]
also, I'm not sure we should put the non natural weapon in the monster. LoneWolf has omitted all non-natural weapon from there races, I've done it too so if the GM want to put another weapon he can.

**Comment by Sklore** [comment]
I love not having the weapons coded. That lets us Dm's make much more interesting monsters. 

I might submit a request to LW to have the melee/ranged weapons better represented on the sheet. Ideally it should be listed twice or have an activation for ranged etc.

**Comment by Sklore** [comment]
Have sent a feature request to LW about this one to better represent weapons that are used in both melee and ranged.
