### ISSUE TITLE
Elemental Adept Feat not supporting taking feat twice for multiple damage types

### ISSUE THREAD

**Issue by MNBlockhead** [Sklore/HL_DD_5e_Colab#136]
I can only add the elemental adept once. I have a character that used feats, rather than ability-score upgrade and took elemental adept twice. Once for thunder and once for lightning. I'm only able to add it once. Once I've selected it, it is not longer available for selection. Moreover, I can only select ONE elemental damage type. from the feat's drop-down selector. 

I will file this as a bug, but am posting here in case someone can think of a workaround in the meantime.

**Comment by shadowchemosh** [comment]
Just posted a work around in the thread you started....
