### ISSUE TITLE
Bug in ft5CDuelWi Duel Wielder feat

### ISSUE THREAD

**Issue by mtassin** [Sklore/HL_DD_5e_Colab#139]
The definition of the feat is
You gain a +1 bonus to AC while you are wielding a separate melee weapon in each hand.
• You can use two-weapon fighting even when the onehanded melee weapons you are wielding aren’t light.
• You can draw or stow two one-handed weapons when you would normally be able to draw or stow only one.

Yet after taking the feat, equipped two rapiers results in a validation error that the offhand weapon must be light.

**Comment by shadowchemosh** [comment]
This was fixed before via a tag that Lone Wolf added.  So this is actually a LW bug.  I will need to report it and see if Aaron can fix...

**Comment by shadowchemosh** [comment]
Update. I have officially reported this to LW about **Hero.TwoWpLight** only half working.  It should also suppress the error message.  Until then all the values are correct so its fully usable feat.  Just ignore the warning message.
