### ISSUE TITLE
Thanks from Lone Wolf To Everyone Involved

### ISSUE THREAD

**Issue by Sklore** [Sklore/HL_DD_5e_Colab#141]
Community Packs

The D&D 5th Edition SRD is a subset of the entire set of rulebooks, so the Hero Lab data files can’t include everything players may want. The Hero Lab user community just changed all that! The just-released D&D 5E Community Pack lets you fill in the holes and go beyond the limits of the SRD. Thanks to the hard work of many volunteers, this free add-on includes all backgrounds, class options, feats, and much more from the Player’s Handbook and other official D&D sources! And users can drop it into Hero Lab with a few quick steps. To get it now, visit our community forums!

Note: The D&D 5th Edition SRD game system in Hero Lab is limited to the content published in the official SRD, and the SRD omits various options from the assorted rulebooks. Using the power and extensibility provided by the Hero Lab Editor, the user community has implemented the majority of the content that’s not in the SRD and made it available to all users. The caveat with the Community Pack is that portions of descriptive text are often paraphrased (and sometimes omitted) to ensure the data files are legally sound. All the mechanics are fully implemented, so everything behaves the way you expect for your character, and you can always refer to the rulebooks for the official language used.

A huge “**Thank You!**” to the volunteer community members that put this package together!

:+1:

**Comment by grandchefpanda** [comment]
:+1:

**Comment by shadowchemosh** [comment]
Ahhh Liz is so nice! :smiling_imp:
