### ISSUE TITLE
Storm Sorcerer option missing.

### ISSUE THREAD

**Issue by mlamkin** [Sklore/HL_DD_5e_Colab#148]
SCAG checked in Hero preferences, but no Storm Sorcerer option under Sorcerous Origins.

**Comment by grandchefpanda** [comment]
I don't think it has been implemented yet

**Comment by Sklore** [comment]
Yeah the bladesinger was done as a priority as one of the contributors was playing it in a campaign. This will get added in eventually likely once we finish the monsters which is the current priority.

**Comment by mlamkin** [comment]
Thank you for the quick response :)  
It really won't be difficult to play without it, just that Hero Lab thinks there's something wrong since I can't choose one of the others.  Fortunately, there's not a lot of huge differences between the bloodlines.  At least at the level I'll be playing at.

**Comment by Sklore** [comment]
Thanks for the request. This will be implemented in the next release.
