### ISSUE TITLE
Feat: Weapon Master

### ISSUE THREAD

**Issue by Tricky110974** [Sklore/HL_DD_5e_Colab#150]
Cannot select Ranged Weapons. Feat only mentions that selection must be Simple or Martial. Does not say must be Melee.

**Comment by shadowchemosh** [comment]
Well look at that.  Sorry somehow I got it in my head it was Melee only.  Thanks for the bug report. This will be fixed in the next release.

**Comment by Tricky110974** [comment]
Thanks for the quick response.
