### ISSUE TITLE
Bootstrapping 5C Spells

### ISSUE THREAD

**Issue by Sklore** [Sklore/HL_DD_5e_Colab#156]
Hi team, 

If we Bootstrap a spell we have created to a monster it does not appear in the Spells In-Play column. 
I'm assuming i need to add something to it. 
Any ideas?

Example: See Barlgura (replicated with other 5C spells).

**Comment by grandchefpanda** [comment]
All monsters with spellcasting  where not included by LW in their 1.2 SRD update, I suppose they are working on it. I think this is better to wait for the next update 1.3 SRD to see how LW will do the spellcasting monsters and NPC.

**Comment by shadowchemosh** [comment]
Are these spell-like abilities or normal spellcasting capability?

**Comment by grandchefpanda** [comment]
normal spellcasting, some as NPC or monsters have spells, with slots, works as a wizards or as a cleric, etc

**Comment by Sklore** [comment]
It's working for official spells and not for ours though making me think this is a separate issue.

**Comment by shadowchemosh** [comment]
So looking at the Barlgura I see it has a racial special called "Innate Spellcasting" which is setup for 4 spells.  One of them a community spell.  When I add this race all 4 spell-like abilities show up on the Spells tab including Phantasmal Force (the community spell).  I appear to be missing something as it seems all good.

The Racial Spellcasting mechanics setup in Pathfinder appear to have been removed in 5e.

**Comment by grandchefpanda** [comment]
Have you selected all the sources. If you put a spell from a source not selected with CTRL-K it will not appear in the inplay but be there in the description because this is text. I had a similar issue just now.

**Comment by grandchefpanda** [comment]
For me it displays too

**Comment by grandchefpanda** [comment]
There is a lot of bugs in the Test Now button, sometime some things don't appear but are there. Happens a lot with attributes. Usually I simply restart Herolab and I can continue to create the monster.

**Comment by Sklore** [comment]
Yup noob mistake. Didn't have the PHB selected. Thanks guys.
