### ISSUE TITLE
DMG - Death domain

### ISSUE THREAD

**Issue by LordMorin** [Sklore/HL_DD_5e_Colab#164]
Here is my DMG user file. It contains my version or Eldarin, Aasimar which you can ignore. What peeps seem to want is the Death domain. Names will have to be changed to conform with the 5e Community pack. Descriptive text may have to be removed in some cases.

After my last attept to modify the Observant feat caused issues, I'll leave this to the experts. :)

[soe_5e_dmg.zip](https://github.com/Sklore/HL_DD_5e_Colab/files/159999/soe_5e_dmg.zip)

**Comment by Sklore** [comment]
@LordMorin 

Ok thanks mate this has been merged with the master branch :+1: 

Looking at the code I can see you have hard coded Reaper to work with the PHB spells. If there any chance you can have a play with this code to make it more flexible? The feature is allowing the selection of all the necro cantrips available but will only display spells that are hard coded to the player. Ideally this code needs to be flexible enough to display any selected spell to the user. 

You can download the Alpha pack here to play around with it all together. 
https://github.com/Sklore/HL_DD_5e_Colab/archive/master.zip

**Comment by LordMorin** [comment]
I'll take another look at it. I'll turn on the additional spells and see what happens, I haven't been playing with them yet.

**Comment by Sklore** [comment]
There are only 2. But ideally we want it so all code words with future additions natively.

**Comment by shadowchemosh** [comment]
To make this more soft-coded like Sklore is asking you will need to allow your class to pick the spell form its spell-list and then once selected make it a "FREE" spell.  Recent post in the forums went over script logic to do this.  In your case even easier as you only have a single specific spell to add.  Meaning you won't need a foreach loop but can use a findchild instead.

http://forums.wolflair.com/showthread.php?t=55248

**Comment by LordMorin** [comment]
Ok, this isn't fully automated, but it works so far.

You have to select you necromancy cantrip from the drop down. Then you can manually add it to your list of prepared cantrip as a freebie.
[soe_5e_dmg.zip](https://github.com/Sklore/HL_DD_5e_Colab/files/162069/soe_5e_dmg.zip)

**Comment by Sklore** [comment]
Thanks @LordMorin. Works great :) much better than i could have even hoped to code.
