### ISSUE TITLE
New Weapon Proficienct: Firearms

### ISSUE THREAD

**Issue by Sklore** [Sklore/HL_DD_5e_Colab#168]
@shadowchemosh 

Did you add the Improvised Melee and Ranged Weapon proficiency?

If so where does that get added?

I'm trying to add Firearms as a proficiency so the Gunslinger class option can function.

**Comment by shadowchemosh** [comment]
You can't actually make a proficiency like Martial/Simple.  The improvised tags where already built into 5e from Pathfinder.  I just added the weapons.

You can sort of mimic the idea but you are forced to use a foreach loop (I say this as foreach loops are massive CPU overhead and will burn battery life on the iPad).  I would make a new tag in the wProperty.? group for Firearms/guns etc that would be on each new gun.

Then assuming you are proficient in ALL guns you would need a script like so:
**First/20000**
```
~ Build all weapon tags on us from all Thing Weapons
foreach thing in BaseWep where "wProperty.5CGuns"
    perform eachthing.pulltags[WepProf.?]
nexteach
~ push all weapon proficiency tags to hero
perform hero.pushtags[WepProf.?]
```
That reads all the guns in HL database and sets the proficiency tags on the hero.

**Comment by Sklore** [comment]
It's like your some sort of Wizard

Thanks!
