### ISSUE TITLE
Gunslinger - Scripting Required

### ISSUE THREAD

**Issue by Sklore** [Sklore/HL_DD_5e_Colab#170]
**STATUS** Incomplete but usable

**OUTSTANDING**

**COMPLETE**
**Grit:** How to set grit point to minimum of 1 or Wis Mod. I have it working to the Wis Mod but this will fail if Wis Mod < 1. 
**Ammunition:** @shadowchemosh you wouldn't happen to have the ability to create custom ammo already coded over in the PF world?
**Firearm Properties:** Is there a way to add the Firearm property numbers in a way that it will be visible to the user? Example: Reload 4, Reload 2, etc.
Have added the gunslinger from DMsGuild.com

**Comment by grandchefpanda** [comment]
Quickdraw script done

**Comment by shadowchemosh** [comment]
First I have to bitch about WotC just stealing everything from Paizo.  My god they made the exact same class as Paizo did?  Sigh guess I shouldn't expect much from WotC anymore...

Sorry rant over.

**Ammunition:** The ability to make custom weapons and ammo is built into the core features of HL Pathfinder.  Nothing I would need to have created.  What sort of "Custom" ammo we talking about?  Can you list some examples?  a) we can use existing logic to make this or b) I guess I could spend a bunch of time making a brand new Gizmo to allow this and other weapon modifications.  I mean then we could add new material types and everything (which has to be coming in books down the road).

**Grit:** use the macro `#attrbonus1[aWIS]` to set your value.  The minimum of "1" is built into the macro logic.  In example you should already be using `#attrbonus[aWIS]` to get the bonus correct? =)

**Firearm Properties:**  I would just put this info as the first thing in the "text Box" in the editor actually.  That way it sort of lines up with the other values displayed.  No good way to change the script that build the UI window popups. =(

**Comment by grandchefpanda** [comment]
Actually, this is not from WotC but from dmsguild.com.

**Comment by shadowchemosh** [comment]
Ok I take my rant back!  But it don't mean I like WotC still. =)

**Comment by Sklore** [comment]
If you don't know about critical role you should check it out. Awesome live stream. Amazing DM. They are all voice actors making for an interesting watch. This is Mae by Matthew Mercer, the DM.

**Comment by Sklore** [comment]
Thanks @shadowchemosh 

**Ammunition:** According to the Ammunition ruling each gun uses unique ammo and you can craft it yourself using Tinker Tools. With that in mind it would be ideal to have a simple add ammunition feature where you could manually enter what type of ammo it is and have is tracked in the tracker resource section for the player to increase / decrease as required. It might already be there, i saw similar thing for the magic ammo. Was just checking to see if something already exists that could be leveraged before I try and create it myself.

**Comment by shadowchemosh** [comment]
I would take a look at the Thing (i5CSilAmmo) I created for the Silver Arrows.  It will actually do any ammo actually.  When you buy you have to say you are getting say 20 (Add new Stack) arrows and then its suppose to add a tracker to the In-Play tab for 20 arrows.  I just noticed its not working and neither is the LW version for "Ammunition, +1".  

Guess another bug to report to LW. =)

**Comment by shadowchemosh** [comment]
Magical/Custom ammo stack bug reported to LW....

**Comment by Sklore** [comment]
Completed.
