### ISSUE TITLE
Jackalwere - need to add the little text behind the language name

### ISSUE THREAD

**Issue by grandchefpanda** [Sklore/HL_DD_5e_Colab#174]
Don't know how to do this, couldn't find a way to access the languages picks

http://forums.wolflair.com/showthread.php?t=55254

**Comment by shadowchemosh** [comment]
Livename is your friend. For example look at all the adjustments I just added into GitHub actually. These all for all sorts of things to have there name changed.

Basically if you know the exact language you can do the following after its live:
**Render 99999999**
`hero.childfound[laXXXXX].field[livename].text &= " (Whatever You want to append)".`

Replace laXXXX with your language Unique ID.

Oh that is you over on the forums that asked the same question. =)

**Comment by grandchefpanda** [comment]
@shadowchemosh My Thanks, each time you help me I go further in the understanding of Herolab scripts. I will check your scripts you just added. #176
