### ISSUE TITLE
Cleric spell/War Priest issue

### ISSUE THREAD

**Issue by Percy-Ikana** [Sklore/HL_DD_5e_Colab#175]
The level of spells a cleric can cast is off, ex. it says a lv 10 cleric has access to lv 6 spells
The amount of times that the War Priest ability can be used is over by one.

![capture1](https://cloud.githubusercontent.com/assets/17689351/13555758/6a6ed282-e38e-11e5-9f05-9591c93fe0d6.PNG)
![capture](https://cloud.githubusercontent.com/assets/17689351/13555759/6a6f381c-e38e-11e5-8b62-966927709a9f.PNG)

**Comment by shadowchemosh** [comment]
Thanks for the bug report...

The 6th level spells issue appears to be a LW issue and a big one.  Looks like ALL full-casters have this issue of getting 6th level spells at level 10.  If you add 10 levels of wizard or sorcerer they are getting 6th level spells. =(

The War Priest ability uses a built in mechanic from LW to calculate the uses per day.  Which also appears to be a bug. =(

I have reported these both to LW.

**Comment by grandchefpanda** [comment]
Hope they release next version soon, there are some nasty bugs.

**Comment by shadowchemosh** [comment]
Honestly.  I would not expect one for a few weeks or more.  I think this extra game system they did has really stretched their already thin resources to the max.  On the good side maybe its enough for them to hire more help actually.

**Comment by shadowchemosh** [comment]
I did get a note that this will be fixed in the next LW update. So closing out the ticket.
