### ISSUE TITLE
Updating COM_5ePack_PHB - Backgrounds

### ISSUE THREAD

**Issue by HippyCraig** [Sklore/HL_DD_5e_Colab#178]
I am currently going through and updating and replacing the Placeholder text on this file.

**Comment by Sklore** [comment]
:+1:

**Comment by Churchill92** [comment]
Any idea where you are at on this @HippyCraig ? I can start somewhere in the middle or end to divvy up the work to expedite the process.

**Comment by HippyCraig** [comment]
Yes please I can use some help, work got in the way the past couple of days.  I have been focusing on General Tab/Abilities and Background Tab/Background.

I have been trying to reword the core descriptions while adding my own flavor text to keep it interesting but keeping the same feel as the original.  Since this is the core rule book I am trying to take my time and get it right.

The other items are open to be updated if you want to jump on the others.  It would be a great help!

**Comment by Churchill92** [comment]
I am going to start at the bottom of Background Tab/Background and work up. I'll keep you apprised of my progress. I'll just upload the information in a text file for someone to add to the files.

**Comment by HippyCraig** [comment]
I would per if you stayed off the tab Im working on I have a system going

**Comment by HippyCraig** [comment]
There are other tabs that need attention as I put above

**Comment by Churchill92** [comment]
Which other tabs need updating then? I see only the mention of Abilities and Background. Do you have a specific one in mind? 

I might be missing something here.

**Comment by HippyCraig** [comment]
Attached file, the ones in Yellow, these all need work on:
![2016-03-09_14-32-56](https://cloud.githubusercontent.com/assets/17074456/13647887/273a889e-e604-11e5-8474-2e0015d22edc.png)

**Comment by HippyCraig** [comment]
Churchill92, how are you making out with the above items?  I have had a lot of real job work for the past week or so.  

I am hoping to finish up the two area's I started, the General Tab/Abilities and Background Tab/Background.

**Comment by HippyCraig** [comment]
I have updated the following Tabs in the backgrounds:
    General Tab/Abilities and Background Tab/Background.
I wanted to get this in in case there was a need to put another release out and at least the core descriptions are updated.  I will work on the other items next, Bonds, Flaws, etc.

**Comment by xdy** [comment]
I've added descriptions to some of the backgrounds and fixed Pirate and Sailor (HL complained that a Pirate ought to add Ship's Passage.

**Comment by LordMorin** [comment]
Accordign to the PHB, you MAY pick Bad Reputation or keep Ship's Passage (one of the other).

**Comment by HippyCraig** [comment]
All the Descriptions were done, did you check before uploading new content?

**Comment by xdy** [comment]
descriptions:
Gah. Sorry. I should know better than to trust my git knowledge. Now to figure out how to roll back my changes...

pirate:
Yeah, I changed Pirate to allow that, but not Sailor. Still, as per above I'll soon roll back my changes. Once I figure out how to...

**Comment by HippyCraig** [comment]
I can replace it with what was up there before the change.

**Comment by xdy** [comment]
Yes, thank you, please do that. Meanwhile, I'll read a few more git manual pages. And go to bed. Both will help with not messing up. :)

**Comment by HippyCraig** [comment]
No Problem, I restored the original file.  Luckily I had an original one still local.    In the future what I would do is make your own branch to work in, uploaded your changes there, and you can do a pull request that some can review before merging it back to the master branch.

Hope that helps!

**Comment by xdy** [comment]
Thank you! I guess shortlived branches is the way to think with git. As githubs interface hints rather strongly. (I.e. update master, create branch, edit file, create pull request, delete branch once merged.)

**Comment by Sklore** [comment]
Can you guys add a status tracker at the top of this issue so we all have visibility on progress?

**Comment by HippyCraig** [comment]
I'm really sorry just haven't had the time with work getting in the way, if someone wants to take over from here.  The updated descriptions that I have are already in the branch, they can take the latest and start there

**Comment by HippyCraig** [comment]
In the future I will try to only take on what I can finish in a short time frame.  Again my apologies.

**Comment by Sklore** [comment]
No need to apologise mate. I'm in the exactly the same situation which is why I think the info will help. Then we know where others are up to so we can step in and help. I've been flat out for a few weeks and stepping back into the issues yesterday was a bit like 'shot where do I start'  😉

**Comment by HippyCraig** [comment]
I was able to merge in the last my changes, there are still bonds, etc that need to be updated. I put in a pull request for you to review

**Comment by Sklore** [comment]
Reviewed and approved :+1:

**Comment by Sklore** [comment]
Placeholders for all PHB Personality Traits replaced with paraphrased text in commit above.

**Comment by Sklore** [comment]
Bond Flaw and Ideals are outstanding for the following:

Noble, Knight, Outlander, Sage, Sailor, Pirate, Soldier, Urchin

**Comment by Sklore** [comment]
Bond Flaw and Ideals are outstanding for the following:

Sage, Sailor, Pirate, Soldier, Urchin

**Comment by Sklore** [comment]
#178 - Replaced Placeholders in Background (Sage)

Bond Flaw and Ideals are outstanding for the following:

Sailor, Pirate, Soldier, Urchin

**Comment by Sklore** [comment]
#178 - All PHB background placeholders replaced with paraphrased text.
