### ISSUE TITLE
D&D 5E Bard Features

### ISSUE THREAD

**Issue by MickMcKee** [Sklore/HL_DD_5e_Colab#183]
-Jack of All Trades(player's Handbook 54). Should it not, in most cases, add that bonus to Initiative?

 -Additional Magical Secrets(Player's Handbook 55). This should not count against the number of bard spells known by the Bard.

**Comment by Sklore** [comment]
Jack of all Trades is not a Community Pack element. Please report this issue directly to LW via their support method. 

Additional Magical Secrets is part of the College of Lore which was included in the SRD and therefore part of the official 5e SRD pack. Please report this issue directly to LW. 

**LW Support for 5e**: http://forums.wolflair.com/showthread.php?t=54821
