### ISSUE TITLE
Where is the weapon type for Unarmed Strike?

### ISSUE THREAD

**Issue by profK** [Sklore/HL_DD_5e_Colab#184]
Hi,
In my world unarmed Strike is a finesse attack(it can be STR or DEX based.)

What file is that in and how would I change that? Can I do it form the editor or do I need to hack the xml?

thanks

JK

**Comment by Sklore** [comment]
Unarmed strike is not  something we have control of to my knowledge. You can see it listed under:

Editor > Race > Natural Attacks > wUnarmed

From there you can make some adjustments. This is not something controlled by the Community Pack though so you would be better seeking guidance directly from Lone Wolf.

**Comment by profK** [comment]
Thanks, at least I know where to look now :)
