### ISSUE TITLE
Updating COM_5ePack_BOLS5e - Spells

### ISSUE THREAD

**Issue by Sethvir** [Sklore/HL_DD_5e_Colab#185]
**STATUS**
Spells A - G complete
Spells G - Z

**OUTSTANDING**

**Comment by Sklore** [comment]
:+1: nice work!

**Comment by Sklore** [comment]
Having just seen one of these... damn mate nice work! You've really gone to town on the formatting.

**Comment by Sethvir** [comment]
You did the heavy lifting by getting them all in a .user file in the first place, which makes editing what's already there that much easier.  Depending upon when you all decide to do another push out community pack, i'll upload where ever I am at that point.

**Comment by Sethvir** [comment]
Having a bit of difficulty pushing up the changes I've made thus far for BOLS, plus the new EN5ider material I have done.  Using Source Tree and added a new branch here as that was what I thought I needed to do push up file changes, but for some reason I can't seem to get the new files to push up through SourceTree.  What configuration am I missing? Tim or Josh?

**Comment by shadowchemosh** [comment]
What error are you getting?  Sorry what you saying is not giving allot of information to work on.  Have you commit anything to the repository successfully yet?  Are you setup to be able to push changes?

**Comment by Sethvir** [comment]
Sorry Tim.  Not in front of that computer right now.  I have a Hero Lab 5e that I pull changes from the Master file for this group and then I have a working one where I worked on the files.  I moved them over to the one connected to this group and Source Tree recognized that the files were different.  I marked them to commit changes so the files moved from the bottom window to the top window and that is as far as I got.  I tried to push them up to my directory here, Sethvir_changes and not to the master but for some reason it isn't uploading them.  Never had a problem when I was doing the Pathfinder ones with you before. I'm wondering if there is some setting that I don't have correct on Source Tree.

**Comment by shadowchemosh** [comment]
When you get in front of the computer sourcetree must be giving you some type of error when you do the "Push".  Copy and paste it and we can see what we can figure out.  

Its possible Sklare didn't add you as a contributor.  Any one can pull down the source but only authorized accounts can upload or make changes.  I have done that before. =)

**Comment by Sklore** [comment]
Hes a contributor so must be something else.

**Comment by Sethvir** [comment]
Ok.  In front of the PC now.  They are listed and checked as staged.  I click the Push button and it opens a dialog box Push: 5e Community and a box that shows Push to Repository [origin] and the https://github.com/Sklore/HL_DD_5e_Colab. Then the section about Branches to Push.  

Push     Local Branch   Remote Branch     Track
[Empty]    master            [master]                [empty]

**Comment by shadowchemosh** [comment]
Hmmm sense you created your own branch back on March 3rd have you done any new merges/pulls to get all the latest changes from the Master?  I am seeing LOTS of changes to the files sense you did your Branch.  First step is to bring your Branch up to the current Master version before you can push it back up.  Otherwise you will rollback the master to the files of March 3rd...

**Comment by shadowchemosh** [comment]
If you go to this link you can see your Branch is 141 commits behind the master:
https://github.com/Sklore/HL_DD_5e_Colab/tree/Sethvir_Changes

**Comment by Sklore** [comment]
I find its better to pull daily and push as often as necessary. I know do little chunks of things at a time and will always push my changes the day they are made to avoid these issues. 

With that said i do keep over-ridding changes made by others someone... Impressive given i'm in a completely different time-zone and working outside of the hours worked by most of you...

**Comment by Sethvir** [comment]
What time zone?  I'm in EDT.  I'm going to have to look at this again this weekend. Source Tree and my files are giving me issues right now.  I'll have to relook at this again this weekend when I have time.

**Comment by Sklore** [comment]
Im in UTC/GMT +9:30 hours

**Comment by Sethvir** [comment]
I'm not sure the files pushed up to the Sethvir_changes directory.

git -c diff.mnemonicprefix=false -c core.quotepath=false push -v --tags --set-upstream origin master:Sethvir_Changes
Branch master set up to track remote branch Sethvir_Changes from origin.

Pushing to https://github.com/Sklore/HL_DD_5e_Colab
To https://github.com/Sklore/HL_DD_5e_Colab
 = [up to date]      master -> Sethvir_Changes
 = [up to date]      V1.2 -> V1.2
 = [up to date]      v1.0 -> v1.0
 = [up to date]      v1.1 -> v1.1
updating local tracking ref 'refs/remotes/origin/Sethvir_Changes'
Everything up-to-date

**Comment by Sklore** [comment]
I dont think this worked. I can't see any recent commits by you. You can always update it manually. That's the way i do it.

**Comment by Sethvir** [comment]
Ok, since I couldn't seem to push up the files via Source Tree I have manually added them via Upload to my branch.  Hopefully I have done this correctly.  5 En5ider articles and updates to the Book of Lost Spells A-G.

**Comment by shadowchemosh** [comment]
@Sethvir your changes are in your "Branch" but not in the main yet =(

**Comment by shadowchemosh** [comment]
I am pulling the files down manually to my system and will push to Main.  Note you have the files have the wrong name so will fix that.....

**Comment by Sethvir** [comment]
Which files?

**Comment by shadowchemosh** [comment]
Just the EN5ider files from your branch.  If you look in this thread you will see the commit logged against and can see the exact files added....

**Comment by Sethvir** [comment]
Still working on updating these spells.

**Comment by Sethvir** [comment]
After a long hiatus due to RL, back to working on this again to get them whipped into shape.  Going to be a while though.

**Comment by Sklore** [comment]
G-Z Complete
