### ISSUE TITLE
Shadow Adjustments - New for 5e...

### ISSUE THREAD

**Issue by shadowchemosh** [Sklore/HL_DD_5e_Colab#189]
This holds useful adjustments that should be added for the 5e Community.  Using this as a To-Do reminder note to myself.

Change any spellcasting class casting attribute:
http://forums.wolflair.com/showthread.php?t=55281

Change weapon type information of item. (ie make a weapon finesse)
http://forums.wolflair.com/showpost.php?p=225720&postcount=97

**Comment by Sklore** [comment]
@shadowchemosh - can this be closed now?

**Comment by shadowchemosh** [comment]
Sure. Was just keeping a to do list for myself so I didn't forget.
