### ISSUE TITLE
Monk martial arts damage is messed up

### ISSUE THREAD

**Issue by stevehammer** [Sklore/HL_DD_5e_Colab#190]
Unless I'm missing errata, the Monk Base class, specifically the Martial Arts ability, is incorrect. In HL, it's shown as the following:

At Levels 1-3, the damage is D4
At Level 4, the damage is D6
At Levels 5-9, the damage is D8
At Levels 10-14, the damage is D10
At Levels 15-19, the damage is 2D6
At Level 20, the damage is 2D8

The correct values are 1-4, d4, 5-10, d6, 11-16, d8, 17-20, d10.

The corrected script for these values is below:

**Comment by Sklore** [comment]
The monk base class is controlled by the core pack and as such this issue will need to be reported to LW. 

http://forums.wolflair.com/showthread.php?t=54821

**Comment by stevehammer** [comment]
thanks. that was a very quick response!
