### ISSUE TITLE
SUPPORT CEASED - Fifth Edition Feats - 162 New Feats

### ISSUE THREAD

**Issue by Sklore** [Sklore/HL_DD_5e_Colab#195]
Have added Fifth Edition Feats by TPK Games. 
http://www.drivethrurpg.com/browse/pub/3782/Total-Party-Kill-Games

Raising this ticket for tracking on scripting of pre-requirements and feat abilities.

**SCRIPTING COMPLETE**
Acrobatic
Acrobatic Steps
Agile Maneuvers
Alertness
Animal Affinity
Arcane Shield
Arcane Strike
Athletic
Augmented Conjuring
Backstab
Beast Slayer
Blind-Fight
Blocking Expertise
Bodyguard
Bouncing Spell
Burning Spell
Catch Off-Guard
Channel Smite
Charging Expertise
Cleave
Combat Caster
Combat Expertise
Combat Reflexes
Command Undead
Concussive Spell
Crossbow Expertise
Danger Sense
Darting Strike
Dazzling Display
Deadly Stroke
Deceitful
Defensive Combat
Defensive Expertise
Defensive Weapon
Deflect Arrows
Deft Hands
Demon Slayer
Diehard
Dirty Fighter
Disarm Expertise
Disorienting Blow
Disrupting Strike
Disruptive Spell
Distant Spell
Dodging Expertise
Dragon Slayer
Dreadful Carnage
Dungeoneer
Eagle-Eyed
Elemental Channel
Elemental Focus
Elemental Mastery
Elemental Spell
Empowered Spell
Endurance
Extended Spell

**PENDING SCRIPTING**
Duelist - Issue (How to +1 AC when PC is fighting with single weapon and shield?)
Extra Channel (Increase Channel Divinity uses by 3?)
Extra Fighting Style (Increase fighting style by 1?)
Extra Ki
Extra Lay On Hands
Extra Inspiration
Extra Rage
Extra Skills
Favored Defense
Feint Expertise
Fight On
Fleet
Fortuitous
Giant Slayer
Great Fortitude
Great Strength
Great Weapon Expertise
Grappling Expertise
Healing Chakra
Heavy Armor Expertise
Heavy Armor
Heighten Spell
Herbal Healer
Heroic Defiance
Improved Beast
Improved Channel
Improved Critical
Improved Initiative
Improvised Weapon
Initiate
Inspiring Leadership
Iron Will
Ironskin
Keen Intellect
Light Armor
Lightning Reflexes
Lightning Stance
Lookout
Linguistics Expert
Lunging Attack
Lycanthrope Slayer
Magical Aptitude
Mage Killer
Manyshot
Master Craftsman
Medium Armor Expertise
Medium Armor Proficiency
Mobility
Mounted Warrior
Overrun Expertise
Parry Spell
Parting Shot
Penetrating Strike
Persistent Spell
Persuasive
Point-Blank Shot
Polearm Expertise
Power Attack
Physician
Quick Draw
Quicken Spell
Raging Strength
Raging Vitality
Rapid Shot
Razortooth
Ritualist
Rousing Performance
Savage Warrior
Selective Spell
Sharp Shot
Shield Expertise
Shield Mastery
Shield of Swings
Sidestep
Skill Focus
Slam Expertise
Snap Shot
Spell Assassin
Spell Focus
Spell Mastery
Spell Penetration
Spirited Charge
Stand Still
Stealthy
Steel Soul
Steeled Mind
Strike Back
Strong Personality
Subtle Spell
Sunder Expertise
Taunt
Thespian
Thundering Spell
Toppling Spell
Toughness
Trip Expertise
Twinned Spell
Two-Weapon Fighter
Two-Weapon Fighting Mastery
Two-Weapon Rend
Undead Slayer
Unarmed Fighting
Weapon Expert
Weapon Specialization
Widen Spell
Wise

**Comment by Sklore** [comment]
Collecting useful Scripts
**Attribute is greater or equal to:**
Expr-reqs
#attrvalue[aSTR] >= X
#attrvalue[aDEX] >= X
#attrvalue[aCON] >= X
#attrvalue[aINT] >= X
#attrvalue[aWIS] >= X
#attrvalue[aCHA] >= X

**Can can spell?**
Pre-req
        ~ Test that the character has at least one spell
        ~ or spell-like ability. &
        var HasSpells as number
        Call 5CHasSpell
        @valid = HasSpells

**Proficient with armor?**
Expr-reqs
tagis[ArmProfGrp.ArmorLight]  <> 0
tagis[ArmProfGrp.ArmorMed] <> 0
tagis[ArmProfGrp.ArmorHeavy] <> 0

**Proficient with skill?**

**Proficient with tool?**

**Comment by grandchefpanda** [comment]
I have also a collection of scripts. Perhaps we can do a wiki page for them.

**Comment by Sklore** [comment]
Thats a good idea actually. Would make the likes of me much more efficient when it comes to scripting :) I'll make one now and add these.

**Comment by grandchefpanda** [comment]
I'm add my scripts tonight

**Comment by Maikera** [comment]
Hi everbody, can someone just check this first try on this issue ? Am i doing everything right ?

**Comment by Sklore** [comment]
Working on my end :+1: 

Acrobatic needs to check for Acrobatics proficiency also. 

Impressive that you figured out how to get the pick working on Acrobatic working already though, well done. 

Tip: When commenting on Commits (or anything really) within GitHub thats related to an open issue, add #<Issue Number> to link the comment and it will link in this page so we can see what's happening related to the issue.

**Comment by Maikera** [comment]
Can't find how to differentiate the arcanes spells from other spells, like nature or holy, to set the prerequisite on the Arcane Shield feat #195

**Comment by Maikera** [comment]
#195 Need help at Arcane Strike feat scripting, need to verify if there's weapon equiped, then add +1 bonus.

**Comment by grandchefpanda** [comment]
I've done that for a monster, I'll check and give you a script

**Comment by grandchefpanda** [comment]
The tags to check ar Hero.EquipMain

Here an exemple where if a weapon is equiped it add the wisdom bonus to the armorclass

PostAttr 10000

> ~ If we're disabled, do nothing 
>  doneif (tagis[Helper.Disable] = 1)
>   if (hero.tagis[Hero.EquipMain] = 1) then
>       hero.child[ArmorClass].field[Bonus].value += #attrmod[aWIS]
>   endif

**Comment by grandchefpanda** [comment]
You can check another exemple in Psychic Defense ability

**Comment by Maikera** [comment]
Thanks chef !

**Comment by Maikera** [comment]
@grandchefpanda 

```
~ If we're disabled, do nothing 
doneif (tagis[Helper.Disable] = 1)
if (hero.tagis[Hero.EquipMain] = 1) then
hero.child[Damage].field[Bonus].value += 1
hero.child[Attack].field[Bonus].value += 1
endif
```

It worked, but this is also working for unarmed attack. shouldn't. Am i missing something ?

**Comment by grandchefpanda** [comment]
This will add the bonus to the weapon itself, ignoring natural weapons

> foreach pick in hero from BaseWep where "!(wGroup.Natural) & (Hero.MainHand)"
>         eachpick.Field[wAttBonus].value += 1
>         eachpick.Field[wDamBonus].value += 1
> 
>         nexteach

**Comment by grandchefpanda** [comment]
corrected script last post, should always include Helper disable

**Comment by Maikera** [comment]
Have working in the feats #195 prerequisites, Acrobatics to Deflect Arrows with all attribute and some feats prerequisite done.

Need help with few feats that i couldn't figure out how to script them:

-Arcane Strike (couldn't make the panda's script work :/ )
-Augmented Conjuring (did the feat prerequisite work but the need to be with Conjuration school)
-Bouncing Spell (Don't know how to put prerequisite of 2nd lvl spell or grater)
-Chanel Smite (There are 2 Channel Divinity and 1 Lay on Hands, must have one of theses, couldn't figure out how to make a "or" structure.)

Thank for the patience.

**Comment by grandchefpanda** [comment]
I didn't work because you had the Helper.Disable Tag on the feat and my script check for it.
I've corrected that with #2f4a44caea5de86f04062f1200358d7723c047dd

**Comment by Maikera** [comment]
#195 Manage to make Channel Smite feat prerequisite work whit #hasability macro, but can't make the Deamon Slayer prerequisite work because you have to have either Arcana or Religion proficiency and i didn't find any macro for skill proficiency to use in a "or" structure.

`<validate>~ Check whether the Channel Divinity or Lay on Hands ability is active
@valid = #hasability[cClrChaDiv]
@valid = #hasability[cPalLayHan]</validate>`

**Comment by Maikera** [comment]
#195
I tried, with no success, find any example of how make a prerequisite for the feats that require proficiency with skill in "or" structure, example: STR or DEX 13 required.

I just know how to do in "and" structure, like " STR and DEX 13 required " with #attrvalue[aSTR] >= X, and i cant use the "@valid" with this script.

Also, i dont know how to flag the ability to cast 2nd lvl spells to make prerequisite.

I really need some help to do those prerequisite script. Pleaaaaseeee !!!!

**Comment by xdy** [comment]
I added some basic scripting to most feats, see https://github.com/Sklore/HL_DD_5e_Colab/pull/334
If someone has a more complete file, feel free to overwrite my stuff, or merge as you see fit. :)

**Comment by xdy** [comment]
Of course, only now that I merged those did I find Maikeras branch, where everything I've done, and lots more, has already been done. <sigh>
Sorry @Maikera ... As I said above, feel free to overwrite my stuff when you decide to merge your branch.
Oh well, at least I make new mistakes every time...

**Comment by Sklore** [comment]
Branches need to be merged regularly or they run the risk of not being accepted due to code changes.

**Comment by xdy** [comment]
Yeah, that's what caused my mistake, I keep my work branches for at most
a day and assumed everyone else did the same (as I said, at least I make
*new* mistakes. :) I just plain forgot to look for a work branch with
changes to this file before I started...

Not sure I'll get anywhere (other than frustrated at git for not working
like any other vcs :), but I'll try to figure out how to merge the files
locally and see if I accidentally added anything Maikera hadn't done
already. :)

/Jonas

**Comment by Maikera** [comment]
I am so sorry guys, i didn't had any time in the last few weeks to continue the work with the feats #195, life just got crazy.

I will try to continue scripting and merge frequently to avoid theses misunderstanding among us.

@xdy Don't worry dude, i got away for awhile, so it's my fault that this issue got freezed.

**Comment by Sklore** [comment]
:) No need to stress. It's a learning curve for us all. If the file hasn't specifically been changes then you should be able to copy the changes in that specific file into a new updated branch and it should all work out.

**Comment by xdy** [comment]
No worries @Maikera , how much free time/energy I have is also, um, highly variable. :)

I'll just wait till you've merged (simply overwrite the file in mater, yours is far more complete) and then I'll add in the changes I had that weren't in your file. (Simple scripting after the Iron Skin feat basically, and a couple of typos I noticed.)

**Comment by Maikera** [comment]
@xdy Ok then, 

I noticed that you had problems doing a "or" structure, like "str or dex 13" required, i was a pain to me to figure out how to do this, i have examples now, it will make our job easier.

I will try to merge then, and we can continue from there.

**Comment by xdy** [comment]
Great!

**Comment by Maikera** [comment]
#195 merged with all i have done so far.

Thank you for the patience

**Comment by xdy** [comment]
Great job! I'll go right ahead and add in what little I had done that you hadn't (I'll only change feats from Improved Initiative and on, will merge within an hour or so I guess.)

**Comment by xdy** [comment]
All I did before has been added to the file, along with fixing some typos I had noticed. Still a lot to go, among other things about half the prereqs in the latter half of the file are missing. But, it's definitely time for me to hit the sack now as it's technically tomorrow. :)

**Comment by Maikera** [comment]
Nice work @xd. And thank you for correcting my grammar mistakes =)

**Comment by Maikera** [comment]
Did almost all prerequisite that was needing script, only this three that i really need some help:

Augmented Conjuring;
Skill Focus;
Weapon Specialization.

Can't do those right now, any help would be very wellcome.

**Comment by Sklore** [comment]
Your conjured creatures are more powerful and robust. 

{b}Prerequisite:{/b}  Spell Focus (Conjuration) 
• Each creature you conjure with any summon spell gains a +2 bonus to attacks and damage and a bonus of +2 hit points per HD for the duration of the spell that summoned it.

**Comment by Maikera** [comment]
@Sklore exactly those, i don´t know how script these prerequisites, for example, the Augmented Conjuring, to be able to use this feat you need to have the spell focus feat and must have chosen the conjuration school, i know how to script only the need of the feat, the specification of the magic school i dont know how to script.

I also dont know how to make the user pick a skill and then gain proficiency in that skill in the skill focus feat, and dont know how to make the user pick a weapon and then check if the user is proeficient with the selected weapon.

**Comment by Sklore** [comment]
Yeah I posted so we could have a look at what needed to be done. Beyond my capability I'm afraid. I would suggest asking @shadowchemosh . He has a wealth of experience.

**Comment by shadowchemosh** [comment]
**{b}Prerequisite:{/b} Spell Focus (Conjuration)** 

Well to do the spell focus test you would first have to script the Spell Focus feat to work.  Otherwise how can you test to see what was selected?  I started adding Magic School logic to 5E only to learn that the why individual Spell DCs are calculated correctly they are NOT displayed anywhere. So even if I make this stuff work you won't see the values reflected anywhere.  Sigh...

Another "Bug" to report to LW...

So why did you guys use hero.tagis[HasFeat.?] feat logic instead of just using the macro #hasfeat[] as its less typing. =)

**Comment by shadowchemosh** [comment]
I see this script logic in feats still:
```
    <arrayval field="usrArray" index="0" value="Strength"/>
    <arrayval field="usrArray" index="1" value="Constitution"/>        

    <eval phase="First"><![CDATA[
       ~ If we're disabled, do nothing & 
       doneif (tagis[Helper.Disable] = 1)
 
       if (field[usrIndex].value = 0) then
         hero.child[aSTR].field[aStartMod].value += 1
       elseif (field[usrIndex].value = 1) then
         hero.child[aCON].field[aStartMod].value += 1
       endif]]></eval> 
```

While that works its not really the best way.  Its much easier to simply go directly after the live Pick on a character instead.  Makes the code super flexible and easier to change.

Here is the script logic I did in the 5e CORE feats:
```
    <fieldval field="usrCandid1" value="component.BaseAttr &amp; (thingid.aSTR|thingid.aCON)"/>
    <eval phase="First"><![CDATA[
      ~ If we're disabled, do nothing & 
      doneif (tagis[Helper.Disable] = 1)
      ~ If nothing chosen then get out now!
      doneif (field[usrChosen1].ischosen = 0)
      
      ~ Increase the selected ability score by 1
      field[usrChosen1].chosen.field[aStartMod].value += 1
     ]]></eval>
```
The custom expression controls which attributes are displayed and allowed to get +1.  The script logic itself is 100% reusable all over the place and requires no changes.  This could even be added into a Procedure making adding the script or modification of the script even easier. =)

Just an FYI.

**Comment by Maikera** [comment]
@xdy Im afraid that i merged a file with the skill focus feat working, but was a old file that undid what you have done with the # hasfeat, sorry about that, my mistake.

**Comment by xdy** [comment]
No worries, I did the same to someone else earlier. :)

**Comment by Sklore** [comment]
Have updated the master list above showing 1/3 of feats are now complete. Well done guys, way more progress than I thought had happened here.

**Comment by Sklore** [comment]
Support for this product has now ceased, This will be hidden from the community pack in the next release.
