### ISSUE TITLE
Detect if a pick (a Weapon) is present on the hero

### ISSUE THREAD

**Issue by grandchefpanda** [Sklore/HL_DD_5e_Colab#196]
for the Aarakocra, the javelin must be a finesse weapon.
I've done this script 
prelevel 10000
perform hero.child[wJavelin].assign[wProperty.Finesse]

but it give an error if the wJavelin is not present, how can I detect the presence of the pick ?

**Comment by LordMorin** [comment]
This worked for a test ability I just threw together.  

First 2500
  ~ If we're disabled, do nothing
    doneif (tagis[Helper.Disable] <> 0)

    foreach pick in hero from BaseWep where "thingid.wJavelin"
      perform hero.child[wJavelin].assign[wProperty.Finesse]
    nexteach

**Comment by shadowchemosh** [comment]
You will have to use a for each loop. A character can have multiple weapons of type Javelin. This is an exception to the avoid foreeach loop. 

But don't use thingid tags. Bad. You want to use IsWeapon.wJavelin 

That way you find weapons that are to be treated LIKE a javelin.

**Comment by LordMorin** [comment]
New to using 'foreach'. I thought it was a loop. :(

I threw this together with a tad of research through examples I already had. :)
I'll take another look at it.

**Comment by grandchefpanda** [comment]
so the script should be ?
```
~ If we're disabled, do nothing
doneif (tagis[Helper.Disable] <> 0)

foreach pick in hero from BaseWep where "IsWeapon.wJavelin"
  perform hero.child[wJavelin].assign[wProperty.Finesse]
nexteach
```

**Comment by LordMorin** [comment]
Like shadowchemosh said, this only finds the first instance of a javelin, not any others the hero is carrying. 

Trying to puzzle it out atm. :)

**Comment by shadowchemosh** [comment]
Almost. I missed the hero.child[] section last time.  For a foreach loop you have to change out the hero.child with with eachpick.  Eachpick means this "Instance" the loop has found.

so it becomes:

```
~ If we're disabled, do nothing
doneif (tagis[Helper.Disable] <> 0)

foreach pick in hero from BaseWep where "IsWeapon.wJavelin"
  perform eachpick.assign[wProperty.Finesse]
nexteach
```

**Comment by LordMorin** [comment]
shadowchemosh:

I don't see any changes . . .

**Comment by LordMorin** [comment]
bah, foudn the change glaring at me. It's ALIVE! :)

**Comment by grandchefpanda** [comment]
thanks, will implement it soon

**Comment by LordMorin** [comment]
I always try to learn soemthign new once per day in HL. Most of the time it is something like 10-20 new thigns. :)
