### ISSUE TITLE
Swashbuckler from SCAG

### ISSUE THREAD

**Issue by Entola** [Sklore/HL_DD_5e_Colab#202]
Would be nice if we could add the Swashbuckler from SCAG. I can't do the scripting but is there anything I could do to assist in completing this task?

**Comment by Sklore** [comment]
I've been working through these.  There are quite a few scag  classes added in need of someone to confirm the scripting.  I'll add this one to my to do list today.

**Comment by Sklore** [comment]
Ok this has been added. I couldn't see any drastic need for scripting yet but i'll have a better look later. 

Probably just needing a script on Rakish Audacity. +Cha on Initiative

**Comment by grandchefpanda** [comment]
Scripted the Rakish Audacity. +Cha on Initiative

**Comment by Sklore** [comment]
:+1:  beat me to it

**Comment by grandchefpanda** [comment]
I had done something similar on the Cambion

**Comment by Sklore** [comment]
This will be release in the next pack. Thanks for the request.
