### ISSUE TITLE
Elemental Evil Player's Companion

### ISSUE THREAD

**Issue by xdy** [Sklore/HL_DD_5e_Colab#209]
**STATUS:** Complete

**OUTSTANDING:**

**COMPLETE:**
Feat > Pre Req of Svirneblin Magic (Sub Race = Deep Gnome)
Racial Special > Powerful Build > You count as one size larger when determining your carrying capacity and the weight you can push, drag, or lift.
Race > Aarakocra
Race > Genasi
Sub-Race > Air Genasi
Sub-Race > Earth Genasi
Sub-Race > Fire Genasi
Sub-Race > Water Genasi
Race > Goliath
Sub-Race > Deep Gnome
Spell > Mechanic Text > Control Winds
Spell > Mechanic Text > Dust Devil
Spell > Mechanic Text > Earth Bind
Spell > Mechanic Text > Elemental Bane
Spell > Mechanic Text > Erupting Earth
Spell > Mechanic Text > Flame Arrows
Spell > Mechanic Text > Immolation
Spell > Mechanic Text > Investiture of Flame
Spell > Mechanic Text > Investiture of Ice
Spell > Mechanic Text > Investiture of Stone
Spell > Mechanic Text > Investiture of Wind
Spell > Mechanic Text > Maelstrom
Spell > Mechanic Text > Maximillan's Earthen Grasp
Spell > Mechanic Text > Mell;s Minute Meteors
Spell > Mechanic Text > Primordial Ward
Spell > Mechanic Text > Pyrotechnics
Spell > Mechanic Text > Skywrite
Spell > Mechanic Text > Snilloc's Snowball Swarm
Spell > Mechanic Text > Storm Sphere
Spell > Mechanic Text > Tidal Wave
Spell > Mechanic Text > Transmute Rock
Spell > Mechanic Text > Vitriolic Sphere
Spell > Mechanic Text > Wall of Sand
Spell > Mechanic Text > Wall of Water
Spell > Mechanic Text > Wall of Wind
Spell > Mechanic Text > Watery Sphere
Spell > Mechanic Text > Whirlwind

I'll start this now. Will try to do a pull request when done. (I.e. I don't know git. :)

**Comment by grandchefpanda** [comment]
Try to separate things into multiple files like the player handbook so we stay organized

**Comment by xdy** [comment]
Just made a pull request. Who knows, I might even have done it right. (For definitions of right including cursing repeatedly at the way git is (maliciously it seems) as different as possible from svn, clearcase and tfs. :)

**Comment by shadowchemosh** [comment]
I actually prefer Git over SVN and especially over TFS.  To me it makes more logical sense.  But I admit I am very strange. =)

**Comment by shadowchemosh** [comment]
By the way maybe its me but I HATE three letter acronyms.  I would think instead of calling the file EEPC be better to put "Elemental Evil Players Companion".  No confusion down the road then.

But if everyone is great with the EEPC and know what is that is cool.  But sometimes as things grown its nice to have the full name. =)

**Comment by xdy** [comment]
re: cvs/git/svn/cc/tfs/etc
It's likely that git:s main problem is that I've been using the others in anger for years whereas git is this newfangled contraption that nobody's paid me to use yet. I.e. 'Git off mah lawn!' :)

As for the rest of the book, I got stuck on Goliath last time I tried (think I deleted the file after deciding to not play a Goliath), but I'll give it a whirl tomorrow or maybe thursday. (The problem with Goliath was how to do 'Powerful Build'.)

**Comment by IrondrakeX** [comment]
I've been rather quiet lately with work picking up and all, but I would like to express my opinion on acronyms.  

Typically people with a clue about the product will be able to pick up on an acronym but for everyone else it's just confusing.  We should stay away from any acronym outside of the PHB or DMG.

**Comment by shadowchemosh** [comment]
> As for the rest of the book, I got stuck on Goliath last time I tried (think I deleted the file after deciding to not play a Goliath), but I'll give it a whirl tomorrow or maybe thursday. (The problem with Goliath was how to do 'Powerful Build'.)

Because 5e is pulled from Pathfinder code I am pretty sure this will be easy.  Well assuming that Powerful Build basically works the same that is.  Its a simple assign tag to hero.

Does anyone have the 5e text for what "Powerful Build" is and how it works?

**Comment by LordMorin** [comment]
Three letter acronyms are fine for file names, but the full name should be used somewhere so tyhe common user knows what you are referring to. :)

I use TLA's all the time for my own use. But I always, always put a reference somewhere, usually where it can't be found, even me . . . :(

**Comment by Sethvir** [comment]
FWIW, I've got the spells portion just about finished.

**Comment by shadowchemosh** [comment]
Aren't you all just funny with all the extra acronyms thrown into this thread now. Sense you all like them so much how about you all STFU! =)  

I put a smiley face after so you can't get mad....

**Comment by Sklore** [comment]
:+1:

**Comment by Sklore** [comment]
To Do:
Powerful Build Scripting?
Pre Req of Svirneblin Magic (Sub Race = Deep Gnome)

**Comment by LordMorin** [comment]
Here is what I've done for my own use with Elemental Evil. 

It contains the 3 races & associated sub-races, a few spells (I've been adding them as I need them), and Ogremoch so far. Also, Svirfneblin Magic feat, Aarakocra & Svirfneblin languages. I added a boulder weapon for Ogremoch. It works but I am not sure about it.

[soe_5e_ee.zip](https://github.com/Sklore/HL_DD_5e_Colab/files/180878/soe_5e_ee.zip)

**Comment by LordMorin** [comment]
Bah, I sent that file too early. I forgot I still hadn't completed Ogremoch. The rest should be good though.

**Comment by grandchefpanda** [comment]
Aarakocra language has already been added with this id: l5CAarakoc

**Comment by LordMorin** [comment]
I know, I figured you could take what you wanted and toss the rest. :)

**Comment by grandchefpanda** [comment]
eheh, I'll take Ogrémoch as soon as you've finished it :)

**Comment by LordMorin** [comment]
I was in a hurry to use it when I created him, left off a bunch of resistances and immunities, etc. Working on it atm.

**Comment by grandchefpanda** [comment]
Don't worry too much if something is missing.

**Comment by LordMorin** [comment]
Updated; Ogremoch should be completed.

[soe_5e_ee.zip](https://github.com/Sklore/HL_DD_5e_Colab/files/180911/soe_5e_ee.zip)

**Comment by grandchefpanda** [comment]
A lot more advanced that I've ever done this Ogremoch, trying to integrate into the community files but it will take some time. I have to study this Activate ability thing.

**Comment by LordMorin** [comment]
I may have been more complicated than I needed, or I may have taken some dirty shortcuts. :)

It was meant for my own use . . .

**Comment by Sklore** [comment]
Source file updated: 5ePotACP and 5eEEPCCP now displaying.

**Comment by xdy** [comment]
All 1st level spells and cantrips now have descriptions (as well as a few other random ones.)

**Comment by Sklore** [comment]
Completed audit of outstanding actions. Consolidated to list at top of this issue.

**Comment by Sklore** [comment]
Added missing mechanic text on spells. 

@shadowchemosh - Do you have any experience with this one? I've not come across any code so far to mess around with carrying limits. 

Racial Special > Powerful Build > You count as one size larger when determining your carrying capacity and the weight you can push, drag, or lift.

**Comment by LordMorin** [comment]
If you are talking about the Powerful Build race feature for the Goliath, this is the code I used:

Post-attributes; Priority: 10000
```

    ~if we've been replaced, get out now
    doneif (tagis[Helper.Disable] <> 0)

    herofield[tEncumLgt].value = herofield[tEncumLgt].value * 2
    herofield[tEncumHvy].value = herofield[tEncumHvy].value * 2
    herofield[tEncumMax].value = herofield[tEncumMax].value * 2
```

**Comment by Sklore** [comment]
Closing as it appears EEPC is complete. We can raise a new issue for POTA where this beast Ogremoch belongs.
