### ISSUE TITLE
Bug in Herolab, can you reproduce it ?

### ISSUE THREAD

**Issue by grandchefpanda** [Sklore/HL_DD_5e_Colab#213]
Can someone try to reproduce this problem, I reported the bug but they cannot reproduce it:

Here how to reproduce the problem:
- Install 5e community files
- Create a new portfolio
- Select NPC and player handbook and monster manual source
- Choose Mind Flayer as Race
Now all is good
- Editor
- open file COM_5ePack_PHB - Monsters.user
- select Race-Race Mind flayer r5CMMMindF
- Test now!
The value of DEX and CON become incorrect.

**Comment by shadowchemosh** [comment]
Yep I get the Dex/Con changing to 10 instead of 12.

I have to ask was it "Hollis" who said they can't reproduce the issue?

**Comment by grandchefpanda** [comment]
Nope, Aaron Beal.

**Comment by grandchefpanda** [comment]
I have this for about 20% of the monster races I have created. The only way is to restart herolab.

**Comment by grandchefpanda** [comment]
same issue with Orc Eye of Gruumsh

**Comment by shadowchemosh** [comment]
I am going to take another look tonight actually and see if I can see a cause.  If not I am going to raise this up to Colen to look at.  I am wondering if the issue is inside the HL engine (ie the binary) part of the software.  I don't see how the authoring kit could be causing the issue.

**Comment by grandchefpanda** [comment]
Perhaps this has something to do with the order of the tags

**Comment by shadowchemosh** [comment]
Nah tag order should not matter.  Each time anything changes in HL all scripts should get re-run from scratch.  My assumption is a bug in the "Test Now!" logic actually.  Because this would only affect editors its not a huge deal but LW should be notified.

**Comment by grandchefpanda** [comment]
They found it, will be solved in next herolab release. I close the case
