### ISSUE TITLE
Not sure if it's been mentioned: Magic Weapons in Normal Weapons section

### ISSUE THREAD

**Issue by Enforcer84** [Sklore/HL_DD_5e_Colab#220]
a few...ok 2 magic weapons are listed in the normal weapons, Dwarven Thrower and Hazirawn

**Comment by shadowchemosh** [comment]
Yikes that Hazirawn weapon is really messed up I think.  The text says its a Greatsword.  But when selected it lets you pick any "Sword".  And once you do it becomes a Dancing Sword.  It does not give a +1H/D and when attuned does not give the extra +2H/D and the necrotic damage. =(

I am going to go with this weapon was never finished/setup correctly.

Dwarven Thrower is from LW and an official but report about it would need to be put in:
http://www.wolflair.com/redirect/bugreport.php?project=5e

**Comment by Enforcer84** [comment]
Will do!
