### ISSUE TITLE
Sword Coast Adventures Guide

### ISSUE THREAD

**Issue by Sklore** [Sklore/HL_DD_5e_Colab#224]
Since I'm not the strongest coder among us this is likely more efficient. All SCAG class options are now loaded. The following present special abilities that need scripting to correctly display options to the player. I'll start working one the ones I'm capable but if anyone knows the solution already feel free to jump in with the code. 

**COMPLETE**
- Searing Arc Strik - Add burning hands as a known spell
- Arcan Initiate - prof in Arcana, +2 Wizard cantrips that count as cleric cantrips. 
- Arcane Mastery - choose 4x spells from wizard spell list (one from 6th, 7th, 8th and 9ths) Count as cleric spells.
- Battleranger Armor - Add in weapon attack (Spiked Armor) ***Does not handle proficiency
- Tiefling Variants - Option to choose variant traits
- Master of Intrigue - proficient in disguise kit, forgey kit and one gaming set. You learn 2 extra languages. 

**OUTSTANDING**
- Radiant Sun Bolt - Add Sun Bolt as spell attack. 
- Royal Envoy - you gain proficiency in the Persuasion skill. If you are already proficient in it, you gain proficiency in one of the following skills of your choice: Animal Handling, Insight, Intimidation, or Performance. Your proficiency bonus is doubled for any ability check you make that uses Persuasion. You receive this benefit regardless of the skill proficiency you gain from this feature.
- Add Searing Sunburst spell attack
- Song of Victory - Add Int Mod to the damage of your melee weapon attacks while your Bladesong is active. 
- Wind Speaker - You can speak, read, and write Primordial. (Knowing this language allows you to understand and be understood by those who speak its dialects: Aquan, Auran, Ignan, and Terran.)
- Half-Elf Variant - Option to choose variant traits

HALF-ELF VARIANTS
Some half-elves in Faeron have a racial trait in place of the Skill Versatility trait. If your DM allows it, your half-elf character can forgo Skill Versatility and instead take the elf trait Keen Senses or a trait based on your elf parentage: 

• A half-elf of wood elf descent can choose the wood elf's Elf Weapon Training, Fleet of Foot, or Mask of the Wild.
• A half-elf of moon elf or sun elf descent can choose the high elf's Elf Weapon Training or Cantrip.
• A half-e lf of drow descent can choose the drow's Drow Magic.
A half-elf of aquatic heritage can choose a swimming speed of 30 feet.

TIEFLING VARIANTS - How to enable the user to pick these options?
Since not all tieflings are of the blood of Asmodeus, some have traits that differ from those in the Player's Handbook. The Dungeon Master may permit the following variants for your tiefling character, although Devil's Tongue, Hellfire, and Winged are mutually exclusive. 

Appearance. Your tiefling might not look like other tieflings. Rather than having the physical characteristics described in the Player's Handbook, choose l d4 + 1 of the following features: small horns; fangs or sharp teeth; a forked tongue; catlike eyes; six fingers on each hand; goatlike legs ; cloven hoofs; a forked tail; leathery or scaly skin; red or dark blue skin; cast no shadow or reflection; exude a smell of brimstone. 

Feral. Your Intelligence score increases by l , and your Dexterity score increases by 2. This trait replaces the Ability Score Increase trait.

Devil's Tongue. You know the vicious mockery cantrip. When you reach 3rd level, you can cast the charm person spell as a 2nd-level spell once with this trait. When you reach 5th level , you can cast the enthrall spell once with this trait. You must finish a long rest to cast these spells once again with this trait. Charisma is your spellcasting ability for them. This trait replaces the Infernal Legacy trait.

Hellfire. Once you reach 3rd level , you can cast the burning hands spell once per day as a 2nd-level spell. This trait replaces the hellish rebuke spell of the Infernal Legacy trait. 

Winged. You have bat-like wings sprouting from your shoulder blades. You have a flying speed of 30 feet. This trait replaces the Infernal Legacy trait.

**Comment by grandchefpanda** [comment]
Arcane Domain #262

**Comment by grandchefpanda** [comment]
LordMorin as interpreted Arcane Initiate as if the cleric can choose cantrips from wizards but keep only 3 cantrips.

**Comment by xdy** [comment]
Hero Lab doesn't load properly for me with these complaints:
Syntax error in ‘evalrule’ script for Thing c5CClrAdn (Eval Rule #1 on line 23
-> Tag ‘Ability.cClrArcana’ not defined
Syntax error in evalrule’ script for Thing c5CClrArMa’ (Eval Rule #1 on line 23
-> Tag ‘Ability.cClrArcana’ not defined
Syntax error in evalmle’ script for Thing ‘cSCCIrArM2’ (Eval Rule 7t1 on line 23
-> Tag ‘Ability.cClrArcana’ not defined

The following patch fixes that:
[patch.zip](https://github.com/Sklore/HL_DD_5e_Colab/files/189858/patch.zip)

**Comment by xdy** [comment]
Also, aren't the descriptions that exactly match the book a problem? I.e. I think that if there is to be a release tomorrow, they should be replaced with placeholders for now (or just go through and alter them.)

**Comment by LordMorin** [comment]
When I created it, it was for my own use. Panda was rushing due to his being away for a few days. He probably forgot. I always use the full descriptions for my own use. :)

**Comment by xdy** [comment]
Yeah, I do the same. :)
Anyway, if he's away for a few days I guess the odds of merge conflicts are small, so I'll go through the file and hack away at the descriptions, starting at the top of the file. In case anyone else feels like joining in, post where you'll start so we don't duplicate work.

**Comment by grandchefpanda** [comment]
I change that now, sorry

**Comment by grandchefpanda** [comment]
Sklore is away, not me ^^

**Comment by LordMorin** [comment]
Opps, my bad.

**Comment by grandchefpanda** [comment]
Ok I fixed the script bugs. You can proceed to remove descriptions, because I can't find what are the wrong ones. #263

**Comment by xdy** [comment]
None are wrong, really. It's just that they are direct quotes from the book, and thus a little too, well, right. :)
I've started hacking away at the descriptions, replacing them with paraphrased text. We'll see how far I get until I run out of caffeine and just mass replace the remaining ones with Placeholder and go to bed. :)

**Comment by xdy** [comment]
Ran out of steam (or caffeine :), everything is either paraphrased or replaced with 'Placeholder...'
Loads in Hero Lab for me, hopefully I've not mucked things up, but it would be nice if someone could give it a quick look.

**Comment by Sklore** [comment]
The original Scag files I've been working on had text from wikis not from the phb. Except for the mechanics which were left.

**Comment by xdy** [comment]
The only ones//I changed tonight were the ones that had text that
exactly matched the book (presumably the ones from LordMorin), the other
ones I left as they were.

**Comment by Sklore** [comment]
Moving comment to correct Issue

@LordMorin 
Here is what I have do so far for SCAG.
Arcane domain, Tiefling variant & traits.

Warning: Some of the Tiefling traits (Cateyes, 6 fingers, ect. have been house ruled so you may want to make them conform to the SCAG rules).

[soe_5e_scag.zip](https://github.com/Sklore/HL_DD_5e_Colab/files/181019/soe_5e_scag.zip)

@grandchefpanda
Will integrate Arcane domain tomorrow

**Comment by Sklore** [comment]
Spiked Armor is now added. The 'weapon' will bootstrap in. There is a technicality though. If you are proficient with medium armor then technically you become proficient with this 'weapon'. As proficiency is not designed to work with armor in the case of weapons I'm unsure how to do this. Have left it as proficiency turned off.

**Comment by grandchefpanda** [comment]
I disagree that if you are proficient with medium armor you became proficient with the weapon spiked armor. I would simply add to the class ability the proficiency of the weapon as for me only Battlerager can use it and thus are proficient with it.

**Comment by Sklore** [comment]
This is where I was taking the ruling from. I certainly can't find any 'ruling' for it but given the armor is listed as medium and medium armor has proficiency it makes sense that you would get the proficiency bonus with the weapon if you are proficient with the armor. 

https://www.reddit.com/r/dndnext/comments/424dte/battlerager_armor_questions/

**Comment by grandchefpanda** [comment]
I agree that this is a medium armor and that you need to be proficient in medium armor to wear it and get the AC, but to use it as a weapon you'll need training and thus need to be proficient with it. Other wearer not Battlerager are not proficient because they are not trained to use it and thus need to attack with disadvantage, if they want.

**Comment by grandchefpanda** [comment]
I'm doing the Tiefling Variants today, already half of it done.

**Comment by grandchefpanda** [comment]
Tiefling Variants done except appearance

**Comment by grandchefpanda** [comment]
#321 finishing Tiefling variants

**Comment by Sklore** [comment]
#224 - Replaced SCAG Background placeholders with paraphrased text.

**Comment by TheEnthusiast** [comment]
@Sklore @grandchefpanda 
Hello there, the attached file has the mastermind rogue archetype done. Just remove the "2" from the names. I'm not sure what else is pending from the SCAG book. Are the monk traditions implemented ?

[COM_5ePack_SCAG - Mastermind2.zip](https://github.com/Sklore/HL_DD_5e_Colab/files/374988/COM_5ePack_SCAG.-.Mastermind2.zip)

**Comment by Cerxi** [comment]
@Sklore @grandchefpanda @TheEnthusiast Well, I know the Half-Elf Variants are missing, and I would give an arm and a leg to see them in!

**Comment by Sklore** [comment]
So I've started to try and figure out how to do the Hallf-Elf variant. 

Honestly not sure if I'm doing this the right way. Basic using Bootstraps with conditionals to determine what the player picks with the array menu. 

Getting a heap of errors and even duplications of abilities at this stage. Uploading in case someone has any idea how to do this.

**Comment by LordMorin** [comment]
Sklore:

How do I download a copy of the latest version of your work on this file. I was going to take a look at what you've already done and wee what I can do if anything. The upload my updated version as a zip like usual..

**Comment by LordMorin** [comment]
By the way, the cleric domain: Arcane, in this file, needs to have it's source set to the Sword Coast Adventures Guide otherwise it still shows up even if you don't have the 5E Scag selected.

**Comment by TheEnthusiast** [comment]
@Cerxi 
We implemented the half-elf variants yesterday. Just to let you know.

**Comment by Cerxi** [comment]
Thanks so much for letting me know! And for your hard work!

**Comment by TheEnthusiast** [comment]
Wow, never say close issue on a merge. This site takes it seriously!

@Sklore 

Now, I've added the missing script for Royal Envoy. I also added 2 new "spells" to represent the spell attacks of the SunSoul monk. I *think* that's what you meant on your Outstanding features.

The rest of the outstanding items seem to be in place already. If you confirm that, we can close this issue.

**Comment by Sklore** [comment]
Looks good!
