### ISSUE TITLE
No Images in .stock/.por files...

### ISSUE THREAD

**Issue by shadowchemosh** [Sklore/HL_DD_5e_Colab#245]
I am commenting here based on this post by Sklore:
http://forums.wolflair.com/showpost.php?p=226708&postcount=6

Images are SUPER heavy protected by companies as they often cost more money then whole books.  Even Paizo goes after people that use there images.  I spent lots of time making sure the .por files I host for Pathfinder do NOT contain images.

I won't host any files that have images in a .por/.stock file as that increases the chance someone comes after me by 1,000%.  Obviously that does not prevent other means but I wanted to make sure its clear.  

Copyrighted images in use in HL looks great will get us/me in trouble. =(

Thanks

**NOTE:** I am really sick and still at work.  So if the above "reads" really bad/angry please note I am just in a hurry and its NOT at all how I am.  I simply sharing info... =)

**Comment by Sklore** [comment]
:) thanks @shadowchemosh and no issues at all. I was just doing some Googling on the issue and it certainly didn't look like a feasible option anyway. You are correct. Everything is under lock and key.

**Comment by Sklore** [comment]
**NOTE:** Hope your feeling better soon! I'm also at work currently managing about 20 projects so i'm also not as active here as i would like to be.

**Comment by shadowchemosh** [comment]
Thanks!  I hope so too.  But I have to go in for a procedure on April 8th to figure out how bad things are.  Currently it ranges from small issue and simple diet change to Cancer.  So crossing fingers for the simple diet change.  LOL =)

**Comment by Sklore** [comment]
Shit mate I consider the diet change to by devastating but cancer! Hope the odds roll in your favor.

**Comment by shadowchemosh** [comment]
Thanks!  Will deal once I know.  I am pretty hopeful that it will fall somewhere on the low end.  Can't do anything about so not that worried.  Be nice to know what is going on. =)  Then at least I will have good information to make decisions.

Going to close this thread.  Now that the image stuff is known...
