### ISSUE TITLE
v1.3 Release date...

### ISSUE THREAD

**Issue by shadowchemosh** [Sklore/HL_DD_5e_Colab#257]
Starting this to update everyone on plans.  You guys have done ALLOT  of stuff and with all the fixes and LW releasing 1.3 its time for us to do the same.

My plans are to release this weekend.  Right now best for me would be Saturday afternoon.  Figure Saturday 1pm CST time.

If everyone can start wrapping up there changes and additions that would be great!

Thanks

**Comment by Sklore** [comment]
It should be noted where we know scripting is missing or something is incomplete in the patch notes.

The 5e feats is 100% text only at this stage. Going to take quite a while to script it all I imagine. 

Midland heroes is incomplete.  I've added in about 70% of the race options. 

There a tickets raised for the things that I am aware need further scripting. 

Would love to see a stock file release of all the monsters panda has completed.  I got about 2 thirds through. It's really easy especially if panda has already added the spell abilities and shadow has added the ability to add the Missing spells. 

I'm down the coast for 4 days with access to internet only when the cloud cover moves perfectly so I won't be around to help sorry guys. 

Looks to be a good release for us though with plenty of new content so well done to all.

**Comment by grandchefpanda** [comment]
Had already done half of missing stock monsters this morning, will do the rest today

**Comment by grandchefpanda** [comment]
all stock done

**Comment by shadowchemosh** [comment]
I am putting together the release notes.  Please no more changes unless its an emergency... =)

**Comment by shadowchemosh** [comment]
Here is the current release notes I have gathered together.  Please speak ASAP if anyone wants changes. =)


<strong>v1.3 March 26, 2016</strong>

<strong>New Features</strong>
<ul>
<li>Community added monsters added as stock files. This means going to the menu "Gamemaster->Show Encounter Builder" will let you quickly and easily added monsters to a encounter.</li>
<li>Monsters added: Scarecrow, Half Ogre, Water Wierd, Slaad Tadpole, Red Slaad, Blue Slaad, Green Slaad, Gray Slaad, Death Slaad, Chasme, Goristro, Manes, Shadow Demon, Yochlol, Winged Kobold, Helmed horror, Grick Alpha, Grell, Quaggoth Spore Servant, Gnoll Pack Lord, Gnoll Fang Of Yeenoghu, Gobelin Boss, Hobgoblin Captain, Hobgoblin Warlord, Young Remorahaz, Orc War Chief, Orc Eye of Gruumsh, Orog, Faery Dragon, Flameskull, Flumph, Gas spore, Kuo-toa, Kuo-Toa Archpriest, Kuo-toa Whip, Bone Naga, Nothic, Peryton, Smoke and Mud Mephits, Githyanki Warrior, Githyanki Knight, Githzerai Monk, Githzerai Zerth, Umber Hulk, Fire Snake, Yuan-Ti Abomination, Yuan-ti Malison, Yuan-Ti, Sahuagin Priestess + Sahuagin Baron, Lizardfolk (Shaman), Lizardfolk (King/Queen), Mezzoloth, Nycaloth, UIltroloth, Fomorian, Galeb Duhr, Dao, Marid, Revenant, Beholder Zombie, Arcanaloth, Mezzoloth, Nycaloth, UIltroloth, Empyrean, Avatar of Death, Larva, & Giant Fly.</li>
<li>DMG added - Death Domain, Weapon of Warning, magic items up to E & Saddle of the Cavalier.</li>
<li>PHB Added - Spells: Secret Chest and Magic Aura</li>
<li>Added 162 feats from TPG Games Fifth Edition Feats. Pre-requirements need to be scripted. Feat special abilities need to be scripted.</li>
<li>Added a number of Homebrew Items commonly seem in use by Jarlaxle Baenre. https://www.reddit.com/r/dndnext/comments/2iv08w/magic_items_belonging_to_jarlaxle_part_1/</li>
<li>Sword Coast Adventures Guide classes added: Barbarian - Primal Path (Path of the Battlerager), Primal Path (Path of the Totem Warrior); Bard - College (College of Fochlucan), College (College of New Olamn), College (College of the Herald); Cleric - Arcana; Druid - The Moonshea Circles, The Emerald Enclave (Moon), The Emerald Enclave (Land); Fighter - Banneret (Purple Dragon Knight); Sorcerer - Sorcerous Origin (Storm Sorcery); Warlock - Otherwordly Patron (The Undying); Paladin - Oath of the Crown; Monk -  Way of the Long Death, Way of the Sun Soul, Order of the Yellow Moon, Way of Hin Fist, The Dark Moon; Rogue - Mastermind, swashbuckler. <strong>NOTE:</strong> No scripting complete yet.</li>
<li>Sword Coast Adventures Guide tools added - Musical Instruments (Birdpipes, Glaur, Hand Drum, Longhorn, Shawm, Songhorn, Tantan, Thelarr, Tocken, Wargong, Yarting, Zulkoon). <strong>NOTE:</strong> No scripting complete yet.</li>
<li>Sword Coast Adventures Guide races added: Shield Dwarf, Gold Dwarf, Moon Elf, Sun Elf, Strongheart Halfling, and Deep Gnome (Svirfneblin). Human Variant Language options. <strong>NOTE:</strong> No scripting complete yet.</li>
<li>Rogue Genius Games Shadow Warrior class added. <strong>NOTE:</strong> Scripting Required for "Exotic Weapon Training".</li>
<li>Added Elemental Evil Player's Companion races & subtypes: Deep Gnome; Genasi (Air, Earth, Fire, Water) & Goliath.</li>
<li>Added Ogremoch from Princes of the Apocalypse</li>
<li>Added Midgard Heroes for 5th Edition Races: Alsied, Centaur (Midgard), Dragonkin, Elfmarked, Gearforged, Ghoul (Darakhul).</li>
<li>New EN5ider articles: 07 - Nature's Remedy; 15 - Strands of Life; 16 - King and Country; 18 - King and Country II; 57 - Scientific Sorcerery & 58 - It's Never Over. <strong>NOTE:</strong> No scripting complete yet.</li>
<li>New adjustment "Weapon Finesse" adjustment that lets a gamer give the weapon property Finesse to any selected weapon.</li>
<li>New adjustment "Casting Attribute" that allows a gamer to change the ability score that a class uses for spellcasting.</li>
<li>New adjustment "Add Single Spell to Class/Race" that lets you add a "single" spell to a class/race list. In example add the Hold Person spell to the Paladin class or the Death Knight race.</li>
</ul> 
<strong>Enhancements and Changes</strong>
<ul>
<li>Misc fixes to the adjustments to make them sort in the list better.</li>
<li>Add Charisma Bonus to Rakish Audacity in SCAG Class</li>
<li>Hord of the Dragon Queen - Fully scripted the greatsword weapon Hazirawn. Spells and extra damage all display when you attune the weapon. In addition it displays in the correct section of the weapons list. Fully scripted the "Wand of Winter" so its charges and spells display on the Spells tab.</li>
<li>Updated many background descriptions and Spells text. Still need to work on the table information but this is a good start.</li>
<li>Script fixes for some Sword Coast Adventures Guide Classes, Arcane domain, and Arcane Banishment.</li>
</ul>
<strong>Bug Fixes</strong>
<ul>
<li>Duel Wielder feat will no longer display an error message when wielding two one-handed weapons (ie two rapiers).</li>
<li>Weapon Master feat is fixed to not have the 2 bootstrapped helper feats count against a characters total feats taken.</li>
<li>Elemental Adept feat - Will let you choose elemental types again.</li>
</ul>
