### ISSUE TITLE
Feat: Spell Sniper

### ISSUE THREAD

**Issue by Sklore** [Sklore/HL_DD_5e_Colab#26]
This mechanic has not been implemented yet.

Suggestion on how to implement:
As Magic Initiate

**Comment by DarkHayZe** [comment]
Warlock is missing from the selection list

**Comment by shadowchemosh** [comment]
The bug is in the Warlock class Helper Thing.  It does not contain the "Helper.FullCaster" tag.

**Comment by shadowchemosh** [comment]
Looks like Warlocks have some type of "special" casting and are assigned a "Helper.WarlocCast" tag instead of "Helper.FullCaster" tag.

**Comment by Sklore** [comment]
That's on the LW side correct?

**Comment by shadowchemosh** [comment]
I thought so but turns out no.  I was restricting the list to Full-Casters which I guess a Warlock is but it needs to allow for this Secondary Tag "Helper.WarlocCast".

Similar issue so the Spells Pre-Req bug.  I didn't know Warlocks had "special" rules.  I am fixing it now...

**Comment by shadowchemosh** [comment]
Eventually I think I will be less and less helpful because I don't know the "game rules". =)
