### ISSUE TITLE
Multiattack text adjustement

### ISSUE THREAD

**Issue by grandchefpanda** [Sklore/HL_DD_5e_Colab#261]
@shadowchemosh Can you create an adjustment to change the multiattack text. If we change the weapon of a monster or npc, we need to do that too.

**Comment by shadowchemosh** [comment]
As soon as I can....  Busy weekend...

**Comment by grandchefpanda** [comment]
It's not urgent ^^

**Comment by shadowchemosh** [comment]
So when you say "multiattack" text.  Which "exact" field are we talking about?  I see three that holds text: wDamExtra
wAttackEff
wTarget

**Comment by grandchefpanda** [comment]
It is rMultiatt, it's just below Multiattack choices in the race editor

**Comment by shadowchemosh** [comment]
That is on the race itself not the weapon..  Ok thanks...

**Comment by shadowchemosh** [comment]
Added in commit 146381e2a80fa7fa74fe098c5181447e6f688554.

Thanks

**Comment by grandchefpanda** [comment]
thanks
