### ISSUE TITLE
Extra Attack Calculation is Incorrect for Monk/Bladesinger Wizard

### ISSUE THREAD

**Issue by PropheticSteel** [Sklore/HL_DD_5e_Colab#274]
If you make a character with 3 levels of monk and 2 levels of wizard without an arcane tradition, everything looks fine.  As soon as you select the Bladesinger arcane tradition, however, it activates your Extra Attack at level 5 on the Monk tab (it is no longer grayed out, though Slow Fall and Stunning Strike are still gray).  Likewise, if you add an additional level of wizard (so Monk 3 / Wizard 3), it also highlights the level 6 Extra Attack on the Wizard tab.

I tested this same thing with Fighter/Monk and everything works correctly.  I'm not sure if this problem occurs with other class combinations, but it definitely does with Monk / Bladesinger Wizard.

**Comment by Sklore** [comment]
Found it, its because they are both using the same Extra Attack (cExtraAtt).

**Comment by Sklore** [comment]
Will be resolved in the next release. Thanks for the detailed big report.
