### ISSUE TITLE
Waterdhavian Noble Should not have Survival Proficiency - should have a gaming set proficiency

### ISSUE THREAD

**Issue by PropheticSteel** [Sklore/HL_DD_5e_Colab#275]
Waterdhavian Noble Should not have Survival Proficiency. Additionally, it should have tool proficiency in a gaming set.

**Comment by Sklore** [comment]
This will be fixed in the next release. Thanks for submitting!

**Comment by PropheticSteel** [comment]
This was not corrected in the latest release.
