### ISSUE TITLE
Feedback Required for Official LW Newsletter

### ISSUE THREAD

**Issue by Sklore** [Sklore/HL_DD_5e_Colab#278]
I'm at work so wont have time to think about this straight away. If there is anything people would life included please comment below. Off the top of my head, the addition of all the missing monsters, classes and races from the core books is the key achievement so far. 

Hi there!
 
We’d like to throw a shout-out to the Community Packs in our newsletter later this week. Specifically, we want to make sure to explain what the Community Pack is and then highlight some of the most recent updates. Are there any recent updates to the Community Pack that you want to make sure we give a shout out? Anything else that you’d like us to cover? The newsletter will go out at the end of the week, so please make sure you let me know by Wednesday.
 
Thanks,
Liz Theis
 
Business Manager
Lone Wolf Development

**Comment by grandchefpanda** [comment]
Perhaps also says that we are busy implementing all the missing mechanics from sources books and adventures.

**Comment by Sklore** [comment]
Have emailed Liz :)
