### ISSUE TITLE
Great weapon master issue

### ISSUE THREAD

**Issue by mkillroy** [Sklore/HL_DD_5e_Colab#279]
Howdy,

I have a Barb half orc with a great sword of wounding. I took the great weapon master feat and when I click to activate, it doesn't change anything on the magic item. It does it on the non-magic items but that one it doesn't add the +10 damage and -5 to hit.

**Comment by Sklore** [comment]
@shadowchemosh - do you have any idea how this works? The script makes no reference to magic weapons but shouldn't have to given it is looking for the heavy weapon tag.

**Comment by shadowchemosh** [comment]
It was a timing issue in the script. Very rarely should a script fire at First 100. I fixed this last night. 

Also noticed many feat scripts fire at First 100. =(
