### ISSUE TITLE
Background: Noble Knight adding Feature returns "Nothing to choose from"

### ISSUE THREAD

**Issue by CrusherJoe** [Sklore/HL_DD_5e_Colab#281]
![noble knight feature issue](https://cloud.githubusercontent.com/assets/9998385/14119008/c6e83168-f5b1-11e5-9c27-0f4f083d8040.PNG)

This results in a validation error, "Background: Choose more feature for your character."

**Comment by LordMorin** [comment]
I can't see the name of the actual background, but it looks to me like Noble Knight. I keep forgetting to report this myself. I've fixed it for my own use twice now, but keep forgetting to report the problem.

In the 'COM_5ePack_PHB - Backgrounds.user' file, on the backgrounds tab, under Noble Knight, the Custom Ability Count needs to be set to 0, not 1.

**Comment by xdy** [comment]
I think I've seen it a couple more places (I know Noble has the same problem), I'll go through and fix them.

**Comment by CrusherJoe** [comment]
Y'all are the Kings of Swing. Thank you!

I'll pull Backgrounds.user from Git this evening when I get home.


Thank you again!
