### ISSUE TITLE
Replacement Text: Barbarian and Bard

### ISSUE THREAD

**Issue by Gwaithador** [Sklore/HL_DD_5e_Colab#285]
[SRD Community File Replacement Text 3-26-2016.docx](https://github.com/Sklore/HL_DD_5e_Colab/files/201346/SRD.Community.File.Replacement.Text.3-26-2016.docx)

**Comment by Gwaithador** [comment]
I developed replacement text for the barbarian and bard. If this meets the 20% standard, I'll do some more. Please let me know if this acceptable.

**Comment by dschwarm** [comment]
Great work! This looks fine to me.

I am not sure how we "validate" the 20% rule...Your barbarian and bard things look fine to me, but I assume we should run it through some kind of text comparison tool and save the results in case of audit? I am sure there is precedence on this, I just do not know what it is.

**Comment by Sklore** [comment]
Absolutely no idea if there is any formal way to do it. So far we have just been making the necessary changes and releasing the new text. As long as we verify that the text is satisfactorily different we should be ok to proceed to update.

**Comment by Sklore** [comment]
Love your work :) This will be released in the next update.

**Comment by Gwaithador** [comment]
Thanks gents. I'll start on the cleric, and proceed from there.
