### ISSUE TITLE
Out of the Abyss : Monsters

### ISSUE THREAD

**Issue by grandchefpanda** [Sklore/HL_DD_5e_Colab#295]
**Completed:**
Derro - Added to *.stock
Derro Savant - Added to *.stock
Drow template as a subrace - Stocks will be done when NPC from SRD are out

**Pending:**
Ixitxachitl
Vampiric Ixitxachitl
Ixitxachitl Cleric
Duergar Darkhaft
Duergar Kavalrachni
Duergar Keeper of the Flame
Duergar Soulblade
Duergar Stone Guard
Duergar Xarrorn
Drow Spore Servant
Chuul Spore Servant
Duergar Spore Servant
Hook Horror Spore Servant
Troglodyte Champion of Laogzed
Awakened Zurkhwood
Bridesmaid of Zuggtmoy
Chamberlain of Zuggtmoy
Female Steeder
Male Steeder
Droki
Grisha
Narrak
The Pudding King
Yestabrod
Baphomet
Demogorgon
Fraz-Urb'luu
Graz'zt
Juiblex
Orcus
Yeenoghu
Zuggtmoy
Quenthel Baenre

**Comment by grandchefpanda** [comment]
Added Derro

**Comment by Sklore** [comment]
BTW: I have the parser ready for Fifth Edition Foes, lemme know if you want to play around with it.

**Comment by grandchefpanda** [comment]
Added Derro Savant #301 
@Sklore thanks but I feel it easier to do them one by one

**Comment by grandchefpanda** [comment]
Drow template #302

**Comment by dungeonguru** [comment]
Hey grandchefpanda, I have some time and the sourcebook, do you want me to help add the remaining monsters?

**Comment by grandchefpanda** [comment]
Please do so, I have not time to add anything anymore myself.

**Comment by dungeonguru** [comment]
**Update**: Got all the way up to Baphomet before stopping for a bit. That leaves:
Demogorgon
Fraz-Urb'luu
Graz'zt
Juiblex
Orcus
Yeenoghu
Zuggtmoy
Quenthel Baenre
and a handful of magic items that can be tacked on.

**Comment by dungeonguru** [comment]
Merged all items into master.

**Comment by Sklore** [comment]
Reopening this. I'm going to go through and put the monsters back in the monster file. Because that file has already been released to the public we will cause chaos by removing it. The upgrade process for Hero Lab does not by default remove old files. It just upgrades and adds new ones. So everyone will get duplicate errors because their system will still have the old name.

**Comment by dungeonguru** [comment]
Ah, I thought releases would see that and have a mechanism. I think it might just be easier to rename the new file to the old name then, since the new file isn't public. There weren't many items outside monsters in it.

**Comment by Sklore** [comment]
Ok file has been renamed. Looking really good!
