### ISSUE TITLE
Replacement Text: Cleric

### ISSUE THREAD

**Issue by Gwaithador** [Sklore/HL_DD_5e_Colab#298]
The replacement text in this document was completed only for those areas identified with "placeholder." Some of the domains already had features listed, so I omitted them from this document. Mechanics text was unchanged, though occasionally mechanic text 'blended'  with flavor text. When in doubt, I made changes to a word like "enemy" to "foe", attempting to leave the integrity of the mechanical text statement.
 
[SRD Community File Replacement Text 4-5-16.docx](https://github.com/Sklore/HL_DD_5e_Colab/files/207556/SRD.Community.File.Replacement.Text.4-5-16.docx)

**Comment by Sklore** [comment]
:+1:  Will implement it asap!

**Comment by Sklore** [comment]
Will be release in the next update :)
