### ISSUE TITLE
Replacement text: Druid, Fighter, Monk and Paladin

### ISSUE THREAD

**Issue by Gwaithador** [Sklore/HL_DD_5e_Colab#309]
Flavor text changed with the 20% rule, the mechanics, per the guide, are unchanged. There was far more mechanic text than flavor text for most. Again, where it seemed to blend, I changed the words without changing the mechanics (the word "enemy" to "foe", for example).
[SRD Community File Replacement Text 4-9-16.docx](https://github.com/Sklore/HL_DD_5e_Colab/files/211601/SRD.Community.File.Replacement.Text.4-9-16.docx)

**Comment by grandchefpanda** [comment]
@Sklore Are you ok to replace the description you have taken from the Wikis with the text changed from the Player handbook ?

**Comment by Sklore** [comment]
Absolutely. I'm prepping for a game currently so in a quiet scramble to populate a city.

**Comment by grandchefpanda** [comment]
I will try to do a part (or all) of it today

**Comment by grandchefpanda** [comment]
#317

**Comment by Gwaithador** [comment]
I also completed the replacement text for the other classes.  I posted it all to GitHub. I started on the backgrounds, but I see that Hippie Craig is working on the backgrounds.
