### ISSUE TITLE
Replacement Text: Ranger, Rogue and Sorcerer

### ISSUE THREAD

**Issue by Gwaithador** [Sklore/HL_DD_5e_Colab#311]
Same rules applied as before. Mechanical text was left unchanged. Where the flavor text and mechanical text seemed to bleed, the text was changed to meet the 20% rule without altering the rules as intended.
[SRD Community File Replacement Text 4-10-16.docx](https://github.com/Sklore/HL_DD_5e_Colab/files/211841/SRD.Community.File.Replacement.Text.4-10-16.docx)

**Comment by Sklore** [comment]
Placeholder's updated - will be released in the next release.
