### ISSUE TITLE
Replacement Text: Wizard and Warlock; Last PHB Class Text

### ISSUE THREAD

**Issue by Gwaithador** [Sklore/HL_DD_5e_Colab#312]
I managed to finish the Wizard and Warlock replacement text today. Followed all previous rules.
[SRD Community File Replacement Text 4-10-16 final.docx](https://github.com/Sklore/HL_DD_5e_Colab/files/211931/SRD.Community.File.Replacement.Text.4-10-16.final.docx)

**Comment by Sklore** [comment]
Placeholder's updated - will be released in the next release.
