### ISSUE TITLE
En5ider Files - Various

### ISSUE THREAD

**Issue by Sethvir** [Sklore/HL_DD_5e_Colab#315]
Some more Alpha work done on the following En5ider Articles.
1) 70 - Children of Earth
2) 65 - Priests of Elemental Power
3) 64 - Priests of Misfortune
4) 63 - Fell Grafts
5) 61 - Speaking with Fists
6) 60 - Sinister Spellbooks
7) 57 - Explorers of the Multiverse
8) 50 - Friends Close, Enemies Closer
9) 48 - Heroes of the Blade
10) 44 - Treasures Dark and Terrible
11) 42 - Heroes of the Night
12) 39 - I Ain't Afraid of No Ghosts
13) 35 - Masters of the Wild
14) 31 - Forgotten Lore - Divine
15) 25 - Paladin's Dark Vows
16) 22 - Art of Peace
17) 21 - Forgotten Lore - Arcane
18) 15 - Strands of Life
19) 9 - Circles of Power

**Comment by Sethvir** [comment]
After a long hiatus due to RL, back working on these again.  Going to be slow going, but making progress.

**Comment by Sklore** [comment]
[en5ider files.zip](https://github.com/Sklore/HL_DD_5e_Colab/files/769113/en5ider.files.zip)

**Comment by Sklore** [comment]
Files added for release in next update
