### ISSUE TITLE
SCAG - Bladesinger - Extra Attack

### ISSUE THREAD

**Issue by LordMorin** [Sklore/HL_DD_5e_Colab#316]
Need to add a CustDesc field to Extra Attack which reads:

"Beginning at 6th level, you can attack twice, instead of once, whenever you take the Attack action on your turn."

Reason: It's a 6th level class feature for a Bladesinger not 5th, which is what the Bladesinger's version of Extra Attack currently reads as.

**Comment by grandchefpanda** [comment]
corrected with 84e1d0df3c1d6cb173eb04af555cca3da46ba608

**Comment by LordMorin** [comment]
It figures, I just discovered it while trying to resolve an issue on my end. I have a homebrewed artificer class I found on the net that also gives an Extra attack at 6th level and for some reason the combination of the 2 classes is giving the Extra attack early . . .

**Comment by grandchefpanda** [comment]
Don't forget that, if you have time to spare, to help for the scripting of SCAG, I think you are the only one except ShadowChemosh to be able to script it for now.

**Comment by LordMorin** [comment]
For the last week, between RL and scripting for my own campaign, I haven't had time for much of anything. hoping that changes soon though. I have some Unearthed Arcana material I want to pass along: The mystic v2, the Eberron wizard Artificer subclass. Also, Been working on creatures for Princes of the Apocalypse  for my own campaign.

Biggest problem, as usual, is tags since I scripted everything for my own SOE files . . .

**Comment by grandchefpanda** [comment]
It's true that the tags can be problematic, but we've already been able to convert most of your work that you send us (I think there is still 1 or 2 races from prince of the apocalypse that need to be done), so if you have something, keep it coming ;-)

**Comment by PropheticSteel** [comment]
This is the same error listed in still-open issue 274 
https://github.com/Sklore/HL_DD_5e_Colab/issues/274
