### ISSUE TITLE
Powerful Build not working for Goliath race?

### ISSUE THREAD

**Issue by seelenamt** [Sklore/HL_DD_5e_Colab#318]
I apologize ahead of time if I'm just missing something, but Goliaths have the trait "Powerful Build", meaning when determining carrying capacity, as well as the weight they can push, drag, or lift, they count as a size larger. 

It seems that it is not accounting for this trait- A 20 Str goliath should be able to carry 600 lbs (20 *  15 * 2) because they are effectively large size (determining carrying capacity from size is on page 176 of the PHB)

**Comment by LordMorin** [comment]
That's because the 5e Community Pack version hasn't been scripted yet. This is the script I came up with for Powerful Build. It's worked fine. I thought I had uploaded to the group before this. Sorry.

Phase: Post-attributes, Priority: 10000

    ~if we've been replaced, get out now
    doneif (tagis[Helper.Disable] <> 0)

    herofield[tEncumLgt].value = herofield[tEncumLgt].value * 2
    herofield[tEncumHvy].value = herofield[tEncumHvy].value * 2
    herofield[tEncumMax].value = herofield[tEncumMax].value * 2

**Comment by Sklore** [comment]
It's in the current pre-release which you can download here: https://github.com/Sklore/HL_DD_5e_Colab/archive/master.zip

You need to copy the content of the download into your 5E folder and reload HeroLabs.
