### ISSUE TITLE
Layout & Companion Error

### ISSUE THREAD

**Issue by corwynguild** [Sklore/HL_DD_5e_Colab#319]
Hi everyone,
    First let me say, awesome job and thanks.

    However, I've been playing with the packs to see what errors I could get and I found a couple in my first try.   
     One, when you add a horse, the classes section for the horse shows a validation error saying it wants you to enter a class, but if you do, it also shows up red (after all, who's heard of a horse bard *grin*).
     Two, when I entered the extra languages the PC gets, when it prints, it puts them in a different section, instead of having them all together.   
     I did notice some stuff not in there for spells, for one... can't make a certain magic item.  A simple scroll of silence... just noticed that it is a ritual now.  Don't know if it can be made into a scroll, but it won't come up either way (if it's supposed to, it doesn't, if it's not... then ignore and sorry)
I did take a screen shot if you need it, let me know.

Corwyn
(corwynguild@gmail.com)

**Comment by Sklore** [comment]
Hi @corwynguild, 

Thanks for contacting us. 

You have contacted the Community Pack Team however so we only handle issues directly related to the Community Pack. The issues you have raised all appear to be related with the core 5e SRD content provided by Lone Wolf, you can raise issues directly to the core team using the link below. 

http://www.wolflair.com/redirect/bugreport.php?project=5e
