### ISSUE TITLE
Issue #275 not corrected in latest release

### ISSUE THREAD

**Issue by PropheticSteel** [Sklore/HL_DD_5e_Colab#322]
https://github.com/Sklore/HL_DD_5e_Colab/issues/275

The resolution on this one says it was to be corrected in the latest release, but I just checked, and it is still outstanding.

**Comment by LordMorin** [comment]
Are you referring to the HL 1.4 5e patch or the 1.3 5e Community patch?

**Comment by PropheticSteel** [comment]
My mistake, I just realized it was an SRD patch, not a community pack patch.

**Comment by LordMorin** [comment]
lol. I kind of thought that. :)
