### ISSUE TITLE
Bard - College of Valor - Extra Attack Error

### ISSUE THREAD

**Issue by PropheticSteel** [Sklore/HL_DD_5e_Colab#325]
See attached.   Under Extra Attack, the feature says in bold "**Extra Attack (6th level)"** which is correct, but then the text says "Beginning at 5th level..." 

So the next just needs the 5 changed to a 6.
![capture](https://cloud.githubusercontent.com/assets/17396890/14665424/c90679ee-0698-11e6-8a01-0edb94556b90.JPG)

**Comment by grandchefpanda** [comment]
I think the extra attack is in the SRD, but we can easily replace the text for College of Valor, will check that tonight

**Comment by PropheticSteel** [comment]
I think the SRD only contains College of Lore, right?  Lore doesn't even get an extra attack, so I think it's in the community pack.

**Comment by Sklore** [comment]
This will be fixed in the next release.
