### ISSUE TITLE
Two copies of Spare the Dying

### ISSUE THREAD

**Issue by BoomerET** [Sklore/HL_DD_5e_Colab#329]
Spare The Dying
Spare the Dying

Noticed while configuring Book of Shadows for Warlock.

**Comment by Sklore** [comment]
spSparDyi
sp5CSpareD

So looks like LW have added this in even though it's not in the SRD. It was likely required by a class. Will need to check to see if this is coded in with any other 'things' as simply deleting our's could cause other concerns.

**Comment by Sklore** [comment]
This will be resolved in the next release. Thanks for the report.
