### ISSUE TITLE
v1.4 Release Prepartation

### ISSUE THREAD

**Issue by Sklore** [Sklore/HL_DD_5e_Colab#330]
Hi Team, 

I think it's a good idea to put a release out with our current changes. The Aplha / Beta tags will give the user-base a better understanding of the content. Can you please close out any changes you want published with the next release. 

Please update the Wiki with the changes you remember making. This will form the release notes. 
https://github.com/Sklore/HL_DD_5e_Colab/wiki/3.-Pending-Changes

Would be nice to get scripting complete on the official books if anyone has the knowledge to close out the issues below. 
DMG: #87 
SCAG: #224 

It's quietened down significantly since the release of the custom monster functionality given users can now add things themselves quite easily.

**Comment by grandchefpanda** [comment]
I don't have anything still open (and unfortunately no time to work on other stuffs for the next weeks). Ok for the release. :-)

**Comment by shadowchemosh** [comment]
Just adding a note so I get notified about this thread.  Let me know when you guys are ready...

**Comment by grandchefpanda** [comment]
Now that 1.5 is out, think we must convert shadow dragon template and drow template from subrace to template. Currently they give warnings as subrace but look it will be ok as template. I will try to do it this tonight or this weekend.

**Comment by Sklore** [comment]
I'm going to try replace all the placeholders in the backgrounds prior to release.

**Comment by grandchefpanda** [comment]
Convertion from subraces to templates done #354 and #353

**Comment by Sklore** [comment]
All backgrounds placeholders now replaced with Paraphrased text.

**Comment by shadowchemosh** [comment]
I think you guys should release this weekend or "soon".  You are 158 commits (fixes/changes) past the last release.  That is ALLOT of features that the community is missing out on. =)

I mean I am totally jealous of the amount of help you guys have.

**Comment by Sklore** [comment]
/just found that button... See now that's a handy feature! :+1: 

I'll start updating the release log.

**Comment by Sklore** [comment]
Ok have trawled through the list of changes. 

Certainly understand the need for Merge Requests descriptions to be informative now. Makes this task much more efficient. 

Changes are listed here. Feel free to add if you are aware of any further outstanding. 
https://github.com/Sklore/HL_DD_5e_Colab/wiki/3.-Pending-Changes

With that in mind, pretty much able to release whenever you  are available @shadowchemosh 

Thanks all.

**Comment by shadowchemosh** [comment]
Will be doing this deploy today....

**Comment by shadowchemosh** [comment]
And its out!

Here is the Forum Ready release notes:

```
[b]v1.4 May 19, 2016[/b]

[b]New Features[/b]
[list]
[*]DMG - New Items Added (Saddle of the Cavalier, Cap of Water Breathing, Cloak of Invisibility, Driftglobe, Efreeti Chain, Elixir of Health, Gloves of Thievery, Mariner's Armor, Potion of Fire Breathing, Potion of Invulnerability, Potion of Vitality, Sending Stones, Sentinel Shield,Rod of Pact Keeper, Alchemy Jug).
[*]Adv League - Rage of Demons - Added monsters and NPC : Giant Two-headed Goat, Wild Dog, Wild Dog Alpha, Rothé Zombie, Breex Vandermast, Red Plume Patrol, Captain Erlich, Evil Sorcerer.
[*]Out of the Abyss - Added monsters : Derro, Derro Savant
[*]Out of the Abyss - NPC Races : Drow Template
[*]Monster Manual - Added monsters : Dracolich template
[*]New Adjustment - Change weapon type information of item
[*]New Adjustment - Natural Weapon, Extra Damage
[*]New Adjustment - Natural Weapon, Target
[*]New Adjustment - Multiattack Text
[*]New Adjustment - Spell DC, Specific School. NOTE: Currently individual spell DCs are not displayed in HL.
[*]New Adjustment - Spell DC, Single Spell. NOTE: Currently individual spell DCs are not displayed in HL.
[*]Added in a generic "Spell Attack" weapon that can be added to any character.
[*]New adjustment - "Spell Attack Dmg" that lets a gamer set any type of damage onto the selected "Spell Attack" weapon. This is helpful for both those using iPads or paper sheets.
[*]SCAG - Deities - Added all missing gods from normal FR pantheon
[*]SCAG - Tiefling Variants
[*]En5ider 07 Nature's Remedy - No scripting completed
[*]En5ider 15 Strands of Life - No scripting completed
[*]En5ider 16 King and Country - No scripting complete
[*]En5ider 18 King and Country II - No scripting complete
[*]En5ider 34 Chessmaster and Commanders - No scripting complete
[*]En5ider 57 Scientific Sorcery - No scripting complete
[*]En5ider 58 It's Never Over - No scripting complete
[*]Rage of Demons - New Monsters (Red Plume Patrol, Breex Vandermast, Derro)
[*]DDEX3-2 - New Monsters (Captain Erlich, Evil Sorcerer)
[*]Rage of Demons - Poison Weapon Added
[*]HOMEBREW - New Spell (Word of Censure)
[*]HOMEBREW - New Cleric Domain (Exorcism)
[*]PHB - New Spells (Mage's Faithful Hound, Mage's Magnificent Mansion, Mage's Private Sanctum, Mage's Sword)
[/list]
[b]Enhancements and Changes[/b]
[list]
[*]Added tags to source selection to indicate current status of content. Alpha - Have started adding the 'Things' to the tool. Beta - All 'Things' added and usable however scripting will be missing or incomplete. - Content is released, may contain placeholders still.
[*]PHB - All class 'Placeholders' replaced with relevant text.
[*]PHB - Backgrounds (All 'placeholders' replaced with relevant text).
[*]SCAG - Backgrounds (All 'placeholders' replaced with relevant text).
[*]SCAG - Added Arcana suggested domain to some deities.
[*]5eFeats - Pre-Requisites coded into all feats.
[*]5eFeats - Expertise added to all feats except Skill Focus.
[*]Elemental Earth - Replaces Spell placeholders with relevant text.
[/list]
[b]Bug Fixes[/b]
[list]
[*]Great Weapon Master - Now correctly applying result to magic weapons
[*]Monster Manual - Bone Naga spellcasting has correct spellcasting attribute now
[*]Monster Manual - Flame Skull renamed to Flameskull
[*]PHB - Feats (Dual Wielder spelling corrected)
[*]War Cleric Bugs resolved
[*]SCAG - Storm Sorcery Sorcerer: Now receiving Fly correctly at 18th level instead of Level 1.
[*]Fifth Edition Feats - "Spell Focus" feat to be able to actually Select a school of magic and have its DC bonus reflected on spells. NOTE: Currently individual spell DCs are not displayed in HL.
[/list]
```

**Comment by Sklore** [comment]
Thanks to everyone involved. 

Forum has been updated. 

Onward to 1.5. I would size to see as much focus as possible on getting the outstanding Dmg and Scag content completed. There's a few scripts outstanding if anyone has the required skills to smash those out. Once the official content is all done we can move back onto 3rd party material.
