### ISSUE TITLE
Duel Wielder

### ISSUE THREAD

**Issue by Sklore** [Sklore/HL_DD_5e_Colab#34]
http://forums.wolflair.com/showpost.php?p=224413&postcount=78
Logged by: TonganJedi (LW Forums)

Fantastic work on the script for Dual Wielder! One thing to note: it appears to adjust properly in the client, but doesn't appear properly on the character sheet.

For example, I selected the feet, equipped two rapiers, and the print preview shows both rapiers in the main hand and the bonus damage from the ability modifier is not removed from the off-hand weapon.

This could be an issue with the sheet generator, but I thought I'd point it out just in case. Thanks again!

**Comment by shadowchemosh** [comment]
http://forums.wolflair.com/showpost.php?p=224578&postcount=93

More issues posted about this feat.  I will need to read into this as I think this is really similar to Pathfinders TWF rules.  If so those mechanics should be in HL still and we can make sue of them.

Will try and take a look soon...

**Comment by shadowchemosh** [comment]
This is fixed but will not suppress the error until LW releases v1.2+ of 5e.
