### ISSUE TITLE
War Cleric Issues

### ISSUE THREAD

**Issue by Golonne70** [Sklore/HL_DD_5e_Colab#343]
Hi, 
I noticed the following issues with the Cleric class War domain : 

War Priest (c5CClrWarP) Tag ClSpecWhen should be 1 (gain at 1st lvl) not 2
War Priest (c5CClrWarP) Tag ChargeCalc should be AttrOnly and FinalMin1 (not /HD) 
Channel Divinity : Guided Strike (c5CClrGuiS) Tag ClSpecWhen should be 2 (gain at 1st lvl) not 6

Thanks for everything guys, you're awesome !

**Comment by xdy** [comment]
Thank *you* @Golonne70 for a good bug report. Wish the ones at work were this specific. :)

**Comment by Golonne70** [comment]
You're welcome @xdy, I'm self-taught with the editor but nothing like what you guys are capable of... Glad I could help. I've just bought 5e license, I will keep my eyes open if I notice something else.
