### ISSUE TITLE
Background Spelling Corrections

### ISSUE THREAD

**Issue by AEIOUsometimesY** [Sklore/HL_DD_5e_Colab#361]
Thank you for all the work on the backgrounds! This is just spelling clean up for the new text.

**GLADIATOR**
Personality: Story: capitalize "I" after "situation"
Personality: Gossip: capitalize "I" after "as"
Personality: Attention: capitalize "I" after "of"
Personality: Perfection: capitalize "I" after "everything"
Ideal: Tradition: "alot" should be "a lot"
Ideal: People: capitalize "I" after "When"
Bond: Instrument: capitalize "I" after "one"
Bond: Idolize: capitalize "I" after "that"
Flaw: Scandal: "follw" should be "follow"
Flaw: Satirized: capitalize "I" after "though,"

**Comment by AEIOUsometimesY** [comment]
**CHARLATAN**
Personality: Love Easily: capitalize "I" after "as"
Personality: Love Easily: capitalize "I'm" after "not"
Personality: Flattery: "alway's" should be "always"
Personality: Love Easily: capitalize "I" after "cards,"
Ideal: Charity: capitalize "I" after "wealth"
Ideal: Charity: capitalize "I" after "ensuring"
Ideal: Friendship: "loast" should be "last"
Bond: Fleeced: "swingled" should be "swindled"
Bond: Fleeced: capitalize "I" after "ensure"
Bond: Child: capitalize "I" after "because"
Bond: Noble: capitalize "I" after "day"
Bond: Noble: capitalize "I" after "that"
Bond: Revenge: capitalize "I" after "someone"
Flaw: Fool: capitalize "I" after "that"
Flaw: Greedy: capitalize "I" after "but"

**Comment by AEIOUsometimesY** [comment]
**CITY WATCH**
No spelling to correct.

**Comment by AEIOUsometimesY** [comment]
**CLAN CRAFTER**
Personality: Commitment: "anbd" should be "and"
Ideal: Freedom: "No on" should be "No one"
Ideal: Freedom: "persueing" should be "pursuing"
Bond: Workshop: "learny" should be "learned"
Bond: Worthy: "who" should be "whom"
Flaw: Coffers: "stol" should be "stole"

**Comment by AEIOUsometimesY** [comment]
**CLOISTERED SCHOLAR**
Personality: Polysyllabic: "works" should be "words"
Bond: Preserve: "inveolves" should be "involves"

Bond: Question: the text for this actually matches Bond: Soul.  I recommend changing it to "A single question has become an obsession for me and I am determined to discover its answer"

Bond: Soul: "sould" should be "should"
Flaw: Anatomy: "it's" should be "its"
Flaw: Obvious: "visibile" should be "visible"
Flaw: Secret: "Honeslty" should be "Honestly"

**Comment by AEIOUsometimesY** [comment]
**COURTIER**
Personality: Commitment: "anbd" should be "and"
Personality: Known: "It" should be "It is"
Ideal: Freedom: "No on" should be "No one"
Ideal: Freedom: "persueing" should be "pursuing"
Bond: Workshop: "learny" should be "learned"
Bond: Worthy: "who" should be "whom"
Flaws: Coffers: "stol" should be "stole"

**Comment by AEIOUsometimesY** [comment]
**CRIMINAL**
Personality: Trust: "take" should be "takes"
Bond: Debt: capitalize "I'm" after "which"
Bond: Mistake: "with" should be "which"
Flaw: Money: "loyla" should be "loyal"
Flaw: Tell: capitalize "I'm" after "when"
Flaw: Okay: capitalize "I" after "that"
Flaw: Okay: capitalize "I" after "but"

**Comment by xdy** [comment]
Hi,

An even better way to help with text changes is to actually update the file
in question and attach it to an issue.
In this case, go to the hero lab data directory (in my case c:/program
data/hero lab/data/5e) and open the file 'COM_5ePack_PHB -
Backgrounds.user' in any text editor (notepad for instance). Ignore the xml
formatting, just edit the actual background description texts without
changing anything else.
Then come here (https://github.com/Sklore/HL_DD_5e_Colab) go to the issues
tab and create a New Issue, attach the file and one of us will take a look
at it and include the changes in the next release.
Or if you know git, you coul fork the project, change the file in your
repo and send a pull request. But an issue with the changed file included
works just fine too.

/Jonas

**Comment by AEIOUsometimesY** [comment]
Sounds good.  I'll do that. I'm new to Github so bear with me.  I'll take
the Backgrounds on for editing.

Thanks for the guidance!

-- Steve

**Comment by Sklore** [comment]
You could probably open it in something that supports spelling correction and have it highlight all the issues.

**Comment by xdy** [comment]
In case you use word (or some other word processor), do make sure you save
it as a text file as word processors tend to want to change things like
quotes.

/Jonas

**Comment by xdy** [comment]
Closing this issue as the work was done in #362
