### ISSUE TITLE
Vicious Mockery

### ISSUE THREAD

**Issue by IrondrakeX** [Sklore/HL_DD_5e_Colab#367]
Vicious Mockery was deprecated.  The current live spell has no mechanical text included.  Is there a way to deprecate spViciMock in favor of sp5CVicioM?  I wasn't quite sure what deleting the deprecated thing and replacing it would entail.

**Comment by Sklore** [comment]
If you want to turn it back on yourself you can:

Open editor > Open COM_5ePack - Deprecated Things.User > General > Hidden > Remove sp5CVisioM

We get complaints when there are duplicates so it makes sense that we depreciate things as LW add them to the core pack but I can see why our version could be considered better. Perhaps paraphrase the text yourself and submit it to LW in a bug report and ask them to update it.

**Comment by Sklore** [comment]
Please report issue to Lone Wolf as they now control the text on this spell.
