### ISSUE TITLE
Homebrew - Alchemist (Outstanding Scripting)

### ISSUE THREAD

**Issue by Sklore** [Sklore/HL_DD_5e_Colab#369]
The Homebrew Alchemist is lacking the following scripting. 

**To Do:**
Code Restriction - Start with 2x spells (Extracts) +1 per level
Extracts Per Day - Set limit on extracts per day. 
Bomb: Add as attack
Bomb: Increase damage as level increases. 
Elemental Resistance: Code resistances, increase choice to include Poison. 
Mutagen: Increase AC +1
Feral Mutagen: Add bite attack, add 2x claw attack
Grand Mutagen 1 : Selected Abil Score +4

**Complete:**
Equipment should replace pistol with hand crossbow given pistols don't exist in core. 

**Notes:**
Left out the Science skill as it is not included in core D&D 5e.

**Comment by TheEnthusiast** [comment]
@Sklore What's the idea here? Implement pathfinder's alchemist? Do you have a rough sketch? Do you have a .user with what's implemented?

**Comment by Sklore** [comment]
I have implemented most of it already. If you check under the homebrew class file its in there. THis is a list of stuff I havn't figured out how to do yet.

**Comment by TheEnthusiast** [comment]
Interesting. But I wanted the class description, with features and so on. For example, you mention a Science skill. Is this described somewhere? Shouldn't you start with proficiency in the alchemist supplies and/or the Herbalism kit?

 The sneak attack could be your bomb progression. Just change the description.

The AC increase has been coded in the warforged race, if you want to take a look.

**Comment by Sklore** [comment]
I know i copied them somewhere. Perhaps in the notes or description field ofnthe class.

**Comment by Sklore** [comment]
Finally near my computer. 

In: COM_5ePack_Homebrew - Class.user

There are 2x alchemists. Both have the source in 2 locations. 
The Class description. Link at the bottom. 
From within the editor in the Author Comments on the right.

Source: https://www.reddit.com/r/UnearthedArcana/comments/3wwmh6/the_alchemist_a_non_magical_variant/

Source: http://www.enworld.org/forum/rpgdownloads.php?do=download&downloadid=1109

**Comment by LordMorin** [comment]
I don't know if this has been reported but both these Alchemist classes show up in the class list even if you haven't selected then under Configure Hero. This lets you chose either class but then gives you errors because you don't have them checked off.

**Comment by Sklore** [comment]
Cheers, i'll look into that.

**Comment by Sklore** [comment]
There's a bigger issue here. I'm seeing all class options regardless of what's ticket. Can you verify the same on your end?

**Comment by TheEnthusiast** [comment]
@Sklore ,

I'm not sure about you, but on my system, with the latest files, I see only the classes from the books I selected.

**Comment by LordMorin** [comment]
I'm pretty sure this was fixed since the last update. The fixes just haven't gone out yet.

**Comment by Sklore** [comment]
Yeah the class issue is fixed. 
Pretty sure it's just the coding issues outstanding here.

**Comment by Gfchanney** [comment]
The description for instant alchemy is the description for Infusion. Is that a known issue? Ididnt see anything anywhere.

**Comment by dungeonguru** [comment]
Is anyone working on this currently? Looking to clean up old tickets if we can.
