### ISSUE TITLE
sbName on silvered ammunition/weapons

### ISSUE THREAD

**Issue by dungeonguru** [Sklore/HL_DD_5e_Colab#379]
Minor request for you to add the following to the end of the silvered weapon eval script (and any other custom material you might convert later). 

      field[sbName].text = field[livename].text

As is now, the shortblock just lists it out as "Silvered Ammunition" or "Silvered Weapon" but would be a simple fix to one of the next releases.

**Comment by Sklore** [comment]
Has been added in for the next release. Thanks.
