### ISSUE TITLE
Backgrounds: Bonds (Too many)

### ISSUE THREAD

**Issue by Sklore** [Sklore/HL_DD_5e_Colab#38]
Testing indicates Bonds is not functioning since the addition of the bonds from HOTDQ. 

Raising bug to investigate.

**Comment by shadowchemosh** [comment]
Just a NOTE that this is on my to-do list still.  I have a few ideas on how to fix I just want to make sure its a universal method so that we can use the same logic for "other" adventures that come along.

**Comment by Sklore** [comment]
I have raised a bug request with LW on this one to find out what they think.

**Comment by Sklore** [comment]
Tested and confirmed this is now resolved.
