### ISSUE TITLE
New Class Id?

### ISSUE THREAD

**Issue by Sklore** [Sklore/HL_DD_5e_Colab#382]
Hi Team, 

Anyone know how to set a new class id to enable custom class use within the macro below?

#levelcount[class_id]
Counts how many levels you have of the specified class. For example, to count how many levels you have in the Ranger class, you would use #levelcount[Ranger].

~ Check whether you have at least 5 levels of the Fighter class
@valid = 0
if (#levelcount[**X_New_Class_?**] >= 5) then
  @valid = 1
  endif

**Comment by LordMorin** [comment]
What I've found, from experience, is to save, Test, then shut down and
restart HL. Otheriwse I neven get #levelcoutn to recognize the new class. .
.

**Comment by Sklore** [comment]
Good call! That's all it needed. Pulling my hair out over that. Thanks.

**Comment by LordMorin** [comment]
I did the same more than once till I figured it out.
