### ISSUE TITLE
Question: Can you rename an official tab?

### ISSUE THREAD

**Issue by Sklore** [Sklore/HL_DD_5e_Colab#384]
Example: Alchemist uses the spell system since it's mechanically the same. Can you rename the tab that appears to "Alchemist Discoveries"?

Pretty sure this is a @shadowchemosh question.

**Comment by shadowchemosh** [comment]
So the answer is "sort" of.  Pathfinder had logic for changing the words Spells to something else as it happened for several classes including Paizo's Alchemist.

I changed those values and only "some" of 5e changed.  The words 'Spells' appears to be hard-coded to several places including the tab name in 5e. =(

Here is the script that will at least change the Formula Book.  You can also just set these fields on the "Class" tab in the editor.  I was just using an adjustment for testing.

```
    hero.childfound[cHelpAlc].field[cSpBkName].text = "Formula Book"
    hero.childfound[cHelpAlc].field[cSpellName].text = "Formulas"
```

You can try putting in a bug report as the software only "Half" changes its displays when these values are changed.  Meaning it really should be all or nothing....

**Comment by Sklore** [comment]
Thanks Shadow. Have implemented per your suggestion and logged a request with LW.
