### ISSUE TITLE
Hex

### ISSUE THREAD

**Issue by Amniculi** [Sklore/HL_DD_5e_Colab#391]
Hex is missing from the warlock spell list.

**Comment by Sklore** [comment]
Hi @Amniculi,

I'm unable to replicate this issue. Hex is under sp5CHex and is available to the Warlock class. 

Have you got the '5e Players Handbook' source enabled?

**Comment by Amniculi** [comment]
Is there something special I need to do to enable it?

**Comment by xdy** [comment]
Seems to work for me also. Are you doing something significantly different from what I do?

Start Hero Lab, load d&d 5e, make sure '5e players handbook' is enabled on the 'new portfolio' dialog, click ok, go to the classes tab, level up, select warlock, click add & close, go to the warlock spells tab, click the 'add more spells known' button. There I see the Hex spell among the available spells, and if I select it and press 'add & close' my character gets it, and it's also visible on the 'Spells' tab and if I print a character sheet.

**Comment by Amniculi** [comment]
The Player's Handbook has been purchased, but it's not showing up on on the new portfolio dialogue.

**Comment by Sklore** [comment]
purchased? do you have the community pack installed?

**Comment by Sklore** [comment]
Purchased? Have you added the Community Pack or are you just using the base install that you get from Lone Wolf?
