### ISSUE TITLE
Wood Elf Resource Overspent Error?

### ISSUE THREAD

**Issue by digitalDojoNZ** [Sklore/HL_DD_5e_Colab#392]
Kia ora. 

For some reason when I select a Wood Elf as a subrace I get a "Resource Overspent" error.

It says "only one subrace can be chosen" but I've only chosen the one.
![capture](https://cloud.githubusercontent.com/assets/16280702/15981063/c67ec154-2fc4-11e6-9be9-8d2934601734.jpg)

**Comment by Sklore** [comment]
@digitalDojoNZ - please provide the steps you took to produce this error. I'm unable to replicate it.

**Comment by Sklore** [comment]
Closing as unable to replicate. If you are able to replicate this issue please provide the steps you took.
