### ISSUE TITLE
Unearthed Arcana: Feats

### ISSUE THREAD

**Issue by LordMorin** [Sklore/HL_DD_5e_Colab#395]
I've created and scripted the feats from the new Unearthed Arcana: Feats update. As far as I can tell everything is working as it should be.

http://dnd.wizards.com/articles/features/feats

I've tried to created it in 5e Community format, but you will want to double check my work probably. :)

_**Note:** For some reason this site won't let me upload the file as a ZIP. Any ideas on why? Am I posting_

 this in the wrong location?

**Comment by Sklore** [comment]
You can send me a cloud link (dropbox, etc). Attachment issues would likely be something for Github to troubleshoot. I'm not aware of any changes.

**Comment by LordMorin** [comment]
kk, I was wondering. I'll set up a dropbox link and add it to my original posting here.

**Comment by LordMorin** [comment]
Here is my dropbox link to my oe_5e_ue_feats.user file. Let me know if this works.

https://www.dropbox.com/s/36ws6tgdgzk3cuh/soe_5e_ue_feats.user?dl=0

**Comment by Sklore** [comment]
Everything looks good on this end. Have added to the pack for next release :D Love your work!

**Comment by LordMorin** [comment]
Thanks to ShadowChemosh for the one issue I was having. :)

**Comment by Sklore** [comment]
Without @shadowchemosh I doubt we would have half the stuff functioning :+1:
