### ISSUE TITLE
Request : Unearthed Arcana - Waterborn Adventures

### ISSUE THREAD

**Issue by direwolves** [Sklore/HL_DD_5e_Colab#399]
Are there plans to update for Waterborne Adventures? I have a PC using the Mariner fighting style and I don't see it anywhere in the current version?

**Comment by Sklore** [comment]
No idea what that is sorry, is it released in any official 5e content?

**Comment by Sklore** [comment]
Found it: http://dnd.wizards.com/articles/features/unearthed-arcana-waterborne-adventures

**Comment by direwolves** [comment]
Yeah, is there any plan to incorporate that into the collab pack for Hero
Lab?

**Comment by digitalDojoNZ** [comment]
@direwolves Maybe you could do that for us?

**Comment by Sklore** [comment]
I can do the data entry (i'm not a strong scripter) but it's not going to happen until I have some free time which is a limited resource these days sorry.

**Comment by Sklore** [comment]
Ok Mariner added. The rest of this UA is already added as part of SCAG. 

I have not completed the scripting on Mariner. I tried copying all sorts of code but alas could not find the correct one. @shadowchemosh or @grandchefpanda might be able to jump in here and do it in their sleep. 

Scripting Required: As long as you are not wearing heavy armor or using a shield, you have a swimming speed and a climbing speed equal to your normal speed, and you gain a +1 bonus to AC.

**Comment by TheEnthusiast** [comment]
Hi,

I created the attached .user file in the HL editor. It implements the Mariner style, including the AC and the speeds as needed. Please take a look. Feel free to add it to the package.

I also have another work in progress for the Eberron UA article. I have the races implemented, plus the Artificer. Where could I upload the .user file?

[Vini_Waterborn.zip](https://github.com/Sklore/HL_DD_5e_Colab/files/351454/Vini_Waterborn.zip)

**Comment by Sklore** [comment]
Thanks! :+1: 

Just create an issue and attach to it. Then I can load it in.

**Comment by Sklore** [comment]
BTW always happy to welcome new people to the project if your keen to help more. We are low on people with descent scripting skills.

**Comment by Sklore** [comment]
Implementation complete with thanks to @TheEnthusiast 

Will be released in the next update. You can get it early by downloading and putting the files in your 5e folder.
