### ISSUE TITLE
typo with Stout Halfling subrace

### ISSUE THREAD

**Issue by mercenary-kantor** [Sklore/HL_DD_5e_Colab#400]
Under Halfling Subrace Stout:  Second Paragraph, Second line should read "stocky" not "ntocky"

**Comment by Sklore** [comment]
I'm not showing an issue. Unless someone already fixed this. 

"Stout halflings are shorter and stockier than other halflings, and they usually live among dwarves. Halflings are quiet, retiring, and do not seek attention. They are farm folk, pastoral people who don't get excited about much. 

The stouts are about six inches shorter than other halflings, standing about 2'6" tall, and are comparatively stocky in build. They usually weigh between 30 and 35 lbs. They have brown or black eyes. Halfling men often have long sideburns, but beards are rare among them and mustaches are almost never seen. Halflings prefer simple, comfortable, and practical clothes. Unlike members of most races, they prefer actual comfort to shows of wealth."

**Comment by mercenary-kantor** [comment]
and are comparatively stocky in build.  In my Hero lab V7.6b and community D&D 5e srd V1.5 this is written "ntocky".  mercenary-kantor 

    On Friday, July 1, 2016 11:10 PM, Sklore <notifications@github.com> wrote:
 

 I'm not showing an issue. Unless someone already fixed this. "Stout halflings are shorter and stockier than other halflings, and they usually live among dwarves. Halflings are quiet, retiring, and do not seek attention. They are farm folk, pastoral people who don't get excited about much. The stouts are about six inches shorter than other halflings, standing about 2'6" tall, and are comparatively stocky in build. They usually weigh between 30 and 35 lbs. They have brown or black eyes. Halfling men often have long sideburns, but beards are rare among them and mustaches are almost never seen. Halflings prefer simple, comfortable, and practical clothes. Unlike members of most races, they prefer actual comfort to shows of wealth."—
