### ISSUE TITLE
Add Eberron Material

### ISSUE THREAD

**Issue by TheEnthusiast** [Sklore/HL_DD_5e_Colab#405]
Hi, 

So, this is not an issue. I created the Races, Dragonmarks and the Artificer as described here: http://media.wizards.com/2015/downloads/dnd/UA_Eberron_v1.1.pdf

I'm contributing this to the project. The attached file has the whole material. To see it, you'll need to check the Book Eberron on the initial screen, under 5e Sourcebooks -> Unearthed Arcana

The only missing item is the Action Points, which I don't know how to add.

There's also an issue with the unarmed attack of the razorclaw shifter's shifting feature, which does not use DEX to damage. This is a bug in HL which WL told me they have fixed in the next version of the software (when it comes out).

[Vini_Eberron.zip](https://github.com/Sklore/HL_DD_5e_Colab/files/360566/Vini_Eberron.zip)

**Comment by TheEnthusiast** [comment]
@Sklore 
The Update 1.6 from yesterday fixed the DEx to damage thing I mentioned in my earlier post.

**Comment by Sklore** [comment]
Brilliant, I'll add this in asap.

**Comment by Sklore** [comment]
Thanks for the contribution :D this has been added to the next release.
