### ISSUE TITLE
Cleric "Knowledge Domain" 2nd level ability "Knowledge of the Ages" validation error

### ISSUE THREAD

**Issue by dragsys** [Sklore/HL_DD_5e_Colab#409]
The Cleric Knowledge domain has the ability "Knowledge of the Ages" ( ID -- c5CClrKnoA ), at level 2 which allows a character to choose a skill or tool at time of usage to become proficient in.  

The entry on the "Cleric" tab under "Class special abilities" for Knowledge of the Ages wants the player to select the skill or tool from a drop down. As this is chosen at the time of usage, the need for the drop-down choice is non-existent and if it is not chosen, it causes the validation script to fail and return an error, which is added to the printed character sheet.

**Comment by Sklore** [comment]
This really doesn't need a selection at all then. This can be managed in-game by player and DM as it comes up. I'll remove the script from the pick. 

C h a n n e l D i v i n i t y :
K n o w l e d g e o f t h e A g e s
Starting at 2nd level, you can use your Channel Divinity to tap into a divine well of knowledge. As an action, you choose one skill or tool. For 10 minutes, you have proficiency with the chosen skill or tool.

**Comment by Sklore** [comment]
Will be fixed in next release
