### ISSUE TITLE
Cleric of Life not adding Guardian of Faith to Spells Known

### ISSUE THREAD

**Issue by Mozmonar** [Sklore/HL_DD_5e_Colab#410]
Upon gaining 8th level Clerics of Life Domain add Death Ward and Guardian of Faith to their spells known/memorized list. Currently only Death Ward is added. Workaround is that you can add Guardian of Faith manually but when you add your additional spell you get validation error for having too many spells.

**Comment by Sklore** [comment]
Cleric of Life is maintained by Lone Wolf. Please report this issue directly to them.

http://www.wolflair.com/redirect/bugreport.php?project=5e
