### ISSUE TITLE
Weasel familiar

### ISSUE THREAD

**Issue by Seaners4real** [Sklore/HL_DD_5e_Colab#413]
Hello, I'd love to be able to select weasel as my wizard's familiar.

**Comment by Sklore** [comment]
Hi @Seaners4real, 

rWeasel is maintained by Lone Wolf. Looks like they just need to tick the 'Can be familiar' box in the thing. Given the Find Familiar spell allows selection of the Weasel this option should be ticket and as such this can be considered a bug. Please log a request to LW directly using the link below:

http://www.wolflair.com/redirect/bugreport.php?project=5e
