### ISSUE TITLE
Boltnine Homebrew races

### ISSUE THREAD

**Issue by Mozmonar** [Sklore/HL_DD_5e_Colab#414]
So I am not sure if this is appropriate to request... I am trying to get up to speed on adding stuff but I am pretty crap at it as yet. So I request these races. Please and thank you.

[Shardmind.pdf](https://github.com/Sklore/HL_DD_5e_Colab/files/400800/Shardmind.pdf)
[Ursine.pdf](https://github.com/Sklore/HL_DD_5e_Colab/files/400802/Ursine.pdf)
[Elapidae.pdf](https://github.com/Sklore/HL_DD_5e_Colab/files/400801/Elapidae.pdf)

**Comment by Sklore** [comment]
Can you please provide sources for these.

**Comment by Mozmonar** [comment]
https://www.reddit.com/r/UnearthedArcana/comments/3yckze/boltnine_homebrew_is_shutting_down_heres_a_mirror/

**Comment by Sklore** [comment]
Ok all added. @Mozmonar please test and let me know if you find any issues. Will be released in the next patch. You can try it now by downloading from the link below and putting the files in your 5e Hero Labs folder and restarting Hero Labs. 

https://github.com/Sklore/HL_DD_5e_Colab/archive/master.zip

**Comment by Mozmonar** [comment]
Thank you so much. That was fast. One think I will note, the Ursine needs to have regular unarmed attack added to it (even though they superior natural attacks with bite and claw. The reason is if you take monk class with Ursine it fails to add and calculate the monk's increasing unarmed damage.

**Comment by Mozmonar** [comment]
Hmm it seems they need to be added for the Elapidae and Shardmind as well.

**Comment by Mozmonar** [comment]
Elapidae don't have the ability to choose their subraces. I see the subraces present in the file but they are not able to be selected.

**Comment by Sklore** [comment]
Ok unarmed strikes are added. Thanks for that. 

I can see and add the subraces without issue. Can you please double check this.

**Comment by Mozmonar** [comment]
Right you are. When I made a copy of Elapidae and added unarmed attacks on my .usr file I failed to add the subraces. On the original the subraces were there. My bad.

**Comment by Sklore** [comment]
I still need to check if any scripting is required. That's not a strength for me though so will take longer.

**Comment by TheEnthusiast** [comment]
@Sklore, @Mozmonar 

I took a look on these races and...

- The Elapidae are "feature complete", nothing is missing.
- The Shardming do not register their immunity to disease nor the resistance to psychic. The text is there, but the resistance/immunity do not show on the character sheet. 
- The ursine are "feature complete" as well, but the monk tradition was not implemented. 

I'll work on these over the weekend, and also try to do the Druid article from this week's UA.

**Comment by TheEnthusiast** [comment]
@Sklore @Mozmonar , all done, I'm closing this one.
