### ISSUE TITLE
Cleric Divine Strike damage types

### ISSUE THREAD

**Issue by Mozmonar** [Sklore/HL_DD_5e_Colab#416]
I'm starting to feel like a pest. I apologize.
Currently Cleric Domains of Nature, Tempest, Trickery, and War all use Radiant damage for Divine Strike.
In PHB they are as follows...
Nature Domain: Cold, Fire, or Lightning (choose for each attack)
Tempest Domain: Thunder
Trickery Domain: Poison
War Domain: same as equipped weapon

Death Domain correctly uses Necrotic for Divine Strike

**Comment by Sklore** [comment]
Mate pest away. There's way too much date to input and not enough quality checks :+1:  I'll be the first to admit that lol. I'll check into this later.

**Comment by Sklore** [comment]
Ok so looks like Death Domain is the only one we made a unique Divine Strike. The rest all make use of the same Divine Strike thing. 

To Do: Create unique Divine Strikes for all unique Cleric Domains. Link them to each domain correctly.

**Comment by Sklore** [comment]
These are more complex actually and partially work. The main description is incorrect but the spell attack text updates correctly.
