### ISSUE TITLE
Release Schedule

### ISSUE THREAD

**Issue by Sklore** [Sklore/HL_DD_5e_Colab#42]
@shadowchemosh 

Now that we have functional Feats i believe we have replaced all missing PHB items. 

From here what are out next steps in order to release an initial pack to the public?

There are some things that are not ready to be release to the public. HOTDQ still contains 100% of the original text for example. 

I was thinking we should create a new Public repository to handle the files that are released to the public opening up the ability for the public to use the Issues register for tracking and reporting purposes.

**Comment by shadowchemosh** [comment]
So what is currently in this repository is everything you want to release correct?  Do we have any release notes we want to share?

Here is an example of what I usually do with Bug Fixes, New Features, and Data Authoring:
https://github.com/shadowchemosh/HL-Pack-Basic/releases

If so I will simply remake the .hl file and then you can feel free to use the URL in this post to give to the public (ie put into the forum post).
http://www.shadowsoftware.net/herolab/5e/updates.xml

As for future updates this is WAY simpler than Pathfinder and I expect it to stay that way for awhile.  Doing future updates just requires making the .hl file and updating the server.  Need about 20 minutes to do these steps.  I can do this during the week but not until after work.  Figure 10pm CST time zone before I can do during the week....

**Comment by Sklore** [comment]
Brilliant, 

Well i have made an initial post and FAQ post. 

http://forums.wolflair.com/showthread.php?p=224539#post224539

I have removed all files not ready for release and moved them to a private repository (sending invites to everyone now). 

Let me know once you are ok for me to release the URL :)

**Comment by shadowchemosh** [comment]
I am updating the Release Notes based on what you put in the forum post.  Should be ready really "Soon".

**Comment by shadowchemosh** [comment]
I created a draft copy of the Release notes:
https://github.com/Sklore/HL_DD_5e_Colab/releases

Let me know if that looks good?

Also good job with the juggling the baby and typing.  You must have the Ambidexterity feat! =)

**Comment by Sklore** [comment]
Looks good :)

Just reading one a story now, should have like 20 minutes free time soon ;)

**Comment by shadowchemosh** [comment]
Damn a whole 20 minutes!  Don't go too crazy or nothing. =)

We are good to go.  Giving out this URL will now allow access to the 5e Community Pack v1.0.
http://www.shadowsoftware.net/herolab/5e/updates.xml

**Comment by Sklore** [comment]
Post updated - let the fun begin and hopefully let the hate on the SRD release reduce :)

Thanks to everyone who helped get this across the line and Tim you are an absolute asset the to community. 

Sending out invites to the private copy of the repo shortly.

**Comment by shadowchemosh** [comment]
I would put the URL in a CODE brackets so people can't click on it.  It will be confusing as they will click on it expecting to just get the file which they can't as they will see XML.  I know this from experience. =)

**Comment by Sklore** [comment]
done

**Comment by shadowchemosh** [comment]
Sweet!

**Comment by shadowchemosh** [comment]
What we will do in the near future is I can setup a User ID/Password that will allow you access to the 5e folder on my server. Then once you know how to make the .hl and change the update.xml you will be free to take it out of my hands.  You will simply use a FTP client like FileZilla to easily upload/download or make changes to the files in the 5e directory.

This is what I did with Sendric and the d20 (3.5) package.

**Comment by Sklore** [comment]
Ok that sounds great

**Comment by Sklore** [comment]
Closing this discussion now that we have release.
