### ISSUE TITLE
Spell Attack Adjustment

### ISSUE THREAD

**Issue by Tricky110974** [Sklore/HL_DD_5e_Colab#421]
When adding the adjustment, I cannot select anything in the menu. I can change the Spell Name and Damage.

**Comment by Sklore** [comment]
I don't believe this does what you want it to do. The custom expression text makes me thing this is looking for weapons that apply spell damage. 

Original - Custom Expression = component.BaseWep & thingid.w5CSpellAt

Spells themselves do not have fields to list damage. For the purpose of the program they are basically just items with associated text that can be picked by the player. The text contains the damage. Therefore this cannot be adjusted with an Adjustement. 

This is how the app is built. Any requests to implement better spell functionality would need to be raised with Lone Wolf.
