### ISSUE TITLE
Banneret (Purple Dragon Knight) is in the wrong menu

### ISSUE THREAD

**Issue by Cerxi** [Sklore/HL_DD_5e_Colab#423]
As an archetype, it should be under "Martial Archetypes", along with Battle Master, Champion, and Eldritch Knight. Instead, it is listed under Fighting Styles. Unique ID is c5CFtrPuDK

**Comment by Sklore** [comment]
Thanks for the report. This will be fixed in the next release. Alternatively you can get it early using the download button and copy the contents of the zip to your 5e Hero Labs folder.
