### ISSUE TITLE
Tomes and Manuals

### ISSUE THREAD

**Issue by craetus** [Sklore/HL_DD_5e_Colab#429]
Are these items correctly updating the character, or am I not doing something correctly?

**Comment by Sklore** [comment]
Is this a specific item or class option?

**Comment by craetus** [comment]
A number of items:

Tome of Clear Thought
Tome of Understanding
Tome of Leadership and Influence
Manual of Bodily Health
Manual of Gainful Exercise
Manual of Quickness of Action

Each of these add +2 to a stat, and raise the stat maximum from 20 to 22. Currently, when you select the item, it doesn't actually affect your stats. Now, you can add +2 to a stat as a permanent adjustment, but it will not allow you to go above the racial maximum. It stops at 20 instead of 22.

Unless I am doing something incorrectly after deleting one of these items.

**Comment by Sklore** [comment]
Ok these are all maintained by Lone Wolf. Looks like there is no coding on them. You will need to report this to LW to have fixed. 

http://www.wolflair.com/redirect/bugreport.php?project=5e
