### ISSUE TITLE
Familiars and Pact of the Chain

### ISSUE THREAD

**Issue by Killanath** [Sklore/HL_DD_5e_Colab#43]
Warlocks who select Pact of the Chain can acquire familiars, and have additional options to choose from for doing so, but these options don't appear in the community files: imp, pseudodragon, quasit, or sprite.

Not sure if this is an oversight, or just because the monsters in question aren't in the files yet.

**Comment by Sklore** [comment]
Looking at how this is working it is reliant on the Monster Manual entries which have not been released by LW yet. LW have indicated they are looking to release this in the next big update for the 5e SRD pack. With that in mind we won't add these in as that would just cause conflicts in the near future.
