### ISSUE TITLE
Staff of Defense from Lost Mine of Phandelver.

### ISSUE THREAD

**Issue by LordMorin** [Sklore/HL_DD_5e_Colab#432]
This zip contains a .user file containign the Staff of Defense from the Lost Mine of Phandelver module. I created it in response to a HL 5e Posting by SFornelli but thought it might be added to the Community pack.

[soe_5e_LMoP.zip](https://github.com/Sklore/HL_DD_5e_Colab/files/464816/soe_5e_LMoP.zip)

**Comment by Sklore** [comment]
Thanks @LordMorin 

Totally never noticed staff's have 2x entries in the tool.

**Comment by Sklore** [comment]
Ok this will be added with the next release.

**Comment by LordMorin** [comment]
Always liek to help when I have the time. I'm way behind on my promise of Unearthed Arcana's Mystic v2 class. :/
