### ISSUE TITLE
Unearthed Arcana - Sorcerer Subclass - Favored Soul

### ISSUE THREAD

**Issue by LordMorin** [Sklore/HL_DD_5e_Colab#435]
I thought the Community had already added this to the pack otherwise I would have uploaded it earlier.

This is from the Unearthed Arcana - Class Design variants.
Sorcerer bloodline - Favored Soul
Thanks to ShadowChemosh for his help with this a while back.

Jobsays was asking about it and I was surprised to find I hadn't uploaded it, so here it is.

[soe_5e_ue_favoredsoul.zip](https://github.com/Sklore/HL_DD_5e_Colab/files/470599/soe_5e_ue_favoredsoul.zip)

**Comment by Sklore** [comment]
Thanks @LordMorin 

This will go out with the next release.
