### ISSUE TITLE
Druid: Thousand Forms Incorrectly Applied

### ISSUE THREAD

**Issue by bdavis19** [Sklore/HL_DD_5e_Colab#440]
I created a 2nd level Druid, 1st level Monk using the human variant. On my sheet, as a racial bonus, is listed the Alter Self at-will, which is the Circle of the Moon Druid's level 14 feature: Thousand Forms. So it seems like this is being applied too early to the character.

**Comment by Sklore** [comment]
We've had one similar to this one before. The spell is bootstrapped to the The Thousand Forms thing which is being correctly called at L14. 

@shadowchemosh / @grandchefpanda - can anyone remind me how we solved this one previously. Did we have to add an Eval script to handle the bootstrapping?

**Comment by LordMorin** [comment]
If this has been added as a Class Ability, then when it was chosen as part of the subclass under Class Special Abilities, level 14 should be set there. 

If I am misreading what you were asking my apologies. I haven't seen the subclass. If the Circle of the Moon was created by HL, then they'll have to fix this one.

**Comment by LordMorin** [comment]
Ah, here we go. Circle of the Moon is part of the Community pack. The PHB Classes COM file to be exact.

You need to add this to the bootstrapped spell for Thousand Forms under Class Specials.

Set the Alter Self's Condition to Priority 2500 and the Tag Expression to: count:Classes.Druid >= 14.

I did that at my end and it seems to have fixed the issue.

**Comment by Sklore** [comment]
This is one of ours. 

The sub-class bootstraps 'Thousand Forms' at L14 using the ClSpecWhen tag. 
Thousand Forms bootstraps the spell. 

The issue being that the spell is adding straight away despite the L14 ClSpecWhen tag.

**Comment by Sklore** [comment]
Ok this one will be fixed in the next release. Thanks for the bug report @bdavis19
