### ISSUE TITLE
To Do: Psionic Handbook

### ISSUE THREAD

**Issue by Sklore** [Sklore/HL_DD_5e_Colab#447]
Source: https://drive.google.com/file/d/0B2bXgsHg7PtJNEdpNHBVRDVOXzA/view

**To Do:** 
- Full check of everything provided. This file contains alot of content not specific to the Psionic Handbook. 
- All names need to be updated to include 5C. 

There is a forum discussion taking place about this content: http://forums.wolflair.com/showthread.php?t=56191&page=5

Warning: It's apparent a number of people are interested in this content and have reached out to the author for a copy. Due to the requirement to rename everything, the next release should include a warning about conflicts. 

Original File Name: 
GeorgeMagic.user
GeorgeMagicv2.user

**Comment by LordMorin** [comment]
Sklore:

  I downloaded this from browse files. Are you sure this is from the Consolidated Psionic Handbook (CPH)?

It looks more like my version from the Unearthed Arcana site. From what I saw when I went in to it to give you a hand it covers only the UA materials, not the extended materials from the CPH.

I don't care but you might want to put it under Unearthed Arcana if it is a version I uploaded. :)

**Comment by Sklore** [comment]
You sure? It was cross referenced with this:

https://drive.google.com/file/d/0B2bXgsHg7PtJNEdpNHBVRDVOXzA/view

**Comment by LordMorin** [comment]
At the moment I am NOT sure. Try to test it out atm. I have to completely remove my version from my 5e folder to test it. They conflict with each other big time.

I'll post here shortly.

**Comment by Sklore** [comment]
Send me through a copy of your UA one. Then I can add them both ;)

**Comment by LordMorin** [comment]
They are not the same. I must have re-downloaded my own upload . . . I think. Now that I have it working, I can see that it goes up to 20th level and mine doesn't. 

I can also see that if I use it instead of creating my own version, I'll have to re-do everything I've done in relation to my version of the Unearthed Arcana original . . .

So the mistake is mine and you have it right.

**Comment by Sklore** [comment]
I assume they share the same ability names. Probably why it's causing errors?

**Comment by LordMorin** [comment]
Most definitely.

I'll have to create my own version of the CPH then delete the Community version when it goes official <sigh>

The community version will use the class abilities as spells. Mine has them set up as true class abilities, This allows me to apply the bonuses from the in-play tab, something I don't think you can do in the community version without a shitload of adjustments.

In other words I like the way mine is set up. :/

**Comment by Sklore** [comment]
@LordMorin  - did you get the Order of the Knife Fighter Styles working? If so can you share?

**Comment by LordMorin** [comment]
I deleted the .user file for Psionic Handbook. It conflicts with my own Unearthed Arcana version. Mine may only go to 10th level so far, but its fully scripted. The version in the new Community Pack will NOT be easy to script due to the way its been implemented.

I can take a look at it if you want me to, but it means temporarily removing all my own stuff because of conflicts with the CPH. :)

**Comment by Sklore** [comment]
Perhaps you will know the answer without needing to do that. 

Situation: FIghter / Paladins / Rangers ger fighting styles. Which is easy to setup from a class using using a Primary or Secondary table. 

How would you however setup that same functionality from a Custom Ability. Perhaps a configurable?

~ @shadowchemosh might know the answer here also.

**Comment by shadowchemosh** [comment]
@LordMorin why do you get conflicts?  Are you using 5C in your Unique ID's of Things?

@Sklore can you expand your question some.  I am not fully getting the idea.  Are you trying to get a Custom Ability to appear for multiple classes or are you trying to get Ranger Fighting Styles to appear for the Fighter class?  Remember I don't know allot of about 5E so what maybe obvious to you guys is not to me. =)

**Comment by shadowchemosh** [comment]
@LordMorin never mind.  After re-reading the this thread I see the answer. =)

**Comment by LordMorin** [comment]
Chemosh:

  I created the Unearth Arcana version of the Mystic v2 a long while back. I've also created a lot of homebrew material for that version of the Mystic. Because of the new Psionic Handbook is based off the UA Mystic, it used several id's that I used myself (ie. cHelpMys & others). Normally I use soe in my tags and id's. Rather than do through all my scripts looking for conflicts I just deleted the Community version since I'll never use it.

**Comment by LordMorin** [comment]
I posted my reply just after your last response. :)

**Comment by shadowchemosh** [comment]
So one tip I can give is that you can actually make a Class Helper ID longer than 7 characters.  So for my home brew classes I have say cHelpS2Mys this way having "S2" I prevent ever conflicting with anything LW adds.  For Pathfinder Path of War I actually went with cHelpPoW1 and then cHelpPoW2 using numbers to prevent any conflicts.

Just an FYI. =)

**Comment by LordMorin** [comment]
Chemosh:
  The Order of the Knife is am Archetype for the Mystic introduced in the home-brewed expansion of the Unearthed Arcana Mystic.

It grants the Mystic his or her choice of one of the following Fighting Styles: Duelist, Great Weapon Fighter, or Two Weapon Fighting.

I've never added fighting styles to a Archetype before, so I'm trying to figure it out atm by creating the archetype for my version of the Mystic.

**Comment by LordMorin** [comment]
Learnign somethign new:

  Chemosh, I didn't realize you could have a Class Helper Id longer than 7 characters . . . 

:)

**Comment by shadowchemosh** [comment]
I found the pdf and was reading it over.  So if the Mystic takes "order of the Knife" ability then the class should offer a new set of choices to pick (Fighting Style) from the existing Duelist, Great Weapon Fighter, or Two Weapon Fighting Custom Abilities.  This should all display on the "Mystic" tab correct?

If that is correct then yes this is pretty easy to do actually especially with the new features of the *Extend tab that Colen added.  I should be able to wipe up a working version this afternoon.

**Comment by LordMorin** [comment]
Bah, you are an evil individual Chemosh. I'd completely forgotten about the Extend tab except for adding spells to new classes or existing classes . . . :(

Thanks for pointing that out to me.

**Comment by shadowchemosh** [comment]
Hopefully the comments on the commit and in the .user files are enough to explain how I accomplished this.  If not feel free to ask. =)

**Comment by Sklore** [comment]
Thanks guys 😁 quite a few people will be very happy about this.
