### ISSUE TITLE
Release Preparation - V1.6

### ISSUE THREAD

**Issue by Sklore** [Sklore/HL_DD_5e_Colab#452]
@shadowchemosh 

Gday Tim, 

Could you schedule us in for a push to V1.6 when you have free time please mate. Just updated the 'Pending Changes' and realized there's quite a bit of new content, some of which I'm sure other's are keen to use. 

Notes have been updated to: https://github.com/Sklore/HL_DD_5e_Colab/wiki/3.-Pending-Changes

I've tested with a fresh install of the GitHub copy of the Comm Pack and have not received any errors.

**Comment by shadowchemosh** [comment]
Yep as soon as I can.

**Comment by shadowchemosh** [comment]
So I would really prefer to not include this new Work-In-Progress folder actually.  A) I will never be able to remove it from peoples computers.  B) Removing the files from this folder could be done but it will require tracking and doing "Empty" files.  This just adds a whole extra step to the creation of the .hl file.  If we can prevent of the need of doing that with the 5e pack I would appreciate.

If someone really wants those files point them to GitHub to download. =)

**Comment by shadowchemosh** [comment]
Release notes formatted for forum:

```
[b]v1.6 September 28, 2016[/b]

[b]New Features[/b]
[list]
[*]Homebrew - Psionic Handbook
[*]Ranger - The Ranger, Revised
[*]Homebrew Race - Shardmind
[*]Homebrew Race - Ursine
[*]Homebrew Race - Elapidae
[*]Unearthed Arcana - New Warlock Patron - The Seeker
[*]Unearthed Arcana - New Warlock Pact - Pact of the Star Chain
[*]Unearthed Arcana - New Warlock Patron - The Undying Light
[*]Unearthed Arcana content - Modifying Classes - New Sorcerer Bloodline - Favored Soul
[*]Multiple Classes - Fighting Style - Close Quarters Shooter
[*]Multiple Classes - Fighting Style - Tunnel Fighter
[*]Ranger - Ranger Archetype - Deep Stalker
[*]Sorcerer - Sorcerous Origin - Shadow
[/list]
[b]Bug Fixes[/b]
[list]
[*]Added missing unarmed strikes for all HB races. 
[*]Wood Elf Sub Race - Removed extra bonus language. 
[*]Purple Dragon Knight - moved to Martial Archetypes instead of fighting style. 
[*]Cleric Divine Strikes damage types fixed
[*]Fixed superiority dice to reset per short rest instead of once per battle. 
[*]Scripting added for Sentinel Shield
[/list]
[b]Work In Progress[/b]
[list]
[*]Added 'Work In Progress' folder (NOTE: Content in this folder will not appear in Hero Labs. You can download the files from GitHub to load this content but it's not supported in it's current state)
[*]Added Primeval Thule file to WIP folder.
[*]Added Homebrew Vampire classes and templates to WIP folder.
[*]Added Magic The Gathering races to WIP folder.
[/list]
```

**Comment by Sklore** [comment]
fair call, happy for it to be left out. I honestly just wanted to put a coy of it somewhere where i couldn't lose it.

**Comment by shadowchemosh** [comment]
Makes sense.  Plus it allows other editors to easily get access to the files if they wish.  =)

**Comment by shadowchemosh** [comment]
P.S. - v1.6 is released to the wilds!

**Comment by Sklore** [comment]
Thanks mate :)
