### ISSUE TITLE
Request: Spell Less Ranger Varient

### ISSUE THREAD

**Issue by Sklore** [Sklore/HL_DD_5e_Colab#456]
UA Modifying Classes

Request: http://forums.wolflair.com/showthread.php?t=56690

**Comment by CptCOOTS** [comment]
If no one is doing this then I can. If I don't hear by tonight then I'll get to work on this.

**Comment by Sklore** [comment]
Did you do this one @CptCOOTS ?

**Comment by TheEnthusiast** [comment]
On a related issue, anibody working on the ranger/rogue UA?

Enviado de meu ASUS

-------- Mensagem Original --------
De:Daplunk <notifications@github.com>
Enviado em:Mon, 30 Jan 2017 02:33:47 -0200
Para:Sklore/HL_DD_5e_Colab <HL_DD_5e_Colab@noreply.github.com>
Cc:Subscribed <subscribed@noreply.github.com>
Assunto:Re: [Sklore/HL_DD_5e_Colab] Request: Spell Less Ranger Varient (#456)

**Comment by TheEnthusiast** [comment]
@Sklore , @Dehkul,

I've implemented the spell less range with merge #587 

Cheers!

**Comment by Sklore** [comment]
Legend!
