### ISSUE TITLE
Request: Arcane Tradition Theurgy

### ISSUE THREAD

**Issue by Mozmonar** [Sklore/HL_DD_5e_Colab#459]
This seems like it will require scripting beyond my current ability. If someone is willing and able I'd appreciate if they could add this. Thanks.

Source: https://media.wizards.com/2016/dnd/downloads/UA%20Non-Divine%20Faithful%20SFG.pdf

**Comment by TheEnthusiast** [comment]
I'm trying to do this one. I'm stuck in the part were you add the spells to the wizard's list. I can get the spells as spell like abilities, or straight into the spellbook, but not on the spelllist.

**Comment by LordMorin** [comment]
Take a look at the Arcane domain for the Cleric. It adds Wizard spells to a cleric. You should be able to use similar scripting for a Wizard to add cleric spells.

**Comment by TheEnthusiast** [comment]
Just to give an update, I finally managed to add the spells to the wizard list (yay!). Took me just 15+ hours of testing to reverse engineer it. I need to script the stuff for all of the domains. I'll give more details as soon as I'm able. It WILL take a while to complete.

**Comment by TheEnthusiast** [comment]
Here's the description, before I forget what I found:
http://forums.wolflair.com/showpost.php?p=237218&postcount=2

**Comment by TheEnthusiast** [comment]
@LordMorin @Sklore 
Does anybody know how to test if a specific source was checked? For example, I'd like to offer the arcana domain only if scag is checked.

**Comment by LordMorin** [comment]
Set the source to Sword Coast Adventures Guide.

**Comment by TheEnthusiast** [comment]
@Sklore 
Any Idea why the Improved flare from the Light Domain (lvl 6 feat.) uses a separate tracker from the one used by Warding Flare? My reading of the abilities is that they share the same pool.

**Comment by TheEnthusiast** [comment]
@Mozmonar @LordMorin @Sklore 
I've Done it! See comit 505 . Or get the attached file.

[COM_5ePack_UA - Faith Classes.zip](https://github.com/Sklore/HL_DD_5e_Colab/files/587894/COM_5ePack_UA.-.Faith.Classes.zip)

**Comment by Sklore** [comment]
Sorry guys, I've had a very sick household. Will catch up on comments eventually. 

Great to see things progressing though :)

**Comment by Mozmonar** [comment]
Thanks for this!

**Comment by TheEnthusiast** [comment]
I guess we can close this one.
