### ISSUE TITLE
Inconsistent Proficiency Handling

### ISSUE THREAD

**Issue by Sklore** [Sklore/HL_DD_5e_Colab#460]
We've gotten several bug reports about tool proficiencies that are granted by backgrounds in the 5th edition SRD community data pack appearing in the equipment section on the printed character sheet. The reason behind this bug is partly a bug in our data files, and partly due to a mistake in the community files. The bug in our data files has been taken care of, and will appear in the next release.

However, we've also spotted a mistake in how tool some tool proficiencies are being handled in the community data files. For example, the Urchin background not only has the tags to grant proficiency with the disguise kit and thieves' tools, it has bootstrapped copies of them as well. This is redundant. Only the tags are needed to grant proficiency with a specific tool.

**Comment by LordMorin** [comment]
Personally, I find that the Rogue doesn't add Thieves' Tools either. I always have to remember to add them manually on the Skills tab before adding a Rogue level. If you try to add it after adding a Rogue level, you can't. I have always assumed this was an issue at my end with a conflict between Rogue Thieves' Tools and my own stuff I have yet to track down.

**Comment by Sklore** [comment]
This has been provided by Lone Wolf btw. I know we did some work arounds early in the peace to get proficiency to show due to some issues on their end. Looks like that will all need to be reversed.

**Comment by Sklore** [comment]
Ok this issue is now fixed. Have checked all backgrounds within the community pack. Looks like this issue was isolated to the PHB backgrounds. Will be fixed in the next release.
