### ISSUE TITLE
Wizard - School of Divination

### ISSUE THREAD

**Issue by LordMorin** [Sklore/HL_DD_5e_Colab#461]
I decided to create a School of Divination school wizard today for the 1st time. I was playing a Standard human. The DM started us at 2nd level.

I was surprised to find I'd received Darkvision. I figured out that the 10th level School of Divination ability 'The Third Eye' was giving me Darkvision early. I also believe, but am not sure yet, that the other abilities that can be granted by the 'The Third Eye' ability don't seem to be present.

I had a group of friend over for a impromptu Thanksgiving dinner and D&D session so I haven't had a chance to do more than take a cursory look at the ability. I think the issue is with the Darkvision bootstrap's conditional. I also think the ability is missing its other 3 bootstraps.

I'll take a closer look when I get the time unless someone  else resolves the issues before then. :)

**Comment by Sklore** [comment]
This is probably a Bootstrap issue. We found this with other things that were bootstrapped at the correct level but trigger immediately. I wrote up some info on it here:

https://github.com/Sklore/HL_DD_5e_Colab/wiki/Bootstrapping-Methods

**Comment by LordMorin** [comment]
kk. I'll try to take a look at it tomorrow.

**Comment by LordMorin** [comment]
OK, I've added the 3 missing choices for the 10th level School of Divination 'The Third Eye' ability. I've fixed the existing Darkvision Conditional and added similar Conditionals for the missing choices. Everything seems to be working fine.

I added the 3 missing abilities under Racial Abilities sicne that is where Darkvision is. You can move them over to Abilities if you want.

[COM_5ePack_PHB - Classes.zip](https://github.com/Sklore/HL_DD_5e_Colab/files/523027/COM_5ePack_PHB.-.Classes.zip)

**Comment by LordMorin** [comment]
I just noticed a bug in the The Eye ability. It should be 1/short rest not once per day.

**Comment by Sklore** [comment]
Ok this has been uploaded. Thanks. I removed the spell bootstrap from the See Invisibility though as it was reading as a spell instead of the ability. Clearer this way.
