### ISSUE TITLE
Forest Gnome

### ISSUE THREAD

**Issue by Nomad0772** [Sklore/HL_DD_5e_Colab#472]
Is it possible to have an update to include the Forest Gnome as a race option

**Comment by Sklore** [comment]
The Forest Gnome is already included in the community pack. Sounds like you may not have the Community Pack installed properly. Please see the link below for instructions on how to install it. If you do have the Community Pack installed you should check the configuration of your character (Character > Configure Hero > Ensure 5e Players Handbook is ticked). 

http://forums.wolflair.com/showthread.php?t=55090
