### ISSUE TITLE
Homebrewed Class Sources

### ISSUE THREAD

**Issue by LordMorin** [Sklore/HL_DD_5e_Colab#475]
The following classes need to have the sources set under the Class Level tab:

COM_5ePack_Homebrew - Classes
Alchemist
Alchemist (Non-Magical)
Blood Hunter

COM_5ePack_Homebrew - Psionic Handbook
Mystic

If the sources are not set here then they still show up in the class list even if not checked under Configure Hero. This causes errors.

**Comment by Sklore** [comment]
Thanks! I noticed this a few days and couldn't figure it out given they are selected in the Class tab!

**Comment by LordMorin** [comment]
I was trying to disable a bunch of syuff for a buddy's dungeon. He wants to use just the PHB . . . :/

The stuff just wouldn't go away. :)

**Comment by Sklore** [comment]
I was doing the same thing, i just completely forgot about the Class Level tab.

**Comment by Sklore** [comment]
Ok this will be fixed in the next release. Thanks!

**Comment by LordMorin** [comment]
I fixed it in my copies, but it would have reverted unless the Community pack was fixed also :)

**Comment by Sklore** [comment]
The more people telling me about errors the better the pack gets. :)
