### ISSUE TITLE
Ranger (2016) HP error

### ISSUE THREAD

**Issue by Nalroth** [Sklore/HL_DD_5e_Colab#479]
The Ranger(2016) doesn't seem to be loading Hit points properly. It also errors out Hero Labs when I click on the question mark next to the HP line.

Hero Lab has encountered an error and needs to close. Sorry! To help us fix this error, please send the following to support@wolflair.com in a single email:

1) A description of what you were doing (unless you include this, we won't have enough information to fix your problem!)

2) This file:
D:\Documents\Hero Lab\crashreports\Hero Lab-7.6b-623-20161023-094455.dmp

3) Finally, please copy and paste this information into the email (you can right-click this message to do so):

D:\Programs\Hero Lab\HeroLab.exe 7.6b 623

major: 6, minor: 1, build: 7601, platform: 2, version: Service Pack 1, spmaj: 1, spmin: 0, suitemask: 00000300, type: 1
ACCESS VIOLATION
Address: 0x00568eb0
Type: bad read

**Comment by LordMorin** [comment]
Make sure that, under the Character tab, you go to Configure hero and make sure you have '5e Unearthed Arcana - The Ranger, Revised' checked off. If it isn't then you get the errors you are getting.

This was a common bug to a few Homebrewed classes and has been fixed I believe for the next update.

**Comment by Sklore** [comment]
@Nalroth - did the fix above sort your issue?

**Comment by Nalroth** [comment]
It did work. Not super intuitive, but I understand the reasons for why it
is the way it is.

**Comment by Sklore** [comment]
Thanks mate. The source issue has already being fixed so should improve next release.
