### ISSUE TITLE
Charlatan missing Tool Proficiencies

### ISSUE THREAD

**Issue by azuravian** [Sklore/HL_DD_5e_Colab#48]
The Charlatan is missing both the Disguise Kit and Forgery Kit from its Tool Proficiencies granted by the background.

**Comment by shadowchemosh** [comment]
This has already been reported as issue #45 please see it for details.

**Comment by azuravian** [comment]
I actually entered this as a new issue because I made a copy of the Charlatan background in the Editor and it doesn't include the two proficiencies.  This is separate from the fact that none of the proficiencies show up on the skills tab.

**Comment by shadowchemosh** [comment]
All related to the same underlying issue.

**Comment by azuravian** [comment]
Just to make sure that I'm being clear (it's possible I'm not).  All other backgrounds that grant proficiencies directly, have those proficiencies checked in the "Tool Proficiencies" list within the editor.  Charlatan does not.  I've attached screenshots comparing the sailor and the charlatan backgrounds to show what I mean.

![charlatan](https://cloud.githubusercontent.com/assets/7379812/13205200/58ece0aa-d8b0-11e5-9b4e-95bdd65ba0bf.png)
![sailor](https://cloud.githubusercontent.com/assets/7379812/13205201/58ee0a84-d8b0-11e5-97dd-cfc433e472bd.png)

**Comment by Sklore** [comment]
Thanks @azuravian i have resolved this under #51 and will push with the next release.

**Comment by shadowchemosh** [comment]
@Sklore I am confused as I fixed all the LW bugs I found.  But you just deleted all my fixes in the Background.user that actually made Background Tools work.  You added a "ProfTool.?" which I mentioned several times does NOT work.

So if you could let me know what I am missing about backgrounds then I would appreciate it.  If the method I added in was incorrect be happy to learn why.

Thanks

**Comment by Sklore** [comment]
@shadowchemosh Sorry i didn't realize this over-rid your change. 

I have re-submitted with your changes and the two Tool proficiency correctly ticked (tagged).

```
<tag group="ProfTool" tag="gKitDisgui"/>
<tag group="ProfTool" tag="gTooForger"/>
```

**Comment by shadowchemosh** [comment]
@Sklore no problem that can happen. I was just confused.. LOL =)

It looks like the ProofTool tags didn't make it on to Charalatan but instead it got:

```
    <tag group="AllowTool2" tag="gKitDisgui"/>
    <tag group="AllowTool2" tag="gTooForger"/>
```
I went ahead and changed them to ProofTool tags.

My current "fix" until we get an answer from LW is to bootstrap the Tools directly to the background with three special tags.  These tags cause the Tool to appear on the Skills tab and will cause the ProofTool.? tag to get pushed to the hero.  Getting the tag onto the Hero actually causes the character to have the proficiency. =)

```
    <bootstrap thing="gKitDisgui">
      <autotag group="Helper" tag="TrainTool"/>
      <autotag group="Hide" tag="Tool"/>
      <autotag group="Proficienc" tag="Tool"/>
      </bootstrap>
```

Currently this is the only way I could get it work.  So if you do any new backgrounds you will have to do the same thing at least until we hear from LW. =)

**Comment by Sklore** [comment]
This is what happens when you stay up all night adding 300+ spells /zzzz

**Comment by shadowchemosh** [comment]
@azuravian sorry for the confusion.  The underlying issue is that setting the "Ticks" in the editor that you showed does not currently work.  I have sent in a bug report to LW about that issue.  I have done a work around that will work.

If you want to try it out "before" the next release you can by downloading the file directly from GitHub using this URL: https://raw.githubusercontent.com/Sklore/HL_DD_5e_Colab/master/COM_5ePack_PHB%20-%20Backgrounds.user

Then start 5e game and go to **Tools->Explorer Folders->Game System Data Folder**.  That will open the correct location for where you should place the **COM_5ePack_PHB - Backgrounds.user** file.  Let it overwrite the existing file.

Then restart HL and 5e.  Give Charlatan a try and it should all be good now. =)

**Comment by azuravian** [comment]
Fantastic.  Works excellently now.  I assume the same fix will need to be made for other methods of adding tool proficiencies (such as the rogue assassin archetype).  Backgrounds seem great!!!  Thanks for all of your work.

**Comment by shadowchemosh** [comment]
@azuravian - That is a good point about Tool Proficiencies.  I was not aware of being able to get them from classes.  I am not an 5e expert.  =)

Will take a look as soon as I can to see if I can find all the different Things that give Tool Proficiencies and make the same change...

**Comment by BDragon1209** [comment]
Great job everyone, I for one really appreciate all the work which you have put into this.  I am currently in the process of adding in all of the descriptions, text, etc for my use.  One question, will any additions I make be overwritten when the next update comes around, or does the update system in Hero Lab simply add in new coding selectively.

**Comment by shadowchemosh** [comment]
@BDragon1209 if you change any file that starts with "COM_5ePack_" then it will get replaced with version 1.1 that is coming out soon.  Basically the installer totally replaces the COM_5ePack files every-time a new update loads.  So yes your stuff will be lost.

**Comment by shadowchemosh** [comment]
Still waiting to hear back from LW.  But I think we may wish to go with a new Configurable called "proficiencies" bootstrapped to the 5e mechanic. Then have all Things (Classes, Feats, Magic items) increase the number of allowed proficiencies on this new configurable.  This allows player to pick everything from the same place, it gives a consistent "feel" to the UI and allow the proficiencies to display correctly on the Skills tab.

Right now we have several ways it appears these proficiencies are getting onto characters.  This includes different methods LW did for some of the classes.  The biggest issue being that when the proficiencies is only added by script it does not display anywhere on a character...

Thoughts?

**Comment by shadowchemosh** [comment]
@Sklore thoughts on the above comment.  Do you want me to make a "central" place to have feats, class abilities, magic items, select proficiencies (ie a new tab) when a "selection" is allowed.  In example the "Skilled" feat, "Channel Divinity: Knowledge of the Ages" class ability, "Student of War" class ability, etc...
