### ISSUE TITLE
COM_5ePack_Homebrew - Classes.user

### ISSUE THREAD

**Issue by LordMorin** [Sklore/HL_DD_5e_Colab#480]
The Cleric Domain: Exorcism needs to have a source set, otherwise it shows up when you do not have this source selected.

I did not see a specific source for the Exorcism domain, so I set it to Various Homebrew Options in my file. Of course this will be undone with the next update unless fixed in the official source. :)

**Comment by Sklore** [comment]
Thanks, this will be fixed in the next release.
