### ISSUE TITLE
Tome Of Beasts

### ISSUE THREAD

**Issue by HippyCraig** [Sklore/HL_DD_5e_Colab#481]
I updated the file COM_Source_110 - Third Party Publishing.1st to include the Tome of Beasts as a source to be used in the file COM_5ePack_TOB - Monsters.user.

If you are going to contribute to COM_5ePack_TOB - Monsters.user please make sure the source files on your local copy are updated and use the newly added source for all monsters related here.

I am attaching a spreadsheet here to keep track of what I am working on and what other want to take as well.  I think this can be updated in this thread so its something new I am trying, thanks all for your patients as I attempt to create this large tome.  All help is welcome!!!

[TomeOfBeasts.xlsx](https://github.com/Sklore/HL_DD_5e_Colab/files/546658/TomeOfBeasts.xlsx)

**Comment by Sklore** [comment]
I think we should be careful with this one. I've spoken to Kobold Games and confirmed they are already in discussions with LW to create content. Not specifically Tome of Beasts just yet but they are already porting some other stuff.

**Comment by Sklore** [comment]
I've spoken to Frog God Games also btw and they are going to discuss bringing Fifth Edition Foes to RW too.

**Comment by Sklore** [comment]
We could perhaps offer to assist with the creation of content on the promise of a copy when its done?

**Comment by HippyCraig** [comment]
Should I take the TOB down then?

**Comment by Sklore** [comment]
Yeah i think so, for now. Let's see what happens. There's no point in us creating something if the content owner wants to do it themselves. I'm both curious and nervous to see the impact the RW market place is going to have on HL.

**Comment by Sklore** [comment]
Kobold Press 9-time Creator 4 days ago
@Joshua : We're looking at Realm Works, and have had conversations with the Lone Wolf crew. So far, though, we don't have a deal to provide this title there; we're launching with some other titles.

**Comment by Sklore** [comment]
Here's the discussion with Frog God Games. 
https://www.facebook.com/frog.god.games/posts/1298658873500263

**Comment by HippyCraig** [comment]
I took Tome of Beasts down for now.  If it needs to be reopened let me know but I will also close this issue as well.
