### ISSUE TITLE
Rod of the Pact Keeper Issue

### ISSUE THREAD

**Issue by DarthMord** [Sklore/HL_DD_5e_Colab#487]
Added this item to the character. Equipped it and marked it as attuned.

It does not change the Spell Attack total nor the Spell Save DC value to reflect the bonus it gives.

I went to fix it but cannot find the variables to add a bonus to.

==========

On a side note, I used an idea I saw in Community Packs for Pathfinder to create a Concentration skill to tally up the bonuses. Help text has the rules language on how Concentration checks work too.

**Comment by Sklore** [comment]
This is because the scripting for this was never added. 

If anyone knows how to do this let me know but I'm afraid I have no idea how to go about this.

**Comment by LordMorin** [comment]
Like the Wand of the War Mage I created 3 versions instead of just the 1 with 3 variants in a dropdown. Much easier to work with and you don't have players switching the bonus around.

Fully scripted now, you just have to import/replace the one in 'COM_5ePack_DMG - Equipment.user' file.

[COM_5ePack_DMG - RotPK.zip](https://github.com/Sklore/HL_DD_5e_Colab/files/555115/COM_5ePack_DMG.-.RotPK.zip)

**Comment by LordMorin** [comment]
Ok, I was tired when I created these. :)

I forgot to test them on a non-warlock; forgot to put in a doneif to get out of the script if the character had no warlock levels. This also prevents anyone who is not a warlock from getting the bonuses. I checked on multiple spellcasting classes to verify this time . . .

Here is the proper version . . .

[COM_5ePack_DMG - RotPK.zip](https://github.com/Sklore/HL_DD_5e_Colab/files/555136/COM_5ePack_DMG.-.RotPK.zip)

**Comment by DarthMord** [comment]
I tested it on some characters. Works exactly as advertised.

Thank you!

**Comment by LordMorin** [comment]
You should have left this open until Sklore could incorporate it into the actual Coomunity pack . . . (unless you did of course, then bravo) . . . :)

**Comment by DarthMord** [comment]
There was a note indicating that Sklore added a commit that referenced this item. It has a sub-note saying that it replaced Rod of the Pact Keeper with working versions.

Good point though. I'll re-open it so he can close or confirm it's good then I will close.

**Comment by LordMorin** [comment]
If they do include this, you need to remember to delete my .user file when the next update comes out. Otherwise, conflict city. :)

**Comment by Sklore** [comment]
Yeah I had to head out before I finished this. There's a conflict still. It's working on my pc just need to upload it. I've left the original but moved ot to depreciated.

**Comment by LordMorin** [comment]
Which version are you using? What was the conflict?

The first file I failed to triple check and found issues if you were not playign a warlock.

I didn't see any errors in the 2nd version, so if there are some let me know what they are so I can fix them. :)

**Comment by DarthMord** [comment]
I'm using the second one that mentions checking against class levels to ensure only warlocks get the bonuses.
I did notice a text thing on the magic panel with the updated item. When it's equipped, it also shows 1/long rest. That does NOT show when unequipped.
Otherwise, the file works fine as far as I could see, including showing up on the in-play tab too.


Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: LordMorin <notifications@github.com> Date: 10/27/16  11:29 PM  (GMT-05:00) To: Sklore/HL_DD_5e_Colab <HL_DD_5e_Colab@noreply.github.com> Cc: DarthMord <darthmord@cox.net>, State change <state_change@noreply.github.com> Subject: Re: [Sklore/HL_DD_5e_Colab] Rod of the Pact Keeper Issue (#487) 
Which version are you using? What was the conflict?

The first file I failed to triple check and found issues if you were not playign a warlock.

I didn't see any errors in the 2nd version, so if there are some let me know what they are so I can fix them. :)

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/Sklore/HL_DD_5e_Colab","title":"Sklore/HL_DD_5e_Colab","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/Sklore/HL_DD_5e_Colab"}},"updates":{"snippets":[{"icon":"PERSON","message":"@LordMorin in #487: Which version are you using? What was the conflict?\r\n\r\nThe first file I failed to triple check and found issues if you were not playign a warlock.\r\n\r\nI didn't see any errors in the 2nd version, so if there are some let me know what they are so I can fix them. :)"}],"action":{"name":"View Issue","url":"https://github.com/Sklore/HL_DD_5e_Colab/issues/487#issuecomment-256827937"}}}

**Comment by Sklore** [comment]
It's the second version. The conflict is with me trying to hide the old version not the new one.

**Comment by LordMorin** [comment]
When you say old version are you talking about my first version or the original Community Pack version. I am also not sure what you mean about 'hide'.

**Comment by Sklore** [comment]
So basically you can't delete something that has been released to the public. Well shouldn't. So we add them to COM_5ePack - Deprecated Things.user. It means it's still actually there but no longer an option that can be selected. I just made a mistake in the last change.

**Comment by Sklore** [comment]
Ok this will be released with the next update. Thanks all. 

If anyone wants to spend some time helping close out all the open tickets, please go for your life.

**Comment by LordMorin** [comment]
The one and only time I tried to work with the GIT site I messed things up. Thus, I tend todownload when I can, fix issues, then upload as a zip file to be checked and imported into the official commpunity pack .user files.

**Comment by Sklore** [comment]
Sometimes you need to break things to learn how not to break things. If you had any idea the shit i've messed up so far you would be nervous leaving me responsible for the amount of change i make ;)

If you guys are happy waiting for updates thats ok, i just don't have the time I did a year ago.
