### ISSUE TITLE
Feature Request: UA Gothic and Homebrew Artisan Classes

### ISSUE THREAD

**Issue by sistercoyote** [Sklore/HL_DD_5e_Colab#489]
UA Gothic: https://dnd.wizards.com/sites/default/files/media/upload/articles/UA%20Gothic%20Characters.pdf
Artisan Homebrew: http://dnd-5e-homebrew.tumblr.com/post/139541909590/artisan-class-by-dersitephantom-the-rest-of-the

I'm working on developing the Monster Hunter from UA Gothic but I can't figure out how to add the acquisition of one of a set selection of languages to the "Hunter's Mysticism" skill, nor how to indicate that Detect Magic is Ritual only.

I started building the Artisan but couldn't figure out how to develop either the artisan points nor the inventions into things.

Thanks!

**Comment by TheEnthusiast** [comment]
Unless i missed a step, this is already implemented and merged. @Sklore, could you confirm? 

Enviado de meu ASUS

-------- Mensagem Original --------
De:sistercoyote <notifications@github.com>
Enviado em:Fri, 28 Oct 2016 20:28:22 -0200
Para:Sklore/HL_DD_5e_Colab <HL_DD_5e_Colab@noreply.github.com>
Assunto:[Sklore/HL_DD_5e_Colab] Feature Request: UA Gothic and Homebrew Artisan Classes (#489)

**Comment by TheEnthusiast** [comment]
@sistercoyote 
You can grab a copy of COM_5ePack_UA - Gothic.user in the files to have the Monster hunter. As for the artistry points:

1) Open the editor
2) Go into Class, then Class special.
3) Click new(Blank) 
4) Add the name, id and descriptions, 
5) Check "show in tracked resource list"
6) Set your base charges to 3
7) Set the usage period to /long rest
8) Now click on Eval script
9) Add a new script on post-levels, priority 15000

use this code:

doneif (tagis[Helper.ShowSpec] = 0)
doneif (tagis[Helper.Disable] <> 0)

if (#levelcount[Artisan] >=X) then
   perform trkMax+=N
endif

Replace X by the level where you increase the points value, and N by how many extrapoints  to have. You'll need to do it a few times to acount for all the increments.

**Comment by sistercoyote** [comment]
Thanks for the pointer, and thanks for the coding tips!

**Comment by TheEnthusiast** [comment]
@sistercoyote 
Can we close this issue? Is there anything else?

**Comment by sistercoyote** [comment]
No, that's everything -- thanks!
