### ISSUE TITLE
UA Ranger: Greater Favored Enemy

### ISSUE THREAD

**Issue by Gwaithador** [Sklore/HL_DD_5e_Colab#490]
The UA Ranger is missing the "Greater Favored Enemy" feature in the class. This likely would require some sort of scripting too, because the damage increases to +4.

**Comment by TheEnthusiast** [comment]
It's implemented in the favored enemy. When you choose a second enemy, it pushes "greater" into the title. Might not show in all places.

Enviado de meu ASUS

-------- Mensagem Original --------
De:Gwaithador <notifications@github.com>
Enviado em:Sun, 30 Oct 2016 16:08:56 -0200
Para:Sklore/HL_DD_5e_Colab <HL_DD_5e_Colab@noreply.github.com>
Assunto:[Sklore/HL_DD_5e_Colab] UA Ranger: Greater Favored Enemy (#490)

**Comment by TheEnthusiast** [comment]
The Favored enemy and Grater Favored enemy need to be redone. I only copied the original ranger's list, without realizing the different lists, and the advantage on the saves.

**Comment by Sklore** [comment]
This will need to be split into 2 separate abilities. The way it works now is completely different mechanically.

**Comment by TheEnthusiast** [comment]
@Gwaithador , @Sklore 

This is fixed. The Favored enemy wasn't a thing with a list, it was a list of things, that's why I never found the original. Now it's properly implemented.
