### ISSUE TITLE
Insignia of Claws (horde of the dragon queen)

### ISSUE THREAD

**Issue by HippyCraig** [Sklore/HL_DD_5e_Colab#491]
I added this item to the monk and its not adding any of the bonus's to unarmed strike and natural weapons.

**Comment by LordMorin** [comment]
At the moment, the item has no scripting.

The following eval script needs to be added:
Phase: First, Priority: 100

>     doneif (field[gIsEquip].value <> 0)    
> 
>     foreach pick in hero from BaseWep where "component.BaseNatWep"
>       eachpick.field[BonEnhance].value += 1
>       nexteach

Also, the Source for this item should be set to' Hoard of the Dragon Queen'.

**Comment by HippyCraig** [comment]
Thanks I updated Insignia of Claws its now part of the main branch.  Thanks for the help

**Comment by LordMorin** [comment]
np, that one was easy.

**Comment by Sklore** [comment]
#493

**Comment by HippyCraig** [comment]
I noticed something odd, when I check the Insignia of Claws I see the addition to the unarmed attack.  I save it and then later when I reopened the same profile, it wasn't added even though its checked.   I had to uncheck and recheck for it to show, but again saving and reopening the profile its not part of the calculations again.

**Comment by LordMorin** [comment]
I might have to change the Priority, and maybe the Phase . . .

I'll take another look at it soon as I can.

**Comment by HippyCraig** [comment]
Ok let me know and I will test and upload the changes if succsesful

**Comment by LordMorin** [comment]
Ok, try this. It seems to have fixed the issue on my system at least.
Phase: Post-attributes, Priority: 10000


>     doneif (field[gIsEquip].value = 0)    
> 
>     foreach pick in hero from BaseWep where "component.BaseNatWep"
>       eachpick.field[BonEnhance].value += 1
>       ~perform eachpick.assign[component.BaseMagicl]
>       nexteach

**Comment by HippyCraig** [comment]
so far so good I will keep testing and then upload the changes 

Thanks!!!!

**Comment by HippyCraig** [comment]
#495 Fixed insigna of the claw
