### ISSUE TITLE
Wild Shape adjustment

### ISSUE THREAD

**Issue by LordMorin** [Sklore/HL_DD_5e_Colab#494]
This adjustment is for Wild Shape. So far it looks good. I'd like to add more features at some point in the future, but for now what I have seems to work great.

To simulate a wild shape you add a beast as a hireling. You name it Wild Shape (beast name).

You add the Wild Shape adjustment; no need to set anything.

Features:
- imports the druid's INT, WIS, and CHA scores.
- imports the druid's Proficiency bonus.
- imports the druid's skill & save Proficiencies.

That's it for now.

Chemosh; when I upload it would it be possible to list it under 'Shadows of Endore' as the Source?

You'll want to change the soe_ in front of my .user file name to COM_ of course. :)

[soe_5e_master_adjustments.zip](https://github.com/Sklore/HL_DD_5e_Colab/files/570423/soe_5e_master_adjustments.zip)

**Comment by Sklore** [comment]
Have emailed LWD to find out their plans for Wild Shape. This should really be handled by them.

**Comment by Sklore** [comment]
Response from LWD received. Looks like this is going in. 

Hi there,
Support for Wild Shape is on our long-term to-do list, but it isn't something we have planned for the next couple of months. Hope this helps!
Colen

**Comment by DarkHayZe** [comment]
Cause you know, its not important or anything /eyeroll

**Comment by Sklore** [comment]
This has been added and will be released in the next update
