### ISSUE TITLE
Volo's Guide to Monsters Player Races

### ISSUE THREAD

**Issue by Mozmonar** [Sklore/HL_DD_5e_Colab#497]
Quick and Dirty addition of New Player Races from VGM minus the Firbolg and the Goblinoids.
They seem to work but might need additional fine tuning.

[VGM-in-Progress.zip](https://github.com/Sklore/HL_DD_5e_Colab/files/577285/VGM-in-Progress.zip)

**Comment by Sklore** [comment]
The Goblin in the com pack is a homebrew btw so we should still add Volo's. I don't have the book and likely won't until Christmas so I can't really work on these at this stage.

**Comment by Mozmonar** [comment]
Yeah I just didn't get to the goblinoids (goblins, hobgoblins, bugbears,
orcs, etc.) included yet. I will likely get around to them as well unless
someone else beats me to it.

**Comment by Sklore** [comment]
Hanging for this book!

**Comment by Sklore** [comment]
Ok all races now added. There is one outstanding issue: 

Outstanding Issues: Yuan-Ti Pureblood > Innate Spellcasting > Suggestion (need to restrict this to L3, activating at L1 currently.

**Comment by Mozmonar** [comment]
Thanks. Sorry about the Yuan-Ti Pureblood goof.

**Comment by Sklore** [comment]
Nothing to do with you mate. I entered that one 😆

**Comment by Mozmonar** [comment]
Haha gave myself credit and then took the blame!

**Comment by TheEnthusiast** [comment]
@Sklore 
About the suggestion spell, add a bootstrap condition:

First/500
(count:Classes.? >= 3)

That should do it.
