### ISSUE TITLE
Tool Proficiency for Inheritor background

### ISSUE THREAD

**Issue by DaCyclops** [Sklore/HL_DD_5e_Colab#500]
Putting together an Adventurers League character and it appears that for the Inheritor background the Background Tool Proficiency lists all the valid gaming/instrument options, but doesn't actually allow you to pick one without complaining about the number of choices being too many.

A quick jaunt in the editor found "Tool Table #3" had no "Number of Choices" listed. Adding a 1 there myself caused more validation errors, but moving all the tool choices into "Tool Table #2" and giving it a "Number of Choices" seemed to work, though doesn't show any text where you actually click to add.

**Comment by TheEnthusiast** [comment]
fixed, I moved the tool selection to table 1, no issues so far.
