### ISSUE TITLE
The (Not Really) Complete Tome of Spells (5CCTS)

### ISSUE THREAD

**Issue by Mozmonar** [Sklore/HL_DD_5e_Colab#510]
Two mistakes I have come across.

Echoes is in HL as a cantrip but in the source material it is 2nd level.

Battletide is 4th level in HL but in the source material it is 5th level.

https://drive.google.com/file/d/0B0Qx4NeOkTzTZ2lrT2JoeUxQclU/view?usp=sharing

**Comment by Sklore** [comment]
Thanks :) 

This will be fixed in the next release.
