### ISSUE TITLE
Error when Favored Soul Sorcerer chooses War Domain

### ISSUE THREAD

**Issue by Mozmonar** [Sklore/HL_DD_5e_Colab#513]
If you make a sorcerer and select the favored soul sorcerous origin an then from the "Chosen of the Gods" tab select War Domain you get the following error...

This error pops up. Not sure what is actually failing because the domain spells do continue to be added.

> Invalid tag expression specified for 'foreach' statement
> Location: 'eval' script for Thing 'cfgUSFSCol' (Eval Script '#1') near line 22

**Comment by LordMorin** [comment]
Hmmmm . . . 

Well I built a new Favored Soul Sorcerer with the War domain and didn't get this issue. :/

I'll presume the obvious since you can select Favored Soul, but you may want to double check that '5e Unearthed Arcana - Modifying Classes' is checked under Configure Hero.

**Comment by Mozmonar** [comment]
Yeah I do have it checked and I'm not having this issue with other domains...well other domains I have tried. I haven't tried them all.

**Comment by Mozmonar** [comment]
Ok just quickly tried all the ones I have on my system. Arcana, Death, Exorcism, Knowledge, Life, Light, Nature, Tempest, Trickery, Void (homebrew), and War. Only war causes this error. And it caused it prior to me adding in Void last night.

**Comment by LordMorin** [comment]
Is this a multi-classed sorcerer or single classed?

Do you have homebrewed material of you own that might be conflicting?

cfgUSFSCol is responsible for creating the Chosen of the Gods tab. The fact that you are able to actually select the War domain means it is showing up.

I tried to create the Favored Soul way back when it first came out on Unearthed Arcana but in the end it was ShadowChemosh who created the scripting for it. I've never had an issue with it . . . :(

Not sure what is causing your issue since I can't duplicate it.

**Comment by LordMorin** [comment]
Hmmm . . . do you have any other Homebrewed domains installed? Besides Void sicne you just added that and were having the issue before then.

**Comment by Mozmonar** [comment]
For the purposes of testing this out it is a single classed sorcerer. I do have some modified domains that expand the bonus spells for a domain up to 9th level. But I have the base domains still there as well. And this issue happens on but my expanded bonus spells War domain and the standard issue war domain. But I take your point and I will isolate the homebrewed domains and give it a try. Easy enough to just temporarily remove that .user file.

**Comment by Mozmonar** [comment]
Ok with homebrew domains user file removed the problem still exists for me with War domain

**Comment by LordMorin** [comment]
I am at a loss. Like I said, I can't get the issue to occur at my end.

I presume you gotten the same issue with multiple characters, not just the one?

Do you get the same issue when you include absolutely no homebrewed material on the character?

**Comment by Mozmonar** [comment]
Well clearly something is different between our setups...but for the purposes of testing this out I launch HL, create a new character, select nothing other than class (sorcerer) and add 1 level, select favored soul for sorcerous origin, go to the chosen of the gods tab, and select war domain and the error is there and pops up with every change made to the character form that point forward.. I have not made any actual play characters with this setup and only dscovered it as i was testing out the homebrew expanded bonus spell domains and found the issue on war...reverted to the standard issue war domain and same issue.

Who knows...must be just something odd on my end

**Comment by LordMorin** [comment]
Most of the bugs I've helped fix I found while doing the same thing.

I seldom download newly updated .user files from the GIT site until they actually go Live. If you have, you may have newer versions of files that I don't. That's all I can think of. The error sounds to me like a conflict between the Favor Soul .user file and something you have that I obviously do not.

Maybe when ShadowChemosh logs in later today or tonight he'll have some ideas.

**Comment by Mozmonar** [comment]
I appreciate you looking into it either way :)

**Comment by LordMorin** [comment]
Like I said, I originally tried to create the Favored Soul, but it was ShadowChemosh who created it in the end. He came up with a way to make it work where my method didn't. :)

I always like to follow up on stuff I had a hand in. :)

**Comment by TheEnthusiast** [comment]
@Mozmonar 
Hi,

1) Please open your COM_5ePack_UA - Classes.user with the editor.
2) Go to General->Configurable 
3) Edit the #1 eval script of cfgUSFSCof
4) Go to line 22 and add the following code before this foreach loop: "foreach pick in hero from BaseSpell where searchexpr"

Code:
debug " spell tag list: " & searchexpr

5) Click ok, save and compile the thing
6) Go back to hero lab and create a new sorcerer/favored soul
7) Click on Develop->Floating Info Windows->Show Debug Output
8) Select the war domain in the Chosen of the gods tab
9) Check the output generated in the Debug Output window.
10) Post it here.

**Comment by Mozmonar** [comment]
Will do when I get a chance. Today is pretty busy with family stuff. Thanks!

**Comment by TheEnthusiast** [comment]
@Mozmonar 

Do you still have the issue?

**Comment by Mozmonar** [comment]
To be honest I forgor to get around to checking after Thanksgiving
craziness. My apologies.

**Comment by Sklore** [comment]
I have just done a fresh install of the Community Pack and tested this with no errors received. 

Changing this from Bug to Pending Customer so we can get an over-view of what needs to be fixed so be can push an update out.

**Comment by Sklore** [comment]
Closing this out as no more information was provided. Please reopen the ticket if this is still an issue.
