### ISSUE TITLE
SCAG - Half-Elf Variants

### ISSUE THREAD

**Issue by Sklore** [Sklore/HL_DD_5e_Colab#517]
Half-Elf Variants is not implemented properly. 

This needs to be looked at and fixed prior to release. 

Perhaps it would be better moving this to the WIP folder instead of pushing out this half baked version that I tried to make. 

HALF-ELF VARIANTS
Some half-elves in Faerun have a racial trait in place of the Skill Versatility trait. If your DM allows it, your half-elf character can forgo Skill Versatility and instead take the elf trait Keen Senses or a trait based on your elf parentage: 

• A half-elf of wood elf descent can choose the wood elf's Elf Weapon Training, Fleet of Foot, or Mask of the Wild.
• A half-elf of moon elf or sun elf descent can choose the high elf's Elf Weapon Training or Cantrip.
• A half-elf of drow descent can choose the drow's Drow Magic.
A half-elf of aquatic heritage can choose a swimming speed of 30 feet.

**Comment by TheEnthusiast** [comment]
@Sklore 
I re implemented the half-elf variants. I believe you can remove the half-elf(variants) from the three. Is there anything else from SCAG missing?

**Comment by Sklore** [comment]
Mate well done :)

There's another ticket for the outstanding SCAG issues under Sword Coast Adventures Guide #224. 

So I'll close this one off.
