### ISSUE TITLE
v1.7 broke Exorcism Domain

### ISSUE THREAD

**Issue by ethernetguru** [Sklore/HL_DD_5e_Colab#537]
The latest update broke the request that you had fulfilled for me.  http://forums.wolflair.com/showthread.php?t=55654

**Comment by ethernetguru** [comment]
http://harbinger-of-doom.blogspot.com/2015/02/d-5e-exorcism-domain.html

**Comment by Sklore** [comment]
@ethernetguru when you say broke what do you mean? I've just tested this out and don't appear to be having any errors with the Exorcism domain. Can you please provide more information.

**Comment by ethernetguru** [comment]
In the cleric Tab, the Exorcism domain is shown in red prompting HA to have me select a new domain.

![image](https://cloud.githubusercontent.com/assets/6391748/21852139/c46930d4-d7c6-11e6-9d61-950c1b844f4d.png)

**Comment by ethernetguru** [comment]
![image](https://cloud.githubusercontent.com/assets/6391748/21852252/398bca84-d7c7-11e6-9564-4919c81992d1.png)

**Comment by Churchill92** [comment]
I too am having the same problem as ethernetguru. When selecting a character with the domain in question, the domain appears to be IGNORED as far as being processed by HeroLab.  This domain broke with the recent update as I had no problem before this time.

**Comment by LordMorin** [comment]
Have you checked to see if Character Tab > Configure Hero > Homebrew
Options to see if Cleric - Exorcism Domain is checked?

**Comment by Churchill92** [comment]
@LordMorin That was my problem. I selected the options and BAM the domain appeared.

Thank you for your help.

**Comment by LordMorin** [comment]
np. One of the thing we are trying to fix is missing sources for everything
that is missing them. That way you can turn them off if they aren't being
used in a particular campaign. :)

**Comment by Sklore** [comment]
I'm also going along fixing the "not allowed in adventure league games"  which this was setup incorrectly for. 

Sounds like this issue is the fact that the source info was not originally set and  now it it. Please check to ensure you have the source enabled.

**Comment by ethernetguru** [comment]
That fixed it for me as well.
