### ISSUE TITLE
Update: Princes of the Apocalypse New Monsters

### ISSUE THREAD

**Issue by BioDD** [Sklore/HL_DD_5e_Colab#538]
Please add these to the Monsters list so I can create encounters with them. I love everything about this app and want to use it all the time!
Feathergale Knight
Howling Hatred Initiate
Howling Hatred Priest
Hurricane
Skyweaver
Thurl Merosska
Windharrow
Aerisi Kalinoth
Black Earth Guard
Black Earth Priest
Burrowshark
Sacred Stone Monk
Stonemelder
Hellenrae
Miraj Vizann
Marlos Urnrayle
Eternal Flame Guardian
Eternal Flame Priest
Flamewrath
Razerblast
Bastian Thermandar
Elizar Dryflagon
Vanifer
Crushing Wave Priest
Crushing Wave Reaver
Dark Tide Knight
Fathomer
One-Eyed Shiver
Shoalar Quanderil
Gar Shatterkeel
Drannin Splithelm
Ghald
Oreioth
Wiggan Nettlebee
Air Elemental Myrmidon
Earth Elemental Myrmidon
Fire Elemental Myrmidon
Water Elemental Myrmidon
Imix
Ogremoch
Olhydra
Yan-C-Bin

**Comment by Sklore** [comment]
It will take a bit to make all this... but... I have these already made with the custom monster creator. Let me see if I can find a way to share that as a short term fix for you.

**Comment by BioDD** [comment]
Thank you! I thought about doing it that way but just figured I would ask
since the community pack is so comprehensive already. Just let me know if
you find a way to share

**Comment by Sklore** [comment]
I have a superb way to share...  But it requires Realm Works with beta access 😕

There is a way.  If I load them all into a single fight from realm works you could then load them into your own portfolio.

**Comment by Sklore** [comment]
For personal use only: https://drive.google.com/file/d/0B_6BXlzLTlj8U1dQZGZqZ3NNZkk/view?usp=sharing

There's a bug in it somewhere but it does not seem to stop it from working.

**Comment by Sklore** [comment]
Closing this one for now. Custom monster provides easy enough functionality to add monsters.
