### ISSUE TITLE
To Do: New Content To Be Added To Source Files

### ISSUE THREAD

**Issue by Sklore** [Sklore/HL_DD_5e_Colab#54]
Reminder to add new files to 1st and source files. 

The Book of Lost Spells is complete
SCAG Backgrounds is complete

**Comment by shadowchemosh** [comment]
Can add one for "The Book of Lost Spells" tonight most likely when I get home.  I looked up that book and I see its from FGG.  Pathfinder stuff is broken up differently because of "License" issues.  So for us FGG is part of the 3PP pack.

In this case for 5e we don't have to worry about HL License Keys yet.  But would it make sense for the all Frog Game Games stuff to be together under a new parent?

1) example we could do:
```
User Content (Parent)
-Community Packs (Parent)
--5e Core Pack (v1.00)
---5e Sourcbooks (Parent)
----Sword Coast Adventures Guide
----The (NR) complete tome of spells
----Frog God Games (Parent)
-----Book of Lost Spells
---5e Adventures
----Tyranny of Dragons
-----Hoard of the Dragon Queen
-----Rise of Tiamat
```

2) This example moves the 3PP stuff to its own section to make it more clear what is from WotC and what is not:
```
User Content (Parent)
-Community Packs (Parent)
--5e Core Pack (v1.00)
---5e Sourcbooks (Parent)
----Sword Coast Adventures Guide
---3PP Sourcbooks (Parent)
----The (NR) complete tome of spells
----Frog God Games (Parent)
-----Book of Lost Spells
---5e Adventures
----Tyranny of Dragons
-----Hoard of the Dragon Queen
-----Rise of Tiamat
```


Let me know any thoughts.
Thanks!

**Comment by Sklore** [comment]
I like the idea of separating the 3PP material  out from the official stuff. We have already had a few questions about what some of the 3PP stuff is so this will make it clearer and hopefully trigger people to go searching and even purchase the material.

**Comment by shadowchemosh** [comment]
Sounds good.  Will go with the 2nd example then.  This is whats nice using the .1st files.  Making these kind of changes becomes pretty easy. =)

**Comment by Sklore** [comment]
Yeah I've been paying attention to the code you are putting in there. Looks easy enough to use and makes it so much easier to control. 

I notice you remove the <Parent> flag on the source material from everything. I'm assuming i shouldn't be putting that in anywhere? Is that controlled by the 1st files?

**Comment by Sethvir** [comment]
I agree on option 2.  Makes sense to organize it that way.  I've got a bunch of En Publishing EN5IDER stuff done.  At least the text in, if not fully functional, but as Josh said, there doesn't seem to be an OGL designation associated with any of that material at this time.

**Comment by shadowchemosh** [comment]
Ok done!

I also added the EN Publishing parent and a child source for EN5ider.  Hopefully that is what you wanted @Sethvir.  If not its easy enough to change.  Just let me know.

Thanks

**Comment by Sklore** [comment]
Thanks Shadow - Closing out.
