### ISSUE TITLE
with the Magic Initiate feat

### ISSUE THREAD

**Issue by mercenary-kantor** [Sklore/HL_DD_5e_Colab#540]
Printout of hero in HL does not include the spells of the magic initiate feat from 5eSCPHB.  It just prints the normal spell list of a spell caster without the extra spells of that are provided by the feat. .

**Comment by Sklore** [comment]
Interesting - It does include the cantrips but does not include the 1st level spell.

**Comment by Sklore** [comment]
@shadowchemosh - Mate pretty sure this was one you put together. Can you think of any reason only the cantrips would be making their way through to the printed sheets? I can see you created a Configurable to get this to work.

**Comment by shadowchemosh** [comment]
Honestly it must have something to do with these be 'Racial' spells setup with the Helper.SpellLike tag.  The character sheet dossier is most likely setup to ignore or not include those when printing.

You would need to report to this LW to look at.  Either they have to fix it or tell us what we are missing to force these to print.  When dealing with the character sheet of HL its like a black hole. =(

**Comment by Sklore** [comment]
Thanks mate,  reading through the code the racial bit was also what jumped out as being different. I'll get in contact with LW.

**Comment by Sklore** [comment]
Reported to LW.

**Comment by Sklore** [comment]
LW have confirmed they have fixed this. The update will release in the next patch.
