### ISSUE TITLE
1st level ranger(Sept 2016) in hl has a bug

### ISSUE THREAD

**Issue by mercenary-kantor** [Sklore/HL_DD_5e_Colab#542]
under Ranger (Sept 2016) tab, with the Special button for special abilities:  1st level reads Favored Enemy and Greater Favored Enemy.

**Comment by Sklore** [comment]
Ok so this one is pissing me off... 

I have fixed the issue raised. Both now appear correctly. 

BUT....

If you pick Favored Enemy = Humanoid you get to choose 2x languages instead of 1!

@TheEnthusiast, @shadowchemosh @xdy - Any ideas where this might be coming from?

**Comment by LordMorin** [comment]
As far as I know, when you pick Humanoid, you get to pick two types of
humanoid. Thus, you get a language for each.

What I want to know is why Aasimar & Drow aren't showing up in the list of
humanoid races while Tieflings, wood elves, and high elves are.

**Comment by TheEnthusiast** [comment]
The humanoid option means any humanoid. You no longer pick a subrace.

Enviado de meu ASUS

**Comment by Sklore** [comment]
It's all fixed now. The humanoid option specifically had the abValue set to 2. Took me about 2 hours to find that.
