### ISSUE TITLE
Tool Issues

### ISSUE THREAD

**Issue by LordMorin** [Sklore/HL_DD_5e_Colab#546]
I still have issues with the Rogue not adding Thieves' Tools, but that is an issue for Wolflair since its in the original Rogue code.

However, I have been finding a lot of backgrounds are no longer adding tools. One example of this is the Spy variant of the Criminal background

Disguise kit and Forgery kit aren't being added visibly to the character's list of tool Proficiencies. I say visibly because when go to add them manually, they are not in the list of available tools meaning they have been added, but just aren't showing up.

**Comment by Sklore** [comment]
Ok there was an issue with this but its not the one you described. The spy was setup to give too many gaming proficiencies. I have fixed that now. Not sure where the Forgery Kit should be coming from? 

Per RAW for the Criminal and Spy they get the following:

Skill Proficiencies: Deception, Slealth
Tool Proficiencies: One type of gaming set, thieves' tools
Equipment: A crowbar, a seI of dark common clothes including a hood, and a bell pouch containing 15 gp

I suspect what is happening is the place you are used to seeing the proficiency has changed. LW asked us to modify our code and as such the proficiency is now displayed on the Special tab up the top of the left column. 

Will close this for now as it appears fixed. Please let me know if you don't see the proficiencies on the Special tab as expected.
