### ISSUE TITLE
Multiclassing: Error with Caster Levels for Eldritch Knight & Arcane Trickster, Ranger/Paladin too.

### ISSUE THREAD

**Issue by TakedaMat** [Sklore/HL_DD_5e_Colab#549]
I have a EldKnt 4/Wiz 5 that is presenting as if I have 7-caster levels in error.  It should be on 6 via the amount of spell-slots, prepared, etc.  I checked and it appears that Rangers and Paladins are rounding up too (once they have spell casting).

Rangers & Paladins provide 1 per 2 levels rounded down. 

Eldritch Knight and Arcane Trickster provide 1 per 3 rounded down.

**Comment by LordMorin** [comment]
Eldritch Knight - L4 - 1st - 2 (Your casting level is 2)
Wizard             - L5 - 1st - 4, 2nd - 3, 3rd - 2 (Your casting level is
6)

Your casting levels don't stack so I am not sure where you are getting 6
and/or 7 from . . .

Cantrip Casting Level - 9

**Comment by TakedaMat** [comment]
5e D&D Eldritch Knight 4/Wizard 5:

Your effective level for earned spell slots is only One for the Eldritch Knight when you Multiclass for each 3 (total EKn) levels.  So Wizard 5 +1 (for the 3 of the 4 of the Eldritch Knight) = 6.  Check out Multiclassing in the PHB.  Looks like the calculation is off for all semi-casters.  It's quite a bit different from Pathfinder and 3.0-3.5 D&D.

Character/caster level for Cantrips is total character levels of course.

**Comment by LordMorin** [comment]
I'd take another look at the Eldritch Knight chart. At 4th level you are the equivalent of a 2nd level caster. You have 2 cantrips, 4 prepared spells and 3 spell slots. SO you are the equivalent of 5 + 2 = 7

PHB - p.72 I believe.

**Comment by TakedaMat** [comment]
5e PHB pg 164.  Are you still thinking 3.0?

Nope on the second level caster in the example you just gave, no longer a metric that way. Durations and such, dmg, etc aside from Cantrips don't scale by level, just spell-slot used.

I'm not sure what you're referring to but I think you should re-read Multiclassing in 5e. 

I can post the text of that whole thing here if you like?

**Comment by LordMorin** [comment]
I am looking at the Eldritch Knight and the Arcane trickster charts in the PHB at the moment. Ignore the multi-class chart for the moment.  A 4th level Eldritch Knight (or Arcane Trickster) are the equivalent of a 2nd level cast at 4th level.

**Comment by TakedaMat** [comment]
Sorry but you're wrong. Pg 164.  There is no 'Caster Level' anymore except for Cantrips and that defaults to a Character level regardless of spell-Caster levels.  I'm talking about the Multiclassing dynamic and how many slots you get. I'll write it all out straight from the PHB. Take me a few minutes.

**Comment by LordMorin** [comment]
I've been running 5E since beta testing. I am currently running 2 separate 5e campaigns. I KNOW what I am talking about.

You have 5 levels of Wizard.
As a Level 4 Eldritch Knight you have 2 levels of caster. It's right there in the Elditch Knight class description if you read it.

As for Cantrip, the casting level for them is the sum-total of all your class levels. If you are a level 5 wizard and level 4 warrior (doesn't have to be even a Eldritch Knight) then you casting level for the cantrip is 9. Thus you do 2 dice of damage with the cantrip.

Official rulings from WotC: http://dnd.wizards.com/articles/features/rules-answers-june-2016

**Comment by TakedaMat** [comment]
*Straight from Pg 164 of the PHB:*

*++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++*

*Spell Slots. * You determine your available spell slots by adding together
all your levels in bard, cleric, druid, sorcerer, and wizard classes, half
your levels (rounded down) in the paladin and ranger classes, and a third
of your fighter or rogue levels (rounded down) if you have the Eldritch
Knight or the Arcane Trickster feature.  Use this total to determine your
spell slots by consulting the Multiclass Spellcaster table.

If you have more than one spellcasting class, this table might give you
spell slots of a level that is higher than the spells you know or can
prepare.  You can use those slots, but only to cast your lower-level
spells.  If a lower-level spell that you cast, like burning hands, has an
enhanced effect when cast using a higher-level slot, you can use the
enhanced effect, even though you don't have any spells of that higher level.

For example, if you are the aforementioned Ranger 4/ Wizard 3, you count as
a 5th level character when determining your spell slots: you have four 1st
level slots, three 2nd level slots, and two 3rd level slots.  However, you
don't know any 3rd level spells, nor do you know any 2nd level ranger
spells.  You can use the spell slots of those levels to cast the spells you
do know - and potentially enhance their effects.

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

So ... If you can quote me from WotC and not some house rule that this
above from the PHB is wrong I'm all ears.  Nothing on that link says squat
about multiclassing that changes or effects any aspect of what we're
discussing.

So a Eldritch Knight 4/ Wizard 5 counts as a 6th level character for spell
slots, which on page 165 shows I'd have 4-1st level slots, 3-2nd level
slots and 3-3rd level slots.

If you're still using Caster Levels that must be a house-rule.  Which is
fine, but for the community stuff I'd thought you'd stick to the RAW.

**Comment by TakedaMat** [comment]
Again, if you're reading that Eldritch Knight has two caster levels at 4th
level, that's either Beta, 3.0 or 3.5 or Pathfinder.  There is no such
reference whatsoever in the 5e PHB.

On Sat, Jan 14, 2017 at 5:50 PM, Takeda Mataroshi <takedamataroshi@gmail.com

**Comment by LordMorin** [comment]
If you look at the top of the Multi-classing table the header states:

M u l t i c l a s s S p e l l c a s t e r :
S p e l l S l o t s p e r S p e l l L e v e l

**Comment by TakedaMat** [comment]
LOL!  What point are you trying to make?

**Comment by TakedaMat** [comment]
Show me where it says that a 4th level Eldritch Knight is a 2nd level caster.  Where?

**Comment by TakedaMat** [comment]
Sounds like you have Edition-Blur™ which is understandable ... I've played since D&D was new and persecuted by Jack Chick.  That's why I've read this bit like 10+ times.

**Comment by TheEnthusiast** [comment]
@LordMorin 

I'm not sure if you understood his point. While a normal 7th level EK follows the table on page 76 of the PHB, a multiclassing one follows the table on pg. 166 . Which means you actually loses some spells. Same applies to the wizard. Basically you ignore the original class(es) spell slot progression to use the one described on chap. 6.

@TakedaMat 

Having that said, I do not know if we can fix this issue, because I believe the multiclass code came from LWD's core package. I believe we need to open a request with them.

@Sklore 

Do you know/remember if the multiclass code was added in the community package? I cannot find anything about it.

**Comment by Sklore** [comment]
The multi-classing itself is handled by LW. There are some settings in the classes though that impact multi-classing.

**Comment by TakedaMat** [comment]
Hmm. What if there was an add-on that allowed you to adjust the
contribution of 'spell-casting levels' for the multiclassing spellcaster
table? Like a new 'adjustment' or house-rule that allowed you to adjust the
calculation? Could be good for custom classes.

**Comment by TheEnthusiast** [comment]
@TakedaMat 

Actually, when you create a new class in the editor, there are settings to tell if the class is full caster, half caster or 1/3 caster. The program then uses an internal "thing" (for lack of a better term) called cHelpXXX (cHelpWiz for Wizards) that handles these maths.

It seems the current code merely "stacks" the spells slot progression from each individual class tables, generating the issue.

I'll check the lonewolf forums, maybe they have seen this already.

**Comment by TakedaMat** [comment]
Cool!  I just want this to work right so I can use it.  I'm not
knowledgeable enough with the editor to be less than dangerous. I've tried
stuff before and some worked but it was trial and error.  I abandoned any
attempt to do that several updates ago. Love the product though.  I'm
grateful to all of you for filling in the gaps and transliterating the SRD
and such to Herolab!

**Comment by TheEnthusiast** [comment]
Heh, trial and error is how everyone starts with herolab. Feel free to destroy everything. In the worst case you just have to redownload the game system again. 

Anyway, I've open the case 113626 with LW, let's see how long they take to respond.

**Comment by TakedaMat** [comment]
Sounds good!  Thank you!

Takeda

**Comment by TheEnthusiast** [comment]
I received word from the Support team. It's taken care of and the fix will be present in the next release of the core package.

**Comment by TakedaMat** [comment]
Great! Thank you. 😎😃

Takeda
