### ISSUE TITLE
Gladiator

### ISSUE THREAD

**Issue by OregonPinkRose** [Sklore/HL_DD_5e_Colab#55]
Gladiator: Background
Either it needs a custom entry, or it needs combat chosen already and only two other choices available.

**Comment by Sklore** [comment]
Are you referring to the Entertainer Routines?

**Comment by OregonPinkRose** [comment]
Yes.
In reading the gladiator sub-background, it says that Combat replaces the
Entertainer Routines, though you may still know tumbling or such.

**Comment by Sklore** [comment]
Have added Spectacular Combat in as a defining event. Enabled only for the Gladiator. Correct the weapon choice text.
