### ISSUE TITLE
Downtime tab: "Add" button missing in iPad

### ISSUE THREAD

**Issue by erossing** [Sklore/HL_DD_5e_Colab#550]
In the Downtime Journals section of the Downtime tab on the iPad, the Add button is missing. There's a dialog to enter the # of days, but no way to add that to the journal.

I see the button as expected in the Windows version of Hero Lab.

I'm using a 9-inch iPad Pro with iOS v10.2, Hero Lab v7.6.4, D&D 5th Edition SRD for iPad v1.9 and D&D 5e Community Pack v1.7.

**Comment by Sklore** [comment]
Please log this fault with LW directly using the support options listed in the 5e forums. We don't control this feature.

**Comment by Sklore** [comment]
http://www.wolflair.com/redirect/bugreport.php?project=5e
