### ISSUE TITLE
New content now available... That we already partially support

### ISSUE THREAD

**Issue by Sklore** [Sklore/HL_DD_5e_Colab#554]
@shadowchemosh 

OK this is the day I was waiting for and the reason I have been so reluctant to keep adding new content from 3rd party providers. 

What do you recommend in this situation?  The midland heroes exists in the community pack but is now officially for sale. 

I feel like we should not provide content for free where a company is working with LW to support 5e.

**Comment by shadowchemosh** [comment]
Well we can remove it from the Pack.  This means anyone that had characters built with this stuff will have 100% broken and unusable characters.  They will be forced to purchase the new content from LW and pretty much rebuild there character.  That is sort of the hammer and nail approach.

What I have done in Pathfinder is say I will no longer add "new" features for that book.  I will continue to make sure what we have works.  But will no longer improve it or its scripts.

Sense the official content stuff is most like 100% scripted and functioning I would assume over time that people that want Midland heroes will officially buy it.  Many people want "official" stuff and will feel better buying it.

I never really found a good third option.  The only "sort of" third option is to say we will support Midland heroes for 2 months and after that they are getting removed.

**Comment by Sklore** [comment]
I have emailed LW for their opinion on the matter also. Want to get all the information before any decisions are made.

**Comment by Reangelis** [comment]
First of all, let me say I'm completely ignorant of what you guys do.  But in reading through it, I have an idea that might help.  

You said that amending the community pack by removing the content that is now for sale from the vendor would create broken characters if they've used the options in question to create their characters, and force them to purchase the pack, and build their characters from scratch.   It's literally been decades since I've done any programming, so I have no idea if this will work or not, but what if the people who used the option were to purchase the pack from the vendor first, THEN downloaded the revised community pack, or update, or whatever.  This would overlap the options they were using, and possibly keep them from having to build the character again, from scratch, wouldn't it?

**Comment by Sklore** [comment]
Unfortunately it won't work that way. For all intensive purposes they are two completely separate classes from a programming logic perspective.

**Comment by Sklore** [comment]
LW got back to me with a solution. 

> Hi Josh,
>
> Thanks for getting in touch about this. I think the ideal thing to do 
> for us would be to say that the Midgard Heroes (and fifth edition feats, 
> see below) are no longer supported as part of the community pack, and 
> then "obsolete" them. There's a tag, Helper.Obsolete, that you can 
> assign to races, feats, and backgrounds from those sources - the things 


> will still be present in the data files, so old files using them will 
> still load, but the races and feats won't appear in the selection list 
> any more (I'll add the same checks to backgrounds for the next 5e release).
> 
> If you remove the Midgard Heroes and TPK 5e Feats sources from all the 
> things, and add the attached file to the data files, those entries will 
> be removed from the list, but old saved portfolios shouldn't report 
> errors when loading.
> 
> This way new people won't be able to use that content, but it'll still 
> stick around if it's been used by someone before now.

[5e_community_loadmods.zip](https://github.com/Sklore/HL_DD_5e_Colab/files/733737/5e_community_loadmods.zip)

So looks like this is the approach we are going to take. 

@shadowchemosh - do you have any concerns or knowledge we can feed on here to predict any issues with this approach?

**Comment by Sklore** [comment]
Ok so that took a while but appears to have worked just fine. Have confirmed that I can continue to open a *.por file that contains a character using for the 5eFeats and Midgard Heroes content. 

COM_5ePack_Loadmods.user - this file now exists in the primary pack. Should we need to remove support for future products it looks pretty simple to use.
