### ISSUE TITLE
Add additional attunment functionality

### ISSUE THREAD

**Issue by jeffstokes72** [Sklore/HL_DD_5e_Colab#559]
Please add the ability to create additional attunement slots via boons? Or some mechanic?

**Comment by LordMorin** [comment]
The line of eval code to do this isL

herofield[tAttunMax].value += 1

I;m too fuzzy mined on flu medicines to set up the full code atm. Sorry.

The only time I've done things was on items I gave to players. These were named items keyed to the individual.

Creating an Adjustment to do it would normally be the work of a few minutes . .

**Comment by jeffstokes72** [comment]
Ah I have 0 idea how to implement any of this you mention but I'll give it the school of hard knocks try :)

**Comment by TheEnthusiast** [comment]
@jeffstokes72 

Hi, 

I've added the adjustment you need to our COM_5ePack_PHB - Adjustments.user file. Grab it from the Code section, or wait for the new version.

You will see it in the Personal->Adjustments->Equipment->Extra Attunement in your hero. Add it and set how many extra attunements the character will have.

You are welcome.

**Comment by jeffstokes72** [comment]
@TheEnthusiast OH MY LORD! THIS IS AN EPIC WIN THANKS!

seriously. this is awesome sauce. appreciate it!
