### ISSUE TITLE
Dublicate Spells found

### ISSUE THREAD

**Issue by Jacqual** [Sklore/HL_DD_5e_Colab#56]
I have created a Mage and a Warlock, I have found that the spells Find Familier and Eldritch Blast have duplicate posting. Other spells may also be duplicated as well.

**Comment by Sklore** [comment]
This will now be resolved in the next release. Thanks for pointing this out. 

DUPLICATE SPELLS

* Originally missing from SRD Pack
spDruidcra - Added by HL
sp5CDruidc - COM_5ePack_PHB - HIDDEN

* Originally missing from SRD Pack
spGoodberr - Added by HL
sp5CGoodb - COM_5ePack_PHB - HIDDEN

* Originally missing from SRD Pack
spViciMock - Added by HL
sp5CVicioM - COM_5ePack_PHB - HIDDEN

* Originally missing from SRD Pack
sp5CChrOrb - Added by HL
sp5CChroO - COM_5ePack_PHB - HIDDEN

spFeatFall
sp5CFthFal - ROT (Removed)

* Originally missing from SRD Pack
spFindFami - Added by HL
sp5CFindFa - COM_5ePack_PHB - HIDDEN

spContFlam
sp5CCntFlm - ROT (Removed)

spEnlargeR
sp5CEngRed - ROT (Removed)

* Originally missing from SRD Pack
spLevitate
sp5CLevit - COM_5ePack_PHB - HIDDEN

spMagiMout
sp5CMgcMth - ROT (Removed)

spMirrImag
sp5CMrrImg - ROT (Removed)

* Originally missing from SRD Pack
sp5CPhantF - COM_5ePack_PHB
sp5CPhtFrc - ROT (Removed)

spSeeInvi
sp5CSeInvs - ROT (Removed)

spGaseForm
sp5CGasFrm - ROT (Removed)

spGlypWard
sp5CGlyWrd - ROT (Removed)
sp5CCTSGoW -  Part of the Not Really Complete Tome od Spells (NRCTOS)

spSending
sp5CSndng - ROT (Removed)

spSlow
sp5CSlw - ROT (Removed)

spStinClou
sp5CStkCld - ROT (Removed)

spWateBrea
sp5CWtrBrh - ROT (Removed)

spFireShie
sp5CFirSld - ROT (Removed)

spAnimObje
sp5CAnmObj - ROT (Removed)

spHoldMons
sp5CHldMst  - ROT (Removed)

spMislead
sp5CMisled  - ROT (Removed)

spMagiJar 
sp5CMgcJar - ROT (Removed)

spMoveEart
sp5CMveErh - ROT (Removed)

sp5CCTSAcS
sp5CLSAcSt - Book of lost spells. Added (BOLS) to name to help distinguish. 

spWish
sp5CWsh - ROT (Removed)

* Originally missing from SRD Pack
spEldrBlas - Added by HL
sp5CEldBla  - COM_5ePack_PHB - HIDDEN
