### ISSUE TITLE
Would like chosen class skills to receive proficiency bonuses properly.

### ISSUE THREAD

**Issue by Reangelis** [Sklore/HL_DD_5e_Colab#560]
When choosing the skills your (double) proficiency bonus adds into for your class, my Hero Lab only offers Thieve's Tools as an option...for Rogue and Fighter, and for 4 separate options.  I would assume these are supposed to be different options, that were just overlooked, or coded wrong, or something.  Fighter was my first class, then I added two classes of Rogue, and still only have Thieve's tools as an option.  This throws off Passive Perception, as well as the other three skills I chose, when using the printed version.  I don't know if this has been reported, but I'd be thankful if you could check the issue out, and let me know if it is fixed, or if I'm doing something wrong.  I downloaded the Community Pack, and installed it, and got a ton of extra content, so everything else seems to be doing well...but this is aggravating.  I created a third level Fighter 1/Rogue 2 character, if you need that info to recreate the situation.  In the area where it lists your class benefits, it offers the 4 pulldown boxes...but only has Thieve's Tools as an option.  Sorry for being so repetitive with my info...I'm just trying to give as much detail as possible.  Thank you!

**Comment by Sklore** [comment]
It's working as intended. 

**Expertise:**
At 1st leveI, choose two of your skill proficiencies, or one of your skill proficiencies and your proficiency with thieves' tooIs. Your proficiency bonus is doubled for any ability check you make that uses either of the chosen proficiencies.

So as long as you are proficient in other skills they also become a choice for you to select. No other tools will become available though per the RAW above.
