### ISSUE TITLE
COM_5ePack_Tribality - Classes

### ISSUE THREAD

**Issue by LordMorin** [Sklore/HL_DD_5e_Colab#566]
I was looking to use the Archfey patrons added by the Tribality. I noticed they had some scripting issues that needed to be resolved so I thought I'd fix them and then upload the new version to the site.

I think I've fixed the scripting and other bugs I saw in the Ability text. 

For 'The Silver Prince’s Armaments', the TODO says it always adds Medium armor, shield and martial. As far as I know, its supposed to always do this when you take this patron so I left it along. I did fix it so it added Heavy Armor proficiency if you took Pact of the Blade at 3rd level.

If you find anything I missed just post it here and I'll see what I can do.

[COM_5ePack_Tribality - Classes.zip](https://github.com/Sklore/HL_DD_5e_Colab/files/746022/COM_5ePack_Tribality.-.Classes.zip)

**Comment by Sklore** [comment]
Changes will be added in the next patch.
