### ISSUE TITLE
Entertainer: Gladiator

### ISSUE THREAD

**Issue by OregonPinkRose** [Sklore/HL_DD_5e_Colab#567]
Should get the Disguise Kit as a Proficiency, along with a musical instrument.

Don't see Disguise Kit listed anywhere as a Proficiency Kit.

**Comment by LordMorin** [comment]
We'll be getting around to it. The HL update to 5E messed up a fair number of our items that add tools. We are just waiting for them to finalize changes before we make fixes of our own.

**Comment by OregonPinkRose** [comment]
This doesn't seem to be fixed.
Disguise Kit should still show up for a Gladiator.

**Comment by Sklore** [comment]
It appears to be working on this end. Please check to ensure you are looking in the right space as I believe the visual output of the tool proficiency has changed a few times recently. 

![2017-02-14 13_42_46-hero lab - unnamed hero - no file](https://cloud.githubusercontent.com/assets/8046697/22913574/873d6eea-f2bb-11e6-966e-a29aca9dd6f4.jpg)

**Comment by OregonPinkRose** [comment]
You are right that it is there, under Special.
But it's not under Background. 
Which would be fine, except I choose the Instrument there, and expected to choose Disguise Kit as well.
I can live with this, it just seems odd.

Thank you though for following up for me.

**Comment by Sklore** [comment]
Yeah that appears to be a design decision made by LWD. It's not something we control.
