### ISSUE TITLE
Placeholder Replacement

### ISSUE THREAD

**Issue by LobsterJ** [Sklore/HL_DD_5e_Colab#571]
I enjoy writing in my downtime and would be willing to replace all the placeholder text. I don't know anything about Github so I don't know how to go about doing it. Would you like the help? I would append the question label to this but I do not even know how to do that.

**Comment by Sklore** [comment]
I don't think there are many left now but absolutely happy to have any assistance in filling the rest of the gaps. 

Using the 'Search This Repository' function above i can only see 4 placeholders left.

**Comment by Sklore** [comment]
Looks like the following files have placeholders still:
COM_5ePack_HOTDQ - All.user 
COM_5ePack_SCAG - Classes.user 
COM_5ePack_PHB - Races.user 

You are absolutely welcome to fill those gaps 👍

**Comment by Sklore** [comment]
Placeholders all updated.
