### ISSUE TITLE
Blood Hunter: Missing Data and Issues

### ISSUE THREAD

**Issue by Churchill92** [Sklore/HL_DD_5e_Colab#573]
Created a Blood Hunter using the HomeBrew data sets

When printing off a Character sheet the following issues occur:

1. No Order Printed/Displayed: Picked Order of the Mutant, printed character sheet, no order of the mutant found or other abilities associated with it.

2.  Blood Curses: The print out prints EVERY blood curse not just the ones that were selected. 

3. Crimson Rite Dice: These are not shown correctly either. On print out I see "While active, attacks from this weapon deal an additional 1.d4 rite damage" the "." after the number 1 might be throwing the print out off.

I've uploaded the PC in questions as a .zip I created some custom gear (weapon and armor) that should not impact anything.

**Comment by Sklore** [comment]
No Order Printed/Displayed: Picked Order of the Mutant, printed character sheet, no order of the mutant found or other abilities associated with it. **FIXED**

Blood Curses: The print out prints EVERY blood curse not just the ones that were selected. **Yes the way this was implemented means it prints them all as it's technically one ability.** 

Crimson Rite Dice: These are not shown correctly either. On print out I see "While active, attacks from this weapon deal an additional 1.d4 rite damage" the "." after the number 1 might be throwing the print out off.
**This never calculated any damage. I have improved it by allowing the selection of more rite per the level up requirement and then the special rites at level 14. What I have not done is any of the scripting as I have no idea how to do it. I have included a screenshot of the ability in case someone knows how to both remove HP and deal damage to the player + apply the 1d4 extra damage per the different types.**

![2017-02-12 16_29_20-563826-blood_hunter_class_1 8](https://cloud.githubusercontent.com/assets/8046697/22860021/7903ab90-f140-11e6-8f29-97b1823b5d90.jpg)

**Comment by Churchill92** [comment]
1. GREAT!

2. hmm ok

3. I'm quite ok with the handling on our for the hit point damage and reduced hit points as long as the scaling of damage (1d4,1d6,etc.) works

**Comment by TheEnthusiast** [comment]
![bloodhunter](https://cloud.githubusercontent.com/assets/20332156/22955275/642a0b6a-f302-11e6-8a6b-25de95c56cc5.png)

This error shows up to me, I'm not sure if its related to the 2.1 core package.

It shows as soon as I open the class selection list

**Comment by Churchill92** [comment]
I created a new character with Bloodhunter and did not get that error.

I loaded an old character with Bloodhunter and did not get that error.

**Comment by Sklore** [comment]
I get the same error as soon as I click the Class button.

**Comment by Sklore** [comment]
If you change the tool Choice to be in Tool Table #2 instead of Tool Table #2 it works fine...

I'll raise this to LWD.

**Comment by roninjedi78** [comment]
It simply won't show the tool table for me to select a tool proficiency, and continues to show that it's missing. 

Not sure if its related, but if I select Profane Soul, a tab for adding spells never appears either.

**Comment by Fenris447** [comment]
The Blood Hunter was updated on DMsGuild in January 2020, so the version in the 5e Community Pack is very much out of date. With nobody actively working on it or requesting it, I’m closing the issues related to this homebrew class. If someone wishes to do the work to fully update it, feel free to open a new ticket.
