### ISSUE TITLE
Herolab Community Pack Addition for 5e

### ISSUE THREAD

**Issue by Dehkul** [Sklore/HL_DD_5e_Colab#575]
Hi, 

I saw that you added the Unearthed Arcana content - Modifying Classes - New Sorcerer Bloodline - Favored Soul. From http://dnd.wizards.com/articles/unearthed-arcana/modifying-classes
I was hoping we could see the Rangers with no spells. 

Thanks very much for everything,
We are big fans!

**Comment by Sklore** [comment]
This has already been requested, see the link below. We will get there eventually. 

https://github.com/Sklore/HL_DD_5e_Colab/issues/456
