### ISSUE TITLE
Temporary hit points not available on iPad

### ISSUE THREAD

**Issue by mark-drury** [Sklore/HL_DD_5e_Colab#576]
I can use temp hit points on Hero Lab Mac, and when I save my portfolio they appear on my hero on iPad but there is no way to modify them on the iPad, you can't re-add the points if you get a new source of temp hit points.

Thx

**Comment by Sklore** [comment]
You will need to report this to Lone Wolf. This support is only for the community pack. 

http://forums.wolflair.com/showthread.php?t=54821

**Comment by mark-drury** [comment]
Done, sorry i’m new to this and missed the distinction between the community pack and the main developer. 

Mark
