### ISSUE TITLE
Haunted One background from Curse of Strahd

### ISSUE THREAD

**Issue by TTR-STEVE** [Sklore/HL_DD_5e_Colab#577]
Hi,
Is there no data from Curse of Strahd?
The Haunted One background is on page p209 of Curse of Strahd . It does not seem to be in the Community Pack.

**Comment by LordMorin** [comment]
I started running the Curse of Strahd module but my group for it broke up. I have a .user file with the Haunted One background and several of the monsters from the module. Unforunately it also has some homebrewed material which I added as part of my own campaign. I'll upload my file but someone will have to cut out the stuff not wanted for the Community Pack.

[soe_5e_cos.zip](https://github.com/Sklore/HL_DD_5e_Colab/files/764297/soe_5e_cos.zip)

**Comment by DarkHayZe** [comment]
If you want just the Background and related stuff I have it in my personal files

**Comment by DarkHayZe** [comment]
I just uploaded it, the only thing (I think) that it doesn't have is the source. I could not figure out how to do layered sources.

**Comment by Sklore** [comment]
Ok this is important. The text cannot be the same as the book if it's going in the community pack . It must be 20% different. I havnt seen the upload yet as on phone but if its a direct cut and paste it needs to be changed. Mechanics are fine as they cannot be copyright.

**Comment by DarkHayZe** [comment]
Okay, That is an easy fix.

**Comment by Sklore** [comment]
There's quite a few place holders. Mainly in the Scag stuff I think. Where you see that it's because the rewrite has not been done yet. It's a quick way to get the content out if you need to put it in the tool before you have a chance to rewrite it all.

**Comment by DarkHayZe** [comment]
That makes sense, this wasn't too big. It is done now.

**Comment by DarkHayZe** [comment]
Didn't I close this one like 2 wks ago?

**Comment by Sklore** [comment]
I'll put the source in today unless that was done already?

**Comment by DarkHayZe** [comment]
I could have sworn I took care of it

**Comment by Sklore** [comment]
Easy way to keep track is to put the ticket number into the description of the change you make. Then it will link back to the ticket. 

#577

**Comment by Sklore** [comment]
Ok so you did set the source on the background. What you have missed you would have never done I'd wager. If you checkout the COM_Source_101.1st files they are what control the menu in the character config. Have a look at the structure. They are pretty easy to figure out how they work. When you need to add a new source you just add in the section of source code with the necessary changes. 

<source
   id="p5eCOSCP"
   name="Curse of Strahd"
   selectable="yes"
   parent="p5eCoS"
   sortorder="11"
   description="Curse of Strahd sourcebook. Use is allowed for gaming groups only.">
   </source>

**Comment by DarkHayZe** [comment]
Is there a trick to getting new .1st files to load? I am trying to replicate this for my own stuff but with no luck, I even tried linking it to the Community packs with no luck either.

**Comment by DarkHayZe** [comment]
Never-mind I got it working... figures I would right after asking...haha
