### ISSUE TITLE
Background: Spy

### ISSUE THREAD

**Issue by OregonPinkRose** [Sklore/HL_DD_5e_Colab#58]
Check a clean install first. I don't think I messed it up but I might have.

It appears that Land Vehicles is a chosen Tool Proficiency instead of Thieves' Tools.

It also appears All Starting Equipment is blank. It should be the same as Criminal: 
A crowbar, a set of dark common clothes including a hood, and a belt pouch containing 15 gp

And Criminal Specialty isn't listed as the Custom Ability Name. It's blank.
And Criminal Specialty isn't listed as the Custom Ability Plural. It's blank.

**Comment by Sklore** [comment]
This will be fixed in the next release.
