### ISSUE TITLE
Spell Attack Calc Error

### ISSUE THREAD

**Issue by TakedaMat** [Sklore/HL_DD_5e_Colab#585]
If you start as say a Cleric then Multiclass into a Wizard and pick up Firebolt (as a Wizard) it will still calculate your Spell Attack (at least on the iPad) as though Wis was the applicable stat. 

There is no way to associate it to Int and no way to just adjust by adding a bonus to attack because it's not an option. I've tried in the adjustments but has zero effect.

**Comment by Sklore** [comment]
Thats an issue for LWD to address. Please raise a ticket via the official support path below. 

http://forums.wolflair.com/showthread.php?t=54821

**Comment by TakedaMat** [comment]
okay ... thought this was right ... sigh.  Was directed here last time.

**Comment by Sklore** [comment]
This is just for the Community Pack. It can get rather confusing as to who supports what but basically any of the core SRD functionality needs to be raised directly to LWD.

**Comment by TakedaMat** [comment]
Okay fair enough. So do you get the ones that LWD won't touch?  Like do
they pass them along?

Takeda

**Comment by Sklore** [comment]
They direct people with issues with the Community Pack to us yes.

**Comment by TakedaMat** [comment]
Okay cool.  So one spot to post. :D

Takeda
