### ISSUE TITLE
COM_5ePack_PHB - Feats.user

### ISSUE THREAD

**Issue by LordMorin** [Sklore/HL_DD_5e_Colab#591]
I found an issue that I'm surprise has yet to be reported. :)

When you move at least 10-feet, you can add +5 to the damage roll, not the attack roll.

> When you use your action to Dash, you can use a bonus action to make one melee weapon attack or to shove a creature.
> • If you move at least 10 feet in a straight line immediately before taking this bonus action, you either gain a +5 bonus to the attack’s damage roll (if you chose to make a melee attack and hit) or push the target up to 10 feet away from you (if you chose to shove and you succeed).

The following is the corrected code for the eval script:

      ~ If we're disabled, do nothing & 
      doneif (tagis[Helper.Disable] = 1)
      ~ If not active get out now!
      doneif (field[abilActive].value = 0)
      
      ~ Give a untyped bonus to melee attack damage
      hero.childfound[Damage].field[dmmBonus].value += field[abValue].value

I forgot, you also have to change the Activation Name to: Activate Charge (+5 bonus damage / ignore if pushing)

**Comment by Sklore** [comment]
This will be fixed in the next update.
