### ISSUE TITLE
Bug: Observant feat not modifying passive perception

### ISSUE THREAD

**Issue by BobTheSkull** [Sklore/HL_DD_5e_Colab#597]
At least in iPad app the Observant feat is not increasing passive perception by 5 in view stat block even when check passive perception on observant feat resource.

**Comment by TheEnthusiast** [comment]
Tested on windows, with package 1.8, shows alteration.

Are you using the last community package?

**Comment by BobTheSkull** [comment]
5th edition SRD 2.1.
Community package 1.8.
Verified on Windows client that does alter when passive is selected for Observant.
On iPad when passive is selected for Observant then view stat block it does not show change.

Guess it is an issue with iPad client.
Closing issue and thank you for checking it.
