### ISSUE TITLE
Mousefolk does not have Unarmed strike

### ISSUE THREAD

**Issue by SpaceCadetEve** [Sklore/HL_DD_5e_Colab#599]
This prevents them from being used with Monk properly

**Comment by LordMorin** [comment]
This .user file adds Unarmed Strike to the COM_5ePack_Homebrew - Races.user file. It will probable be added to the next update. You should be able to extract the file and overwrite your current version.

[COM_5ePack_Homebrew - Races.zip](https://github.com/Sklore/HL_DD_5e_Colab/files/818800/COM_5ePack_Homebrew.-.Races.zip)

**Comment by Sklore** [comment]
This will be fixed in the next update.
