### ISSUE TITLE
Monster Hunter not granting bonus proficiencies

### ISSUE THREAD

**Issue by Malvisk** [Sklore/HL_DD_5e_Colab#601]
I created a Shield Dwarf at 5th level and choose Monster Hunter for the martial archetype.  The Bonus Proficiencies is added to the special abilities, but it doesn't prompt with the ability to choose those proficiencies and the tool.

**Comment by Malvisk** [comment]
to compensate for the missing skills, I added an adjustment allowing for two proficiencies and added them.  I then moved on to a different character to make adjustments.  When I came back to the dwarf monster hunter, it stated I still needed to pick 2 proficiencies. So it would appear that the choice of selecting the bonus proficiencies wasn't made available until after I would close and reopen the character.

**Comment by Sklore** [comment]
@shadowchemosh - Going to call on you for this one mate. Any chance you can offer some wisdom. I assume it's a timing issue but I can't modify the timing. Getting the following message:

"Specified thin is actively in use. All references must be deleted before changes can be applied."

I'm fairly certainly you created the configurable. It's in the COM_5ePack - HelperThings.user. 

The class option mentioned above is in COM_5ePack_UA - Gothic.user. 

Bonus Proficiencies
When you choose this archetype at 3rd	level, you	gain	proficiency in two of the following skills of your choice: Arcana, History, Insight, Investigation, Nature, or Perception. You can gain proficiency with a tool of your choice in place of one skill	choice.

**Comment by shadowchemosh** [comment]
@Sklore the message your getting is telling you that you have bootstrappes and maybe even bootstrapped conditions in affect.  This means you can no longer use Test Now!.  You will be reuired to do a CTRL-R to reload HL to do any testing.

In addition don't create a "test" character to save your place when dealing with bootstraps.  It causes all sorts of strange issues.

**Comment by DarkHayZe** [comment]
I can add the 3 proficiencies, just don't remember how to limit it to the aforementioned choices.

**Comment by DarkHayZe** [comment]
@shadowchemosh or @Sklore if you have any suggestions on adding tools to the list of skill choices available... This is how I am doing it...
![image](https://user-images.githubusercontent.com/17392134/44189206-bb982500-a0e7-11e8-9111-a023efce5aa2.png)

![image](https://user-images.githubusercontent.com/17392134/44189212-c652ba00-a0e7-11e8-900f-e5c4fc7030c3.png)

**Comment by DarkHayZe** [comment]
Update 3: I have gotten it to show the list of Skills and Tools (It is back to including Perception, which the character is already proficient in)

BUT... I cannot get it to push the Tool selection over to the character. Or hide tools one is already proficient in.

Updated Custom Expression: 

(component.BaseSkill & (Reference.skArcana | Reference.skHistory | Reference.skInsight | Reference.skInvestig | Reference.skNature | Reference.skPercep) & !Helper.Proficient) | component.Tool 

Select from: All Things

**Comment by DarkHayZe** [comment]
Update 4:

I have ventured on a different path to solving this, and have completed step 1 in doing so. Using embedded if/then/else statements for the skill/tool selection. I still need to figure out how to get tools to populate, but I think I have an idea. Will continue to update as I move forward.

**Comment by DarkHayZe** [comment]
Update 5:

I have it more or less working... I have it so it calls the Proficiencies configurable with only 1 tool selection available... Not quite what I wanted to do, as I wanted to avoid calling a configurable to do the job.

That leaves me however with one issue...
![image](https://user-images.githubusercontent.com/17392134/44332214-2bcce080-a431-11e8-849e-0f5c165cc8c8.png)

As you can see, I need to figure out how to replace all the tools listed with just one option that says "Tools"

**Comment by DarkHayZe** [comment]
Update 6: 
I found a workaround... I created a new "Skill" called "Tools". If anyone knows of a cleaner way to do this, please let me know.

**Comment by DarkHayZe** [comment]
I have uploaded it... though I think I did that part wrong...lol It's been too long, I thought I remembered how, but then it didn't compare the two... oops. Closing this for now.
