### ISSUE TITLE
Request: UA Mystic

### ISSUE THREAD

**Issue by Sklore** [Sklore/HL_DD_5e_Colab#603]
Might as well just put this here before everyone comes and requests it. 

http://media.wizards.com/2017/dnd/downloads/UAMystic3.pdf

**Comment by LordMorin** [comment]
Finally, even if it means having to do a major upgrade due to all the basic changes, I can update my version of the Mystic. :)

**Comment by Sklore** [comment]
Most feedback I have seen on this one is that its completely broken.

**Comment by DarkHayZe** [comment]
Broken or not, it is still being used

**Comment by furby076** [comment]
I am working on this. Please note, I need help, especially with the disciplines being primary
https://github.com/Sklore/HL_DD_5e_Colab/issues/646

**Comment by Sklore** [comment]
Closing this for tracking under new ticket.
