### ISSUE TITLE
Firbolg racial ability "Hidden Step" not being tracked.

### ISSUE THREAD

**Issue by MindReaper1** [Sklore/HL_DD_5e_Colab#605]
The Firbolg racial ability "Hidden Step" is usable as a bonus action once per short/long rest.  This is not showing up in either the Tracked Resources & Abilities section of the In Play tab, or the Racial Spells & Spell-Like Abilities section of the Spells tab.

**Comment by Sklore** [comment]
This will be fixed in the next update. Ability will show under the Specials column, tab and In-Play tab.
