### ISSUE TITLE
Gunslinger Issues

### ISSUE THREAD

**Issue by DarkHayZe** [Sklore/HL_DD_5e_Colab#607]
#1 The Bad News gun is listed at 2d25... Unless there is a internal reason for this, it should be 2d12. Also upon a further review the weight is off as well. The pack lists it at 10 and the source lists it at 25. 

I have fixed this in my copy, but that doesn't do everyone else any good.

![gunslinger](https://cloud.githubusercontent.com/assets/17392134/24143536/055442c0-0df8-11e7-9357-0922256f520b.PNG)

#2 Gunslinger is supposed to gain Tinker's tools proficiency at level 3 upon choosing the archetype. Once again I have fixed my copy but the main community file needs to be fixed/updated.

#3 Gunslinger is adding proficiency bonus to initiative at level 3 instead of level 7.

**Comment by Sklore** [comment]
#1, #2, #3 - Fixed in next release

https://github.com/Sklore/HL_DD_5e_Colab/wiki/Bootstrapping-Methods
