### ISSUE TITLE
More Gods from SCAG

### ISSUE THREAD

**Issue by grandchefpanda** [Sklore/HL_DD_5e_Colab#61]
> <?xml version="1.0" encoding="UTF-8"?>
> <document signature="Hero Lab Data">
>   <thing id="deiCMEeli" name="Eelistraee" compset="Deity" uniqueness="unique">
>     <fieldval field="deiPortfol" value="Goddess of song and moonlight"/>
>     <fieldval field="deiSymbol" value="Sword-wielding dancing drow female silhouetted against the full moon"/>
>     <usesource source="5ePHBCP" parent="p5ePack" name="5e Players Handbook"/>
>     <tag group="AlignTemp" tag="ChaotGood" name="Chaotic Good" abbrev="CG"/>
>     <tag group="SuggDomain" tag="cClrLife" name="Life" abbrev="Life"/>
>     <tag group="explicit" tag="11"/>
>     <tag group="DeityCat" tag="Drow"/>
>     <tag group="SuggDomain" tag="cClrNature"/>
>     </thing>
>   <thing id="deiCMDrPtn" name="{bmp npcclass} The Drow Pantheon {bmp npcclass}" compset="Deity" uniqueness="unique" isshowonly="yes">
>     <usesource source="5ePHBCP" parent="p5ePack" name="5e Players Handbook"/>
>     <tag group="explicit" tag="11"/>
>     <tag group="DeityCat" tag="Drow" name="The Drow" abbrev="Drow"/>
>     </thing>
>   <thing id="deiCMKia" name="Kiaransalee" compset="Deity" uniqueness="unique">
>     <fieldval field="deiPortfol" value="Goddess of necromancy"/>
>     <fieldval field="deiSymbol" value="Female drow hand wearing many silver rings"/>
>     <usesource source="5ePHBCP" parent="p5ePack" name="5e Players Handbook"/>
>     <tag group="AlignTemp" tag="ChaotEvil"/>
>     <tag group="explicit" tag="11"/>
>     <tag group="DeityCat" tag="Drow"/>
>     </thing>
>   <thing id="deiCMLolth" name="Lolth" compset="Deity" uniqueness="unique">
>     <fieldval field="deiPortfol" value="Goddess of spiders"/>
>     <fieldval field="deiSymbol" value="Spider"/>
>     <usesource source="5ePHBCP" parent="p5ePack" name="5e Players Handbook"/>
>     <tag group="AlignTemp" tag="ChaotEvil"/>
>     <tag group="explicit" tag="11"/>
>     <tag group="DeityCat" tag="Drow"/>
>     <tag group="SuggDomain" tag="cClrTricke"/>
>     </thing>
>   <thing id="deiCMSelv" name="Selvetarm" compset="Deity" uniqueness="unique">
>     <fieldval field="deiPortfol" value="God of warriors"/>
>     <fieldval field="deiSymbol" value="Spider over crossed sword-and-mace"/>
>     <usesource source="5ePHBCP" parent="p5ePack" name="5e Players Handbook"/>
>     <tag group="AlignTemp" tag="ChaotEvil"/>
>     <tag group="explicit" tag="11"/>
>     <tag group="DeityCat" tag="Drow"/>
>     <tag group="SuggDomain" tag="cClrWar"/>
>     </thing>
>   <thing id="deiCMVhae" name="Vhaeraun" compset="Deity" uniqueness="unique">
>     <fieldval field="deiPortfol" value="God of thieves"/>
>     <fieldval field="deiSymbol" value="Black mask with blue glass lenses inset over eyes"/>
>     <usesource source="5ePHBCP" parent="p5ePack" name="5e Players Handbook"/>
>     <tag group="AlignTemp" tag="ChaotEvil"/>
>     <tag group="explicit" tag="11"/>
>     <tag group="DeityCat" tag="Drow"/>
>     <tag group="SuggDomain" tag="cClrTricke"/>
>     </thing>
>   </document>

**Comment by grandchefpanda** [comment]
I can't attach a user file, nor can I zip it and drop it. It says it don't support the format. Copy paste the tags don't show the tag except when I edit the message. How can I transfer file to you ?

**Comment by grandchefpanda** [comment]
as a txt it works
[COM_5ePack_PHB - Deities - More.txt](https://github.com/Sklore/HL_DD_5e_Colab/files/143161/COM_5ePack_PHB.-.Deities.-.More.txt)

**Comment by Sklore** [comment]
This will be added in the next release.
