### ISSUE TITLE
COM_5ePack_UA - WarWiz issue

### ISSUE THREAD

**Issue by LordMorin** [Sklore/HL_DD_5e_Colab#611]
I know this is not out in the official 5E Community Pack yet, but I downloaded it and have been playing with it.

The issue I found is with the Wizard's Lore Mastery archetype.

It's 2nd level ability Lore Master is supposed to grant the wizard expertise in the skills Arcana, History, Nature, and/or Religion if he is proficient in the skill. Unfortunately the scripting was set for tools, not skills. I fixed the issue in the attached file.

I don't know if the rest of the file is up to date with the latest version on the site. I actually had to go back and fix several of my feats and abilities that granted expertise since they also were no longer working. I used the Bardic Expertise ability as a basis for getting Experise working again.

[COM_5ePack_UA - WarWiz.zip](https://github.com/Sklore/HL_DD_5e_Colab/files/883733/COM_5ePack_UA.-.WarWiz.zip)

**Comment by Sklore** [comment]
Updated with provided file. Will be released in next patch.
