### ISSUE TITLE
Blood Hunter subclasses

### ISSUE THREAD

**Issue by wheelercub** [Sklore/HL_DD_5e_Colab#614]
New to GitHub redirected from the HL 5e Community Pack forums. One of my group decided to roll up a Bloodhunter, Order of the Profane Soul, and unfortunately none of the spells or abilities have been added to Hero Lab yet. Does anyone know how to add the Warlock-like spell progression for this Bloodhunter Subclass? Also, I checked out the other Subclasses as an alternative and it appears all of them need a little work adding class abilities.

**Comment by wheelercub** [comment]
Here's a copy of the main Blood Hunter subclass information: https://drive.google.com/open?id=0BwZoXORhZHGwSDJycEZZeGhmb1k

Here's the Order of the Lycan subclass info: https://drive.google.com/open?id=0BwZoXORhZHGwaXE2OEtNNTN0MHc

**Comment by Fenris447** [comment]
The Blood Hunter was updated on DMsGuild in January 2020, so the version in the 5e Community Pack is very much out of date. With nobody actively working on it or requesting it, I’m closing the issues related to this homebrew class. If someone wishes to do the work to fully update it, feel free to open a new ticket.
