### ISSUE TITLE
LMoP Spider Staff not +2

### ISSUE THREAD

**Issue by Conandy1970** [Sklore/HL_DD_5e_Colab#616]
The Spider Staff magic item from Lost Mine of Phandelver is coming in as  +2 weapon, and it should not be.

**Comment by LordMorin** [comment]
The attached file fixes the issue. Since I created the original version for a forum member only fair I fix it. :)

[COM_5ePack_LMOP - Equipment.zip](https://github.com/Sklore/HL_DD_5e_Colab/files/904676/COM_5ePack_LMOP.-.Equipment.zip)

**Comment by Sklore** [comment]
Are you able to upload changes yourself?

https://github.com/Sklore/HL_DD_5e_Colab/wiki/How-to-upload-your-changes-to-GitHub

**Comment by LordMorin** [comment]
Last time I tried to work with the GIT site, I messed things up royally. :(

**Comment by Sklore** [comment]
This will be fixed in the next release.
