### ISSUE TITLE
Ranger (Spellless)

### ISSUE THREAD

**Issue by DarkHayZe** [Sklore/HL_DD_5e_Colab#621]
I am not sure I did it right, but I think I just pushed my update for the "Official" Ranger (Spellless)
Just in case though I am including it 

I fixed the Combat Superiority Dice so that

They now do the following

1) They increase in quantity at the appropriate levels
2) Shows die type in "In-play" tab

[COM_5ePack_UA - Ranger_nospells.zip](https://github.com/Sklore/HL_DD_5e_Colab/files/907480/COM_5ePack_UA.-.Ranger_nospells.zip)

**Comment by Sklore** [comment]
The push did not work. Try this:

https://github.com/Sklore/HL_DD_5e_Colab/wiki/How-to-upload-your-changes-to-GitHub

**Comment by DarkHayZe** [comment]
I think I got it this time, that was way different. I totally misunderstood one of the first steps the first time.
