### ISSUE TITLE
Warlock Homebrew

### ISSUE THREAD

**Issue by PlatinumKobold** [Sklore/HL_DD_5e_Colab#625]
I got in touch with the person who runs the Warlock Homebrew blog and they gave me permission to hand type any of their content and send it to you for programming. I'm going to start with the Paladin archetypes I had mentioned before but if there is anything else from that blog you would like me to transcribe for you to add to the community pack please let me know.

On a side note, do you plan on eventually adding all of the Unearthed Arcana content eventually? Just wondering because my party's Wizard really wants to take School of Battle when he hits level 3 in a few months.

**Comment by DarkHayZe** [comment]
Do you mean the new UA: Wizard Revisited?

**Comment by PlatinumKobold** [comment]
http://media.wizards.com/2017/dnd/downloads/MJ320UAWizardVF2017.pdf
Specifically the War Magic school.

**Comment by Sklore** [comment]
Eventually, people do it as they have time. Alot of us who enter content dont actually use any of the content we enter. So other things generally take priority. That's my experience anyway ;)

**Comment by Sklore** [comment]
Going to close this for neatness sake. Please open a new ticket once you have transcribed the pdf. And thanks :)
