### ISSUE TITLE
Burglar Feat

### ISSUE THREAD

**Issue by dagda21** [Sklore/HL_DD_5e_Colab#629]
It seems that when chosen, this feat does not double your proficiency score when using Thieves Tools.

**Comment by DarkHayZe** [comment]
I believe I have it fixed. Will push it shortly so it will be available with the next update.

**Comment by LordMorin** [comment]
You'll probably want to fix all the tool feats that came alogn with burglar. They all have the same issue with the Expertise parts of their scripts.

I was going to upload a zipped ,user file with all those feats fixed.

**Comment by DarkHayZe** [comment]
How many feats are there that do this?

**Comment by DarkHayZe** [comment]
I have found two references, once in UA - Classes once in UA - Feats

**Comment by LordMorin** [comment]
These are the UA feats that have this scripting issue: Alchemist, Burglar, Gourmand, & Master of Disguise.

I created others based on this UA article for other tools my group uses

**Comment by DarkHayZe** [comment]
Hmmm... They didn't show up on my search, but I have them fixed and will reupload shortly

**Comment by LordMorin** [comment]
It's an easy fix once you figured out what was wrong. I just look at the Rogue's Expertise ability myself. :)

**Comment by DarkHayZe** [comment]
I also updated the reference in the wiki
