### ISSUE TITLE
Death Cleric - Reaper

### ISSUE THREAD

**Issue by Cerxi** [Sklore/HL_DD_5e_Colab#637]
As it is, the level 1 feature of the Death domain cleric, "Reaper", forces you to take Chill Touch. This is invalid; both Spare the Dying (PHB) and Toll the Dead (from the new UAStarterSpells) are Necromancy cantrips and should be valid choices.

**Comment by Cerxi** [comment]
Right, but you're missing the fact that it gives you a bonus cantrip known. Maybe I want to spend that on Spare the Dying or Toll the Dead so my non-bonus cantrip slots are open for other things. It's a perfectly valid option and one that should be supported.

**Comment by Sklore** [comment]
It's tripping at the usrCandid1 field value. 

**Current:** component.BaseSpell & sLevel.0 & sSchool.Necromancy

If you enter just **sSchool.Necromancy** you get a much larger list of spells but it still does not list Spare the Dying or Toll the Dead.

**Comment by Sklore** [comment]
Ok so it's ONLY showing spells that are assigned to classes other than the Cleric.

**Comment by DarkHayZe** [comment]
I have no problem selecting spare the dying, and as far as Toll the Dead, has UAStarterSpells been released as a Com Pack yet?

**Comment by DarkHayZe** [comment]
Never mind, I found starter spells, though it is not populating  Toll the Dead for me.

**Comment by DarkHayZe** [comment]
I'm not sure how exactly I fixed it, but I got it working

**Comment by DarkHayZe** [comment]
Ah, cause I hadn't added it to my spell list yet.

**Comment by DarkHayZe** [comment]
However, it is not listed as a bonus cantrip, and is taking up a spell slot

**Comment by DarkHayZe** [comment]
I think I almost have it, I just need to know what field to refer to for "Max Cantrips Known Count" for level 0

**Comment by Sklore** [comment]
Hmm isn't there a feat that gives cantrips.

**Comment by DarkHayZe** [comment]
They do it by adding a tab ie Magic Inititiate

**Comment by Sklore** [comment]
hero.childfound[cfg5CMagIn].field[cfgMaxSp1].value += field[abValue5].value

**Comment by DarkHayZe** [comment]
Yeah that is what I was looking at

cfg5CMagin refers to a Configuration I believe cfgMaxSp1 refers to a field in that cfg. abValue5 is easy enough its just a field.

**Comment by Sklore** [comment]
Is this it? sLevel.0

**Comment by DarkHayZe** [comment]
That did it

**Comment by Sklore** [comment]
file:///C:/ProgramData/Hero%20Lab/data/5e%20-%20Test%20Lab/authoring/5thededittut6.htm

**Comment by DarkHayZe** [comment]
So it appears...lol
