### ISSUE TITLE
i can't get skill proficiencies to work

### ISSUE THREAD

**Issue by tomlan71** [Sklore/HL_DD_5e_Colab#639]
is this an issue with the files or am I missing a setting?

**Comment by DarkHayZe** [comment]
Can you be more specific?

**Comment by tomlan71** [comment]
the skills section doesn't allow me to add proficiency gained from class or backgrounds

**Comment by tomlan71** [comment]
I have the latest file downloaded

**Comment by DarkHayZe** [comment]
What class/background are you choosing?

**Comment by tomlan71** [comment]
the last one was a rogue/ sailor

**Comment by tomlan71** [comment]
it says to choose proficiencies from a list but I cant get any to work

**Comment by DarkHayZe** [comment]
Hmm... I have not had this problem, did you have this problem before installing the Community Pack?

**Comment by tomlan71** [comment]
no, but none of the backgrounds save acolyte were available

**Comment by DarkHayZe** [comment]
I want to preface this by saying that I presume you know what you are doing, but I am going to go over the basics anyways.

Well it should automatically add the background skills as they are not choices beyond the background itself. The skills are added on the class tab. 

Could you screenshot your HL screen where they aren't showing up? I just tried to reproduce the issue on my end and it loaded normally. Also which packs are you selecting when you create a new character?

**Comment by tomlan71** [comment]
im embarrased to say, I cant remember how to screenshot. yea, the background is correct. However the Rogue gives me a choice of 4, no no way to select them that I can see

**Comment by tomlan71** [comment]
but the background bonuses arent calculating into my skill bonuses

**Comment by DarkHayZe** [comment]
If you are on windows 10 or 8, there is an app called 'Snipping Tool'. Other wise Ctrl Print Screen will do it, then you just have to paste it into paint or something similar.

**Comment by LordMorin** [comment]
Have you gone to the Character tab > Configure Hero > Ability options? If
you do, make sure Background proficiency & Personality trait Proficiency
are unchecked.


<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by tomlan71** [comment]
yes! that did it

**Comment by tomlan71** [comment]
it was a setting issue after all

**Comment by tomlan71** [comment]
thanks for your assistance

**Comment by LordMorin** [comment]
I got caught with the issue a while back, and many others have since. :)

**Comment by tomlan71** [comment]
I appreciate the help
