### ISSUE TITLE
One fix and a couple of requests

### ISSUE THREAD

**Issue by brandonsiville83** [Sklore/HL_DD_5e_Colab#642]
The entry for "Bad News" in the weapons category for the gunslinger build by Matthew Mercer should read 2d12, not 2d25.  I would like to see the Dawn War deities listed in the Dungeon Master's Guide added as well as the new warlock pacts that were added recently and the finished Mystic class from Unearthed Arcana over the past month and a half.

**Comment by LordMorin** [comment]
The warlock pacts are already done and will, most likely be in the next update.

**Comment by brandonsiville83** [comment]
Awesome!

**Comment by DarkHayZe** [comment]
Bad News should already be fixed as well

**Comment by LordMorin** [comment]
There's a way to download the current version of the 5e Community Pack, but I can never remember how. :(

**Comment by DarkHayZe** [comment]
The "Clone or Download" button on the code tab will do that...

The Mystic class isn't an easy one, at least not from my perspective. I have been working on it as I find time but it is no where near done.

**Comment by DarkHayZe** [comment]
Mainly I have been working on a much needed revision to Goliaths and DMing

**Comment by LordMorin** [comment]
I made my own version of the Mystic. I don't like the way they did the Community version. They did the talents as spells. My version allows you to apply the talents directly to the character where possible.
I have yet to update it to v3 though.

**Comment by dungeonguru** [comment]
Closing issue, since it appears that all outstanding parts of the request are addressed with the next release.
