### ISSUE TITLE
Bard Skill Proficiencies

### ISSUE THREAD

**Issue by Kyuhunter** [Sklore/HL_DD_5e_Colab#648]
I hope this is the right place to post this.
When I leveled up my bard to bard level 3 I chose the Lore College, which allows me to take another 3 skill proficiencies. But when I click "Add more skill proficiencies" it says: "Nothing to choose from". 
My guess is that Jack of all Trades counts as proficiencies and it does not allow another proficiency. But thats just a guess. Any ideas?

**Comment by DarkHayZe** [comment]
I can't replicate this, are your files up to date?

**Comment by LordMorin** [comment]
On the off chance this might be your issue go to your Character tab >- Configure Hero and make sure that the 'Background Proficiency' & 'Personality Trait Proficiency' checkboxes are Unchecked.

**Comment by Kyuhunter** [comment]
Thanks LordMorin! This fixed it for me!
