### ISSUE TITLE
Custom Ability Array Creation Methods failing

### ISSUE THREAD

**Issue by dungeonguru** [Sklore/HL_DD_5e_Colab#649]
When you create a custom ability score array with scores above 15 or below 9, the fields are using the core rules enforcement rules, which disallow scores outside of that range.

Entering the bug here, if it's a Hero Lab side bug, will be glad to enter it there too. 

Sample code snippet:

<thing id="crea5ELV2" name="Fixed V2" compset="Creation">
<fieldval field="creaName" value="Fixed V2 (18/14/13/12/10/6)"/>
<arrayval field="creaAttArr" index="0" value="18"/>
<arrayval field="creaAttArr" index="1" value="14"/>
<arrayval field="creaAttArr" index="2" value="13"/>
<arrayval field="creaAttArr" index="3" value="12"/>
<arrayval field="creaAttArr" index="4" value="10"/>
<arrayval field="creaAttArr" index="5" value="6"/>
<tag group="explicit" tag="20" name="20" abbrev="???"/>
</thing>

**Comment by Sklore** [comment]
This would be something on the Hero Lab side not the community pack I'd wager. We don't control the core functionality.
