### ISSUE TITLE
Request: Unearthed Arcana - Revised Subclasses

### ISSUE THREAD

**Issue by HippyCraig** [Sklore/HL_DD_5e_Colab#651]
I was trying to add college of swords to my bard and I added the UA Bards but that didnt work.  After some investigation its only in the UA Kits of Old.  

Any idea why?  Should it be moved and there is a new version that was published last week with some revisions?  Should that be added or modify the existing?

**Comment by Sklore** [comment]
The Revised Sub Classes have not been added. We would need to add them all in as new or replacements.

**Comment by Sklore** [comment]
https://media.wizards.com/2017/dnd/downloads/UA-RevisedSubclasses.pdf

**Comment by HippyCraig** [comment]
I am wondering if its worth waiting as the "xanathar guide to everything" might have the final version  of this in it.  Instead of trying to update or recreate maybe wait for the new Guide?  Thoughts?

**Comment by Sklore** [comment]
I persoanlly don't use any of the UA. More than happy to wait for Xanthers.

**Comment by dungeonguru** [comment]
The College of Swords is in Xanathar's and a request is opened. Will we be discontinuing support of UA articles when an official option makes it to print? Will be using the Hide to allow folks to move over as we've done in the past?

**Comment by dungeonguru** [comment]
Beginning work on Xanathar's - the UA subclass will get marked obsolete.
