### ISSUE TITLE
Weapon: Legendary Weapon Wave not Proficient?

### ISSUE THREAD

**Issue by Churchill92** [Sklore/HL_DD_5e_Colab#653]
While attempting to create a Cleric of the Sea God the legendary weapon Wave.

Cleric is able to use Tridents: Check (Equipped Trident of Fish Command as test)
Cleric Worships a god of the Sea: Check  (Njord norse god of the ocean)
Attuned: Check

When looking at the Character I see the big 0 next to the name with "You are not proficient with that weapon"

Also I see no Damage dice (should be 1d6) when adding this weapon to the character sheet.

Any idea on why there is no listed damage and not proficient?

**Comment by Churchill92** [comment]
Anyone? Is this a Lone Wolf fix?

**Comment by DarkHayZe** [comment]
If you upload your file I will take a look at it

**Comment by Churchill92** [comment]
[Garius High Omen of the Sapphire Spite.zip](https://github.com/Sklore/HL_DD_5e_Colab/files/1046476/Garius.High.Omen.of.the.Sapphire.Spite.zip)

**Comment by DarkHayZe** [comment]
I need the .user file you are creating the weapon in

**Comment by Churchill92** [comment]
I'm not creating a new .user file. I'm using the ones that I download through the SRD packs on here and through HL. 

These aren't custom files or weapons, these are the legendary weapons that are listed in the DMG from White Plume Mountain,etc.

**Comment by DarkHayZe** [comment]
Okay, give me a minute

**Comment by DarkHayZe** [comment]
I was able to fix it, I will upload the corrected file shortly. After that you can either download the Compack Manually or wait for the next update push.

**Comment by DarkHayZe** [comment]
Done
