### ISSUE TITLE
Unearthed arcana: hexblade

### ISSUE THREAD

**Issue by truwizard19** [Sklore/HL_DD_5e_Colab#654]
Hello! Really enjoying the community generated content! I was wondering if there was any plan to add the hexblade warlock? Thank you!

**Comment by LordMorin** [comment]
Hexblade is in and will be in the next release of the community pack. You
can also download it in advance from the GIT site.

**Comment by truwizard19** [comment]
Thank you!

**Comment by truwizard19** [comment]
Is there a tutorial on how

**Comment by truwizard19** [comment]
To use this content on hero lab iPad?

**Comment by LordMorin** [comment]
I copy/pasted this from an earlier issue posting.

The "Clone or Download" button on the code tab will do that...

If you click on the code tab, you'll see a list of all the files in the Community Pack. Click on Download on the right, save as a .zip to you desktop. (or someplace you can find it. Then extract the zip into you 5E folder overwriting everything.

Don't do just the file you want, there's updates in other files to what you want.

**Comment by dungeonguru** [comment]
Closing this issue since it looks like the work has been done by LordMorin for next release.
