### ISSUE TITLE
Warforged Composite Plating

### ISSUE THREAD

**Issue by Xahaar** [Sklore/HL_DD_5e_Colab#661]
The Composite Plating feature of the Warforged race (included in the Unearthed Arcana: Eberron module) applies a +1 armor bonus.  The bonus seems to be overridden by armor instead of as stacking bonus.

**Comment by DarkHayZe** [comment]
I am looking into this, but my guess is that it is a natural AC and thus would not stack with worn armor.

**Comment by Xahaar** [comment]
Thanks DarkHayZe.  For what it's worth, natural armor seems distinct from armor bonus:

Natural armor is a static calculation, much like a worn armor (12 + Dex Mod) and doesn't stack, much the same way that you don't benefit from wearing chain mail over padded armor.

Some bonuses like the monk's Unarmored Defense explicitly preclude the wearing or armor or shield, saying "while you are wearing no armor and not wielding a shield, your AC equals 10 + your Dexterity modifier + your Wisdom modifier."  [This article ](http://dnd.wizards.com/articles/features/rules-answers-january-2016) covers the specifics and overlap of the varying class abilities affecting armor as well and their interaction with natural armor.

However... there are still instances where flat stacking bonuses to armor apply:
Defense Fighting Style - "While you are wearing armor, you gain a +1 bonus to AC."
Ring of Protection - "You gain a +1 bonus to AC and saving throws while wearing this ring."
Bracers of Defense - "While wearing these bracers, you gain a +2 bonus to AC if you are wearing no armor and using no shield."
And, in my opinion, some racial abilities such as:
Beasthide Shifter - "While shifting, you gain a +1 bonus to AC."
Warforged Composite Plating - "Your construction incorporated wood and metal, granting you a +1 bonus to Armor Class."

By this interpretation, both the beasthide and warforged racials would stack with monk/barbarian unarmored defense rules for the same reasons that a Ring of Protection or even Bracers of Defense stack.

Anyhow, that's my $.02. 
Thanks for reading!

**Comment by DarkHayZe** [comment]
You are correct, and if it is not stacking properly with non armor AC bonuses that it should be, that is a hero lab bug. The warforged armor is in place as natural AC. I am waiting to hear back from official people at WoTC on whether or not it is considered Natural Armor.

**Comment by DarkHayZe** [comment]
Based on the feedback I have received I am updating it to a bonus to AC rather than natural armor. The only problem I have is it is not showing up as a listed bonus. So the calculation shows 10 + (armor of 2) = 13, it does work with both armor and unarmored defense though.

**Comment by DarkHayZe** [comment]
Updated, you can manually update your file(s) or wait till the next update push
