### ISSUE TITLE
Vampire (Zendikar) Missing Common Language

### ISSUE THREAD

**Issue by giengus** [Sklore/HL_DD_5e_Colab#665]
The COM_5ePack_MTG_Races .user file has the new Zendikar Vampire in it, but the race is missing the Common language.

As per Plane Shift Zendikar.pdf (pg 15):
 "Languages. You can speak, read, and write Common and Vampire."

**Comment by DarkHayZe** [comment]
Uploading fix now

**Comment by DarkHayZe** [comment]
Fixed, you may manually update, or wait until the next update push
