### ISSUE TITLE
Tempest Cleric - Wrath of the Storm

### ISSUE THREAD

**Issue by Grymm428** [Sklore/HL_DD_5e_Colab#672]
The package for D&D 5e has too many uses of the Wrath of the Storm Ability.

**Comment by DarkHayZe** [comment]
Uploading fixed file shortly

**Comment by DarkHayZe** [comment]
Done, you can either manually update to the new version, or wait until the next update push.

**Comment by DarkHayZe** [comment]
Update:
Well spotted indeed! It's been taken care of, and you can look for this in our next update.
--
Hollis McCray
Lone Wolf Development Support - support@wolflair.com
http://www.wolflair.com

**Comment by Grymm428** [comment]
How do I manually update?

**Comment by LordMorin** [comment]
I copy/pasted this from an earlier issue posting.

The "Clone or Download" button on the code tab will do that...

If you click on the code tab, you'll see a list of all the files in the Community Pack. Click on Download on the right, save as a .zip to you desktop. (or someplace you can find it. Then extract the zip into you 5E folder overwriting everything.

Don't do just the file you want, there's updates in other files to what you want.
