### ISSUE TITLE
starter spells

### ISSUE THREAD

**Issue by TheEnthusiast** [Sklore/HL_DD_5e_Colab#674]
Hello,

The starer spells file shows up under user content instead of together with the other UAs.

Also,the cantrip hand of radiance shows up as a first level spell, instead of a cantrip.

**Comment by DarkHayZe** [comment]
I don't have that first issue
![image](https://user-images.githubusercontent.com/17392134/26858718-909a916c-4af8-11e7-8cc1-6980aeb497d8.png)

Fixed the 2nd issue

**Comment by DarkHayZe** [comment]
File is updated

**Comment by DarkHayZe** [comment]
Maybe your .1st files aren't up to date

**Comment by TheEnthusiast** [comment]
could be. If the cantrip is fixed, you can close this issue.
