### ISSUE TITLE
COM_5ePack_UA - WarWiz.user missing update

### ISSUE THREAD

**Issue by TheEnthusiast** [Sklore/HL_DD_5e_Colab#676]
Hello, 

Somehow, the file with the new warlock invocations has reverted pull 592, which implemented 5 invocations I forgot to add on the first file version. Can someone readd these missing invocations.

I'm currently without my computer to do it.

thanks.

**Comment by DarkHayZe** [comment]
Whomever does this, download the updated one from Github, I updated it last night for the new updates from the Warlock from the June 5th UA.

**Comment by LordMorin** [comment]
I know I did a bug fix on the warlock invocations. I corrected scripting errors. I zipped the .user file and uploaded (it was working at that time for me).

I don't know if it was my file that reverted though.

It should still be in the archived bug fixes.

**Comment by Sklore** [comment]
https://github.com/Sklore/HL_DD_5e_Colab/commit/aff7b29ffd01f8571808e7f9059a4d7d0f196ba6

**Comment by LordMorin** [comment]
Could someone who has COM_5ePack_UA - WarWiz.user installed create a Lore Master wizard and tell me if the Lore Mastery Class ability is actually working. I just discovered that mine is not granting Double Proficiency t0 Arcana, History, Nature and Religion.

I just need to know if its just me of if others have the same problem now.

**Comment by mumblewump** [comment]
I'm getting the double proficiency bonus from Lore Mastery added to skills where I shouldn't be getting it. Specifically, my character is proficient in Arcana and History, but not Religion or Nature; all the same, HL is showing +8 for all four skills (INT + double proficiency), instead of just the first two.

**Comment by dungeonguru** [comment]
I see two issues:

1. The skill script should read: 
       if (hero.child[skArcana].tagis[Helper.Proficient] <> 0) then
         perform hero.child[skArcana].assign[Helper.ProfDouble]
       endif
    component.BaseSkill <> 0 will always be true since the skills are in the baseskill array (always).

2. Timing. You need to run the skill script post-levels after 15000 and before 20000. The Helper.Proficient tag doesn't get pushed on skills till the calc skProfBon runs at 15000. Just change the timing to 15500 and it works fine with the code change I suggest above.

**Comment by dungeonguru** [comment]
Fixed Lore Mastery, it will now only add double proficiency to the skills you are proficient in and not all skills with next release.
