### ISSUE TITLE
VGtM: Tabaxi

### ISSUE THREAD

**Issue by LordMorin** [Sklore/HL_DD_5e_Colab#678]
I was playing with the Tabaxi from Volo's Guide to Monsters.

The Tabaxi ability 'Cat's Claws' is an Unarmed attack that uses Slashing damage.

The following tag needs to be added to the Claw attack: IsWeapon.wUnarmed

Otherwise abilities like the Monk's Unarmed attack don't apply to the Tabazo Claws as it should.

**Comment by dungeonguru** [comment]
Had to do some research and found where Sage Advice/Jeremy Crawford states that the Tabaxi unarmed attack is monk friendly indeed. Fix added to next release.
