### ISSUE TITLE
Softpaw Mousefolk Tool Proficiency Issue

### ISSUE THREAD

**Issue by jplcny** [Sklore/HL_DD_5e_Colab#681]
I noticed while making a character using the 5e Community Pack, when I created a Mousefolk race and selected the Softpaw subrace I ran into an issue. Softpaw Mousefolk get one tool proficiency in either a musical instrument or an artisan tool. When I selected a tool, I still got an error from Hero Lab stating "Softpaw: Not enough tool proficiencies chosen.

I'm wondering if Hero Lab doesn't know what to do with the cToolMax field when it is used with a subrace. I tried to find another race that gives a tool proficiency based on a subrace for comparison, but didn't find one. (I didn't look all that hard, though.)

**Comment by jplcny** [comment]
This remains an issue. I saw that a change was made to Mousefolk in the 2.0 release, but this remains an issue.

**Comment by Sklore** [comment]
Yeah I looked into this but have yet to figure out a way to fix it. Still on the To Do list.

**Comment by dungeonguru** [comment]
Here's a workaround, it opens the Proficiencies tab (by calling the Skilled feat subroutine), so I'm not sure if you want to go this route:

1. Remove the cToolMax field - this is setting the # of tools to 1, not adding 1 to the total number.
2. Put this eval script in at post-levels/10000 (along with the customary doneif statements): 
               hero.childfound[cfg5CProf].field[cToolMax2].value += 1

Give it a spin, and if that works upload the changed .user file. The proficiency tab looks a little odd if you give your mousepaw the "Skilled" as well, but it appears just fine in the pdf/statblock output.

**Comment by dungeonguru** [comment]
Update: I've figured this out.
Remove the cToolMax field and add this to the post-level/10000 script

doneif (tagis[Helper.Disable] <> 0)
hero.child[RaceHelper].field[cToolMax].value += 1

I'll upload to my branch and push it out for next release.
