### ISSUE TITLE
Pistol weapons

### ISSUE THREAD

**Issue by vicored** [Sklore/HL_DD_5e_Colab#682]
Hello, the problem him having is that the pistol weapons is set to be a melee weapon and there's no stats in armory section exp for the name pistol.

And also, is pistol using dex for att. When selecting a gun that also seems to have a problem. The bug is affecting all the range weapons that are gun related.

Thank for the help.
 for D&D 5 sorry

**Comment by dungeonguru** [comment]
I think this is being addressed in the next patch? I see in the notes:

- Added projectile category to the firearm weapons. Otherwise they do not add dex bonus to attack and damage

Anyone have a comment?

**Comment by Sklore** [comment]
Yeah pretty sure this has already been addressed. Will close this out but please test post release (which im going to try push out this week) and let us know.
