### ISSUE TITLE
ranger 2016 and fighter fighting styles

### ISSUE THREAD

**Issue by mercenary-kantor** [Sklore/HL_DD_5e_Colab#683]
you can duplicate fighting styles with a dual class which is prohibited by the rules.  Such as +1 Defense twice.

**Comment by dungeonguru** [comment]
I think this is happening because the Fighting styles that are granted to the revised ranger are copies of the fighting styles that LW provides, so the revised Ranger selects styles that are copies and not the originals, which is allowing for duplication.

**Comment by TheEnthusiast** [comment]
Yes,

When I wrote that ranger, I did not know about Extend Thing. I'm not sure how to fix it without breaking existing characters.

**Comment by Sklore** [comment]
You could create a new copy of it with the correction in place and then hide the original. This way people can still use the original but wont be able to pick it for new characters forcing them to update over time.

**Comment by dungeonguru** [comment]
I'm updating the ranger (2016) file to extend the cHelpRgC class to the official fighting styles and changed the fighting styles to  be:
'Archery - Depreciated', etc....

This will mean that anyone with Ranger (2016) should see that their fighting style is depreciated and when they check out their Fighting Style choice, they'll see the new ones.  This removes the ability to duplicate the fighting style. 

I also added Helper.Obsolete tags, so when you go to replace the 'Depreciated' Fighting style, only the new valid ones show up.
