### ISSUE TITLE
VGtM: Monsters

### ISSUE THREAD

**Issue by dungeonguru** [Sklore/HL_DD_5e_Colab#685]
All Monsters and variants entered. Stock files created and tested. 

**Concern 1** - Lots of typos or incorrect information in the NPCs - example: Conjurer is 9th level Wizard, the slots shown under spellcasting is for a 10th level wizard. Sent message to Wizards to see if some errata files are stowed away for VGtM

**Concern 2** - xTelepathy had no way to increase the range to miles, so created a ab5CLRTele copy that is set to mile range. Accepts a value like Telepathy does - it prints out as mile instead of miles but is minor issue. Noticed that neither Telepathy or the new Telepathy show up on the sheet - just the statblock & printed output, not sure if a big bug since they both have the Show On Specials checked...

**Completed**:
- Aurochs
- Banderhobb 
- Barghest 
- Beholder: Death Kiss 
- Beholder: Gauth
- Beholder: Gazer
- Bodak
- Catoblepas 
- Cave Fisher
- Chitine
- Choldrith 
- Cow - **BONUS** - variants: Ox, Rothe, Deep Rothe, Stench Kow
- Cranium Rat 
- Cranium Rat: Swarm of Cranium Rat 
- Darkling
- Darkling Elder
- Deep Scion 
- Demon: Babau 
- Demon: Maw 
- Demon: Shoosuva
- Devourer 
- Dinosaur: Brontosaurus
- Dinosaur: Deinonychus 
- Dinosaur: Dimetrodon 
- Dinosaur: Hadrosaurus 
- Dinosaur: Quetzalcoatlus 
- Dinosaur: Stegosaurus 
- Dinosaur: Velociraptor 
- Dolphin
- Draegloth 
- Firenewt 
-  under Firenewt: Giant Strider 
- Flail Snail
- Froghemoth
- Giant: Cloud Giant Smiling One 
- Giant: Fire Giant Dreadnought 
- Giant: Frost Giant Everlasting One 
- Giant: (Hill Giant) Mouth of Grolantor 
- Giant: Stone Giant Dreamwalker 
- Giant: Storm Giant Quintessent 
- Girallon
- Gnoll: Flind
- Gnoll Flesh Gnawer
- Gnoll Hunter
- Gnoll Witherling
- Grung
- Grung Elite Warrior
- Grung Wildling
- Guard Drake **Bonus** all 5 chromatic variants
- Hag: Annis Hag 
- Hag: Bheur Hag
- Hobgoblin Devastator
- Hobgoblin Iron Shadow
- Ki-rin 
- Kobold Dragonshield - Damage resistance is chosen similar to Dragonborn!
- Firenewt Warlock of Imix - **99%** - add the penetrates magical darkness to darvision? Adding Warlock trait to Specials list seems to be best option since there are no fields to manipulate the post sense text distance abbreviation? (Same with every creature and NPC warlock).
- Kobold Inventor - Note: Weapon Inventions are clunky.
- Kobold Scale Sorcerer - Set sorcery points to 3, but probably should be related to rSpCastLev - but this is an NPC...
- Korred 
- Leucrotta
- Meenlock
- Mind Flayer - Alhoon
- Mind Flayer - Elder Brain
- Mind Flayer Variant - Mindflayer Lich (Illithilich) - created as Illithilich
- Mind Flayer - Ulitharid
- Mindwitness
- Morkoth
- Neogi
- Neogi Hatchling
- Neogi Master
- Neothelid
- Nilbog
- Orc Blade of Ilneval
- Orc Claw of Luthic
- Orc Hand of Yurtrus
- Orc Nurtured One of Yurtus
- Orc Red Fang of Shargaas
- with Orcs : Tanarukk
- Quickling
- Redcap
- Sea Spawn - Piscine Anatomy attacks were pulled out as seperates but this is clunky.
- Shadow Mastiff
- Slithering Tracker
- Spawn of Kyuss
- Swarm of Rot Grubs
- Tlincalli
- Trapper
- Vargouille
- Vegepygmy
- Vegepygmy Chief
- Beast Vegepygmy: Thorny
- Wood Woad
- Xvart
- Xvart Warlock of Raxivort
- Yeth Hound
- Yuan-Ti Anathema
- Yuan-ti Broodguard
- Yuan-ti Mind Whisperer
- Yuan-ti Nightmare Speaker
- Yuan-ti Pit Master
- **NPCS FINISHED**
- Abjurer
- Apprentice Wizard
- Archdruid
- Archer
- Bard
- Blackguard
- Champion
- Conjurer
- Diviner
- Enchanter
- Evoker
- Illusionist
- Kraken Priest
- Martial Arts Adept
- Master Thief
- Necromancer
- Swashbuckler
- Transmuter
- War Priest
- Warlock of the Archfey
- Warlock of the Fiend
- Warlock of the Great Old One
- Warlord

**Comment by Sklore** [comment]
:) with monsters just remove the descriptive text. Much more efficient that way.

**Comment by dungeonguru** [comment]
True enough for descriptions but making sure the special abilities aren't 100% isn't easy either.

**Comment by Sklore** [comment]
The trick there's to strip it back to mechanics only.

**Comment by dungeonguru** [comment]
Created a branch for the files and uploaded what I have so far so if something happens to me someone can take my scraps up. I'm updating the first post with where the progress is sitting at. The files are functional -  listed the few bugs as noted in the first comment.

**Comment by Sklore** [comment]
Jeezus... nice work

**Comment by dungeonguru** [comment]
Should be able to finish up all the NPCs by this weekend - going to make spot rulings on the typo and mechanics questions I've accumulated - then I'll merge to master. The boggle scripting at this point is an option I'm still exploring - don't know how/where I would like to see the activation and what type of toggle mechanism for the menu I want to use. If I can't figure something nice out, I'll just remove the activation and let the DM fill in with imagination (as it should be).

**Comment by Sklore** [comment]
Jeezus christ... are you parsing this in? Bloody quick.

**Comment by dungeonguru** [comment]
Yeah, my words per minute typing speed is really high (20 years in IT did that for me) and a lot of the monster families share a lot of base stats and abilities (almost all the orcs had identical STR/DEX/CON, etc.).   I also am between gigs right now, so 8 hours to just hammer away while the wife isn't around gives me advantage on it.

**Comment by dungeonguru** [comment]
Closing the work.
