### ISSUE TITLE
Multiclassing Spellcasters

### ISSUE THREAD

**Issue by dndoverlord** [Sklore/HL_DD_5e_Colab#686]
Creating a paladin 5 / sorcerer 3 disallows 2nd level spells for the paladin which is wrong. It appears that the paladin is counted as a half caster when determining spells but according to the PHB on pg 164 that is wrong. 
Quote: "**Spells Known and Prepared**. You determine
what spells you know and can prepare for each class
individually, as if you were a single classed member of
that class. If you are a ranger 4/wizard 3, for example,
you know three 1st. level ranger spells based on your
levels in the ranger class." 
If you look at the ranger, a 4th level ranger knows 3 first level spells but if it was counted as a half caster it would only know 2.

**Comment by TheEnthusiast** [comment]
The code handling multiclassing comes from the core 5e module provided by lone wolf. Please open a ticket with them. 

Also, make sure you are using the latest version of the 5e system. We already had this issue reported with the eldritch knight at the beggining of the year.


Regards.
