### ISSUE TITLE
Opportunity for Paid Data Entry

### ISSUE THREAD

**Issue by Sklore** [Sklore/HL_DD_5e_Colab#687]
Hi Team,

So the reason why I've been quiet for so long is because I'm doing data entry for a number of companies in both Realm Works and Hero Lab. There's quite a bit of stuff in the pipe for 5e that I'm certainly excited about :)

I've just been contacted by a publisher looking for someone to assist with some Hero Lab data entry. Specifically putting a series of products that offer alternative races into the tool. 

I don't have the capacity to take on the races so I said I would put the feelers out to see if there is anyone here interested. 

It would be a paid gig although I have no idea about rates etc. That would be between you and the publisher. 

Obviously you would need to be comfortable doing data entry in Hero Lab for 5e, there will be deadlines to meet and quality will be a requirement. 

If anyone is interested please let me know and I will connect you with the publisher.

**Comment by DarkHayZe** [comment]
I would be very interested in this opportunity. Sounds like just my kind of gig.

**Comment by Sklore** [comment]
Can you email me the following: daplunk@adam.com.au

Full name:
Facebook Profile Link: (This is how I was contacted)
Short description of your Hero Lab experience:

I can then pass that along for you.

**Comment by DarkHayZe** [comment]
Sent

**Comment by Sklore** [comment]
Have forwarded your details to the publisher 👍
