### ISSUE TITLE
Flight for a Tempest Cleric?

### ISSUE THREAD

**Issue by Grymm428** [Sklore/HL_DD_5e_Colab#689]
Upon creating a Tempest Cleric, I received the special ability to fly.  I'm sure that is an error.  Thank you for working so hard to update the Community Pack.

-Scott D.

**Comment by dungeonguru** [comment]
I think if we add 

doneif(#levelcount[Cleric] < 17)

to the top of the eval script for Stormborn it should work, not sure if that's the best method to fix this . I'm rusty on the Helper.Disable calls and how it works with the ClSpecWhen mechanism.

**Comment by dungeonguru** [comment]
I added this fix to next release.
