### ISSUE TITLE
Release Preparation V1.1

### ISSUE THREAD

**Issue by Sklore** [Sklore/HL_DD_5e_Colab#69]
@shadowchemosh 

I have consolidated all of the changes made since release and updated the release document. I don't think i did it properly so you may want to have a look. 

I've also been using this Wiki Entry to track changes on the go. I find this efficient and easy to modify on the fly and has made updating the release file alot easier. 

Are we able to push out 1.1?

**Comment by shadowchemosh** [comment]
I could do a quick release tonight. If I do a pull down from main right now it's already to go?  I just need to double check the release notes file?

**Comment by Sklore** [comment]
Yes I've tested and had no issues. The content of the release notes is there. Just pretty sure I did the formatting wrong. Thanks mate.

**Comment by shadowchemosh** [comment]
OK.  But issue. I am now getting a load error:

`File: COM_5ePack_PHB - Deities.user (line 770) - Encountered unknown element tag '?xml'`

Let me try and fix that first....

**Comment by shadowchemosh** [comment]
Um looks like every deity in the COM_5ePack_PHB - Deities.user file has been duplicated.

Look at the file in GitHub at Main:
https://github.com/Sklore/HL_DD_5e_Colab/blob/master/COM_5ePack_PHB%20-%20Deities.user

Then look for deity id "dei5CNuita" you will find it twice...????

**Comment by shadowchemosh** [comment]
Looks like the file was some how duplicated.  Starting at line 770 the file is repeated a second time...

**Comment by shadowchemosh** [comment]
I am going to take out the repeated data.  I am going to assume the first set of data in the file is correct..

**Comment by shadowchemosh** [comment]
I made the fixes to this b32873fb75c2d9f9c139d0cd6ff498a22a2eb296 commit.  Going to create the .hl file now for v1.1.

**Comment by shadowchemosh** [comment]
Ok v1.1 is out in the wild.  You can copy/paste the below into a HL Forum post to have it formatted nicely.

```
[b]v1.1 February 24, 2016[/b]

[b]New Features[/b]
[list]
[*]The Book of Lost Spells 5e - 706 new spells
[*]The (Not Really) Complete Tome of Spells - 470 new spells (Only A-C currently assigned to classes)
[/list]
[b]Enhancements and Changes[/b]
[list]
[*]Source files updated to ensure clarity between Official and 3rd Party source material
[*]DEITIES - Deities from SCAG. The Drow Pantheon (Eelistraee, Kiaransalee, Lolth, Selvetarm, Vhaeraun)
[*]BACKGROUNDS(SCAG) - 13 new backgrounds added
[*]CLASS OPTION - Human Variant - This has been made Obsolete. Replaced with in official HL release.
[/list]
[b]Bug Fixes[/b]
[list]
[*]FEAT(Elemental Adept) - Fire add as options
[*]FEAT(Spell Sniper) - Pre-req now recognizes Warlock spells
[*]BACKGROUNDS(Tool Proficiency Display Issue) - Tool proficiency's that are hard coded will now be visible to the player. This is a temp work-around as this is not currently displayed by default.
[*]BACKGROUND(Charlatan) - Missing tool proficiency added
[*]BACKGROUND(Spy) - Equipment added, tools corrected, proficiency corrected
[*]BACKGROUND(Naming Conventions) - Some naming conventions were incorrect and had to be fixed. This will impact the following: bBMilitiaA updated to b5CMilitia | btSdIndepe updated to bt5CSdInde | btBDefuse updated to bt5CDefus
[*]CLASS(Naming Conventions) - Some naming conventions were incorrect and had to be fixed. This will impact the following: cClrTempes updated to c5CClrTemp
[*]CLASS(Wizard Schools) - Will not appear if the Community Pack is not selected.
[*]SPELLS(Duplication) - Many duplicate spells removed. There are a few variant spells of the same name, have added the source book abbreviation in brackets after those spell names to assist in differentiation.
[/list]
```

**Comment by Sklore** [comment]
:+1:

**Comment by shadowchemosh** [comment]
Ok I am off to bed as its really late here and have work in the morning.  If any major issue happens with the release I "maybe" able fix it before I leave in the morning.

Later!

**Comment by shadowchemosh** [comment]
Does not look like like any major issues with the .hl file so closing out this issue.
