### ISSUE TITLE
Bonus Class Abilities

### ISSUE THREAD

**Issue by DarkHayZe** [Sklore/HL_DD_5e_Colab#690]
Does anyone know what the field name for Secondary Class Abilities? In order to give a bonus choice.

I know the Primary is [cGiveSpec]

**Comment by dungeonguru** [comment]
I know in pathfinder it is [cGiveSp2nd], not sure if it is the same for 5e.

**Comment by DarkHayZe** [comment]
That sounds familiar, will give it a shot... I know I have seen it somewhere, just no idea where.

**Comment by DarkHayZe** [comment]
That worked beautifully (Once I got the rest of the code to work...haha) Thank you.
