### ISSUE TITLE
Bootstrap issues

### ISSUE THREAD

**Issue by DarkHayZe** [Sklore/HL_DD_5e_Colab#691]
I need to figure out a way to bootstrap some free class spells, but only if the subrace matches one of three choices.

I have tried bootstrapping it at the class level, at the class special level. But it either doesn't show up at all or shows up regardless of whether or not the subrace prereq matches. I have tried making the prereq the subrace, and an ability the sub-race gives... with no change.

@shadowchemosh @LordMorin

**Comment by LordMorin** [comment]
How are you doing this? Inside a class, sub-class or a feat?

**Comment by DarkHayZe** [comment]
Class

**Comment by LordMorin** [comment]
And what subraces are you working with?

**Comment by DarkHayZe** [comment]
Custom Race, Custom subrace, custom class.

Basically, the Class assigns an ability. And if you have one of the three sub races, it changes what that ability does. I have everything working, except for the free spells that it gives, instead of the other powers of the ability.

So I need it to...

1. Load Race
1a. Load Sub Race
2. Load Class
2a. Check Sub Race
3. Load appropriate ability set.

**Comment by LordMorin** [comment]
Are you using one ability that selects the spells based on subrace/subclass or are you using a separate ability for each subrace or subclass? If its for each subclass, then it would be easiest to have a separate ability with its own spells for each subclass. . .

**Comment by DarkHayZe** [comment]
The ability only changes for one subrace. I have tried it a couple different ways.

I tried having it so it was all one ability, and the spells were conditioned to only show for the correct sub race.

I have tried making it it's own ability to be called instead. 

I haven't had any luck either way.

**Comment by DarkHayZe** [comment]
Currently, I have it set so everything but the spells is in one ability, I just can't get it to recognize properly that the matching sub race is active.

**Comment by LordMorin** [comment]
Since it is only spells, I'd make it 2 ability. One for each set of spells. Then I'd bootstrap the various sets of spells to the appropriate subclass. That way each subclass gets the spells appropriate to it.

**Comment by DarkHayZe** [comment]
It's not the subclass that changes what is given. It's the sub race. And it is only for this class, the ability is part of the base class.

**Comment by LordMorin** [comment]
kk, I am getting a clearer picture now. :)

**Comment by DarkHayZe** [comment]
Yeah, sorry it's not the most straight forward class..lol

**Comment by DarkHayZe** [comment]
I just had a thought... The sub race gives a spell of its own. If I can check for that spell as the bootstrap condition... maybe that will work... I am just not sure what the coding for that would be.

**Comment by DarkHayZe** [comment]
Maybe... I am doing the right thing, it just isn't looking in the right place?

![image](https://user-images.githubusercontent.com/17392134/28939945-9e77c542-7858-11e7-81a6-3002a9eb6c5c.png)

This is my current attempt, for bootstrapping the ability that has the spells. Based on the Racial spell from the sub class. It still isn't working, however, I am thinking maybe it is just not looking in the right place... 

This is bootstrapped at the Class level, as a "Class Special Ability". Is there a command to point it to the right area of the data? Or am I completely off on this line of thinking?

**Comment by LordMorin** [comment]
I'm playing around with conditionals atm myself.

**Comment by DarkHayZe** [comment]
It just doesn't make sense to me... it should work, but it doesn't. Based on everything I know.

I tried moving this Tag Expression to the spell itself, with no luck.

**Comment by DarkHayZe** [comment]
I can do a Pick-req, but that just makes it an invalid choice rather than not loading it.

**Comment by LordMorin** [comment]
Yea, I discovered that already. I'm still trying to discover how to get a Bootstrap conditional that checks subrace to work. I know I am doing something wrong but for the life of me I can't remember how I did this before.

All my resources are on my main system at home, not on this laptop. :(

**Comment by DarkHayZe** [comment]
Dontcha love that... I am half tempted to keep my files on either my Onedrive or my Google Drive for ease of access...lol

**Comment by LordMorin** [comment]
I need to add them to my dropbox. Then they are available whenever I have internet.

**Comment by DarkHayZe** [comment]
Dropbox is probably the better option

**Comment by DarkHayZe** [comment]
Then if I needed, or you needed to, share a file you could send a link, easier than the other two anyways... also ownership rights are muddy with MS and Google cloud storage.

**Comment by LordMorin** [comment]
I use my limited MS storage for my mp3 folder. :)

I'll have to look into google cloud storage. Been using google for years and didn't realize they had such a thing. :)

**Comment by DarkHayZe** [comment]
I don't know if they changed it, but part of the EUA stated that anything you stored on it became the property of Google.... so...

**Comment by DarkHayZe** [comment]
My one Drive has all my PDFs on it, though I also have 1Gb of storage, so...lol

**Comment by DarkHayZe** [comment]
do you know what the text equivalent of "fieldval:" is?

**Comment by LordMorin** [comment]
If fieldval: doesn't work for both values and strings, I'm not sure. Never used it for test before.

Sorry, working on another laptop belong to my sister that needs a reinstall atm.

**Comment by shadowchemosh** [comment]
http://forums.wolflair.com/showthread.php?t=47611
Bootstrap info.

FYI 99% of the time a Bootstrap condition for TAGS looks at the HERO not the Pick.  Using Fieldval: means you are looking at the Pick.

So is the tag Helper.RaceSpell on the Hero?  Based on its name I will say no mean the condition is never true.

You may want a script that sets a value of 1 or o into abValue5 and use the bootstrap condition to key off the fieldval:abValue5 <> 0

**Comment by LordMorin** [comment]
ShadowChemosh showed me how to use fieldval:abValue5 etc a while back.

Sorry, haven't been able to focus on your issue for the last hour or so. My
sister wants me to do stuff and now I have to log out. If you haven't
solved this issue by tomorrow, I'll try to assist again. Also, you might
want to ask ShadowChemosh for an assist in HL forums. He might be able to
solve the issue off the top of his head. :)

**Comment by DarkHayZe** [comment]
That did it, used a script on the sub race to set the value of the ability in question's field abValue5 to 1, bootstrap condition to check that value.

**Comment by LordMorin** [comment]
Now that you said that, I recall having to do something similar a long while back. A year or so back.

**Comment by LordMorin** [comment]
Don't know if this is useful or not, but I thought I'd give you a link:

http://www.infernaldreams.com/HeroLab/Unoff_HL_Authoring_Kit_Manual.pdf

**Comment by DarkHayZe** [comment]
Wait.. someone actually made a manual... haha

Thank you!
