### ISSUE TITLE
Coding Help: Template Changes

### ISSUE THREAD

**Issue by Sklore** [Sklore/HL_DD_5e_Colab#695]
Hi Team, 

I have come across something that I have no idea how or if its possible and wondering if you can provide some assistance. 

I'm attempting to create a template that can be applied to a beast, humanoid or monstrosity. 

These are the two things I'm struggling with. Knowing how powerful Hero Lab is I'm sure it's possible but haven't the faintest idea or ability to program these up. 

_**Challenge Rating:** If the base creature does not possess class levels, innate spellcasting, or spellcasting, increase the challenge by +2. Do not recalculate the creature’s proficiency bonus._

_**Armor Class:** If the creature has natural armor, increase its value by 1. If the base creature was wearing light armor, it instead gains natural armor with an Armor Class of 10 + the creature’s Constitution modifier (minimum 1) + the creature’s Dexterity modifier. If the creature wears medium or heavy armor, or armor of an unusual nature (such as a magic item), it retains that armor._

Does anyone know if it's possible to code these requirements up? I'm not a coder so anyone who can help complete these would be greatly appreciated. 

Thanks, 

Josh

**Comment by TheEnthusiast** [comment]
Working from memory:

There's a task to calculate the field tCR somewhere in the levels phase. I believe you need to increase the value after the Levels phase. It should not impact the proficiency, which is also calculated at Levels.

About the armor, look at the codes for Mariner style, or the barbarian unarmored defense. Both should give you what you need.

Enviado de meu ASUS

-------- Mensagem Original --------
De:Daplunk <notifications@github.com>
Enviado em:Wed, 09 Aug 2017 21:04:05 -0300
Para:Sklore/HL_DD_5e_Colab <HL_DD_5e_Colab@noreply.github.com>
Cc:Subscribed <subscribed@noreply.github.com>
Assunto:[Sklore/HL_DD_5e_Colab] Coding Help: Template Changes (#695)

**Comment by dungeonguru** [comment]
The tCR calculation is also in the Adjustment code for Challenge.

if you put the following in after the Levels code it should adjust the CR. 
herofield[tCR].value += 2

That AC calculation is trickier by far but the barbarian unarmored is what I was going to recommend too.

**Comment by Sklore** [comment]
Thanks guys, making changes to the actual values is something I can likely figure out. For me the challenge will be the trigger to complete the change. 

How do you check to see if the creature possess class levels, innate spellcasting, or spellcasting?
How would you do all the IF THEN OR requirements of the Armor Class changes?

These are things I have no clue on.

**Comment by TheEnthusiast** [comment]
Check if it has Hero.Caster

That should kill anything spell related.


Enviado de meu ASUS

-------- Mensagem Original --------
De:Daplunk <notifications@github.com>
Enviado em:Wed, 09 Aug 2017 22:32:34 -0300
Para:Sklore/HL_DD_5e_Colab <HL_DD_5e_Colab@noreply.github.com>
Cc:TheEnthusiast <ps3nerobr@gmail.com>,Comment <comment@noreply.github.com>
Assunto:Re: [Sklore/HL_DD_5e_Colab] Coding Help: Template Changes (#695)

**Comment by dungeonguru** [comment]
From the editor's help pages, these two macros might help

#totallevelcount[]  < this macro returns the total number of class levels

so 
doneif (#totallevelcount[] > 0)   
~ drops out of script if any class levels are present.

**Comment by TheEnthusiast** [comment]
Here's the code from Mariner style, it deals with the armor conditions:

     field[abValue].value = 1
     foreach pick in hero from BaseArmor where "( ArmorClass.Heavy | ArmorClass.Shield ) & ( Helper.CurrArmor | Helper.CurrShield )"
          field[abValue].value = 0
     nexteach
     hero.childfound[ArmorClass].field[Bonus].value += field[abValue].value

So, your armor code needs to check if there's any sort of armor in the character (BaseArmor) and change the values according to the type of armor the is currently equiped (Helper.CurrArmor)

**Comment by dungeonguru** [comment]
Here's an example of where I'm working on the wererat template - I decided to up the CR on humanoids that get this template, but only if they already have a low CR, it shows a pretty easy to follow set of if then logic.

```
~Adjust CR (rough adjustment)
~ Quit if the CR value is already enough to be Tier 2 play
~ PHB 
doneif (herofield[tCR].value > 4)
if (herofield[tCR].value < 1) then
~ if humanoid is pretty weak, then damage immunity grants it CR 1
   herofield[tCR].value = 1
else
~ Tier 1 monsters should get a CR bump of 1.
   herofield[tCR].value += 1
endif
```
