### ISSUE TITLE
Cantrips as weapons

### ISSUE THREAD

**Issue by Dustin1280** [Sklore/HL_DD_5e_Colab#700]
Is it possible to get cantrips added as weapons so we can have easy access to cantrip weapon attacks?

It would be even better if they took into consideration things like Agonizing Blast and/or Elemental Affinity.

But frankly just being able to add cantrips as weapons would be a huge thing to start with.

**Comment by Sklore** [comment]
If you want cantrips to be more readable within the program that's something you should approach LWD about. Please raise the issue with them.
