### ISSUE TITLE
UA: Feats for Races

### ISSUE THREAD

**Issue by dungeonguru** [Sklore/HL_DD_5e_Colab#701]
Question: For the Grudge-Bearer feat, I have two menu drop downs - one for the ability chosen and one for the chosen enemy. When you choose Humanoid, you're supposed to get a new field with two choices. Is there a way to add another text field underneath dynamically or am I stuck opening a configurable page for the choice of two humanoid types (which much like the Feat Skilled seems to be kinda weak). 

Request to get the UA from 4/2017 into Community files:
http://media.wizards.com/2017/dnd/downloads/RJSJC2017_04UASkillFeats_24v10.pdf
**Progress Log - Finished**
- Barbed Hide:
- Bountiful Luck
- Critter Friend
- Dragon Fear
- Dragon Hide
- Dragon Wings
- Drow High Magic
- Dwarf Resilience
- Elven Accuracy
- Everybody's Friend
- Fade Away
- Fey Teleportation
- Flames of Phlegethos
- Human Determination
- Infernal Constitution
- Orcish Aggression
- Orcish Fury
- Prodigy (works  using call to Skilled 5C procedure)
- Second Chance
- Wonder Maker
- Wood Elf Magic (cantrip shows up on race tag like high elf cantrip does)

**In Progress/Needs scripting**
- Grudge-Bearer: Needs script to flesh out choices on 2 expressions.
-- Race Type is userChosen2
-- Ability is userChosen1
-- Not sure how to handle the Humanoid type - how to call up a text field to fill out?

**Comment by dungeonguru** [comment]
I merged the functional items in with merge pull #714. All feats are working - Grudge-bearer could use some additional work on the Humanoids side, but I ran out of time to work on it.

**Comment by kjbro** [comment]
Minor issue - Elven Accuracy says in your release that it is a damage re-roll, but is in fact an attack re-roll.

**Comment by dungeonguru** [comment]
Fixed Elven Accuracy
