### ISSUE TITLE
Races Post 1.1

### ISSUE THREAD

**Issue by DarkHayZe** [Sklore/HL_DD_5e_Colab#71]
So selecting human, the option for subrace is gone, with the addition of variant human. But it is still saying that I need to choose a subrace for this race.

![capture](https://cloud.githubusercontent.com/assets/17392134/13281061/d2250eb2-da9e-11e5-9988-2b4fa00f572f.JPG)

**Comment by Sklore** [comment]
Thanks this one has already been fixed and will be released in the next release. 

You can ignore it or...

Open the Editor > Open COM_5ePack_PHB - Races.user > Delete the following:
Races > Subrace > Obsolete - Human Variant - Obsolete
Save the changes and restart Hero Labs.

**Comment by DarkHayZe** [comment]
Wonderful, thank you
