### ISSUE TITLE
Bootstrap Does Not Exist

### ISSUE THREAD

**Issue by Tooley1chris** [Sklore/HL_DD_5e_Colab#711]
Just installed todays update and getting an error:
Thing 'cX12'-Bootstrap thing 'c5CPallmSp' does not exist

**Comment by Sklore** [comment]
Can you provide some more details. Maybe a copy of your portfolio. This will be specific to something and we need to know where to look.

**Comment by Tooley1chris** [comment]
Are you saying a missing bootstrap can be because of my own files? Not sure how.
Herolab wont load the custom content because of the error and many files were modified in this update, so I'm not sure which of the .dat files is calling for the bootstrap

**Comment by Tooley1chris** [comment]
well crud. I removed my .user files and it works. I'd have sworn all was well before the update. I usually will get duplicate file errors on updates and their easy fix. I'll figure it out. Thanks!

**Comment by Sklore** [comment]
It won't necessarily be because of your file but your file could be referencing something that is no longer working. This it will only trigger the error when you load that file.
