### ISSUE TITLE
Inserting a carriage return.

### ISSUE THREAD

**Issue by DarkHayZe** [Sklore/HL_DD_5e_Colab#716]
I was wondering if anyone knew how to, or if it is possible to insert a carriage return into a script

So that this...
![image](https://user-images.githubusercontent.com/17392134/29832401-b96758d6-8cad-11e7-8236-b23a9b83e582.png)
looks more like this...
![image](https://user-images.githubusercontent.com/17392134/29832490-07a14552-8cae-11e7-9b96-55d10b549d7f.png)

**Comment by LordMorin** [comment]
You can find it here with a little bit of other stuff. :)

http://hlkitwiki.wolflair.com/index.php5?title=Encoded_Text

**Comment by dungeonguru** [comment]
Echoing LordMorin - short answer is type in \n where you want the carriage return though.

**Comment by DarkHayZe** [comment]
Awesome thank you!

Now if only it wouldn't affect the Statblock as well...haha
