### ISSUE TITLE
Is there a way to change "natural armor"

### ISSUE THREAD

**Issue by DarkHayZe** [Sklore/HL_DD_5e_Colab#717]
I am looking for a way to change the default descriptor tag of "(natural armor)" to something else... For all intensive purposes, it is still natural armor, but I would like it to say something else, for flavor text.

Anyone have any ideas?

**Comment by dungeonguru** [comment]
Give the creature a field "rArmText" with a value of whatever your flavor is. Check out frost giant for an example - they have AC 16 (patchwork armor).  I think it breaks if you equip a shield  though, unless you are running a script in Render or later.

**Comment by DarkHayZe** [comment]
That worked perfectly thank you... I was sure it was out there somewhere, just had no idea where to look, or what creature to look at. And it is a unique monster so I shouldn't have to worry about breaking it... Tried to do it via script, but it didn't take. Though after setting the field, it said my string was too long so that might have been it too... But once again thank you :)
