### ISSUE TITLE
Request: Tal'Dorei Campaign Setting

### ISSUE THREAD

**Issue by CorvusPhoenix** [Sklore/HL_DD_5e_Colab#718]
With the Tal'Dorei Campaign Setting now out, and since Critical Role is so immensely popular, I suspect that a great many users will be overjoyed to see this added to the Community pack sooner rather than later.

**Comment by Sklore** [comment]
I don't have it so it's not something I can assist with. Given its popularity I think it's something the content owner should be engaged about for permission. What type of copyright is there? The best approach would be to engage LWD and request that they add it to the formal support. 

Little bit sensitive with copyright stuff right now with what's happening to other very popular character editors.

**Comment by dungeonguru** [comment]
Has anyone put in a formal request for LWD via support@wolflair.com? Like Sklore above, I do not have this in my library and am not sure if anyone can obtain copyright permissions.  Putting this on hold until we get more answers.

**Comment by Sklore** [comment]
LWD won't have this in their pipeline. They have way too much on their plate as it is. Doubt very much they would take on new contracts at this point.

**Comment by CorvusPhoenix** [comment]
If it helps, the copyright is held by Green Ronin Publishing.

**Comment by Sklore** [comment]
Basically the nuts and bolts of this is if you want it added please approach Green Ronin Publishing and get their permission for us to do it. If we get their permission in writing it's something we can add to the To Do list. I suspect however they would want to do it commercially though.
