### ISSUE TITLE
Set character name

### ISSUE THREAD

**Issue by DarkHayZe** [Sklore/HL_DD_5e_Colab#719]
Does anyone know if / how to set the Character Name within the data file?

**Comment by dungeonguru** [comment]
If you're talking about the actual user entered name, I don't think you can change it in a script but I know you can read it with the following reference:
  hero.child[heroname].field[useredit].text
I just tried an experiment with a feat that would add " Jr." to the end of that field and it came back with the "Only derived fields can generally be modified with scripts" error.  That error usually means don't mess with the field unless you're willing to break something.
