### ISSUE TITLE
Dark Arts Player's Companion

### ISSUE THREAD

**Issue by cxevan7** [Sklore/HL_DD_5e_Colab#724]
Wondering if anyone has created a DATA File for the Dark Arts Player's Companion? It seems pretty awesome and would love to push it to all my players iPads so they can use the spells and stuff.

If not, I could add the spells but I was wondering if anyone could help with the races / archetypes?

The file to the DAPC is here: https://drive.google.com/file/d/0B-g...hVU0c4dEE/view

**Comment by dungeonguru** [comment]
The link provided is invalid. No files there.

**Comment by dungeonguru** [comment]
Closing, without access to materials, can't proceed.
