### ISSUE TITLE
Ranger: Monster hunter

### ISSUE THREAD

**Issue by theycallhimxd** [Sklore/HL_DD_5e_Colab#727]
http://media.wizards.com/2017/dnd/downloads/UAThreeSubclasses.pdf
I don't see the ranger version of monster hunter. Did they make an update or is it just missing?

**Comment by dungeonguru** [comment]
Monster Hunter is a Fighter archetype from the Gothic heroes Unearthed Arcana (4/4/2016). The article you reference doesn't show up in the main UA listings and many of the 2017 articles have not been requested either. I will use this question as a request to get these three subclasses entered.

**Comment by theycallhimxd** [comment]
If you can show me a link into how to create this, I can do it.

**Comment by dungeonguru** [comment]
There's not a formal how-to link I know of, the wiki on github has some pointers, the editor help files have some more info, and the HL forums often have threads that show how to do certain things in scripts. For a ranger archetype, you can go into the editor and on the Class tab, Custom Ability tab you can New (Copy) and try to first copy one of the Ranger archetypes like Beastmaster and pick it apart. The actual abilities will usually be Class Specials.  You can also open up one of the community user files like COM_5ePack_PHB - Classes.user and look at how classes and subclasses are set up.

**Comment by dungeonguru** [comment]
These three subclasses are now part of next release. You can download the current code and they are in the UA Trio of Classes source.

**Comment by dungeonguru** [comment]
When you go to the <> Code tab you should be able to see a button that says clone or download with a little down arrow. You can download the current pre-release files as a zip. Inside the zip are all the files you need to copy/extract to your hero lab folder, which is usually C:\ProgramData\Hero Lab\data\5e but depends on if you custom installed. I think the direct link to download the zip is https://github.com/Sklore/HL_DD_5e_Colab/archive/master.zip
