### ISSUE TITLE
Can't add "Chromatic Orb"

### ISSUE THREAD

**Issue by cmeury** [Sklore/HL_DD_5e_Colab#73]
I found "Fire Bolt" and could add it to my sorcerer, but the "Chromatic Orb" is not in the list.

**Comment by Sklore** [comment]
Found the source of the issue. 

Temp Work-around. Open the Editor. Open COM_5ePack_PHB - Spells.user. 

General tab > *Hidden > Delete the option for sp5CChroO

**Comment by Sklore** [comment]
Fixed under commit a5e9672ca648c682c8574ab9e7c5b776b8897836
