### ISSUE TITLE
Tomb of Annihilation

### ISSUE THREAD

**Issue by dungeonguru** [Sklore/HL_DD_5e_Colab#730]
Request to add monsters and magic items from Tomb of Annihilation.

**Update**:
Created files - .1st, .stock and .user.
Uploaded 1st draft:
- Backgrounds: Archaeologist, Anthropologist
- Magic Items
- Monsters: All monsters, Acererak
- NOT INCLUDED yet: Named NPCs

**Comment by Sklore** [comment]
In case it's useful. The ToA random tables for Inspiration Pad Pro 3 have been created and can be found here:

https://docs.google.com/spreadsheets/d/1qtJ2KC2xUHAJ4pAFH2_4MrGFUofd0O400vaPDPWC5vU/edit#gid=108971754

**Comment by dungeonguru** [comment]
It is useful for my realm works/home setup, not so much for these files.  Have you put a link to these on your realm works in action sticky? People not following the facebook group could really use some direction to check out the group there.

**Comment by Sklore** [comment]
Yeah theres a link from that thread. I generally just post to the FB group these days though. Better discussion.

**Comment by dungeonguru** [comment]
Merged in final changes. #739
