### ISSUE TITLE
Beast Bond ranger spell

### ISSUE THREAD

**Issue by Conandy1970** [Sklore/HL_DD_5e_Colab#731]
The spell, Beast Bond, for rangers in the Elemental Evil player's companion is missing.  Or at least not coming up for a Ranger(2016).

**Comment by dungeonguru** [comment]
OK, the UA articles aren't looked at very often so we'll have to add that spell to the class. In the meantime, use the adjustment on the Adjustments tab to add the spell. Adjustment: "Add Single Spell to Class/Race"

**Comment by Conandy1970** [comment]
Thanks.  I used the Adjustment to add the spell, but it doesn't show up in his Spells tab nor does it print on his Spells sheet using the Print Portfolio. 

I think I have had this happen on another character where the spell was Added via the Adjustment didn't show up in his list of Spells.

**Comment by dungeonguru** [comment]
Merged fix in with pull #737, will be sent out in next patch cycle.
