### ISSUE TITLE
Missing Adjustment "Spells Known"

### ISSUE THREAD

**Issue by Lyroschen** [Sklore/HL_DD_5e_Colab#734]
Version 1.8 of the 5e Community pack listed as a new feature: 
[*]New adjustment "Spells Known" that will increase the number of known spells for spontaneous casting classes.

However, it seems to have been removed or otherwise lost. I am currently using v2.0 of the 5e community pack, although I did download the v1.8 source code, and was not able to locate the adjustment.

Am I simply missing something, or was it removed for a reason? Either way, I would like the feature returned, and don't have enough understanding of the authoring tools to write my own. Any help would be appreciated.

~Lyro

**Comment by Lyroschen** [comment]
I found a post from 1/3/2017 where ShadowChemosh posted that he had added this adjustment to the file: COM_5ePack_PHB - Adjustments.user

Looking back in the commits to that time, I found the file and was able to copy the code from it to my user files and it appears to have worked. For those who would like it, the codes is attached.

[spells known.txt](https://github.com/Sklore/HL_DD_5e_Colab/files/1364159/spells.known.txt)

Best regards,
~Lyro

**Comment by dungeonguru** [comment]
I'm reopening this to track all the accidentally removed code on the release/update that wiped out this and some other adjustments on February 2. Lyroschen, I think you can unsubscribe if you don't want any notifications.

Spells Known
Spells Memorized
Background Section
Background Skill change
Background Skill add
Background Skill remove

**Comment by dungeonguru** [comment]
Merged new file with the missing adjustments back into master branch. with pull #736

**Comment by Lyroschen** [comment]
Hi dungeonguru. Thanks for following up with this. There was a fix implemented for the "Add single spell to class/race" adjustment, that is incorrect in the current file. ShadowChemosh discusses the fix in this thread:
http://forums.wolflair.com/showthread.php?t=57307&page=2

Basically in the custom expression the component
component.BaseClass|component.BaseRace
needs to be replaced with 
component.Class|component.BaseRace

I updated this in the file, and it appears to fix the issue.

While we're at it, in the thread: 
http://forums.wolflair.com/showthread.php?t=11561
Mathias, ShadowChemosh and some others are discussing spell and conferred ability adjustments for Pathfinder. Do we have any of that for 5e?

**Comment by dungeonguru** [comment]
No problem, thanks for narrowing down the search for me to see what got removed in the first place. 

As far as scripts attached to spells, or applying spell effects, it's not something I've heard asked for yet.

**Comment by Lyroschen** [comment]
Consider this me asking for it. One of the common things I use in the Pathfinder is the Mage Armor spell effect adjustment on my mages.

**Comment by julesbravo** [comment]
+1
