### ISSUE TITLE
COM_5ePack_EN5 - 65 - Priests Elemental Power.user

### ISSUE THREAD

**Issue by DarkCable** [Sklore/HL_DD_5e_Colab#735]
@COM At 1st level when you pick Flames you get Fiery Soul but not adding: At 1st level, you learn one of the following cantrips: fire bolt, produce flame, or sacred flame.

**Comment by dungeonguru** [comment]
Adding code for next release (2.2). This ability will now have a dropdown to choose the spell granted and then add 1 to the number of cantrips known. There is an error/validation warning that will ask you to choose the spell selected in the cantrips section of the spell - this is similar to the bonus cantrip abilities of other cleric domains.
