### ISSUE TITLE
Artificer: No ability score increase at Artificer 8

### ISSUE THREAD

**Issue by LiaungYip** [Sklore/HL_DD_5e_Colab#743]
# Summary

Artificer characters don't get the ability score increase they are supposed to at Artificer level 8.

![image](https://user-images.githubusercontent.com/2173684/31572981-b756fdf0-b0f5-11e7-8c5d-a99ba2b67a71.png)

# Steps to reproduce

* Start Hero Lab.
* Select the 5e system.
* Install the latest version of the Community Pack.
* Create a new portfolio.
* Create a new character using the following sources:
  * 5e Player's handbook
  * 5e Dungeon Master's Guide - Beta
  * 5e Monster Manual
  * 5e Unearthed Arcana - Artificer

* On the Classes tab, assign 8 levels of Artificer.
* On the Artificer tab - there are only 2 ability score increases available. There should be 4. (Repeating the above process with a level 8 Sorcerer gives 4 ability points, as expected.)

# Troubleshooting

The ability score increases do appear to be correctly coded - see https://github.com/Sklore/HL_DD_5e_Colab/blob/25fc4ed02574e46f3ba306d378e911925b21fe2d/COM_5ePack_UA%20-%20Artificer.user#L50-L54 .

These also appear correct in the data editor -

* Tools > Show Editor
* Open `COM_5ePack_UA - Artificer.user`
* "Class" tab
* Click "cHelpArt" in column at left
* "Atribute Increase Levels" button below
* the value "2" is recorded against "Row 7", i.e. 2 points should be allocated at level 8

# Versions
D&D 5th Edition SRD - V2.3 (12 Apr 2017)
5e Community Pack  -  V2.0 (19 Aug 2017)
Herolab v8.2a (07 Sep 2017)

# Attachments
* Art the Artificer.por (within zip file) - portfolio showing the issue.
[Art the Artificer.zip](https://github.com/Sklore/HL_DD_5e_Colab/files/1384431/Art.the.Artificer.zip)

**Comment by dungeonguru** [comment]
Actually, the class ability scores table was incorrect. Row 7 should have read 4, row 12 read 6, etc... I have updated the table and the scores are calculating correctly. You can download the fix if you want, or wait till the next release is pushed.

**Comment by LiaungYip** [comment]
Thanks for the fix!
