### ISSUE TITLE
Hero Lab 5th edition srd The Hexblade attack and damage

### ISSUE THREAD

**Issue by sandor7** [Sklore/HL_DD_5e_Colab#745]
I'm running a hexblade warlock. The Hex Warrior feature says "when attacking with a melee weapon that you are proficient with and that lacks the twohanded property, you can use your Charisma modifier, instead of Strength or Dexterity, for the attack and damage rolls." This is not reflected on the attack and damage modifiers. Why is the charisma modifier not reflected in the attack and damage, and how do i fix it?

I posted the above issue on the Hero Lab 5th edition srd forum to get this looked at and was directed here to see if the community authors could address this issue. what should i do to get this issue fixed?

**Comment by LordMorin** [comment]
On the Inplay tab, are you checking off (activating the avility)? I play a
hexblade warlock myself and it works fine.

**Comment by sandor7** [comment]
welp...
it didnt even occur to me that would be a conditional thing. i found it and activated it. it works perfectly. thank you for that.

**Comment by LordMorin** [comment]
np
