### ISSUE TITLE
Three Eldritch Invocations in Patron List by mistake

### ISSUE THREAD

**Issue by Orudeon** [Sklore/HL_DD_5e_Colab#749]
Shroud of Shadow, Tomb of Levistus, and Trickster's Escape (all Eldritch Invocations from 5e Unearthed Arcana - Warlock) are in the Otherworldly Patron selection list by mistake instead of the Invocations list. Furthermore, Tomb of Levistus is the only one of the three that is also in the Eldritch Invocations list.

**Comment by dungeonguru** [comment]
This has already been fixed. If you go to the <> code tab you can download the latest version of the community files in a zip file, you can then unzip them to get the fix you want.
