### ISSUE TITLE
Missing UAs ( Trio of Subclasses)

### ISSUE THREAD

**Issue by binnsr** [Sklore/HL_DD_5e_Colab#751]
I am looking for the Drunken Master monk subclass added in the 3/27/17 UA release ( http://dnd.wizards.com/articles/unearthed-arcana/trio-subclasses ) but don't see that in the list of UAs offered by the Community Pack.

Is this in the works or is there an estimate of when it might be worked on?

**Comment by binnsr** [comment]
I went ahead and created these but do not see how to create a branch and/or upload to this repo.. 
Here is my file for someone with push access to integrate into the Community Pack (and fix what I might have gotten wrong :D )
[https://www.dropbox.com/s/zpxsx0wg7rklqno/00eldamir_UA_Trio_of_SubClasses.user?dl=0](url)

**Comment by dungeonguru** [comment]
Unfortunately, we'll have to refuse the merge and fix some issues. Your identifier RAB will confuse a lot of folks, so we'll have to replace that with the community id: 5C. Your source doesn't exist for anyone else, so we have to pull the source out and give it one that follows the standards. It's nice work, just it'll break a lot of people if we push it as is.

**Comment by binnsr** [comment]
I redid the identifiers.. take a look now.

**Comment by dungeonguru** [comment]
I fixed the issues I see, your code is working fine now.

I will update the Upcoming Changes wiki. I'm not sure when the next push is coming though, so you can re-download the branch with the changes. 

It was odd, the changes you made were to your personal fork and in the work-in-progress folder. I would suggest deleting your forked copy of the source code: the binnsr/HL_DD_5e_Colab fork will just get people confused. You can create local branches on the Sklore, just like you did for your patch-1 branch, which makes merging less confusing.

**Comment by dungeonguru** [comment]
Closing the issue, these UA articles are likely to get moved to the new Xanathar's in the coming days, but the UA article will stay active.
