### ISSUE TITLE
XGTE - Spells

### ISSUE THREAD

**Issue by Sklore** [Sklore/HL_DD_5e_Colab#757]

**Comment by Sklore** [comment]
All spells from A-Z entered. 

To Do:
Sanitise the content
Research trademarked name use
Allocate spells to classes

**Comment by Namorphos** [comment]
New here, but I would be willing to put in time on the textual content. Any guidelines I should look at for Sanitizing or Researching?

**Comment by Sklore** [comment]
Sorry for the delayed response. First week at new job. 

Here are the spell files. Let me know once you have them since we don't want these getting out. The requirement is to:

* Remove all the fluff. Description text, etc. Leave the mechanics so we know how the spell works but the stuff that describes what the spell looks like needs to go. 
* Re-write each spell by 10%
* Remove any trade-marked names (eg, Xanathar's) from spell names and replace with something generic. 

https://drive.google.com/drive/folders/1A6tNJnwl-58_138zmnJzDGO_T1yiw6Ex?usp=sharing

**Comment by Namorphus** [comment]
I've copied them to my own drive. I'll start scrubbing them this weekend.

**Comment by Sklore** [comment]
Thanks 👍 link removed.

**Comment by Namorphus** [comment]
[XGtE Spells - Pull Request](https://github.com/Sklore/HL_DD_5e_Colab/pull/789)

**Comment by dungeonguru** [comment]
Pull request is merged, I'll try to test today and scan through if I get a chance.
