### ISSUE TITLE
Unearthed Arcana: Elf Subraces

### ISSUE THREAD

**Issue by LordMorin** [Sklore/HL_DD_5e_Colab#761]
https://media.wizards.com/2017/dnd/downloads/UA-ElfSubraces.pdf

This is the first real scripting I have done since May.

You may have to change the Source to be compliant with the community pack. The file name is easily changable.

[soe_5ePack_UA - Elf_Subraces.zip](https://github.com/Sklore/HL_DD_5e_Colab/files/1522377/soe_5ePack_UA.-.Elf_Subraces.zip)

Let me know if anyone finds any issues.

**Comment by dungeonguru** [comment]
I have changed the name and source to be more compatible with the community files.  Thanks for the contribution. Only issue I could really see was that Grugach still has the Common language listed. I think we'll have to play around with the Hide.Language tag and timing to get it right, but most folks will work around it.
