### ISSUE TITLE
Dragon Masks from Rise of Tiamat

### ISSUE THREAD

**Issue by philliephil** [Sklore/HL_DD_5e_Colab#765]
I have had the Community Pack for a while and just added a couple of items specifically the black and Red dragon masks.  I am clueless on how to get the masks to add the charisma bonus to AC.  Was there a reason this was overlooked and how can it be added?

**Comment by dungeonguru** [comment]
Need to add a script running post-attribute/10000 that does the following:

```
      doneif (tagis[Helper.ShowSpec] = 0)
      doneif (tagis[Helper.Disable] <> 0)    
      field[abValue].value += #attrmod[aCHA]
      hero.child[ArmorClass].field[tACUnarDef].value = maximum(hero.child[ArmorClass].field[tACUnarDef].value,field[abValue].value)
```

Not sure why it would be omitted - before my time in community, but sometimes not all of a book makes it in as the contributors split it up due to human errors.

**Comment by dungeonguru** [comment]
I'm working on getting these updated for next push - the damage resistance/immunity works for all masks, a mask now adds a copy of Draconic language, adds Legendary Resistance correctly, adds CHA to unarmored defense values. Having issues with the darkvision/blindsight - as senses, it is difficult to add 60 feet to darkvision or a Usage restriction to blindsight.

**Comment by dungeonguru** [comment]
Uploaded fixes
Merge pull request #766 from Sklore/dungeonguru-12102017-multiplefixes
