### ISSUE TITLE
Push pending out as new release?

### ISSUE THREAD

**Issue by dungeonguru** [Sklore/HL_DD_5e_Colab#767]
Given that the change log is getting full, do we want to push the current pending changes out and then have a smaller push after New Year's to push out the Xanathar's Guide? 

I would love to provide a Christmas (US) push including Xanathar's but don't have a copy to help with the classes, I do see that the spells are getting entered now though.

**Comment by Churchill92** [comment]
Push out the current changes and then get Xanathar's Guide out next year. Makes us look productive :)

**Comment by Namorphus** [comment]
On this note: I have semester break almost here, and intend to get XGE. How can I contribute on that end to get XGE out sooner?

**Comment by dungeonguru** [comment]
Shadow, can you bundle up and let me know so I can download and test? I can't see any obvious issues.

**Comment by shadowchemosh** [comment]
So normally its Daplunk that requests releases is he not really involved anymore?

@dungeonguru what would you be testing that I would not already test?  Just confused by the request as no one has ever asked that before.

So daplunk always before provided a the final list of changes/enhancements/bug fixes so I can update the release notes.  Is that available anywhere?

**Comment by dungeonguru** [comment]
Daplunk has been busy, and he left instructions on how to prepare a release a while back - I thought I followed it correctly, but you never know. I'm just trying to help out - its been August since we had a 5e release and things are piled up to where I think we need to have something out there. 

I can test the release once it gets to the download spot. The download tests clear, so I'm not sure what the difference would be. If you need a personal e-mail or contact I can give you one via PM over at the HL forums I suppose. 

The changes are on the [wiki](https://github.com/Sklore/HL_DD_5e_Colab/wiki/3.-Pending-Changes), but here are the v2.1 notes:
**V2.1 Release - 12/14/2017**

**NEW RELEASES**
- Tomb of Annihilation (TOA) - Backgrounds, Magic Items, and Monsters
- Dungeon Master's Guide (DMG) - Epic Boons from the Dungeon Master's Guide have been added!
- Unearthed Arcana - Feats for Races
- Unearthed Arcana - Trio of Classes
- Unearthed Arcana - Elf Subraces

**ENHANCEMENTS & CHANGES**

- Barbarian - Path of the Totem Warrior - Totemic Aspect Eagle now grants flight while raging is activated.
- Barbarian - Path of the Totem Warrior - Spirit Walker, Spirit Seeker - spells granted now show up on spells tab
- Cleric - Light Domain - Removed unnecessary usage tracker on Corona of Light (was limited to Wisdom bonus/day)
- Cleric - Knowledge Domain - Added usage tracker on Visions of the Past (1/long rest)
- Cleric - Nature Domain - Added script to remove the duplicate Cleric cantrips from the Acolyte of Nature feature, now shows only the cantrip that the cleric spell list doesn't already have.
- Ranger - Ranger's Companion - Added scripts and bootstraps to auto-add a beast companion to the Ranger with updated attack, damage, AC bonuses.
- Wizard - School of Illusion - If you are a forest gnome, you now get an extra cantrip slot when you select the school of illusion, to reflect the fact that you already have minor illusion.
- Re-sorted the Unearthed Arcana article listing (is now alphabetically correct). Rescued and consolidated "orphaned" sources.
- Familiars - added missing familiars (lizard, octopus, quipper, etc.)
- Volo's Guide (VGtM): Added Death, Nature and Prophecy Hag variant races options with appropriate Shared Spellcasting and CR adjustments.
- Volo's Guide (VGtM): Added missing Yuan-ti Malison type 4 and type 5 variants
- Volo's Guide (VGtM): Added missing Mind Flayer Psion and several magic items for mind flayer thralls to use.
- Out of the Abyss (OotA): Added missing "baby" Hook Horror and Basilisk monsters

**BUGS**

- Restored adjustments accidentally removed with new release: Spells Known, Spells Memorized, Background Skill change, Background Skill add, Background Skill remove
- Ranger (2016) - added Ranger(2016) to class list for Beast Bond spell.
- Circle of the Land Druid Spells/En5ider 31 - code was removing the circle spells from appearing unless the En5ider source was enabled. This has been fixed. Circle spells now show up correctly, and urban circle shows up only if you have En5ider 31 enabled.
- Unearthed Arcana - Artificer - fixed bug not allowing CR 0-1 Beasts from appearing for selection of Mechanical Companion
- Unearthed Arcana - Artificer - fixed bug not granting ability score/feat increases past 4th level.
- Unearthed Arcana - Warlock - fixed Shroud of Shadows and other Invocations showing as Patrons.
- Unearthed Arcana - Starter Spells - fixed spell level of Healing Elixir
- Hag Coven Variant (MM) - Shared spellcasting statblock showing incorrect attack and save DCs, added script to correct this.
- Elemental Evil Player's Companion (EEPC) - Added missing acid resistance to water genasi and fire resistance to fire genasi.
- Princes of the Apocalypse (PoTA) - fixed extra damage tags on magic items for readability
- Volo's Guide to Monsters - adjusted Orc Intelligence adjustment to be correct.
- Rise of Tiamat (RoT) - fixed several issues with dragon masks - added immunities, legendary resistance, unarmored AC bonus calculation.

**Comment by shadowchemosh** [comment]
Cool thanks for the info. =)

I am going to start working on this in a little bit.  Of course your able to do any tests you wish.  I usually do several tests on the new install package myself. This includes installing fresh and installing over the previous version to make sure no file name changes happened.

If we can not do any more changes to the main until I get the release out I would appreciate it.

Thanks!

**Comment by shadowchemosh** [comment]
Looking over the new files I see allot of stock files now in this.  To do this correctly I need to now make a Windows/Mac version of the installer and a separate iPad installer.  Mostly because the iPad can't do anything with stock files so its not worth eating up the space on the tablets and increased download times.

Its not a really big deal just takes a little longer to make two installs instead of one.

**Comment by shadowchemosh** [comment]
Ok files have been uploaded to the server and are availble if you want to download and test.

I did installs on both Windows/iPad to make sure it correctly upgraded from v2 to v2.1.

Here is the fourm formated release notes:
```
[b]v2.1 December 15, 2017[/b]

[b]NEW RELEASES[/b]
[list]
[*]Tomb of Annihilation (TOA) - Backgrounds, Magic Items, and Monsters
[*]Dungeon Master's Guide (DMG) - Epic Boons from the Dungeon Master's Guide have been added!
[*]Unearthed Arcana - Feats for Races
[*]Unearthed Arcana - Trio of Classes
[*]Unearthed Arcana - Elf Subraces
[/list]
[b]ENHANCEMENTS & CHANGES[/b]
[list]
[*]Barbarian - Path of the Totem Warrior - Totemic Aspect Eagle now grants flight while raging is activated.
[*]Barbarian - Path of the Totem Warrior - Spirit Walker, Spirit Seeker - spells granted now show up on spells tab
[*]Cleric - Light Domain - Removed unnecessary usage tracker on Corona of Light (was limited to Wisdom bonus/day)
[*]Cleric - Knowledge Domain - Added usage tracker on Visions of the Past (1/long rest)
[*]Cleric - Nature Domain - Added script to remove the duplicate Cleric cantrips from the Acolyte of Nature feature, now shows only the cantrip that the cleric spell list doesn't already have.
[*]Ranger - Ranger's Companion - Added scripts and bootstraps to auto-add a beast companion to the Ranger with updated attack, damage, AC bonuses.
[*]Wizard - School of Illusion - If you are a forest gnome, you now get an extra cantrip slot when you select the school of illusion, to reflect the fact that you already have minor illusion.
[*]Re-sorted the Unearthed Arcana article listing (is now alphabetically correct). Rescued and consolidated "orphaned" sources.
[*]Familiars - added missing familiars (lizard, octopus, quipper, etc.)
[*]Volo's Guide (VGtM): Added Death, Nature and Prophecy Hag variant races options with appropriate Shared Spellcasting and CR adjustments.
[*]Volo's Guide (VGtM): Added missing Yuan-ti Malison type 4 and type 5 variants
[*]Volo's Guide (VGtM): Added missing Mind Flayer Psion and several magic items for mind flayer thralls to use.
[*]Out of the Abyss (OotA): Added missing "baby" Hook Horror and Basilisk monsters
[/list]
[b]BUGS[/b]
[list]
[*]Restored adjustments accidentally removed with new release: Spells Known, Spells Memorized, Background Skill change, Background Skill add, Background Skill remove
[*]Ranger (2016) - added Ranger(2016) to class list for Beast Bond spell.
[*]Circle of the Land Druid Spells/En5ider 31 - code was removing the circle spells from appearing unless the En5ider source was enabled. This has been fixed. Circle spells now show up correctly, and urban circle shows up only if you have En5ider 31 enabled. 
[*]Unearthed Arcana - Artificer - fixed bug not allowing CR 0-1 Beasts from appearing for selection of Mechanical Companion
[*]Unearthed Arcana - Artificer - fixed bug not granting ability score/feat increases past 4th level. 
[*]Unearthed Arcana - Warlock - fixed Shroud of Shadows and other Invocations showing as Patrons. 
[*]Unearthed Arcana - Starter Spells - fixed spell level of Healing Elixir
[*]Hag Coven Variant (MM) - Shared spellcasting statblock showing incorrect attack and save DCs, added script to correct this.
[*]Elemental Evil Player's Companion (EEPC) - Added missing acid resistance to water genasi and fire resistance to fire genasi.
[*]Princes of the Apocalypse (PoTA) - fixed extra damage tags on magic items for readability
[*]Volo's Guide to Monsters - adjusted Orc Intelligence adjustment to be correct.
[*]Rise of Tiamat (RoT) - fixed several issues with dragon masks - added immunities, legendary resistance, unarmored AC bonus calculation. 
[/list]
```

**Comment by dungeonguru** [comment]
Thanks! I update the forum with the above release notes. I clean downloaded to my PC just fine and it all looks good. 

 Do you have a rundown or link to where/how you create releases? I'm thinking of running a fork for my own home campaign that is pared down, but was wanting something more automated for my players than cut/copy/paste from a dropbox.

**Comment by shadowchemosh** [comment]
I don't actually.  I can point you to the document that HL provides for making the iPad version which is close.  A few small issues is like adding the correct unique id's, versions, and selecting the correct files.  Having all the files named COM_ really helps.

The real fun is when/if you want to delete or change a files name on someones computer.  Its possible but its a pain...

**Comment by shadowchemosh** [comment]
Crap I just remembered I didn't include the new 5e Custom Character Sheet.  Shoot... I have to fix that asap...

**Comment by dungeonguru** [comment]
OK, I'll wait for a few, was just about to post it is ready on the forums.

**Comment by LordMorin** [comment]
And here I already downloaded it. :)

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by shadowchemosh** [comment]
@LordMorin just download it again and let it install over everything.  It will now include dpmcalister custom character sheet.

Details for use are here:
http://forums.wolflair.com/showpost.php?p=256349&postcount=26

@dungeonguru ok all good now!

**Comment by dungeonguru** [comment]
Closing the issue, thanks for the info @shadowchemosh send me a PM on the forums or somewhere on that document to create releases, should be a good bedtime read.

**Comment by Sklore** [comment]
Look at you guys go! :)

Thanks all, I've started a new job so I'm heavily distracted. Really glad to see things progressing without me 👍
