### ISSUE TITLE
XGTE - Classes

### ISSUE THREAD

**Issue by dungeonguru** [Sklore/HL_DD_5e_Colab#768]
Request for XGTE - Classes

The class file has been uploaded. Anyone interested please take some time to look it over. There are two outstanding issues I know about that  I'm trying to figure out but anyone that can think of an inventive way around it let me know. Also, download the file and play around and see if I have major typos or something generates an error. 

1. Divine Soul (Sorcerer) - the cantrip granted by Divine Magic states "if you later replace this spell". The way I coded it was making the spell known, free, etc. to get it to show up. However, there's not a clear way to allow someone to replace it later. I was debating putting a 6th option and label it "Relearned Spell" - this would kick off an eval script that would add 1 to the number of spells known by the sorcerer through the whole table since this appears to be a free spell known overall.

2. Gloom Stalker (Ranger) - Umbral Sight grants darkvision of 60 to heroes without it, if they have it it adds 30 feet to the range. I've tried several things, can't get a hero with darkvision to get +30 feet to work 100% of the time.

**Comment by Sklore** [comment]
You did them all!? Dude you're a beast.

**Comment by CraziFuzzy** [comment]
So what actually still needs done to get this pushed out to a release?

**Comment by dungeonguru** [comment]
I would wait until the spells and racial feats are finished. I saw where LordMorin stated he was working on the Common Magic Items on the forums. I thought someone was working spells, but nobody has tackled the racial feats (although I think if you copied the scripting from the UA articles, that would help). 
 It would really be more beneficial to wait for the entire book to get put in. I would also suggest some folks download the pre-release and test to make sure that something unexpected isn't broken. (Also, still haven't got a fix in for Umbral Sight or Divine Magic, yet).

**Comment by LordMorin** [comment]
I'm just getting my main system back up and running after the main Hard
Drive died. I hope to work on the items this coming week.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by dungeonguru** [comment]
OK, I just merged in my fixes for Sorcerer: Divine Soul (Divine Magic) and Ranger: Gloom Stalker (Umbral Sight). I also uploaded an updated file for ticket #769 - Racial Feats that includes scripting. All of it seems to work, but please download and verify that anything isn't throwing an error.
