### ISSUE TITLE
Release v1.2 - CHANGE FREEZE IN PLACE

### ISSUE THREAD

**Issue by shadowchemosh** [Sklore/HL_DD_5e_Colab#77]
Just an FYI I put out version 1.2.  Same exact files as yesterday but it correctly handles the rename of the .1st file I did.  Opps...

**Comment by Sklore** [comment]
:+1:  thanks mate

**Comment by shadowchemosh** [comment]
Yeah just figured that all out.

**Comment by shadowchemosh** [comment]
So not releasing a 1.2... Sorry for the confusion.  I totally thought I had done a rename of a file and didn't tell the installer.

Then I was like that would have caused LOTS of errors for people.  And double checked.

**Comment by Sklore** [comment]
We should do another release in the near future. There was one spell removed as i thought it was a duplicate that needs to be put back in. But it's really not a big issue. 

I'm working on the missing monsters currently from the MM so perhaps once they are ready.

**Comment by shadowchemosh** [comment]
Whenever you want is fine with me.  I figure you will want allot of small updates at the start. After a bit things should calm down and you can maybe get into a regular release schedule.

**Comment by Sklore** [comment]
I think we need to push 1.2 out given we are starting to get duplicate bug reports. Let us start working on the next set of bugs instead of the current ones ;)

**Comment by grandchefpanda** [comment]
As you wish :-)
But before I would like you to know that I have put a language in the MM monster user file, didn't know where to put it, if we can let it there or if we must move it before release of 1.2

**Comment by shadowchemosh** [comment]
I like keep things separated in different files.  But it will not hurt anything leaving the languages in with the MM races.  Maybe its my OCD but I like things separate. =)

Otherwise getting v1.2 out anytime this should not be a problem for me.

**Comment by Sklore** [comment]
We have made a few new languages now. Would pay to move them to their own file. I'll try source the ones I've done tonight.

**Comment by Sklore** [comment]
*** CHANGE FREEZE ***

Hi Team, 

Please refrain from pushing any further changes until we can push 1.2 to the public. 

Have created Draft Release notes under release 1.2 in preparation. 
@shadowchemosh - can you please update the public release at your convenience. 

Thanks all, a nice list of bug fixes.

**Comment by shadowchemosh** [comment]
Yep I should have no issues getting this out tonight around 9pm CST time or 3:00 AM Thursday, Coordinated Universal Time (UTC). =)

**Comment by Sklore** [comment]
:+1: Thanks mate

**Comment by shadowchemosh** [comment]
Its out.

Here is a HL Forum formatted version of the release notes:

```
[b]v1.2 March 2, 2016[/b]

[b]New Features[/b]
[list]
[*]DUNGEON MASTERS GUIDE (Race) - Eladrin added
[*]DUNGEON MASTERS GUIDE (Race) - Aasimar added
[*]MONSTER MANUAL - 128 Monsters added. Currently heavy Work In Progress (Monsters listed are complete): Beholder; Death Tyrant; Spectator; Needle Blight; Twig Blight; Vine Blight; Pixie; Hook Horror; Kenku; Quaggoth; Myconid Sprout; Myconid Adult; Myconid;Sovereign and Piercer (some bugs needs LW).
[*]TOOL (Gaming Sets) Added Dragonchess Set & Three-Dragon Ante
[*]DEITIES (SCAG) - Added all deities Pantheons from SCAG : Dwarven, Elven, Orc, Halfling and Gnome Pantheon
[*]RACE (DMG) - Added Aasimar race and Eladrin subrace.
[*]SPELLS - The (Not Really) Complete Tome of Spells - 470 new spells (all assigned to classes)
[*]HELPER - Added functionality to make any weapon/ammmo 'Silvered' or magic and Silvered.
[*]ADJUSTMENT - Added "Equipment, Notes" that allows you to append up to 100 characters to a selected piece of gear description text.
[/list] 
[b]Enhancements and Changes[/b]
[list]
[*]BACKGROUNDS (PHB) Changed background special abilities Uniqueness flag to 'No' enabling the special abilities to display on the Backgrounds tab as well as the Specials tab.
[*]RACE (Tiefling) The official Tiefling was unable to link to learn Hellish Rebuke as part of Infernal Legacy as the spell was not included in the SRD. We have therefore created a community copy of Tiefling and linked the spell correctly. Users who have made Tiefling characters previously may need to update their characters to use the new Tiefling 'thing' within Hero Labs. This can be done by simply "re-selecting" the Tiefling race on the "Race" tab after opening up your character.
[*]The (Not Really) Complete Tome of Spells - 470 new spells all assigned to classes. 
[/list]
[b]Bug Fixes[/b]
[list]
[*]BACKGROUNDS (ab5CPosPri, ab5CRetain, ab5CBadRep) These special abilities were created as Background Custom Abilities instead of General Abilities. Changed these in line with everything else which fixed their display issue.
[*]BACKGROUNDS (Clan Crafter) Fixed Tool Proficiency selection. 
[*]BACKGROUNDS (Far Traveller) Why Are You Here options updated. Duplicate entries for '5' resolved. 
[*]BACKGROUNDS (Inheritor) Fixed Tool Prof pick.
[*]BACKGROUNDS (Inheritor) Fixed Inheritance pick.
[*]BACKGROUNDS (Hermit) Fixed Pilgrim roll value to 8.
[*]BACKGROUNDS (SCAG) Correctly assigned Ideals, Bonds, Flaws. 
[*]BACKGROUNDS (SCAG) Far Traveller roll corrected
[*]CLASS (Rogue) - Fixed Arcane Trickster to only allow selection of 2 cantrips instead of 3. 
[*]FEAT (Spell Sniper) - Modified text on Cantrip selection to set pick to 1 cantrip.
[*]FEAT (Medium Armor Master) - Corrected pre-requisite check to correctly check for Medium Armor Proficiency.
[*]FEAT (War Caster) - Now correctly recognizing the Warlock class in the pre-requisite check.
[*]RACE (Obsolete Human Variant) - The original community Human Variant was made obsolete on 24/02/16 with the release of an official Human Variant. ra5CHumVar was made Obsolete but this caused validation errors as the Human still thought a sub-race had to be picked. Have therefore removed 'ra5CHumVar' resolving the validation error.
[*]SPELL (Chromatic Orb) - Removed this from *Hidden, now available to characters again. 
[*]DEITIES (Drow Pantheon) - Things ID of drow deities were changed to follow naming convention.
[/list]
```

**Comment by Sklore** [comment]
:+1:  love your work. Forum post updated.

**Comment by Sklore** [comment]
Tested with a fresh build. Loads with no errors. Closing out in preparation for new bug reports :)
