### ISSUE TITLE
V2.1 Not Found

### ISSUE THREAD

**Issue by ElderKane** [Sklore/HL_DD_5e_Colab#771]
I've been running the 5e Community Pack on my iPad for some time now. As soon as V2.1 was released, whenever I attempt to download it, it just states **"Specified file could not be located. Please notify support@wolflair.com about this problem"**.

Any help with this would be much appreciated!

**Comment by dungeonguru** [comment]
@shadowchemosh is this something specific to the iPad? I don't have an iPad to test with.

**Comment by ElderKane** [comment]
It appears to be, yes. I have  it on my PC and on my iPad, and the PC downloaded the update just fine.

I'm not too savvy with this stuff, and that's doubly true for Apple products, the tablet is just convenient at the table.

I tried deleting and re-adding the update source, but no dice...

**Comment by shadowchemosh** [comment]
I missed spell a word on the updates.xml file.  SORRY!

Its now fixed and I confirmed on my iPad that it is working.  So totally shut down the HL app and restart and you should be good to go.

My bad... =(
