### ISSUE TITLE
Rogue Expertise dropdown only shows Thieves' tools

### ISSUE THREAD

**Issue by SorenVance** [Sklore/HL_DD_5e_Colab#778]
I'm creating a Dark Elf Rogue character.  In the Rogue Class Special Abilities list, there are a total of 4 dropdowns for Experties: 2 @ 1st level, and 2 @ 6th level.  

Expected:
All four drop downs should have a list of available skills from which to choose.

Actual:
The only available option in all 4 dropdowns is "Thieves' tools"

**Comment by dungeonguru** [comment]
Expertise will only show skills that you already have proficiency in. Have you chosen any skills for Rogue or any background yet? 

If I create a 6th level rogue Dark Elf (without doing anything else) my Expertise dropdowns will only show Perception and Thieves' Tools until I pick skills from either a background or from the add more skill proficiencies dialog above where you choose expertise.

**Comment by SorenVance** [comment]
I can find exactly NOTHING in the first 6 tabs of the character generator that allows me to pick skills.

On the skills tab, the only things that are clickable are the question mark icons next to each skill.  There is nothing visable allowing me to select skill proficiencies

**Comment by dungeonguru** [comment]
IF you can't see this on your Rogue tab, can you restart Hero Lab and verify that you have an active license? This is all behavior built in by Lone Wolf, not by the community. 

![rogue-capture](https://user-images.githubusercontent.com/19558655/34123353-3bd61810-e3fd-11e7-9dba-95606ce7ffae.PNG)

**Comment by SorenVance** [comment]
Neither the Ability Score Improvements nor Languages and Proficiences are available. I am certain (and double-checked_ that my license is current and active.

I recreated the character from scratch, and now the Languages and Proficiences section is available.

**Comment by wolfuser3** [comment]
Nope.  I've tried this 4 times.  I've reactivated my license and deleted and restarted this character 4 times.  The only choice under expertise is Thieve's Tools.  The Languages and Proficiencies line circled above simply doesn't appear on the page.

**Comment by LordMorin** [comment]
Just in case, go to:

<CTRL> K > Ability Options and make sure Background Proficiency & Personality Trait Proficiency are unchecked. That might resolve your issues.

**Comment by wolfuser3** [comment]
That did the trick.  Thanks so much.

**Comment by LordMorin** [comment]
It's something that caught me when HL first came out and I've helped many peeps with that aprticular issue since. :)
