### ISSUE TITLE
XGTE - Common Magic Items

### ISSUE THREAD

**Issue by LordMorin** [Sklore/HL_DD_5e_Colab#787]
Here are the Common Magic Items from Xanathar's. Source and tags should be correct. Let me know if there are issues I missed.

What needed scripting? Feats?

[soe_5ePack_XGtE_Magic_Items.zip](https://github.com/Sklore/HL_DD_5e_Colab/files/1616524/soe_5ePack_XGtE_Magic_Items.zip)

**Comment by dungeonguru** [comment]
I don't think any more scripting is required unless something I put in is wrong. Just need to do some quality checks. I uploaded the feats file a day or two ago, and the scripts appear to be working as expected. 

I uploaded your magic items file after I renamed it and merged it into the master - should be good to download a fresh copy if you want for further testing.

**Comment by LordMorin** [comment]
Ok, I thought feats still needed scripting. I'll grab the latest version
from the GIT site and delete my own file. :)

**Comment by dungeonguru** [comment]
I'm going to sneak in the adamantine weapon and adamantine ammunition into this file, not sure where else to put them.

**Comment by LordMorin** [comment]
I thought they were already in the game.

**Comment by dungeonguru** [comment]
Adamantine armor was, couldn't find ammuntion or weapon.
