### ISSUE TITLE
Ray of Sickness spell

### ISSUE THREAD

**Issue by LordMorin** [Sklore/HL_DD_5e_Colab#79]
Ray of Sickness is in the PHB. I noticed it wasn't in the Community Pack when I was creating the Death domain for my campaign.

**Comment by Sklore** [comment]
It's already there under Unique Id: sp5CRaySi

Have tested and confirmed this spell is available to both Wizard and Sorcerer per PHB.

**Comment by LordMorin** [comment]
Not sure how I missed it. Probably something I did which required a restart
or a CTRL-R and I hadn't done it. I found it and added it to my Death
domain. Thx.
