### ISSUE TITLE
XGtE - Racial Feats - Halfling - Second Chance

### ISSUE THREAD

**Issue by LordMorin** [Sklore/HL_DD_5e_Colab#791]
The feat doesn't allow you to select your choice between Dexterity, Constitution or Charisma.

**Comment by LordMorin** [comment]
In addition, the XGtE - Racial Feat - Elf - Elven Accuracy has the same issue. Haven't checked other similar feats yet.

**Comment by dungeonguru** [comment]
Hmm, maybe you downloaded before I merged those in - can you redownload that file and let me know? The versions I show have dropdowns.

**Comment by LordMorin** [comment]
Yep. I downloaded the latest version and the issue was resolved. Closing this issue.
