### ISSUE TITLE
xgte - Rogue Scout Skills

### ISSUE THREAD

**Issue by macbean101** [Sklore/HL_DD_5e_Colab#792]
at 3rd level, when choosing Scout, it automatically adds proficiency in Survival and Nature.  However, if you already have either, it prompts to add another skill.

**Comment by dungeonguru** [comment]
I see the issue, I'll start work on it.

**Comment by dungeonguru** [comment]
OK, I merged a fix in. The way the rule reads seems to be an exception to the granting of a free skill choice if you already had the skill as it is written with a builtin Expertise and "if you don't already have" as opposed to just granting the skills.
