### ISSUE TITLE
Quick-Fingered

### ISSUE THREAD

**Issue by Humorist** [Sklore/HL_DD_5e_Colab#793]
Hello, I was having issues adding this feat to my character and was wondering if I could get some help figuring out why I can't find it. I check the repository and it is in COM_5ePack_UA - Feats for Skills.user, so I don't understand why I would not be able to see it when I am trying to add feats. If I could get some help that would be awesome. Thank you very much! :D

**Comment by dungeonguru** [comment]
If you just copied over the 1 file, you need to copy over "COM_Source_110 - Unearthed Arcana.1st" as well. This file creates the checkboxes you need to have selected in Configure Hero (Ctrl-K). Without the updated COM_Source file you can't see the option to select the Feats for Skills source when you create a hero.

**Comment by Humorist** [comment]
Thank you I figured it out thanks to your comment. Was trying so hard to figure out what was going on.
