### ISSUE TITLE
Spell Attack As Spell Dice Roll on Ipad

### ISSUE THREAD

**Issue by dubugz** [Sklore/HL_DD_5e_Colab#795]
When i add "Spell attack as a spell" on the iPad Pro, it displays as a ranged spell attack and provides the ability to roll the dice.  Unlike my actual weapon attacks it displays Damage: 0  +???(As Spell) roll again.  It does not allow me to add a spell or roll the dice adding +7 for spell attack Nor do i get to Choose Roll.

**Comment by Sklore** [comment]
I can't provide any assistance here sorry as I don't have access to an ipad. What is this?
"Spell attack as a spell"
I'm not familiar with it.

**Comment by dubugz** [comment]
You can add a weapon spell attack  and on the I play tab it displays a spell attack as a spell. Next to the spell attack there is a dice roller but the dice roll is broken.  The dice roll works on regular weapons but not the spell attack

**Comment by dungeonguru** [comment]
The spell attack "weapon" is incomplete and should probably be devalued or retired until something can be done about it. @Sklore (Daplunk) - this thing is found in the PHB - Equipment file. 

It doesn't really work for PC either, as the scripts can't tell what the spellcasting attribute are on multi-classed characters anyway.

**Comment by LordMorin** [comment]
Under Adjustments > Spells there is an Adjustment called Spell Attack Dmg.
This allows you to give a Spell Attack added under weapons a name and a a
damage (ex. 2d10 fire).

To set up spells to do damage under weapons as you'd like would mean
creating a weapon for each damaging spell. Somebody with an iPad, the
scripting knowledge to go, and the time might create them some time but who
knows when.
