### ISSUE TITLE
XGTE - v2.2 Release

### ISSUE THREAD

**Issue by dungeonguru** [Sklore/HL_DD_5e_Colab#797]
Anyone have any issues with releasing what we have over February 5th - 9th?

**Comment by LordMorin** [comment]
Who did the work on the Archtypes for XGtE? The Hexblade ability to use Charisma instead of Strength or Dexterity needs to be tweaked I think.

You can now only switch the ability at the end of a long rest.

There are a couple of othger minor tweaks like this I keep forgetting to post. I'll try to remember them and post them here.

For the most part though I'd say things are good to go.

**Comment by dungeonguru** [comment]
I did the work, most of those were copied/modified from the original work in the UA files where it made sense. I'll tweak the code for Hex Warrior - I can see where adding the usage tracker is needed. I'm still not 100% on how to best code the 2-handed piece of the pact weapon though.

**Comment by dungeonguru** [comment]
OK, just finished uploading a fix that seems to work - I added the 1/long rest information to Hex Warrior and it now has a dropdown menu that requires you to select a weapon from your gear list (like Pact of the Blade does). It allows any weapon in that list that is not two-handed and any two-handed weapon selected by Pact of the Blade if you have that Pact Boon. I read and re-read the ability in the book, and this means that ranged weapons like the blowgun and dart are valid targets for this ability, unlike pact weapon which is expressly for melee weapons only...

Secondarily, I updated the Eldritch Invocation: Improved Pact Weapon. It changes the dropdown on Pact of the Blade to allow for the four ranged weapons granted, as long as you have a copy of one of them in your equipment list (same behaviour as before).

**Comment by LordMorin** [comment]
I was just looking at the scripts as you posted this. You saved me the time. It sounds like you did what my train of thought was leading me too. :)

**Comment by dungeonguru** [comment]
It's merged. My only outstanding thoughts are for exceptions where a Hexblade might want to use their STR or DEX instead (due to multiclassing or magic effects). Since the ability is phrased "you can" and not "you must", I'm debating internally on what to do - it could be that we need to make it Activated as well.

**Comment by LordMorin** [comment]
I'd add a Check box on the Hex Blade ability to 'Use Dex/Str'. The odds are it'll never be used though, but you never know.

**Comment by LordMorin** [comment]
Just installed latest files for Hex Blade. One thing I'd like to see its the ability showing up again on the Inplay tab > Activated abilities. You may have forgotten a check box on the ability. So far it works great otherwise.

**Comment by dungeonguru** [comment]
@Sklore @shadowchemosh 
I think we're at a point where releasing the current pending content makes sense, Everything seems to be running as expected. Here are the release notes for release 2.2.  Everybody else, unless there's a breakfix we should freeze updates for the next few days. 

@LordMorin - the hex blade hex warrior ability is now showing up on the activated abilities, I uploaded my last updates this morning and they are part of the main line now.  Any new issues we'll open fresh tickets. 

### V2.2 Release - 02/02/2017
**NEW RELEASES**
- Xanathar's Guide to Everything - Classes, Spells, Common Magic Items & Racial Feats
- Tales from the Yawning Portal - Monsters & Magic Items
- Unearthed Arcana - Feats for Skills added.
- Unearthed Arcana - That Old Black Magic added. The tiefling race in this source has both abyssal and infernal subraces. The demon conjuration spells were added for you evil sorcerers and wizards. 

**ENHANCEMENTS & CHANGES**
- Sword Coast Adventurer's Guide (SCAG) - Barbarian totems have had their placeholder text replaced and scripts should be working properly now. Players desiring Tree Ghost must select Tree Ghost as their Totem Spirit (1st Totem Warrior Ability) in order for the spell 'Speak with Plants' to replace the 'Speak with Animals' ritual from Spirit Seeker.
- Unearthed Arcana - The Ranger, Revised - The Ranger (2016) variant class' Fighting Styles were stacking with Fighting Styles earned from other classes or features, this has been fixed. The _'broken'_ fighting styles will show up with ' - Depreciated' added to the end of their names. The Depreciated fighting styles have been removed from the choices presented when Fighting Style is selected again, so only Fighting Styles that haven't been earned via another class or feat will show up on the selection dialog. 
- Unearthed Arcana - Gothic Heroes - The revenant race is depreciated. Dragonborn characters gain a Revenant draconic ancestry, which prompts for the original draconic ancestry and modifies the breath weapon appropriately. Many races with subrace options gain an appropriate Revenant subrace option. Finally, Humans and many other PC races were granted a Revenant variant racial trait. Select the '5e Unearthed Arcana - Gothic Heroes' source in Configure Hero (Ctrl-K) to explore the revised options. 

**BUGS**
- Fixed where Aztec Pantheon was hijacking goblinoid gods. Forced goblinoid gods into the Goblin Pantheon as default.
- En5ider 65 - Priests Elemental Power - fixed Fiery Soul for Flames domain 
- Unearthed Arcana - Lore Mastery school fixed where it would double proficiency on all 4 skill mentioned rather than any you were proficient in. 
- Unearthed Arcana - Gothic Heroes - Inquisitive was showing up as selection even when source was was not selected. This is fixed. 
- Homebrew - Softpaw tool proficiency selection now shows up on Race tab correctly.
- Homebrew - Psionics Handbook - Lurk was showing even when the source was not showing, this is corrected.

**Comment by shadowchemosh** [comment]
Thanks for the heads up.  I will try and get to it today.  Will let you know....

**Comment by shadowchemosh** [comment]
Going to start on this in a little bit...

**Comment by dungeonguru** [comment]
KK, make sure you write the date as 2018, unlike me :(

**Comment by shadowchemosh** [comment]
LOL I will do my best! =)

**Comment by shadowchemosh** [comment]
May have a slight delay. I just found that dpmcalister character sheet is out of date.  I am unable to find a newer version than September but I know he had fixes done to it.  I have sent him an email asking for his latest sheet files.

Hopefully he can back to me soon. =)  Will keep going and doing some testing without his sheet for now...

**Comment by shadowchemosh** [comment]
Just got the new fixed sheets... Moving forward again!

**Comment by shadowchemosh** [comment]
Ok v2.2 is out and released. I tested a few installs and it seems good to me.  Will double check on the iPad now.

Below is the forum formatted release notes.

```
[b]v2.2 February 2, 2018[/b]

[b]NEW RELEASES[/b]
[list]
[*]Xanathar's Guide to Everything - Classes, Spells, Common Magic Items & Racial Feats.
[*]Tales from the Yawning Portal - Monsters & Magic Items
[*]Unearthed Arcana - Feats for Skills added.
[*]Unearthed Arcana - That Old Black Magic added. The tiefling race in this source has both abyssal and infernal subraces. The demon conjuration spells were added for you evil sorcerers and wizards.
[/list]
[b]ENHANCEMENTS & CHANGES[/b]
[list]
[*]Sword Coast Adventurer's Guide (SCAG) - Barbarian totems have had their placeholder text replaced and scripts should be working properly now. Players desiring Tree Ghost must select Tree Ghost as their Totem Spirit (1st Totem Warrior Ability) in order for the spell 'Speak with Plants' to replace the 'Speak with Animals' ritual from Spirit Seeker.
[*]Unearthed Arcana - The Ranger, Revised - The Ranger (2016) variant class' Fighting Styles were stacking with Fighting Styles earned from other classes or features, this has been fixed. The _'broken'_ fighting styles will show up with ' - Depreciated' added to the end of their names. The Depreciated fighting styles have been removed from the choices presented when Fighting Style is selected again, so only Fighting Styles that haven't been earned via another class or feat will show up on the selection dialog. 
[*]Unearthed Arcana - Gothic Heroes - The revenant race is depreciated. Dragonborn characters gain a Revenant draconic ancestry, which prompts for the original draconic ancestry and modifies the breath weapon appropriately. Many races with subrace options gain an appropriate Revenant subrace option. Finally, Humans and many other PC races were granted a Revenant variant racial trait. Select the '5e Unearthed Arcana - Gothic Heroes' source in Configure Hero (Ctrl-K) to explore the revised options.
[*]DnD5E.info Custom Output (dpmcalister) - Character sheet fixes.
[/list]
[b]BUGS[/b]
[list]
[*]Fixed where Aztec Pantheon was hijacking goblinoid gods. Forced goblinoid gods into the Goblin Pantheon as default.
[*]En5ider 65 - Priests Elemental Power - fixed Fiery Soul for Flames domain.
[*]Unearthed Arcana - Lore Mastery school fixed where it would double proficiency on all 4 skill mentioned rather than any you were proficient in.
[*]Unearthed Arcana - Gothic Heroes - Inquisitive was showing up as selection even when source was was not selected. This is fixed.
[*]Homebrew - Softpaw tool proficiency selection now shows up on Race tab correctly.
[*]Homebrew - Psionics Handbook - Lurk was showing even when the source was not showing, this is corrected.
[/list]
```

**Comment by dungeonguru** [comment]
Looks good to me. Is iPad looking good?

**Comment by dubugz** [comment]
Noticed that ghost tree, uthgart tribe shows speaks with plants and speak with animals on the iPad, not on the pc... testing on iPad pro but haven't noticed anything else.

**Comment by shadowchemosh** [comment]
Everything is loading fine on the iPad for me.

@dubugz you 100% sure its different on the iPad?  That would be really strange.  Sometimes their is a slight UI difference between iPad and Desktop but not major differences...

**Comment by dubugz** [comment]
There is an extra category for spells on Ipad play tab called spells it shows speak with animals which does not show on pc

**Comment by shadowchemosh** [comment]
I assume you mean the background "Uthgardt Tribe Member" which from the XML does not give any spells at all.  Testing on desktop and iPad no spells get displayed to me.

Can you provide more details? Or the actual .por file?

**Comment by dungeonguru** [comment]
No, there was a fix to the SCAG Totem Warrior choices. When you have SCAG sources active you can choose Tree Ghost as your first Totem ability (Totem Spirit). It grants speak with plants as a ritual only. Not sure why it would be different on the iPad though...

All the ability does is bootstrap speak with plants and removes the speak with animals via:
perform hero.childfound[spSpeaAnim].assign[Helper.Disable]

**Comment by shadowchemosh** [comment]
That would most likely be the issue. You can't "Disable" a spell-like ability or I would be surprised if that would work.  To prevent a spell from being seen in the UI you would need to use Hide.Spell as Helper.Disable is meant to disable "abilities" like race, feat or class Things.

So that would make sense on why the iPad is showing the spell because it says "Show all non-hidden" spells.  It has no understanding of the Disable tags.

You could put in a bug report to LW and see if they will change that behavior because it would be nice if everything understood "Helper.Disable".

This also falls into the "slight" UI differences you have to deal with between iPad and Desktop. =(

**Comment by dungeonguru** [comment]
I'll split that issue off into a new ticket/fix for next release.

**Comment by Sklore** [comment]
Wow well done guys!

**Comment by dungeonguru** [comment]
Closing out ticket, we'll work on anything new coming in in new tickets anyway. Good work all!
