### ISSUE TITLE
Request for Swordmage

### ISSUE THREAD

**Issue by brandonsiville83** [Sklore/HL_DD_5e_Colab#802]
I would like to request that the swordmage class by Juan Marcano of Coqui games be added.  Its one of my favorite classes from 4th edition (really the only new one I liked) and I think that the same can be said of many people.  I have already purchased the file and am sharing it.  Thank you for your time.

[Swordmage_Class.pdf](https://github.com/Sklore/HL_DD_5e_Colab/files/1692099/Swordmage_Class.pdf)

**Comment by dungeonguru** [comment]
Someone in the community will need to reach out to Juan Marcano/Coqui Games and ask permission to recreate the class in Hero Lab for public distribution and ask if it is OK to paraphrase or directly copy the text. Also, given that he's selling the product for $1, I'm not sure he'll be too happy you reposted the pdf for public consumption for free (@brandonsiville83). 

Until we can get the author's answer, this request will have to go on hold.

**Comment by brandonsiville83** [comment]
Oh crap, I wasn't thinking. If possible I will delete the original post
