### ISSUE TITLE
Issue with Guild Merchant Background

### ISSUE THREAD

**Issue by Alastor2018** [Sklore/HL_DD_5e_Colab#803]
For the Guild Merchant variant of the Guild Artisan from PHB, it says that the Guild Merchant can be "proficient with navigator's tools or an additional language" in place of the proficiency with artisan's tools. A Guild Artisan normally gets one language in addition to the artisan's tools. So, based on the variant, a Guild Merchant should have the option to either get (a) navigator's tools and one language, or (b) two languages. However, when selecting Guild Merchant, it automatically grants proficiency with navigator's tools and does not allow you to go for the other option of selecting instead a second language.

**Comment by Sklore** [comment]
I never figured out how to do this.

**Comment by dungeonguru** [comment]
I think what will have to be done is just create a copy of the Guild Merchant and give it a name like "Guild Merchant (Lang. Var.)" and add the language choice while removing the artisan's tools. If necessary you could always add (Nav. Var.) to the original.

**Comment by dungeonguru** [comment]
A new Guild Merchant (Lang. Var.) will appear after the next release. This removes the navigator's tools and adds a 2nd background language choice.
