### ISSUE TITLE
Xanthar's Guide to Everything - Cleric Grave Domain Bug

### ISSUE THREAD

**Issue by frogprogrammer** [Sklore/HL_DD_5e_Colab#804]
The **Grave** Domain for the Cleric class is still showing as adding **Heavy Armor Proficiency**, which it no longer does.

I've corrected mine via the editor, but it still adds the **Heavy Armor Proficiency** at the bottom of the list of abilities.

Just FYI!

**Comment by dungeonguru** [comment]
Are you sure you're using the xanathar's version? I just built a grave domain cleric from scratch and it doesn't show the heavy armor proficiency at all. The UA article version wasn't touched beyond a rename, so it still has the original coding.

**Comment by dungeonguru** [comment]
The Xanathar's version of the grave domain is verified as working correctly with Heavy Armor not showing up. The UA article differs, so that code has not been touched. Closing the ticket.
