### ISSUE TITLE
Warlock eldritch invocations aren't reflected in the UI

### ISSUE THREAD

**Issue by mmroden** [Sklore/HL_DD_5e_Colab#805]
The following Warlock eldritch invocations do not appear in the UI:

-- Lifedrinker.  The additional necrotic damage is not applied to a 12th level hexblade warlock
-- Improved Pact Weapon. The +1 bonuses are no applied to a flame tongue weapon, which does not have +1 bonuses, but rather +2d6 fire damage with activated.  The bonus appears to only be applied to nonmagical weapons.
-- Agonizing Blast.  The bonus damage from charisma is not reflected in the UI.

**Comment by dungeonguru** [comment]
Agonizing Blast and Lifedrinker are abilities that are part of the SRD, which means that Lone Wolf maintain the original code - you can send an e-mail to support@wolflair.com to try and get them to enhance these abilities. The community can try to write replacements with the enhancements, but anything we do can be affected if they make changes later. 

Improved Pact Weapon is failing to apply the bonus to magical weapons, we will work on tweaking the code to grant the bonus to correct the issue.

**Comment by mmroden** [comment]
Thanks for the response, I'll go ping them.

**Comment by TheEnthusiast** [comment]
"In addition, the weapon counts as a magic weapon with a +1 bonus to its attack and damage rolls, unless it is already a magic weapon that you transformed into your pack weapon"

Working as intended to me.

**Comment by dungeonguru** [comment]
That language is left over from the UA article and needs cleaned up. The XGTE text reads that it gains a +1 bonus to attack/damage unless it is a magic weapon that already has a bonus to attack/damage.

**Comment by dungeonguru** [comment]
The fixes for the improved pact weapon are loaded to the repository. They will push out with the next release so weapons like flame tongue longswords will get the +1 bonuses properly for hexblade warlocks or other warlocks with proficiency in those weapons.
