### ISSUE TITLE
Xanthar's Guide to Everything - Cleric Forge Domain Bug 

### ISSUE THREAD

**Issue by LordMorin** [Sklore/HL_DD_5e_Colab#807]
The abilities granted by the 6th level Forge Domain, Soul of the Forge, are showing up at first level. The Soul of the Forge Domain ability probably just needs a level check added to it. This goes for the +1 to heavy armor and to the Fire Resistance granted

**Comment by LordMorin** [comment]
I was right, it was a missing check.

Adding the following line: count:Classes.Cleric >= 6 with a Priority of 2500 to the Domain's Soul of the Forge bootstrapped ability does fix the issue.

**Comment by dungeonguru** [comment]
Actually, the same thing is happening for Saint of Forge and Fire. Since the bootstrap conditional removes it from the list of abilities altogether, I think a better choice is adding a line to each of the scripts like:

     doneif (#levelcount[Cleric] < 6)  

(or 17 for the Saint of Forge and Fire).
