### ISSUE TITLE
Mastermind lvl 3 ability - Master of Intrigue

### ISSUE THREAD

**Issue by Madcap2112** [Sklore/HL_DD_5e_Colab#811]
Master of Intrigue is supposed to give 2 languages, Proficiency in Disguise and Forgery kits, and Dragonchess Proficiency.  It's not giving any of these.

**Comment by dungeonguru** [comment]
I can see where the disguise and forgery kits are not being added, but when I create a fresh 3rd level rogue and select Mastermind, I get prompted for 2 languages under the Languages and Proficiencies section of the Rogue tab and I also get prompted for a tool choice - of which dragonchess is an option. 

(BTW - the ability grants a gaming proficiency, not just dragonchess). 

If those aren't showing up for you can you describe how you built your character or zip the porfolio up and attach it so we can look at it?

**Comment by dungeonguru** [comment]
Fixes have been uploaded to the repository. These fixes will push out to the community when the next release is published.
