### ISSUE TITLE
Xanathar (and Unearthed Acana) The Celestial Warlock Patron problem

### ISSUE THREAD

**Issue by bmanjnk99** [Sklore/HL_DD_5e_Colab#813]
Whenever "The Celestial" patron is added to a 1st level Warlock it incorrectly adds extra hit points equal to the character's Charisma bonus to the character.  It also adds an additional erroneous hit point each additional level of Warlock added to the character.  This same error occurs in both the Xanathar guide version and the original Unearthed Arcana version of the Patron, so it was likely carried over from the original data file. I tried locating the source of extra hit points in the datafiles (using the Hero Lab editor), but could not locate the origin of the problem. For now, I just use a negative hit point adjustment in the character that I have to increase by 1 for every new level, but hope you can find a permanent solution.

**Comment by dungeonguru** [comment]
The issue seems to be with Celestial Resilience. It is adding the temporary hit points granted by short or long rests before reaching 10th level. 

We'll need to add the line:

doneif (field[xTotalLev].value <= 10)

to the front of the script attached to the ability.

**Comment by bmanjnk99** [comment]
Yep. That did the trick.

**Comment by dungeonguru** [comment]
Fixes have been uploaded to the repository. These fixes will push out to the community when the next release is published.
