### ISSUE TITLE
Xanathar's Guide - Way of the Kensei

### ISSUE THREAD

**Issue by rsmit212** [Sklore/HL_DD_5e_Colab#814]
The longsword is not getting the Dex modifier to damage when selected by a Kensei Monk.

**Comment by dungeonguru** [comment]
The other problem that it's creating, that you're probably not seeing yet, is that all martial weapons (aside from shortsword, which is a monk weapon already) are not updating their base damage when it is smaller than Unarmed Strike damage.

**Comment by dungeonguru** [comment]
Played with this a bit and the least intrusive way of fixing is to add the following lines after the weapon proficiency is pushed (see below). Marking any weapons equipped that share the ID of the proficiency as martial arts weapons (tag: Special.MartArts] allows the base feature of the Monk to make these into monk weapons, granting DEX as higher or if the monk's martial arts Unarmed damage score is higher, it also grants the increased damage. 

Script for 3rd level ability (Path of the Kensei):

```
var searchexpr as string
searchexpr = "(" & field[usrChosen1].chosen.tagids[thingid.?,"|"] 
searchexpr &= "|" & field[usrChosen2].chosen.tagids[thingid.?, "|"] & ")"

~ push the martial arts tag to any weapons chosen
foreach pick in hero from BaseWep where searchexpr
  perform eachpick.assign[Special.MartArts]
nexteach
```

Script for 6th and subsequent abilities (Path of the Kensei Weapon):

```
var searchexpr as string
searchexpr = "(" & field[usrChosen1].chosen.tagids[thingid.?,"|"] & ")"

~ push the martial arts tag to any weapons chosen
foreach pick in hero from BaseWep where searchexpr
  perform eachpick.assign[Special.MartArts]
nexteach

```

**Comment by dungeonguru** [comment]
Fixes have been uploaded to the repository. These fixes will push out to the community when the next release is published.
