### ISSUE TITLE
Skill Proficiencies for Curse of Strahd's Haunted One

### ISSUE THREAD

**Issue by corhen** [Sklore/HL_DD_5e_Colab#817]
First of all, thank you so much for your work on the community pack

Second: As of the most recent errata for the Curse of Strahd character, the Haunted One gets two background skill proficiencies, not one.

Source: https://www.sageadvice.eu/tag/errata/ and https://media.wizards.com/2017/dnd/downloads/DDAL_FAQv6-1.pdf

**Comment by dungeonguru** [comment]
Uploaded the fix. This will be in the next release.
