### ISSUE TITLE
Brawny Feat - Encumbrance (with solution)

### ISSUE THREAD

**Issue by critchie1** [Sklore/HL_DD_5e_Colab#818]
The Brawny feat has this as one of it's special features:

> You count as if you were one size larger for the purpose of determining your carrying capacity.

The existing eval script isn't working correctly. It's targeting the wrong field (tEncum), and is running in a phase that is too early. tEncum actually refers to how much weight you are currently carrying. You can verify this by opening up 'Hero Fields', and filter on 'encum' which should give you about 7 different fields. If you take note of the tEncum value and then go add something with weight (such as a block & tacle), you can see that adding weight to your character increases the tEncum value. 

If you look at the Field History and filter by Encum, you can see that all of the encumbrance values are being calculated in Post-Attributes, so the Post-levels phase it's currently operating in won't actually perform the operation as expected.

**Existing Script**
![image](https://user-images.githubusercontent.com/14001616/37655441-511c6824-2c13-11e8-920b-2df018932dba.png)

The solution is to use tEncumMax as the targeted field, and change the phase to 'Final Phase'. This correctly doubles your total carrying capacity max!

**Proposed Solution**
![image](https://user-images.githubusercontent.com/14001616/37655737-1a0918ea-2c14-11e8-996b-4a76c42f243f.png)

**Comment by ehmitchell3** [comment]
Under "..._UA - Feats For Skills.user"
