### ISSUE TITLE
Adding Missing Deities from SCAG

### ISSUE THREAD

**Issue by grandchefpanda** [Sklore/HL_DD_5e_Colab#82]
I'm currently creating the deities pantheons from SCAG : Elven, Dwarven, Orc, Gnomish and Halfling.
Just to be sure:
1) For the Drow pantheon I put the source to player handbook, should I do the same or put them on the SCAG source, some of the gods are in the player handbook ?
2) In SCAG there is the new Arcane domain, I will not put it for now in the Gods domain and wait for the domain to be created.
3) Some of the already created gods from the player handbook have the SCAG the Arcane domain. Don't know how we could add the domain to them later as they are in player handbook source and the domain will will be in SCAG source, but as point 2 the problem is not for now.

**Comment by shadowchemosh** [comment]
You can source mark a Thing to more than one 'Book'.  That way if "either" source is turned on the Thing will be visible to the player.

**Comment by grandchefpanda** [comment]
ok, I'll put them on SCAG and if I can find them on the player handbook in nonhuman deities then I will check player handbook too

**Comment by shadowchemosh** [comment]
Just FYI Sklore is really the "man in charge" and has a good handle of the 5e rules so he may have better ideas. I just like to chime in with information about "HL" and the editor and stuff. =)

**Comment by Sklore** [comment]
@grandchefpanda I've given you Collaborator access so you can pull and push any changes you make. The more content the merrier IMO. Obviously just have to be careful that we only push quality content into the main branch.

**Comment by grandchefpanda** [comment]
First add this in the mecanic "5e Community Mechanic" in "COM_5ePack - Helper Things" file:

    <tag group="DeityCat" tag="5CDwarven" name="Dwarven Pantheon" abbrev="Dwarven"/>
    <tag group="DeityCat" tag="5CElven" name="Elven Pantheon" abbrev="Elven"/>
    <tag group="DeityCat" tag="5CHalfling" name="Halfling Pantheon" abbrev="Halfling"/>
    <tag group="DeityCat" tag="5CGnomish" name="Gnomish Pantheon" abbrev="Gnomish"/>
    <tag group="DeityCat" tag="5COrc" name="Orc Pantheon" abbrev="Orc"/>

**Comment by grandchefpanda** [comment]
Then here the user file with the deities
[COM_5ePack_PHB - Deities More.txt](https://github.com/Sklore/HL_DD_5e_Colab/files/147308/COM_5ePack_PHB.-.Deities.More.txt)

**Comment by grandchefpanda** [comment]
ok I give it a try

**Comment by grandchefpanda** [comment]
I have pushed the change, but it look like it has changed immediately the master branch, I suppose normally it should had done a branch first then a merge from you.

**Comment by grandchefpanda** [comment]
Or is is because there was only one branch, git always confuse me.

**Comment by Sklore** [comment]
Yeah I've done that a few times. Safer to create your own branch and then Merge it in. I generally create a new Branch for every change i submit or group of changes that im submitting at one time.

**Comment by grandchefpanda** [comment]
I'll do that next time.

**Comment by Sklore** [comment]
If your creating a branch to resolve a raised Issue you can use #<issue number> to link the build to the issue. Very handy.

**Comment by Sklore** [comment]
Also when you submit a change to Master can you update the wiki linked below. That way we can update the release documentation prior to each release. 

https://github.com/Sklore/HL_DD_5e_Colab/wiki/3.-Pending-Changes

**Comment by shadowchemosh** [comment]
Just to make sure you know Sklore you can see all the 'updates' that happened after each version to the repository.
https://github.com/Sklore/HL_DD_5e_Colab/compare/v1.1...master

This is why I try and do detailed comments on the commits so that its easy to copy/paste from the above into the Release notes.

Not saying using the wiki is not a good idea just showing a method that sort of "auto" documents all the releases notes. =)

**Comment by Sklore** [comment]
Will you look at that... :+1:  the more i learn about GitHub the more i'm impressed.
