### ISSUE TITLE
Epic Boons - Boon of Quick Casting

### ISSUE THREAD

**Issue by LordMorin** [Sklore/HL_DD_5e_Colab#820]
I went to use this for the first time and discovered that the drop down won't let me select any of my spells. I am a 6th bard/14 Warlock on this character. I was just wondering if anyone else has had an issue with this boon or if its just me.

**Comment by dungeonguru** [comment]
Well, the spell selection is supposed to be level 1 through 3, but the boon logic says that you have to have it memorized. 

Neither Bard nor Warlock memorize spells, they just know them. Probably need to adjust this to be Helper.Known rather than Helper.Memorized.

**Comment by LordMorin** [comment]
That explains it. Thx. I thought one of my own homebrew might be messing things up/ "_
