### ISSUE TITLE
Soul of the Forge

### ISSUE THREAD

**Issue by erogroth** [Sklore/HL_DD_5e_Colab#821]
Soul of the Forge is providing the +1 to AC at any level. The Forge domain seems to have the tag set to restrict it to level 6 but the AC bonus is still being give to level 1 characters. The Ability itself does not show up in the specials column however. Just the benefits can be seen. I verified this by removing the ability from the forge domain and by testing non heavy armor. Both resulted in proper AC. When adding the heavy armor back in at level 1 there was an extra +1 to AC and mousing over the AC shows +1 (other bonus).

**Comment by dungeonguru** [comment]
This has been addressed in another ticket, the next release push will have the fix in it. Both this and the bonuses from Saint of Forge and Fire were firing off early. 

If you know how to replace the files manually, you can download the pending code fixes via the code tab: or directly here https://github.com/Sklore/HL_DD_5e_Colab/archive/master.zip

**Comment by erogroth** [comment]
Cool. Thx for the update!
