### ISSUE TITLE
Volos Guide Error

### ISSUE THREAD

**Issue by erogroth** [Sklore/HL_DD_5e_Colab#823]
When importing monsters from Volo's Guide using the encounter builder I receive an error:
![image](https://user-images.githubusercontent.com/36180957/38969211-f8bf9ff0-4343-11e8-9aca-de2353398094.png)

I have narrowed it down to being related to only the A-K volo's file. L-Z does not generate this error. If I just create a new NPC without using the encounter builder but selecting one of the races I do not receive an error. I am not sure if this has to do with the user file or the stock file but others are able to reproduce the error and it happens on both my desktop and laptop.

EDIT: I will add that if you load the stock file you will see this error listed many times over. Also, "Strip missing sources" gets rid of the error but I assume doesn't resolve the actual problem.

**Comment by dungeonguru** [comment]
After you strip missing sources, are you saving the .stock file? I can recreate the issue, but when I strip the sources and save the modified portfolio the problem goes away.  

I'll upload fixed copies for next patch, but as a workaround, you can save over your local files after you strip out the offending sources.

**Comment by erogroth** [comment]
Yes. Stripping and saving fixes it, but I thought stripping only stops the error from generating. I assumed that the file still has an issue somewhere that is causing it. If stripping actually fixes whatever the cause was then I guess we are all good. Thanks.

**Comment by Fenris447** [comment]
I've uploaded a new version of the A-K stock file with missing sources stripped and can't recreate the error after using it. Closing the issue. Expect it in 2.3 (hopefully coming soon!)
