### ISSUE TITLE
Question: Favored Terrain Manipulation

### ISSUE THREAD

**Issue by Sklore** [Sklore/HL_DD_5e_Colab#825]
Does anyone know how to code this? Favored Terrain is a Quanternary Ability on the Ranger class but I'm not sure how to increase the ability count. 

> Additional Favored Terrain
> At 7th level, you gain an additional favored terrain for Natural Explorer. You gain an additional favored terrain at 11th level.

**Comment by dungeonguru** [comment]
There's a bit of code in Arcane Archer (Xanathar's) that might be similar enough but I'm not sure how to translate the linkage code to hunt for the base Ranger class as opposed to linking to the subclass that the script runs on (post-level 9000).


```
       doneif (tagis[Helper.Disable] <> 0)

       linkage[table].field[cSpec4thNm].text = "Arcane Shots"
       linkage[table].field[cSpec4thSi].text = "Arcane Shot"

       linkage[table].field[cCustQuTot].arrayvalue[2] += 2
       linkage[table].field[cCustQuTot].arrayvalue[6] += 3
       linkage[table].field[cCustQuTot].arrayvalue[9] += 4
       linkage[table].field[cCustQuTot].arrayvalue[14] += 5
       linkage[table].field[cCustQuTot].arrayvalue[17] += 6
```

I think code like

```
hero.findchild[cHelpRgr].field[cCustQuTot].arrayvalue[6].value += 1
hero.findchild[cHelpRgr].field[cCustQuTot].arrayvalue[10].value += 1
```

would add 1 to the values in the array at 7 and 11 (index is level - 1)

**Comment by Sklore** [comment]
Thanks Dungeon! I shall play around with this tonight.

**Comment by dungeonguru** [comment]
I'm closing this off as a ticket, if you need help with something you're working on you can PM me over on the HL forums.
