### ISSUE TITLE
Request for Mprdenkainen's Tome of Foes

### ISSUE THREAD

**Issue by LordMorin** [Sklore/HL_DD_5e_Colab#829]
Any chance of getting a source added from the new supplement Mordenkainen's Tome of Foes. I've created one of my own, but would rather use one consistent with the Community Pack.

**Comment by dungeonguru** [comment]
I put in a new source to appear after Xanathar's Guide and merged the new .1st file into the main branch. You can re-download COM_Source_110 - Sourcebooks.1st and reload HL to see the new source. 

id="**5eMTOFCP**"
