### ISSUE TITLE
Feats:Grappler only one available...

### ISSUE THREAD

**Issue by KyYorel** [Sklore/HL_DD_5e_Colab#83]
I updated yesterday, and now Grappler (and Custom) is the only feat available to select. Using v 7.5b (#604) of HeroLab; 1.1 of D&D 5e Community Pack, and version 1.2 of the D&D 5th Edition SRD. New character, regardless of level have this problem, as well as level 1 variant humans.  Thanks for your work!

**Comment by KyYorel** [comment]
Only 3 backgrounds are available as well: Acolyte, Clan Crafter, and Cloistered Scholar.

**Comment by shadowchemosh** [comment]
See if the steps on the forum
http://forums.wolflair.com/showpost.php?p=224561&postcount=21

In the above post help.

**Comment by KyYorel** [comment]
Thank you so much. Glad it was user error!
