### ISSUE TITLE
Para/Quasi Genasi

### ISSUE THREAD

**Issue by krumthi** [Sklore/HL_DD_5e_Colab#830]
https://www.dandwiki.com/wiki/Para/Quasi_Genasi_(5e_Race)

So I think that things listed here would be aweseome to put into the community pack. I would do it myself, but I am not sure on how to go thru and do it.

**Comment by dungeonguru** [comment]
The problem we've had in the past with supporting content from sites like homebrewery and dndwiki is that the source material has no version controls and there are no mechanisms to track changes made after we put something into the community files. So, if we put this into the community pack, there is no guarantee we can quickly change it to reflect any future updates. 

That said, this should be a fairly easy thing to create, I think the next release is focusing on getting Mordenkainen's material out though, so it might take a while.

**Comment by Fenris447** [comment]
I’m going to close this, since nobody else seems interested in programming homebrew in the near future.
