### ISSUE TITLE
Soldier Background

### ISSUE THREAD

**Issue by KyYorel** [Sklore/HL_DD_5e_Colab#84]
The Soldier background currently allows single choice between Water Vehicles, a playing card set, and a dice set.  The Water Vehicles should be Land Vehicles, and I believe the Soldier gets both a gaming set skill AND has the land vehicle skill ("One type of gaming set, vehicles (land)" on page 140 PHB), not a choice between the two. Thanks for your dedication.

**Comment by Sklore** [comment]
Thanks for reporting this. Will be fixed in the next release.
