### ISSUE TITLE
Scout Subclass for Fighter

### ISSUE THREAD

**Issue by RealityJaysonJ** [Sklore/HL_DD_5e_Colab#845]
Could someone add this subclass to Fighter.  I've tried myself and it is beyond my capabilities.  Here's two links for resource material.

http://engl393-dnd5th.wikia.com/wiki/Fighter#Scout

https://media.wizards.com/2015/downloads/dnd/04_UA_Classics_Revisited.pdf

**Comment by dungeonguru** [comment]
This will probably get added to the next release - I have it uploaded to my branch and will merge in after the Mordenkainen's work gets finished to avoid overwriting anything that is being worked on by the main group.

**Comment by RealityJaysonJ** [comment]
It has been several months now.  Will the next release be out soon?
