### ISSUE TITLE
Stone of Luck

### ISSUE THREAD

**Issue by KyYorel** [Sklore/HL_DD_5e_Colab#85]
The Stone of Luck increases all saving throws by +1, which is correctly done.  However, all the skill checks are also considered ability checks (p. 174 PHB), as is Initiative (p. 177 PHB).  The Stone of Luck should add +1 to these things as well.  Thanks.

**Comment by Sklore** [comment]
The Stone of Luck is not part of the community pack. You can tell this by looking at the name of it which is miStonGood. All community pack things will have '5C' in the name. 

Please raise this issue directly with Lone Wolf.

**Comment by KyYorel** [comment]
Will do, and thanks for helping me identify what comes from where.
