### ISSUE TITLE
Magic Initiate Spell-Submenu Functionaltiy

### ISSUE THREAD

**Issue by RyanFurnas** [Sklore/HL_DD_5e_Colab#850]
Hello, my name is Ryan and I work with the Support team at LWD,  this is a forwarded and verified report for a BUG which applied to the 5th Ed D&D Community Pack. 

The impacted Source File it applies to is 5e Players Handbook

When using the Magic Initiate Feat to gain access to the Find Familiar Spell does not create the Button used to create the Familiar as it normally does with the Wizard Spell Tab.

Add Feat > Magic Initiate > Choose Wizard Class

I imagine there may be other spells which create sub-menus to add cohorts to the portfolio as well, but this is the first report I could find in search history on the topic. When this spell is normally added for a Wizard

Attached is a copy of a portfolio exhibiting this behavior
[SampleInitFamiliar.zip](https://github.com/Sklore/HL_DD_5e_Colab/files/2128444/SampleInitFamiliar.zip)

-- 
Ryan Furnas
Lone Wolf Development Support - support@wolflair.com
http://www.wolflair.com

**Comment by LordMorin** [comment]
You can do what I do . . . 

Go to the Adjustments tab. At the bottom add a Familiar and select the class for it. 

I'm not sure if we can do it any other way due to coding issues, though I may be wrong about that.

**Comment by RyanFurnas** [comment]
Ok, thanks for the workaround, I'll let the user know!

**Comment by dungeonguru** [comment]
I'll see if I can't figure something out. The problem is that the feats can be chosen without having a class chosen on the character to hook it too - the add familiar adjustment adds the CompAvail.Familiar tag to a class the character already has which then enables the link on either the class or class spells tab. 

This affects both Magic Initiate and Ritual Caster.

**Comment by LordMorin** [comment]
I can see 2 possible options:

1) Cyheck to see if the character has spellcasting capability . . .
2) If the44 character has no spell casting capability give it something like that of an Eldritch Knight or Arcane Trickster, or the Magical Initiate feat itself. The Ritual Master feat would have a similar issue.

**Comment by dungeonguru** [comment]
I may have a solution to this - I put the following in a script on the Feat for Magic Initiative. I am currently playing with timing but I think it has to run after the 1st script on the configurable runs (after Final/50000).

Running as script on Magic Initiative at Final/51000:

```
foreach pick in hero from BaseSpell where "CfgSpell.cfg5CMagIn"
~ loop through all the spells added by the configurable for Magic Initiate
     if (eachpick.tagis[thingid.spFindFami] <> 0) then
     ~ if one of those spells is Find Familiar then 
           foreach pick in hero from Class where "Helper.FirstLevel"
           ~ loop through the class helpers until we find the one chosen at first level
           ~ assign it this tag, which grants the Add a Familiar link on the correct page
                perform eachpick.assign[CompAvail.Familiar]
           nexteach
     endif
nexteach
```

I put an expr-reqs on the feat that looks for tagcount[FirstClass.?] <> 0 or it says you can't select the feat without a class chosen. 

I'm going to test it for a while before I try to update the community files for this or Ritual Caster.

**Comment by dungeonguru** [comment]
Updated the feats Magic Initiate and Ritual Caster with the scripting. The Add a Familiar link will appear either on the Spell tab or on the Class tab depending on the 1st class that was chosen - classes that gain spells will have it on the Spells tab, classes that don't have spells have it show up on the class tab - this is similar to how the Adjustment works. 

The updated feats will appear in the next community update.
