### ISSUE TITLE
Unearthed Arcana – D&D Giant Soul Sorcerer

### ISSUE THREAD

**Issue by LordMorin** [Sklore/HL_DD_5e_Colab#851]
https://media.wizards.com/2018/dnd/downloads/UA_GiantSoul.pdf

Could I please get a Source added for this item from the Unearth Arcana please?

Once it's there, I'll add it to the Community Pack.

**Comment by Sklore** [comment]
Edit this: COM_Source_110 - Unearthed Arcana.1st

Add this:
  <source
    id="p5e<Name>CP"
    name="5e Unearthed Arcana - <Name>"
    selectable="yes"
    parent="p5eUneArc"
    sortorder="20"
    description="5e Unearthed Arcana content - <Name>. Use is allowed for gaming groups only.">
  </source>

**Comment by LordMorin** [comment]
kk, thx. I just remember something about .1st files being special and didn't want to mess it up.

**Comment by Sklore** [comment]
Really all they do is tell the program how to add the check box and what order to add it in. Can't really do any damage with them. One of those things that once you do once you will be confident to do again.
