### ISSUE TITLE
Encumberance with Firbolg + Barbarian

### ISSUE THREAD

**Issue by RyanFurnas** [Sklore/HL_DD_5e_Colab#852]
I have found out that if you create a

I received a report in our support inbox. In the process of investigating it I have seen it is in your domain

"Firbolg
Barbarian
Totem Warrior (Bear)

the Weight Limits are not correctly calculated.

The carry capacity should be that of a large creature (Firbolg, Powerfull
build)
and 2x because of Lvl 6 Bear Totem."

**Comment by dungeonguru** [comment]
This is the Aspect of the Bear ability, we need to change the script to run post-attribute and add the following lines:

    herofield[tEncumLgt].value = herofield[tEncumLgt].value * 2
    herofield[tEncumHvy].value = herofield[tEncumHvy].value * 2
    herofield[tEncumMax].value = herofield[tEncumMax].value * 2

This was due to the way Encum fields were calculated, it should get fixed in the next release of community files.

**Comment by TheEnthusiast** [comment]
Same applies to the Brawny feat from UA Skill Feats.

-------- Mensagem Original --------
De:RyanFurnas <notifications@github.com>
Enviado em:Mon, 25 Jun 2018 14:35:44 -0300
Para:Sklore/HL_DD_5e_Colab <HL_DD_5e_Colab@noreply.github.com>
Cc:Subscribed <subscribed@noreply.github.com>
Assunto:[Sklore/HL_DD_5e_Colab] Encumberance with Firbolg + Barbarian (#852)

**Comment by dungeonguru** [comment]
I fixed the UA article too, will be out in next release.

**Comment by Rasczak76** [comment]
This is still not fixed in mine. Carry weight is still not calculating correctly.
