### ISSUE TITLE
Shillelagh should have a selectable entry on the 'In Play' tab

### ISSUE THREAD

**Issue by binnsr** [Sklore/HL_DD_5e_Colab#853]
Shillelagh should have a clickable entry on the 'In Play' tab to enable attack/damage with Wisdom and also reflect the increased damage die for quarterstaves

**Comment by LordMorin** [comment]
One of these days, I have to re-organize my personal set of Adjustments. I created them for Shilleigh, Mage Armor, Shield, Shield of Faith and others. I'll have to re-tag them to conform with the Community Pack and see if I can have a Source added for whatever stuff I add or what source I should use for them.

In the case of my Adjustments though, they are handled through the Adjustments tab.

**Comment by dungeonguru** [comment]
I'm going to close this out, we have an open request #806 to work on getting Pathfinder like adjustments to add these functions in already. There is no ETA yet on spell adjustments coming to the community files.
