### ISSUE TITLE
Encouter Builder no longer works 

### ISSUE THREAD

**Issue by erogroth** [Sklore/HL_DD_5e_Colab#854]
Hero Lab was updated today to version 8.6 and now I am unable to use the encounter builder. When selecting a creature from the encounter builder to add to a portfolio the creature is not added. If I try to open HL from realm works to insert a portfolio I get an error message: "Unexpected internal error saving file".

**Comment by dungeonguru** [comment]
I think a majority of the encounter builder errors were taken care of with the last patch. Closing this one for now.
