### ISSUE TITLE
Wayfarer's Guide to Eberron

### ISSUE THREAD

**Issue by LordMorin** [Sklore/HL_DD_5e_Colab#858]
Anyone know if we can go ahead and add this to Hero Lab? If so I'll get a start on it. Again, I'll do races, subraces, backgrounds, etc. first.

I've already started it for my own use, but I am keeping it fully compliant with the Community Pack in case.

**Comment by dungeonguru** [comment]
As I understood it, the pdf being offered is the public playtest, and is "a living document" meaning a moving target to keep up to date until the final version that should arrive maybe next year? If you start working it, you'll want to create a new category for DMSGUILD products or maybe put it under Unearthed Arcana? Not sure how to categorize it, but I would think finishing MToF and getting part of this out as soon as we can might help.

**Comment by LordMorin** [comment]
I agree concerning MToF's, however my players are into Eberron, so I need to add the basics to HL for them. I figure if I am going to do it I may as well do it for the community pack at the same time.

Because WGtE costs $$$, I wasn't sure how I should treat it. Also, should I invoke the 10% rule on the text involved?

I'd already put the source under the other 'Official' source books, but I'll move it under DM's Guild.

If permitted, I'll create a new branch for this topic.

**Comment by Sklore** [comment]
This should be treated like any other official content but I share Dungeonguru's concerns in that I expect this content to change between now and the official launch.

**Comment by LordMorin** [comment]
Started uploading WGtE files.

To-date:
- COM_5ePack_WGtE - Backgrounds
- COM_5ePack_WGtE - Dieties
- COM_5ePack_WGtE - Magic_Items (still need to complete)
- COM_5ePack_WGtE - Races
  - added Mark of Detect & Mark of Storms (half-elf)

**Comment by LordMorin** [comment]
COM_5ePack_WGtE - Backgrounds
- updated Sources
    COM_5ePack_WGtE - Dieties
- updated Sources
    COM_5ePack_WGtE - Equipment
- updated Sources
    COM_5ePack_WGtE - Magic_Items
- (still need to complete)
- updated Sources
    COM_5ePack_WGtE - Races
- updated Sources
- added Valenar & Aereni Elves
- Note: have to added high elf and wood elf variants of both races. My bad.

**Comment by LordMorin** [comment]
If anyone uses this, please let me know if you get any errors please.

**Comment by LordMorin** [comment]
CharlieLuce:

Only getting around to this now. How did you go about creating what you have done? Did you take my file and upgrade it? Or did you add to my work?

**Comment by CharlieLuce** [comment]
LordMorin: We added the rest of the Dragonmarks to your existing file since you had the basic structure for the WGtE material already in place. I don't think we changed any of your Dragonmark work except maybe a little cosmetically (like adding (Eberron) to the Race name for the Eberron Half-Elf).

**Comment by LordMorin** [comment]
Ok, thanks for the info. I'll go over it then integrate it into GIT. Post the names of the contributers here and I'll add the names to the internal credits on the file if you haven't already.

**Comment by CharlieLuce** [comment]
It's Charlie & Niccole Luce.

**Comment by Fenris447** [comment]
Closing this, as it's covered under #926 (Rising from the Last War)
