### ISSUE TITLE
DnD 5e - Custom Output - No cantrips shown for cleric

### ISSUE THREAD

**Issue by thermodyn** [Sklore/HL_DD_5e_Colab#868]
Thank you for your work with this.  I would like to use this with my party - they are all new to the game so I think this format is a little easier for them.

I have noticed something peculiar though - if you create a cleric and save the output - the cantrips are not shown in the spell book.

If I create a warlock they are so it looks like something that is particular to the cleric and the template.

I can overcome this by printing the normal spell book from Herolab but it's a complication I would like to avoid.

I have put some samples here:
https://www.dropbox.com/s/dj8z0s0ssh16cwv/sheets.zip?dl=0

If you unzip and look at the cleric (Rhys) the cantrips are not shown in the spellbook.  I also included the PDF with the standard Herolab output.

**Comment by dpmcalister** [comment]
Thanks. I've made amendments to the files. I can't upload directly to the GitHub so I've uploaded v1.3 here. If someone could move it across to the main repo I'd be grateful. If you're on a Windows 10 PC you need to extract the folder to C:\ProgramData\Hero Lab\customoutput\5e. The dnd5einfo_5e will already exist so you're just copying the files over the existing ones. You may wish to back up the existing files first but you shouldn't need to.

[dnd5einfo_5e.zip](https://github.com/Sklore/HL_DD_5e_Colab/files/2280980/dnd5einfo_5e.zip)

**Comment by thermodyn** [comment]
Hello - I just noticed that while the cantrips do show in the spell list now - they are not included in the spell book for clerics. Please see this file as an example.

https://www.dropbox.com/s/ynd9r6zgv6roygd/Rhys.pdf?dl=0

**Comment by dpmcalister** [comment]
Sorry about that. Missed the obvious when fixing the original issue. v1.4 attached now. If you install it as per the instructions above.

[dnd5einfo_5e.zip](https://github.com/Sklore/HL_DD_5e_Colab/files/2323689/dnd5einfo_5e.zip)

**Comment by thermodyn** [comment]
Superb - thanks!
