### ISSUE TITLE
XGTE Spells marked as not available for AL characters

### ISSUE THREAD

**Issue by dungeonguru** [Sklore/HL_DD_5e_Colab#869]
Majority of the spells for XGTE have somehow been marked as not valid for AL, Issue brought up on this thread: 
http://forums.wolflair.com/showthread.php?t=61040

**Comment by Fenris447** [comment]
I’m going to take a look and probably do this some Sunday afternoon when I have time. Is it literally as easy as unchecking the box? 

Also, I don’t think I’m able to assign issues to myself on here. Not the end of the world, but could be helpful going forward.

**Comment by Fenris447** [comment]
Fixed. Closing this out.
