### ISSUE TITLE
Dungeon Master's Guide

### ISSUE THREAD

**Issue by LordMorin** [Sklore/HL_DD_5e_Colab#87]
**STATUS:** In Progress

**COMPLETE**
* Rod of the Pact Keeper
* Staff of the Adder
* Sword of Answering
* Sword of Vengeance
* Tentacle Rod
* Tome of the Stilled Tongue
* Instruments of the Bard x7
* Efreeti Chain - Scripting
* Classes > Scripting - Supernatural Resistance. (gains resistance to bludgeoning, piercing, and slashing damage from nonmagical weapons.)
* Classes > Scripting - Aura of Hate (bonus to melee weapon damage rolls equal to the paladin's Cha mod (min +1)

Blackrazor
Moonblade
Wave

**OUT-STANDING**

**ARTIFACTS**
Axe of the Dwarvish Lords
Book of Exalted Deeds
Book of Vile Darkness
Eye and Hand of Vecna
Orb of Dragonkind
Sword of Kas
Wand of Orcus

**Comment by grandchefpanda** [comment]
I'll give it a try

**Comment by grandchefpanda** [comment]
Eladrin Done

**Comment by grandchefpanda** [comment]
Aasimar Done and both merged into master

**Comment by grandchefpanda** [comment]
#104

**Comment by DarkHayZe** [comment]
Dont forget Paladin: Oath Breaker

**Comment by grandchefpanda** [comment]
On Hold until the monsters are finished

**Comment by Sklore** [comment]
Have added Oathbreaker and Death Domain. 

Death Domain requires further scripting under #164 

Oathbreaker needs scripting on Aura of Hate and Supernatural Resistance.

**Comment by xdy** [comment]
I've added most missing magic items. (Ran out of steam towards the end. :) Some need scripting, left a todo in those.

**Comment by xdy** [comment]
Just realized that Alchemy Jug was missing, added that with #333

**Comment by Sklore** [comment]
Can someone check my work here and advise if the code elements are acceptable. It's been a while :8ball:

**Comment by Sklore** [comment]
I have absolutely no idea if the Artifacts are even possible to do. All have really random effects.

**Comment by Sklore** [comment]
Closing. I see no way to implement artifacts at this time and no one has requested them.
