### ISSUE TITLE
Various unarmed attacks

### ISSUE THREAD

**Issue by DarkHayZe** [Sklore/HL_DD_5e_Colab#871]
I haven't been editing in a while. But I wanted to mention...

Any unarmed type attacks you create need to have a few extra tags. 

EasyWeapon.wUnarmed
IsWeapon.wUnarmed
WepFocus.wUnarmed

DamageOpt.aDEX
MelAttOpt.aDEX

I believe these are all of them, but without these, the attack will not gain benefit from the Monk's unarmed attack modifiers. The last two are what allows you to use DEX instead of STR for an attack's damage and attack rolls.

**Comment by dungeonguru** [comment]
I pulled the Martial Arts code from the Monk ability to clarify this.

You don't have to put the aDEX modifiers on the natural attacks (although many creatures use the higher of STR or DEX, NOT ALL DO). You just need the one of the below things from the search expression in the Martial Arts special ability from the monk. The Martial Arts special ability adds the aDEX modifiers automatically to anything that has the following:

`searchexpr = "IsWeapon.wUnarmed | IsWeapon.wShortswor | Special.MartArts | (wCategory.Melee & wProfReq.Simple & !wProperty.TwoHanded & !wProperty.Heavy)`

So it needs just to have **one** of the 4 conditions:

1. IsWeapon.wUnarmed
       is the Unarmed natural attack
2. IsWeapon.wShortswor
       is a shortsword
3. Special.MartArts
       has the Special.MartArts tag
4. (wCategory.Melee & wProfReq.Simple & !wProperty.TwoHanded & !wProperty.Heavy)

The 4th condition means it has to have the wCategory.Melee and wProfReq.Simple tags, but CAN'T have the wProperty.TwoHanded and wProperty.Heavy tags. Or put in English, it just needs to be a simple melee weapon that does not have the two-handed or heavy  properties. 

If one of those 4 are true about the attack, the Martial Arts ability does the following:
```
        perform eachpick.assign[MelAttOpt.aDEX]
        perform eachpick.assign[DamageOpt.aDEX]
```

It also does some manipulations of the dice number and size based on monk level, but not going to go into that.

**Comment by DarkHayZe** [comment]
Hmm... Interesting, I don't know why it wasn't working for me before. But this definitely worked. Thank you.
