### ISSUE TITLE
Forwarding this on from someone else: XML output

### ISSUE THREAD

**Issue by ehmitchell3** [Sklore/HL_DD_5e_Colab#873]
Hey all,

Life's sucked recently, and I'm slightly back. I wanted to forward this from someone on the Fantasy Grounds College Discord group to see if this is something we can edit, or if this has to go through LWD.

The guy writing it's github is BoomerET.

Thanks!
-Cast
-----------------------------

When saving custom output (Generate XML file), all other races have a 'specsource' node as well as a sourcetext attribute. 

This is missing from dragonborn. 

For example: Dwarven Resilience: 
<special name="Dwarven Resilience" shortname="Dwarven Resilience" sourcetext="Dwarf"> 
     <description>You have advantage on saving throws against poison, and you have resistance against poison damage.</description> 
     <specsource>Dwarf</specsource>
</special> 

The sourcetext attribute, and specsource node are missing from all Dragonborn traits: 

<special name="Damage Resistance (Acid)" shortname="Damage Resistance"> 
     <description>You have resistance to the damage type associated with >your draconic ancestry. 
     </description> 
</special>

**Comment by dungeonguru** [comment]
While I know that we can extend the tag SpecSourc.raDragonbor to the two abilities (Breath Weapon & Resistance), I'm not sure how to tackle the sourcetext portion. I'm thinking this might be an issue with how these abilities are bootstrapped on the Racial Custom Ability as opposed to being added at the base race or subrace things. 

I would suggest opening a ticket with LW regardless as the Dragonborn race and associated draconic ancestries, come from LW and not from the community. They might be able to fix the issue going forward.

**Comment by Fenris447** [comment]
Closing since it’s a LW issue.
