### ISSUE TITLE
Cleric Order Domain

### ISSUE THREAD

**Issue by dubugz** [Sklore/HL_DD_5e_Colab#875]
Is there any plan to add an Order Domain Cleric to the community pack

**Comment by Fenris447** [comment]
Yes! I’m planning to tackle it as part of GGtR.

**Comment by Fenris447** [comment]
Done. It'll be in my next release of the GGTR file.

**Comment by LordMorin** [comment]
Have you uploaded a newer version of your GGTR file? I'm still playing around with the original one you posted. The one with no Sources.

**Comment by Fenris447** [comment]
Not yet. I want to finish the vedalken and Circle of Spores before I put it up. Should be soon, but I also have my next session to prep and that’s gonna take up my free time this week. I have 9 minis to paint >.<

**Comment by LordMorin** [comment]
I know that feeling. A fair chuck of my focusable time these days is addign stuff for mt Eberron campaign and a bit for my Room mates campaign (the other DM) :)
