### ISSUE TITLE
Community Pack

### ISSUE THREAD

**Issue by Tomiii22** [Sklore/HL_DD_5e_Colab#877]
Hi,

i cant download the community pack. When i try it it just Load but dont start the Download.

Can someone help me with that problem.

**Comment by Sklore** [comment]
What are you running Hero Lab on?

**Comment by Tomiii22** [comment]
iPad

**Comment by Sklore** [comment]
I think I read in the forums that there was an issue introduced with the IPad. I don't know much about it though sorry as I don't own an IPad. Is the issue still occurring?
