### ISSUE TITLE
request for additional content

### ISSUE THREAD

**Issue by kcook2674** [Sklore/HL_DD_5e_Colab#880]
I was hoping the following content could be added into the 5e community pack for hero lab! demon hunter is built as a class all its own and I think it has plenty of capable uses!
[demon hunter player guide.pdf](https://github.com/Sklore/HL_DD_5e_Colab/files/2678225/demon.hunter.player.guide.pdf)

**Comment by Sklore** [comment]
Sorry but we are struggling to keep up with official content and won't be adding 3PP content moving forward. Too much effort required to maintain it given the low number of people who use it.
