### ISSUE TITLE
Guildmaster's Guide to Ravnica Source

### ISSUE THREAD

**Issue by Fenris447** [Sklore/HL_DD_5e_Colab#881]
Can we get an official GGtR source added to the source list? I'm making an attempt at the races and would like to align it to the community pack.

**Comment by Fenris447** [comment]
Also, since the Goblin stats are the same as those in Volo's, would we just change the source on that copy of the Goblin to also check off this GGtR source?

**Comment by LordMorin** [comment]
I think I've added sources properly for Unearthed Arcana's Artificer (2019), Guildmaster's Guide to Ravnica, and Wayfinder's Guide to Eberron . As suggested by dungeonguru and RavenX, I also attempted to rename the previous UA Artificer to Unearthed Arcana's Artificer (2018).

Not sure if it went through or not. I did the work so in the Desktop app.

Once I've added my Artificer files (figured out how to), I'll also try adding my updated WGtE files . . .

**Comment by LordMorin** [comment]
A Source for Ravnica should now be part of the Community Pack on GIT. I also added Sources for Wayfinder's Guide to Eberron and Unearthed Arcana - Artificer (2019). Please let me know if things actually worked out. I am just learning to use GIT and am unsure of myself.

**Comment by Fenris447** [comment]
Great stuff! The Ravnica file works perfectly. Did you update your WGTE files in the master branch? I'm seeing Wayfarer's Guide (the older source, I think) **and** Wayfinder's Guide (newer) in my Configure Hero list. I can only use the content if I select Wayfarer's.

**Comment by LordMorin** [comment]
I've been focusing on the UA - Artificer when I can focus. I have to redo the sources for what I have for WGtE then I'll upload that since I seem to have figured out the basics of how to do so. I just have to finish the Artificer first.
