### ISSUE TITLE
How do I use?

### ISSUE THREAD

**Issue by Luirru** [Sklore/HL_DD_5e_Colab#882]
Sorry I am a complete scrub but I have no idea of how to download these files and then import them into Hero Lab. Is there a video or document I can learn from to help me with this?

**Comment by dungeonguru** [comment]
To get and use the "in-development" files you need to go to the tab marked <> Code. There will be a button on it to clone or download. When you click the button, choose the Download ZIP option. 

Once it finished downloading, you can open/extract the zip. In order for HL to open the files you need to extract or copy the extracted files and folders to your HL 5e data folder. On the PC (Windows 10) this is C:\ProgramData\Hero Lab\data\5e.  You will need to let it overwrite the current community files. 

I don't know about Mac or iPad, there are a couple of posts you can search for over on the forums though.

**Comment by Luirru** [comment]
Awesome, thank you. Is there a master file or do I need to do this for every single piece I want?
