### ISSUE TITLE
Adamantine ammunition

### ISSUE THREAD

**Issue by NairbPeak** [Sklore/HL_DD_5e_Colab#886]
When adding Adamantine ammunition it shows up as Silver instead.
And as a side note. Why is ammunition flagged with an error when you add it on the weapons tab? Looking at the Validation errors it says "Silver Arrows: Click the Edit button and pick the weapon to use for this item."
Clicking on the edit button just brings up the Custom Item Name box.

**Comment by Fenris447** [comment]
I can replicate both of these. I need to confirm, but I think this stuff is part of the SRD. It needs to be logged as an error with LWD.

**Comment by Fenris447** [comment]
I submitted a bug report for this to LWD. Closing for now, since we can’t fix on our end.
