### ISSUE TITLE
Long Rest Breaks Displayed Hit Dice

### ISSUE THREAD

**Issue by tjruppel** [Sklore/HL_DD_5e_Colab#887]
Upon pressing "long rest" for an L5 Cleric set to be AL compliant, the displayed "5d8" now displays "55d8" and if done again, it displays "555d8" indicating that the value is not replaced in its register but appended to the value of the register that provides the value to display in that field. 
![error](https://user-images.githubusercontent.com/47327844/52219788-54c02100-286b-11e9-85b4-943469f48c42.jpg)

**Comment by Fenris447** [comment]
I tried replicating this and couldn’t. Can you provide more detail? I made an AL complaint cleric.

**Comment by tjruppel** [comment]
The problem stopped happening two updates ago.

Thanks,
Tom
