### ISSUE TITLE
Deep Gnome Gone

### ISSUE THREAD

**Issue by sirklavis** [Sklore/HL_DD_5e_Colab#890]
I've recently important the Community Pack. I have every source selected and there is no Deep Gnome. I also tried the Main book and the Sword Coast book and still no Deep Gnome. 

Any idea what's up?

**Comment by Fenris447** [comment]
It shows up for me with MToF, SCAG, and EEPC.

**Comment by LordMorin** [comment]
All three of those source have the same version. Selecting any of those sources should allow the Deep Gnome (Svirfneblin) to appear.
