### ISSUE TITLE
Issues with Weapon Master and UA feat options

### ISSUE THREAD

**Issue by AussieHelaman** [Sklore/HL_DD_5e_Colab#891]
If the community pack alone is used the wEapon master gets 3 Maneuvers and all options are available.

If you then select UA feats or UA skill feats, only 2 Maneuvers show and there are missing Maneuver options.

**Comment by AussieHelaman** [comment]
Here's the link to the LW forums... 

https://forums.wolflair.com/showthread.php?t=62201

**Comment by Fenris447** [comment]
I can’t reproduce this error. When I select the Battle Master, I have the same number and selection of maneuvers available to me, regardless of whether I have selected UA-Feats, UA-Feats for Skills, neither, or both. If you can upload the .por where you’re seeing this problem, that would help.

I’ll close the issue for now, and re-open if/when you upload
