### ISSUE TITLE
Necklace of Prayer Beads

### ISSUE THREAD

**Issue by Proffitt** [Sklore/HL_DD_5e_Colab#893]
The implementation for the [Necklace of Prayer Beads](https://roll20.net/compendium/dnd5e/Necklace%20of%20Prayer%20Beads#content) is broken. It isn't a "charges" item, for starters. It's probably complicated enough that you'll need to add "Prayer Bead" as an item where you select the spells and have that item enable or disable based on the attunement of a replacement miNeckPray. So we'll need two Wondrous Items with some scripting to link them.

I can probably figure out the programming and put together a pull request. But I'm hesitant because I don't want to step on any toes or anything. I mean, I can do it in my own .user file but I'd like to submit back here if/when I do so. So where in the file structure would this best belong? I couldn't figure out an obvious file to add it to and I'm reluctant to create a new one. Guidance?

Thanks,
Jacob

**Comment by LordMorin** [comment]
Under Usage Period, just add a new tag called " beads"?

**Comment by Proffitt** [comment]
I'd prefer something that'd track the 1/day spell addition on an individual basis. Which is why a bead item makes sense to me (which can be used to select the associated spell).

**Comment by LordMorin** [comment]
Most bead items, like necklace of fireball, don't get beads back after they are used/ Not sure about necklace of prayer beads.

**Comment by Proffitt** [comment]
"Each bead contains a spell that you can cast from it as a Bonus Action (using your spell save DC if a save is necessary). Once a magic bead's spell is cast, that bead can't be used again until the next dawn."

**Comment by Fenris447** [comment]
The issue here is how variable the thing is.

**Comment by Fenris447** [comment]
I've created a new version of this item. It will be in Release 3.0 and will automatically replace the existing version. If you want it now, grab [the file](https://github.com/Sklore/HL_DD_5e_Colab/blob/fenris447-ongoing-updates/COM_5ePack_DMG%20-%20Equipment.user) and replace your existing copy of that file with this. Enjoy!
