### ISSUE TITLE
Unearthed Arcana - Artificer (2019)

### ISSUE THREAD

**Issue by LordMorin** [Sklore/HL_DD_5e_Colab#894]
- Added 'COM_5ePack_UA - Artificer (2019).user'

This should contain the complete pdf for the new Artificer

**Comment by LordMorin** [comment]
Ok. I have the GITHub desktop app installed. 

I downloaded and installed a copy of the current branch. On the branch on my computer, I added the Sources I mentioned above. 

I copied the updated Source files over to my main HeroLab data path, restarted HeroLab, then proceeded to update my Source references for the UN Artificer (2019). It tested fine. 

I copied mu updated US Artificer file over to my local GITHub branch folder and can see it show up under Changes.

But for the life of me, I can't figure out how to upload them to GITHub for Merging . . .

HELP please. :)

**Comment by LordMorin** [comment]
Down with the flue. The video card in my main system died. I have a replacement coming but it won't arrive until Wednesday . . .

Just not my week . . .

**Comment by LordMorin** [comment]
Ok, I've recreated my Branch on my PC now that it is back up andf running. I have updated Sources for Ravnica, WGtE, and UA - Artificer (2019). Now to see if I can get it to update/upload . . .

**Comment by LordMorin** [comment]
Added 'COM_5ePack_UA - Artificer (2019).user'; hopefully for real this time.
- added new UA - Artificer (2019)
- added Sublasses (Alchemist & Artillerist
- added spells
- added several Adjustments to make it easier for non-Artificer's to add Artificer created items.

**Comment by LordMorin** [comment]
It should be noted, at this time, it is not possible for a 1/2 caster to have spells or cantrips at 1st level. Until HeroLab resolves this issue, when you create a new Artificer, you have to force your cantrip and spells onto the character. This is a hard coded issue that I cannot get around.

Once you get to 2nd level or higher, things SEEM to be working ok but it needs testing.

**Comment by Fenris447** [comment]
I pulled the .user file down and got an error when I reloaded HL:

<img width="464" alt="Artificer Error" src="https://user-images.githubusercontent.com/32333990/55126107-16f8af80-50da-11e9-8d6c-d2ac013583ce.PNG">

**Comment by LordMorin** [comment]
Yea, I saw that when I downloaded the files to my laptop. I have fixed it I thing. Just haven't updated it yet  . . .
I"ll let you know when I do.

**Comment by LordMorin** [comment]
I just updated my current version of the Artificer file. This updates it to use the new 5C Source so should resolve the errors listed above. Let me know.

**Comment by Sklore** [comment]
I made instructions once upon a time for uploading changes to Github. Can be found here. I work solely with the web tool though. 

https://github.com/Sklore/HL_DD_5e_Colab/wiki/How-to-upload-your-changes-to-GitHub

**Comment by LordMorin** [comment]
Yea, I'd found that and other doc's. I think I have it working, but won;t know until someone tries it and chews me out for screwign it up <again> . . . :)

**Comment by LordMorin** [comment]
Added feat - Revenant Blade

**Comment by Fenris447** [comment]
Are you planning to add the new subclasses and the XGTE spells from the latest UA? No rush, just wondering if you’re working on it.

**Comment by LordMorin** [comment]
Working on the new subclasses at this time. Added the spell updates.

Still waiting on Lone Wolf to make hard coding changes to Half Casters to allow cantrips and spells at 1st level . . .

I've added the new Infusions (along with related Adjustments).

I am currently trying to modify my coding on the various companions. I am not happy with how I've done them to date. . .

**Comment by mbriddell** [comment]
I tried saving the USER file for the 2019 Artificer a couple times today and got this error each time:
![Artificer Error 1](https://user-images.githubusercontent.com/38485913/62419261-a6dad700-b641-11e9-8daa-9ea85b9ab1f6.jpg)
![Artificer Error 2](https://user-images.githubusercontent.com/38485913/62419264-ad694e80-b641-11e9-8b5c-d8c66c580990.jpg)

**Comment by Fenris447** [comment]
Mbriddell, I checked line 7 (per that error message) and it looks fine to me. You might be doing a “save as” directly from your browser. That won’t work correctly. You need to copy the raw text of the file from here into the file on your PC.

Also make sure you do the same with COM_Source_110 - Unearthed Arcana.1st

**Comment by mbriddell** [comment]
Appreciate the help. It took me a couple tries but I got it working. I may be able to add the two newer subclasses in the next few days.

**Comment by attobrute** [comment]
Hello All,

Git Hub Noob here...

1. I have logged into Git Hub
2. I am in this repository:  Sklore/HL_DD_5e_Colab
3. I downloaded the 'COM_5ePack_UA - Artificer_(2019).user' file using the only method I know: raw>save as
4. I downloaded the 'COM_Source_110 - Unearthed Arcana.1st', again using raw>save as
5. I copy the two files into my Hero Lab directory: 'C:\ProgramData\Hero Lab\data\5e'
6. I start up Hero Lab
7. I get this same error that Fenris447 got some time ago on Mar 28:

[https://user-images.githubusercontent.com/32333990/55126107-16f8af80-50da-11e9-8d6c-d2ac013583ce.PNG](url)


I am obviously doing something wrong, but I'm not sure what... Do I need to download the file from Lord Morrin's sub fork or some such?!

Please help me!!

**Comment by attobrute** [comment]
![2019-08-29](https://user-images.githubusercontent.com/49269255/63912838-498c4700-ca82-11e9-99df-c4ace40821bb.png)
this is a screenshot of the error I get...

**Comment by LordMorin** [comment]
On the GitHub site, try going to the Code tab and download as a ZIP.
Extract to a folder. Then copy the 2 files over to the Game System Data Folder.

**Comment by attobrute** [comment]
I have sorted it out...
Downloaded the entire HL_DD_5e_Colab file as a ZIP
Copied the entire contents of the ZIP into my 5e folder
No errors on loading! Yahoo!

However, cannot change my old multiclass cleric 5/artificer 3 character to cleric 5/artificer (2019) 3, as the new artificer option doesn't appear in the list when levelling up... Had to recreate the entire character from scratch.

Also, for some reason, it gets unhappy when I try to give the character any artificer spells above level 1... I seem  to recall that this was a bug already known about

**Comment by LordMorin** [comment]
Have you turned on the new Artificer under the Character tab > Configure Hero?

**Comment by attobrute** [comment]
Oh... turned it on, and now can see in the original character... excellent, won't have to re-add my inventory of gear like I feared

**Comment by attobrute** [comment]
Still have the problem with artificer spells over level 1 though... Is it something to do with being a multiclass character?

**Comment by LordMorin** [comment]
That is a hard coding issue that it is beyond my abilities to fix. I've
asked for a fix, but so far nothing. They may be waiting for an official
version of the Artificer before fixing it in case WotC changes that again.

I've just been ignoring the issue while still using it myself.

**Comment by Shayemus79** [comment]
Has anyone added the other 2 subclasses to Artificer 2019?

**Comment by LordMorin** [comment]
I have them partially done. But they aren't pretty. They work for my own campaign, but I haven't felt them up to a standard to upload them.
If people want them badly enough, I'll upload what I have done.

**Comment by Shayemus79** [comment]
I'm looking for the Battlesmith mostly, and truth be told am being a little lazy as I made a bunch of stuff for HL Pathfinder years ago...

**Comment by mbriddell** [comment]
I've made some progress on the other two archetypes. Not 100% complete as I haven't been able to make the Battlesmith construct yet but the other core aspects of them are done. I can upload what I've got later this evening if I can figure that part out.

**Comment by LordMorin** [comment]
I have merged what I have done with the Archivist and Battle Smith archetypes. I am not happy with how I have implemented the pets, I'd rather see them doen the way familiars and ranger pets are.

**Comment by mbriddell** [comment]
I've got the my work on the archivist restored if people want to give it a try. At this point it's only the text for each ability and the spell list. A lot of the archetype-specific abilities have two nested abilities, so it may be better to break those out into separate things rather than keep them nested so they don't stay hidden in large text blocks.
[COM_5ePack_UA - Artificer (2019) Archivist.zip](https://github.com/Sklore/HL_DD_5e_Colab/files/3613366/COM_5ePack_UA.-.Artificer.2019.Archivist.zip)

**Comment by LordMorin** [comment]
I just updated my version the other day at demand. :)

**Comment by Fenris447** [comment]
I just pulled down the version that's live in the Master branch and got some errors. They're all related to eval scripts with a specific tag (field?). Check out lines 530 and 870 of the file to see where the problems are happening:

perform field[usrChosen1].chosen.assign[Custom.5CEbArcFoc]

<img width="464" alt="Art Error" src="https://user-images.githubusercontent.com/32333990/67700286-b38a7500-f97b-11e9-86a9-016b5814e775.PNG">

**Comment by Fenris447** [comment]
I feel very dumb that I didn’t search the GIT for it before posting. It looks like you put it in the WGTE Items file, which I must not have. I’ll try it when I get home.

**Comment by LordMorin** [comment]
Don't feel too bad, I had a similar issue with all the new monster files. I
was trying to use the stuff uploaded for Baldure's Gate: Descent into
Avernus and they drew upon materials I hadn't downloaded . . .

**Comment by Fenris447** [comment]
Closing this as it's now part of #926 (Rising from the Last War)
