### ISSUE TITLE
Missing Tools

### ISSUE THREAD

**Issue by OregonPinkRose** [Sklore/HL_DD_5e_Colab#90]
It appears that Dragonchess Set & Three-Dragon Ante set are missing from the Tool list of things to buy.

Also, Dragonchess Set & Three-Dragon Ante are missing as options for any background that allows gaming sets.

Also, there probably should be a custom gaming set option as a proficiency choice as the text states: A few common examples appear on the Tools table, but other kinds of gaming sets exist.

**Comment by Sklore** [comment]
Thanks Dragonchess Set & Three-Dragon Ante will be added in the next release.
