### ISSUE TITLE
Modern Magic

### ISSUE THREAD

**Issue by MardukBathory** [Sklore/HL_DD_5e_Colab#913]
Hi.  I am going to be joining a Modern 'modern' campaign, soon.  (Well, I'm not sure if that's what you'd call it, but it's going to have aspects of cyber and aether punk)

I had already noticed a while back that the Modern Magic UA never made it to the Community packages, even though it was very early on.  (I assumed they were never covered because of a technical difficulty, rather than a lack of interest, but now I'm not so sure).  

If I wasn't so hopelessly bad with editing races, classes, etc., in HeroLabs, I'd have a crack at it myself, but if anybody else has already taken care of it and would be willing to upload it I'd be more grateful than I could conceivably repay you for.

**Comment by LordMorin** [comment]
I can't even finish what I am already working on currently, so I can be of assistance with UA: Modern . . .

**Comment by MardukBathory** [comment]
I kind of feel I have to ask, now... what are you working on that's causing you such grief?

**Comment by LordMorin** [comment]
UA - The Artificer & Wayfinder's Guide to Eberron.

**Comment by Fenris447** [comment]
Programming this isn’t the hard part, actually. The time consuming aspect is rewriting all the text to be 20% different from the UA as published to avoid copyright issues. If someone is willing to send me the text redone, I can throw this together in a night or two.

**Comment by MardukBathory** [comment]
I've rewritten the Cleric and Warlock subclasses.  I'll do the wizard tomorrow.  Not sure if I'll have time to do all of the spells.  Thanks for letting me know, btw, I really appreciate it!

**Comment by MardukBathory** [comment]
[ModernMagicRephrased.pdf](https://github.com/Sklore/HL_DD_5e_Colab/files/4467750/ModernMagicRephrased.pdf)

I don't know if that uploaded properly.  Anyway, I've rephrased the whole damn thing, except for the names of features, spells, and abilities.  If that needs to be changed then I imagine it would take considerably less effort than writing this thing took.

I warn you, I think I made things less clear in a few places.  But I think I actually made 1 or 2 things more succinct.  (Sadly the improvements are outweighed by the fails).

**Comment by Fenris447** [comment]
Great job! The names of everything can stay the same. I’ll put this together as soon as I have the time (should be this week).

**Comment by MardukBathory** [comment]
So it all made sense?  I didn't obscure anything that was once clear?

**Comment by Fenris447** [comment]
Oh I haven’t had a chance to read through all of it. And I’m not familiar enough with the UA to know how everything is supposed to work. I’ve only skimmed the original to make sure I understand the mechanics of it all. But I’ll try and review it as I go through and program it.

**Comment by Fenris447** [comment]
I’m about halfway through the spells. For the most part, you did fine on the rewrites. But there’s a few places where you added things not in the original spells. Which turns it into homebrew. You’re of course free to do that in your own files and games. But if we’re going to add this as our version of Modern Magic, it needs to be mechanically the same as the published UA.

For instance, you added stuff on Find Vehicle saying the spirit can be dispelled by magic. That’s not in the original text, so we shouldn’t add it here. It’s up to the DM and the player to make that determination, not the Community Pack.

**Comment by MardukBathory** [comment]
Maybe I misinterpreted them.  There's only one place I can think of where I did that, which is because the original didn't make sense, so I 'translated' it as best I could.  (You can't rephrase it if you didn't understand it to begin with, right?)

Hope that isn't too bad of an issue.  I'm sorry if it is, I tried.

**Comment by MardukBathory** [comment]
I may have misunderstood the Find Steed spell all of these years.  It's just generally seemed to make sense to me that any thing that would end a spell's effect would at least cause the fey/fiend/celestial to stop being a vehicle, at least for a time.

Everybody I've asked seems to be drawing a blank.  I'm going to have to ask some larger groups, I think...

**Comment by Fenris447** [comment]
Donezo. Only about half a year later. ;) Enjoy in the next release!

**Comment by MardukBathory** [comment]
I honestly just gave up 😅

**Comment by Fenris447** [comment]
Sorry man! I ended up taking a bit of a break from it all. But I wanted to get it to you eventually. The 2.5 pack just got pushed yesterday, so it’s there for the taking.

**Comment by MardukBathory** [comment]
I meant that in a tongue-in-cheek sort of way, I wasn't trying to be a
dick.  I just figured that if it couldn't be done when everybody was off
work, it probably just couldn't be done and I shouldn't hassle people over
it.

The update on this was a surprise, and so was the update (because it
literally happened between games;- closed it after a game with some friends
here in the UK, opened it for a game with some canadian friends and there
it was!)

But I'm thrilled you did this, and I'm genuinely thankful!

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by Fenris447** [comment]
Nah I didn't take it as dickish. I get it!

I'll take a look at the DMG guns and how we can integrate them better with this UA when I have a chance. It's more complicated than if they were their own category like "Simple" and "Martial" weapons.
