### ISSUE TITLE
Baldur's Gate: Descent into Avernus

### ISSUE THREAD

**Issue by LordMorin** [Sklore/HL_DD_5e_Colab#916]
This issue is for work done or questions/issues about this new adventure

**Comment by LordMorin** [comment]
- Added source for Baldur's Gate: Descent into Avernus (BG: DiA)
- added new Faceless background from BG: DiA

**Comment by LordMorin** [comment]
Trying to figure out how to add the variant background features from BG:DiA.

I plan to add the magic items and monsters/npc's.

**Comment by Fenris447** [comment]
I’m aiming to do all the monsters/NPC’s sometime in the next two weeks. If you want to focus on the backgrounds and magic items, we can avoid doubling efforts.

**Comment by LordMorin** [comment]
I am halfway through magic items. Backgrounds, the new one, is done, and it look like I have to add the new variants separately.

I want to add the monster/npc's simply because I will be runnign BG:DiA myself. . . :)

**Comment by Fenris447** [comment]
So am I 😆.

At least let me give you a barebones dump, like the one we started with for MTOF.

**Comment by LordMorin** [comment]
I won't say no. :)

**Comment by LordMorin** [comment]
- Added BG:DiA magic items

**Comment by LordMorin** [comment]
I've had motherboard issues and just got the parts replaced. I'd started on the monsters, but hadn't wanted to risk file corruption in one of the many blue screens I was getting. I hope to work on things tomorrow.

**Comment by Fenris447** [comment]
Added COM_5ePack_BGDiA - Monsters.user to the branch. It has the base monster data for the whole module.

Are you doing them in any particular order? I can meet you in the middle on them.

I already got started on a stock file. Let me know when you've got these monsters done and I can put them into it.

**Comment by LordMorin** [comment]
I am still working on implementing variant background abilities . . .

**Comment by Fenris447** [comment]
Then I’ll get going on the monsters. I’m probably going to do them in order of when you encounter them, since I’ve already started running the module for a group.

**Comment by LordMorin** [comment]
It will be another 2 weeks before I start my campaign. One of my players is in Europe for 2 weeks.

**Comment by Fenris447** [comment]
All Chapter 1 monsters plus a few more have been added. Stock file included for everything that's finished. Let me know if you find any issues.

**Comment by LordMorin** [comment]
I have tried to download and install the BG: DIA Monsters & Monsters stock files. However, when I install them, I get the following errors:

The data files could not be loaded due to errors. Hero Lab will now attempt to load them in recovery mode. Once loaded, you can access the editor as normal to correct any errors.

The following errors occurred:

Thing 'r5CAmrVa' - Bootstrap thing 'ra5CSuaDefN' does not exist
Thing 'r5CDukTh' - Bootstrap thing 'ra5CDarDevN' does not exist
Thing 'r5CDukTh' - Bootstrap thing 'ra5CDevSitN' does not exist
Thing 'r5CMorVa' - Bootstrap thing 'ra5CIndom' does not exist
Thing 'r5CPeacock' - Bootstrap thing 'ra5CKnSiSm' does not exist
Thing 'r5CThuVa' - Bootstrap thing 'ra5CDarDevN' does not exist

**Comment by LordMorin** [comment]
When I delete the Monsters files, the issue goes away. I don't know what the missing Bootstraps are for, so I can't puzzle out a fix :)

**Comment by LordMorin** [comment]
I went into the 'COM_5ePack_BGDiA - Monsters.user' file with Notepad++.
I am wondering if you referenced racial ability you created in another file that I am skipping over. I ahven't downloaded and installed a complete copy from GIT because I don't want to overwrite files I am still working on and haven't uploaded to GIT myself.

As a test, I grabbed the latest MToF files and get a similar issue of missing bootstraps. Do you keep your bootstraps in a seperate, central .user file somewhere?

**Comment by Fenris447** [comment]
Ah I know what’s going on. Short answer, download the most recent Monster/All files for both Waterdeeps, RoT, HotDQ, PotA, GoS, and GGtR. That *should* be everything you could need.

Long version: I got ambitious early this year and wanted to get us caught up on every monster we haven’t programmed, mainly from those books. I ended up pulling data together of every racial special that wasn’t unique. I catalogued which ones we had already programmed to be used with the “abText” replacement eval scripts, and created new ones for those that did not exist yet.

I *should* have just put them into MTOF or some other single file. But instead I put each ability in the file in which it first appeared. Stupid, I know. So now they’re spread out across those files. Once we do a full release and everyone is updated, we’ll be good to go. But until then, I’ve created problems like what you’re encountering.

On the bright side, I’ve almost finished a HotDQ file and am currently working on RoT as well as MToF and BG:DiA.

**Comment by LordMorin** [comment]
Thanks for the info. Just finished a game session with Baldur's Gate group
so I'll try to grab everything tomorrow. They just got to D10 under the
bath house tonight. I used some placeholder darklings and the proper stats
from DnDBeyond. :/

**Comment by Fenris447** [comment]
Is anyone else running this currently? My party is still on chapter 1 but if anyone else needs the later monsters let me know and I’ll hook you up.

**Comment by Fenris447** [comment]
All monsters and magic items have been programmed. They’ll be in Release 2.3.

**Comment by Fenris447** [comment]
I made a mistake and forgot to upload Tiamat in 2.3. She was complete but was in my RoT .user. That file and it’s .stock are now up on my branch and will be included in the next release as well.

I’m leaving this issue open, since the infernal machines are not in. I haven’t tackled how to make them yet, but I’ll be doing it alongside the GoS ships and AI vehicles when/if I do those.

**Comment by Fenris447** [comment]
Found an issue and writing here so I don’t forget to fix it: the Hollyphant’s trumpeting has no range listed.

**Comment by Fenris447** [comment]
Hollyphant is fixed for next release. Working on the GoS ships. The framework I've built for them will help significantly with building the war machines. More to come soon.

**Comment by Fenris447** [comment]
War Machines have been added. And that does it for BG:DiA! Woohoo.
