### ISSUE TITLE
Firearms (Dragon Heist, Mad Mage, Curse of Strahd)

### ISSUE THREAD

**Issue by kilpatds** [Sklore/HL_DD_5e_Colab#919]
The two Waterdeep season adventures give players an ability to acquire firearms:
* Pistol (Flintlock style, one shot per load)
* Revolver

and also use "smokepowder", as a new magic item with stats in Dragon Heist.

The musket is in Curse of Strahd...

AL rules allow the use, given smokepowder. Could the firearms from the DMG be added, preferably as an optional rule so a given PC can opt in to having them listed or not?

**Comment by Fenris447** [comment]
The major hangup here is the Reload property of the weapons. It just doesn’t exist in Hero Lab, as far as I know. And I don’t know if the coding can be done to create the property as something assignable (like Versatile, Heavy, Ammunition, etc are assignable), plus to make some sort of tracker with a variable number to represent the clip/magazine of each gun.

A much less elegant solution might be possible, where each individual weapon gets a little tracker that the player needs to manually reset every time they reload.

**Comment by dungeonguru** [comment]
It might pay to hit ShadowChemosh up. There is a Reload property available (wProperty.AWReload) that is probably inherited from the shared codebase with Pathfinder. I'm not sure if the trkMax field is applicable for the number of charges between reloading though.

**Comment by LordMorin** [comment]
I thought someone added a Gunslinger class to HeroLab a while back?

DM's Guild sources. The Gunslinger Martial Archetype . . .

**Comment by LordMorin** [comment]
By the way, is anyone else having issues with the HeroLab forums? I have not been able to connect to them since last night.

**Comment by Fenris447** [comment]
I’m working on this. Pistol and Smokepowder are easy enough. The Reload property DOES appear to exist in 5e HL, but I don’t know how useable it is. I’ll let y’all know what I figure out.

**Comment by Fenris447** [comment]
Alright, I gave it a shot. Grab:

- COM_5ePack_DMG - Equipment.user
- COM_5ePack_WDH - Items.user
- COM_Source_110 - Waterdeep.1st

I tried out making trackers for the firearms. If I just made a tracker directly on the weapon, the tracker was always on, regardless of whether it was equipped, and the tracker's name was just the weapon's name. If I made a new tracker and bootstrapped it, that tracker would be greyed out all the time.

**Comment by kilpatds** [comment]
Generally looks good for my purposes.

I forgot to mention bullets (10 for 3gp, 2lbs) from the DMG, and If you can make price contingent on "Is an AL character", then SmokePowder should cost 50gp for AL characters.

**Comment by Fenris447** [comment]
Is that 50gp per packet, or per keg? The book only gave the weight of a full keg as 5 lbs., so I kinda took a stab at the weight for the packet and will have to do the same for costs.

**Comment by kilpatds** [comment]
in AL, 50gp per packet (which has enough for 5 shots)

**Comment by Fenris447** [comment]
Bullets added to DMG, Smokepowder prices added to WDH. I didn't bother trying to make the price contingent on AL chracters, since there's no other price available anyway. If someone wants to ignore the price outside of AL, nothing is stopping them.
