### ISSUE TITLE
Unearthed Arcana: Starter Spells - Healing Elixer error

### ISSUE THREAD

**Issue by CaseyConner** [Sklore/HL_DD_5e_Colab#924]
I noticed that Healing Elixer was not available for a new Warlock I was making despite UA Starter Spells being selected.  I checked it in the editor and it has Cleric instead of Warlock selected.  I removed Cleric and put a check in Warlock and it showed up as it is supposed to.  This is a pretty simple fix that needs to be done to the COM_5ePack_UA - Starter Spells.user file.

**Comment by Fenris447** [comment]
Should be fixed in the main branch now. Please pull it down and confirm so I can close this out.
