### ISSUE TITLE
Eberron: Rising From the Last War

### ISSUE THREAD

**Issue by Fenris447** [Sklore/HL_DD_5e_Colab#926]
With this book coming out tomorrow, this can serve as the main issues thread for the book. I’ve made a project to track our progress:

https://github.com/Sklore/HL_DD_5e_Colab/projects/7

If you’re planning on tackling a particular part of the book, please either put your name on it under the project or make a note here so I can add you.

**Comment by LordMorin** [comment]
I pre-ordered Eberron: Rising From the Last War. When I looked at it this
morning, and saw what they had done to the Warforged, Changeling,
Kalashtar, and other races, and what they ended up with as the Artificer, I
was thoroughly disgusted. I am now sorry I pre-ordered.

I will NOT be doing any work on this new load of crap. Also, WotC is
forcing DDB to remove all usable access to the UA material that is being
replaced by the new garbage. I am assuming they will be forcing Roll20 and
Fantasy Ground to do the same.

It is my recommendation that all the work that has been done for the WGtE
and the Artificer simply be removed. At this time, I have absolutely no
intention of continuing my work on it. I will simply convert the files I
created to private versions and keep that material available for personal
use.

As it is, due to the hard coding issues with cantrips, the Artificer can
never go live as is anyways.

My disgust with WotC at the moment is such as I am seriously considering
going back to Pathfinder (not PF2 since it is Pathfidner gone the way of
D&D 4E and that is the route to failure and WotC discovered. I still have
all the material I purchased for Pathfinder, so I am good there.

**Comment by Fenris447** [comment]
I’ve finished converting the pre-release versions of the full races to their official versions. I’ve also added the Eberron Orc. Next up is two goals:

- Marked subraces/racial variants
- Converting the pre-release versions are of everything to a UA, so that players can choose to use those versions still

**Comment by Lolologist** [comment]
@Fenris447 I haven't done any development for this before but am more than happy to help out some here and there. Where would my efforts be most useful? Additonally, what could I work on that could lead to a new release sooner than later? There's a lot of books that have come out since the last release of this.

**Comment by Fenris447** [comment]
Thanks for the interest! Are you looking to get into the coding of it all, or would you prefer something more analogue?

**Comment by Fenris447** [comment]
And to update everyone on ERftLW progress:

- Races, subraces, and background* is complete.
- All pre-release versions of the above items have been copied and into a UA called “Eberron (2018)”, which will go up alongside the retail files

*I condensed the multiple backgrounds, which were one for each house, down into a single background. A drop-down menu lets you pick your house, which then automatically grants you your tool proficiencies. This results in a cleaner screen when picking backgrounds. 

UP NEXT:
- Convert the pre-release Revenant Blade and Aberrant Dragonmark feats to be marked under the new UA category
- Modify a copy of that Revenant Blade feat into it’s retail version
- Upload all the work!

Once all that’s done, I’m going to hop back to finishing MToF and the BG:DiA monsters. if someone wants to take a look at the Aberrant Dragonmark and figure out an implementation for what changed with it going Retail, please do so!

**Comment by Fenris447** [comment]
Donezo with all the Eberron stuff outlined above. Woohoo! The Aberrant Dragonmark is not fully updated. I did set it up to be available only if you're not already Dragonmarked, and to recharge on a short rest. But everything else about it is still the pre-release version. 

Until Hero Lab makes some changes that will allow us to get the Artificer working properly, I'll be taking a break from Eberron. In the mean time, please feel free to download it and report any problems you have here! I'll be making a thread to explain what you need to download and do for Eberron.

**Comment by Lolologist** [comment]
Thanks for your work, Fenris.

I'm only vaguely familiar with the inner workings of Hero Lab and would prefer whatever I could do that's easier to start, but with a focus on getting work done that can allow an update for some of the older stuff to finally go out.

**Comment by Fenris447** [comment]
**Artificer Problems:**

So the Artificer is unique in two ways:
1. It’s a half caster that gets cantrips and spellcasting at level 1 (Half-Casters usually get spellcasting at level 2, and never any cantrips)
2. When multiclassing, you take half your Artificer levels and round UP when using the multiclassing table to determine your total spell slots.

Hero Lab has the “Half Caster” classification built into it, and it automatically rounds down. This is correct when applied to the Paladin and Ranger. But with the Artificer, it results in the wrong number of spell slots. A level 2 Wizard, level 3 Artificer should be the equivalent of a 4th-level caster, not a 3rd. Hero Lab rounds down with no way to create or modify a type of caster, which means we can never make the math work.

I received a response from Lone Wolf on this and they confirmed they can’t do anything, since a half-caster rounding up isn’t in the SRD. I personally think there’s a middle ground where they program just that little bit, which would allow us to make any kind of homebrew we want with that feature. But I trust their lawyers are smarter than I am. 

So the Artificer acts incorrectly in Hero Lab in two ways:
1. It doesn’t get spellcasting or cantrips at level 1, and we can’t give it to them easily or cleanly.

2. When multiclassing, their spell slots are wrong. 

I’m experimenting with ways to do #2 cleanly by tricking Hero Lab into thinking it has an additional caster level. Basically (x+1)/2 rounded down is equal to x/2 rounded up. But so far I haven’t been able to confirm this works in all situations.

**Comment by Fenris447** [comment]
**Helping Out**

I do have an idea for how you (or anyone else who doesn’t want to code) may be able to help.

One of the biggest time consumers for entering new monsters is adding abilities and changing their text to avoid copyright infringement. We have to strip out the fluff and rephrase the ability.

I could share a google doc where you can add the new, changed text, and then select stuff from drop-down boxes like the ability’s range, damage, recharge rate, etc. Once people update those things, I have ways of automatically turning that stuff into code.

Would that be something you’d be interested in?

**Comment by Lolologist** [comment]
Hi Fenris, sorry for not seeing this until now.

I'd be happy to help with text, just point me at it! I've dealt with
copyright stuff like this before and can ensure no lawyers come a-knocking.

**Comment by Fenris447** [comment]
@Lolologist I have uploaded [a google doc](https://docs.google.com/spreadsheets/d/1WMM9jWdcSgnjmjHtNh7WGZ__L52As2LlL-2e2UsQJbE/edit?usp=sharing) with the un-changed text, alongside a column to add re-written text. Once these are done, I can get the abilities, monsters, and items from ERftLW added!

**Comment by Enforcer84** [comment]
I was setting up an artificer - and you've done a great job on this. The Infusions work perfectly. I was having trouble setting up the Arcane Turret (needs to be set up under the minion tab) I also noticed there's no "Arcane Turret" adjustment as mentioned under the Class Ability.

**Comment by LordMorin** [comment]
I keep meaning to try a rebuild of the latest version of the artificer, but just haven't been able to get started on it. :(

**Comment by Enforcer84** [comment]
Well, the build as it is is pretty darn good. I thought there was more missing but once I started playing around with it I found the Adjustments for the infusions. I keep getting amazed at the community work. Every time I'm proud of my own endeavors, I find they've been done better

**Comment by LordMorin** [comment]
The new infusions need to be added. The number of infusions need to be updated. I am not sure what else needs to be updated.

**Comment by Fenris447** [comment]
Aberrant Dragonmark is done and will be in the next release. Due to coding limitations, there's some manual parts to decrementing Hit Dice when using it. There's a note to that effect on the feat. Also added Greater Aberrant Dragonmark as an option that shows up once you hit level 10.

**Comment by Fenris447** [comment]
Here’s what’s left to do:

- Artificer added (I’m doing this now)
- 2020 Errata (also doing this)
- Items
- Monsters (I have all the base stat blocks, but all their special abilities need to be programmed and .stock files made)

**Comment by Fenris447** [comment]
I've finished the Artificer and the errata updates. The items and monsters still need to be done.

**Comment by Fenris447** [comment]
Every item’s basic stats are batched in now. The items that have more programming needed are in progress, and will be part of release 3.1.

**Comment by Fenris447** [comment]
Items are done. Monsters are next and then we’re feature complete.

**Comment by Fenris447** [comment]
Monsters are done!
