### ISSUE TITLE
Blessings and Charms

### ISSUE THREAD

**Issue by LordMorin** [Sklore/HL_DD_5e_Colab#939]
I found the issue. For some reason I put them in a different .user file than epic boons. Don't ask me why . . . 
It looks like I never upload the file to GIT either, thus I never lost them due to the file never being overwritten . . .

[COM_5ePack_DMG - Supernatural Gifts.zip](https://github.com/Sklore/HL_DD_5e_Colab/files/4371582/COM_5ePack_DMG.-.Supernatural.Gifts.zip)

**Comment by Fenris447** [comment]
Thanks for putting them up! I made a few tiny changes and rewrote the text. I'm uploading them now for the next release!
