### ISSUE TITLE
Rogue no ability to pick skill prof.

### ISSUE THREAD

**Issue by FindsTheLost** [Sklore/HL_DD_5e_Colab#945]
![image](https://user-images.githubusercontent.com/48066135/79054923-051b7900-7c17-11ea-906d-df8079f97ae4.png)

I just loaded the pack and when creating a 5th ed Rogue the Select prof is missing. I can do it in basic mode of the software but on the one with pack I cannot. 

Any help?

**Comment by FindsTheLost** [comment]
I uninstalled all software,
Reinstalled base made rogue and tested was able to set when I put the Custom back in it broke it again.

**Comment by Fenris447** [comment]
Can you upload the .por file for this character? I’ll take a look at it and see what’s going on.

**Comment by Fenris447** [comment]
I took a look and can’t replicate the problem myself. Definitely going to need the .por file of your character to see what’s happening.

**Comment by Fenris447** [comment]
I think I figured it out. On your Configure Hero screen, towards the bottom under “Ability Options,” do you have “Background Proficiency” checked? That enables a variant rule where your class doesn’t provide you proficiencies.

**Comment by LordMorin** [comment]
How many times has that turned out to be the problem. :)

**Comment by Fenris447** [comment]
No response from OP; closing this.
