### ISSUE TITLE
Equipping/Unequipping Hide Armor

### ISSUE THREAD

**Issue by GarThor** [Sklore/HL_DD_5e_Colab#946]
Does not effect AC...

![image](https://user-images.githubusercontent.com/43391503/79899225-5c60dc80-83c1-11ea-93ad-69ddf75236a3.png)
![image](https://user-images.githubusercontent.com/43391503/79899269-6aaef880-83c1-11ea-8028-bfd3c72806bc.png)

**Comment by dungeonguru** [comment]
Your AC shouldn't change in this case - your Barbarian's Constitution is 14 (+2). 

Your Unarmored Defense states that your barbarian gains a bonus to AC equal to their Constitution modifier if wearing no armor. 

Wearing Hide: Base 10 + 2 (Hide) +2 (DEX) = 14
Unarmored: Base 10 + 2 (DEX) + 2 (CON) = 14

**Comment by GarThor** [comment]
Ah… thanks… I must have missed that…

I guess I should just sell my hide armor then…

~Garret

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
