### ISSUE TITLE
Totem Spirits have copy-pasta errors.

### ISSUE THREAD

**Issue by GarThor** [Sklore/HL_DD_5e_Colab#947]
![image](https://user-images.githubusercontent.com/43391503/79899560-d2fdda00-83c1-11ea-93f3-078727d4a922.png)

![image](https://user-images.githubusercontent.com/43391503/79899701-00e31e80-83c2-11ea-9dba-1b0393ad8e4f.png)

![image](https://user-images.githubusercontent.com/43391503/79899814-27a15500-83c2-11ea-8209-55797ebff4be.png)

![image](https://user-images.githubusercontent.com/43391503/79899890-46075080-83c2-11ea-86e2-5d3ef66d5e20.png)

I think others may also have copy pasta errors, but without the books open to those pages I can't be certain (I don't have a copy of "Sword Coast Adventurer's Guide")

**Comment by Fenris447** [comment]
Fixed and will be included in next update.
