### ISSUE TITLE
Path of the Storm Herald (Xanthar's Guide Version)

### ISSUE THREAD

**Issue by GarThor** [Sklore/HL_DD_5e_Colab#948]
Probable type-o...

![image](https://user-images.githubusercontent.com/43391503/79900585-4ce29300-83c3-11ea-801f-13dca24f3a73.png)
It reads that it increases to 2d6 at lvl 20, and then goes up to 3d6 @ lvl 15, before finally going up to 4d6 at 20 again?

**Comment by Fenris447** [comment]
Fixed and will be included in next update.
