### ISSUE TITLE
Artificer Issues

### ISSUE THREAD

**Issue by Tigron16** [Sklore/HL_DD_5e_Colab#949]
The Official Artificer class is missing from Eberron - Rising From the Last War.

**Comment by Fenris447** [comment]
It’s not so much “missing” as it “was never added.” Make sure to check the release notes for the Community Pack: https://github.com/Sklore/HL_DD_5e_Colab/wiki/3.-Pending-Changes

If something isn’t in there, it’s probably not in the pack. The Artificer has a lot of issues preventing it from being easily programmed into the pack, but it hasn’t been abandoned.

Any issues with Eberron: Rising from the Last War should be put under #926 until/unless that issue has already been closed.
