### ISSUE TITLE
Unearthed Arcana Subclasses 1,2 & 3.

### ISSUE THREAD

**Issue by INUYAHA** [Sklore/HL_DD_5e_Colab#952]
Unearthed Arcana Subclasses released 1/14/20, 2/6/20, 2/24/20. 

I would do it myself but I dont even know where to begin.

https://media.wizards.com/2020/dnd/downloads/UA2020-Subclasses01.pdf
https://media.wizards.com/2020/dnd/downloads/UA2020_02_06_Subclasses2.pdf
https://media.wizards.com/2020/dnd/downloads/UA2020-Subclasses03_0224.pdf

**Comment by Fenris447** [comment]
Honestly I’d love to do these, but my priority is going to remain official 5e content until we’re caught up. I have a hard enough time getting player options done for content as it releases. So I don’t expect to get to these until/unless they become official.
