### ISSUE TITLE
Explorers Guide to Wildemount not showing items

### ISSUE THREAD

**Issue by AquaGrass** [Sklore/HL_DD_5e_Colab#953]
In my campaign I have selected the book, however I cannot find the following items.

acheron blade - I have searched in the Weapons, Magic, and Gear tabs.

Corpse Slayer - I have searched in the Weapons, Magic and Gear tabs

Dispelling Stone - I have searched in the Gear and Magic tabs

Goggles of object reading - I have searched the Gear and Magic tabs.

Not sure if this has been pointed out before, or if I am a complete idiot. Either way, I will put this here.
![fix 1](https://user-images.githubusercontent.com/67184535/85196589-fa710600-b28f-11ea-8c03-17a21cfa2d9d.PNG)

**Comment by Fenris447** [comment]
They have not been added to the Community Pack. Check the release notes. If something isn’t listed as having been added, there’s a 99% chance it’s not in the pack.
