### ISSUE TITLE
Add Custom Option

### ISSUE THREAD

**Issue by foggyone** [Sklore/HL_DD_5e_Colab#956]
When selecting spells the current spell list is incomplete, and likely always will be.  If you have a special ability that grants a spell not on your list you can't add it.  Either display all spells using Everything and Only Valid Items as filters.  And/or add the option to create a Custom Spell with the functionality found in add gear.

Add Custom as an option for magic.  

You can name a custom feat but there is nowhere to enter information about what that feat does.  Add a large text field to enter what it is your custom feat does.  Bonus points to give your custom feat the ability to add a +1 to an ability score.

Add Custom as an option for Patron.  Add a large text field to enter what it is your custom patron grants.  
Bonus points to allow your custom patron spell list to show as valid in your Warlock Spells tab.

Add Custom as an option for musical instruments or tools.

Add a Custom option for Bardic Colleges.

I have a Warlock Bard so this isn't a complete list of where 'custom' would come in handy, just the places I've noticed.

Thanks for all you do.

**Comment by Fenris447** [comment]
I appreciate the suggestions, but almost none of that is something we can do with the community pack. If you want to create custom anything, that's exactly what the editor is for. Go to Tools -> Show Editor. There are tons of resources on the Hero Lab forums and the wiki here, and you can use existing spells, patrons, feats, bardic colleges, etc. as templates to work from.
