### ISSUE TITLE
Tasha’s Cauldron of Everything

### ISSUE THREAD

**Issue by Fenris447** [Sklore/HL_DD_5e_Colab#958]
It’s hitting on November 17th and there’s plenty to do. I’ve made a new project for Release 3.0, which will include Tasha’s. If anyone wants to help, particularly with the subclasses, spells, and items, I’d be very grateful for the assistance. Otherwise it’s gonna take a while for me to do it myself.

If you want to volunteer for something, add your name at the end of the title for it, like I have on some of these already. Or just post here that you’re working on it and I can mark you down.

**Comment by LordMorin** [comment]
I wish I had it in me to help. I just can't focus the way I used to when it
comes to scripting . . .

**Comment by Fenris447** [comment]
To update, I have all the variant class features, spells, feats, sidekicks, custom lineage, and the full Artificer class done. Right now I'm working on subclasses. I've got 6/22 done, not including the reprints, which are updated as well.

**Comment by Fenris447** [comment]
Subclasses are done. Racial features are done (but I'm not confident they'll work 100%, since there's so many individual races, subraces, variant races, and racial specials to test). 

All that's left are items, which will be for a future release.

**Comment by Fenris447** [comment]
I’m about 35% done with the items. I batched in the basics of all of them, but there are a bunch that have a lot of programming work to do on top of that.

**Comment by Fenris447** [comment]
Done with the items! And I think that does it for Tasha's for the Community Pack. Hooray!
