### ISSUE TITLE
Icewind Dale: Rime of the Frostmaiden

### ISSUE THREAD

**Issue by Fenris447** [Sklore/HL_DD_5e_Colab#963]
I'm working on some of this for release 3.1. There are spells, items, and monsters in the book that can be added to the Community Pack. At least the spells will make 3.1. The rest are maybes, but they're on the (very large) list of monsters and items that we're behind on.

**Comment by Fenris447** [comment]
I’m making some progress on the monsters. All the abilities are programmed, but are not yet matched with the monsters. I’m improving my monster parser to automatically pull in all standard (as in, +# to hit, #d# + # bludgeoning damage) attacks automatically, which will drastically reduce programming time spent on each individual monster.

**Comment by RodainTheDwarf** [comment]
I have entered all the monsters into My hero lab I can share the file if you want to go over it an make sure it parse's correctly. I think I have it done right though.

**Comment by Fenris447** [comment]
I’d definitely love to see them! Can you send me the file(s) at Fenris447@gmail.com?

**Comment by RodainTheDwarf** [comment]
Absolutely, i can send you the full stock file if you prefer. I have all
the monsters, items and spells. I don't know if they are done the same way
you do yours, but the data matches the book. I'm at work right now, but i
will send them when i get off later tonight.

**Comment by RodainTheDwarf** [comment]
Here is zip file with both the stock file for the monsters and the user
file that has everything all the Icewind Dale stuff

**Comment by Fenris447** [comment]
There’s nothing attached here. If you’re posting by replying to the emails, I don’t think it pulls in attachments that way

**Comment by RodainTheDwarf** [comment]
ok I'll email them to you directly.

**Comment by Fenris447** [comment]
Almost all items are done. Just four left to do, and they’ll be fast.

> ok I'll email them to you directly.

I got your stuff. Great job all around! A few notes: most of your items have their basic info, but are missing stuff like charges and programming for what they do for your character, if anything. Also, because monster abilities can’t be selected by the player, they don’t need sources. Leaving sources off also means that if another monster in the future has the same ability, we don’t have to make a new one; we can just use one that’s already made. 

There are a ton of abilities that we also have in the pack as modular. For example, you can find a specific version of Pack Tactics and bootstrap it to your new monster; let’s call it “Bug dog.” On the bootstrap, you can add the abText field and set it to “bug dog”. The modular ability will automatically add that, so on the bug dog it reads “The bug dog has advantage on...”

This prevents us from having to make multiple copies of abilities that do the same thing for each individual monster.

You did catch a few things I missed, like the Ice Pick, Professor Orb, and the Laser Pistol. So thanks for all your effort!

**Comment by RodainTheDwarf** [comment]
Awesome, thanks!

**Comment by Fenris447** [comment]
Done! Items, charms, language, monsters, and spells are all complete and uploaded, ready for release 3.1.
