### ISSUE TITLE
Subreddit because LWD Forums are down

### ISSUE THREAD

**Issue by Fenris447** [Sklore/HL_DD_5e_Colab#965]
Since the LWD forums are down, I set up a subreddit for any and all LWD discussion. There’s nothing there yet, but feel free to swing by and share with the rest of the LWD community if you can. 

https://reddit.com/r/LoneWolfDevelopment

**Comment by LordMorin** [comment]
Any word on what is going on with the Hero Lab forums?

**Comment by Fenris447** [comment]
No idea what the issue was, but it’s fixed now. I got permission from LWD to post about the subreddit on the forums, so at least people are now aware the subreddit exists as a backup.
