### ISSUE TITLE
Hide Deity Adjustments

### ISSUE THREAD

**Issue by Fenris447** [Sklore/HL_DD_5e_Colab#968]
Enforcer84 raised a suggestion for a way to hide deities. I'll shoot for these to be in release 3.2. See [this thread](http://forums.wolflair.com/showthread.php?t=59846&page=2) for details.

**Comment by Fenris447** [comment]
I’m still having trouble making this work. It’ll probably be delayed until release 3.3, as the only viable solution I can come up with is going to take some time.

**Comment by Fenris447** [comment]
I've made progress. I was hoping to sneak it into 3.2, but I won't be able to. The forums are down, and the code I was going to base this on is posted there. Ugh.

**Comment by dungeonguru** [comment]
You're in luck, I have a bookmark to the Eberron source code in the Pathfinder files:

Go to github.com/shadowchemosh/HL-Pack-Pathfinder and you can search for the Eberron Mechanic - 

The actual hide deity code snippet in COM_CampaignPack_Eberron - Mechanic.user is as follows

  
  
  
  <thing id="ECSDeities" name="Eberron Mechanic, Deities" description="Hide all non-Eberron deities if the source &quot;Hide Non-Eberron Deities&quot; is turned on." compset="Simple" uniqueness="unique">
    <usesource source="srcOnlyEbe"/>
    <eval phase="First" priority="10000"><![CDATA[
      ~ Find all non-Eberron deities
      foreach thing in Deity where "!DeityCat.S2Eberron & !thingid.deiAtheist & !thingid.deiOther"
        ~ If no deity category then pull the thingid
        If (eachthing.tagcount[DeityCat.?] = 0) Then
          perform eachthing.pulltags[thingid.?,HideDeity]
        ~ If we have a category then pull the cateogry only
        ~ if we have not already pulled it.
        Else
          If (eachthing.intersect[DeityCat,DeityCat] = 0) then
            perform eachthing.pulltags[DeityCat.?]
          Endif
        Endif
      nexteach
      ~ Create Hide Deity Catagory tags
      perform pulltags[DeityCat.?,HideDeiCat]
      ~ Push the hide deity tags to the hero
      perform hero.pushtags[HideDeiCat.?]
      perform hero.pushtags[HideDeity.?]
      ]]></eval>
    </thing>

**Comment by Fenris447** [comment]
Thanks for providing the code! I didn’t have a chance to work on it before ShadowChemosh pushed the release, so it didn’t make it into 3.2 :( But it’ll definitely be in 3.3.

**Comment by Fenris447** [comment]
This is now done and ready to be included in the next release. The dungeonguru provided is perfect; I just had to add stuff to let the user choose their deity category and we were good to go. Thanks everyone for the suggestion and help!
