### ISSUE TITLE
Arcane Trickster - Too many cantrips

### ISSUE THREAD

**Issue by azuravian** [Sklore/HL_DD_5e_Colab#97]
When you select the Arcane Trickster roguish archetype you are supposed to get "Mage Hand" as well as 2 other cantrips of your choice.  There are two issues at play here:

First, mage hand only seems to show up on the printed spell list.  It doesn't add it to the Rogue Spells tab.
Second, you are given the option to select 3 cantrips, when you should only be allowed to select 2.

**Comment by Sklore** [comment]
Fixed the Cantrip selection issue, 

Might need some more technical skills in on the ability to display Mage Hande on the Rogue Spells tab. 
@shadowchemosh, do you know how to achieve this? It's bootstrapped in like normal which i imagine means it knows nothing of the Rogue Spells tab.
