### ISSUE TITLE
Telepathic feat linked to Shadow Touched effect

### ISSUE THREAD

**Issue by BlackRose-XIII** [Sklore/HL_DD_5e_Colab#972]
For some reason, adding the Telepathic feat to a character causes it to add the "Shadow Touched" tab to the character, instead of the intended effect.

In case this ends up being relevent, character is a 9th level Tiefling Aberrant Mind Sorcerer.

**Comment by Fenris447** [comment]
Yup. You’re definitely right. The shadow touched code is right there, built into the Telepathic feat. If you can just ignore it for now, it’ll be removed in the next update. 

If it’s really bothering you, delete lines 402 and 425-433 in the TCOE feats file.

**Comment by BlackRose-XIII** [comment]
Yeah it's not a big deal, just wanted to make it known. Thanks!

**Comment by Fenris447** [comment]
Fixed for next update. Thanks for the report!
