### ISSUE TITLE
Bladesinging subclass adds Performance proficiency twice

### ISSUE THREAD

**Issue by BlackRose-XIII** [Sklore/HL_DD_5e_Colab#975]
I haven't look into the code because I'm not particularly good at it, but I believe the Bladesinging subclass for wizard is adding Performance prof 2x, because when it is added to a character it immediately triggers a "duplicated proficiency" selector on the skills tab for performance. If the character was already proficient, it adds 2.
My best guess is that both the subclass itself and the "Training in War and Song" subclass feature (gained immediately upon taking the subclass) are adding proficiency, causing the duplication.

**Comment by Fenris447** [comment]
You’re close! Apparently Training in War and Song itself is adding it twice. Another good catch. Keep ‘em coming!

**Comment by Fenris447** [comment]
Fixed for the next release. Thanks again!
