### ISSUE TITLE
Eldritch Mind (TCoE) listing Tome Pact as prereq

### ISSUE THREAD

**Issue by BlackRose-XIII** [Sklore/HL_DD_5e_Colab#978]
As title, TCoE invocation Eldritch Mind is requiring Pact of the Tome as a prerequisite like the UA version, but the TCoE version should not have this prereq.

**Comment by BlackRose-XIII** [comment]
Removed prerequisite, created pull request

**Comment by Fenris447** [comment]
Good catch, and the code fix you put in looks perfect. I’ll push it in.
