### ISSUE TITLE
Twilight Domain - Cleric

### ISSUE THREAD

**Issue by jaq1231** [Sklore/HL_DD_5e_Colab#987]
Hello! 
I wanted to let you know that the domain spells for the Twilight domain of the Cleric has one small error. The 1st level spells are Faerie Fire and Sleep. Currently in the pack, it is Faerie Fire and Identify. 
Thank you so much for your time and your help!

**Comment by Fenris447** [comment]
Thanks for the report. It's been updated for the next release.
