### ISSUE TITLE
Barding

### ISSUE THREAD

**Issue by Fenris447** [Sklore/HL_DD_5e_Colab#989]
Requested by Polecat.

Per PHB: "Barding is armor designed to protect an animal's head, neck, chest, and body. Any type of armor shown on the Armor table in this chapter can be purchased as barding. The cost is four times the equivalent armor made for humanoids, and it weighs twice as much."

**Comment by Fenris447** [comment]
This was easier than I expected. They're now present in the Gear tab, and you can add them to any non-humanoid creature. They don't have an actual cost, as there's no way to have a minion charge a purchase to the master. So you'll have to manually deduct the cost from the Hero. But the cost is listed in the description for each Barding option.

**Comment by LordMorin** [comment]
When I need barding, I put armor on the mount and use one of the pre-existing adjustments to rename it.
