### ISSUE TITLE
Circle of Spores Circle Spells

### ISSUE THREAD

**Issue by Remandred** [Sklore/HL_DD_5e_Colab#991]
Gaseous form does not add in as a free spell at 5th level druid(it does not add in at all). Taking a look, it seems that the source thing is looking for 'sp5CGasFor' but there is another 'spGaseForm' that does add the spell. (Note the Circle of Spores Circle Spells are in GGtR) Thank you!

**Comment by Fenris447** [comment]
Yup, it looks like I programmed it with the wrong Gaseous Form. Feel free to switch it in your own file to the proper one in the meantime, but I'm uploading the fix for the next release.
