### ISSUE TITLE
Dnd 5e blood hunter blood maledict ability not working

### ISSUE THREAD

**Issue by columbusmedic90** [Sklore/HL_DD_5e_Colab#992]
Hello,

The blood Hunter class level 2 ability blood maledict is supposed to let you pick a second blood curse there is no drop-down menu to pick the second blood curse.

**Comment by Fenris447** [comment]
I’ll take a look and see if it’s a quick fix. But keep in mind that the Blood Hunter is wildly outdated and no longer supported.

**Comment by Fenris447** [comment]
Okay I found it and fixed it. It'll be updated in the next release to give two curses at level 2.

**Comment by columbusmedic90** [comment]
Thank you for your response. You are awesome!
