### ISSUE TITLE
Not seeing spells from TCoE when running HL on iPad

### ISSUE THREAD

**Issue by Sidthiel** [Sklore/HL_DD_5e_Colab#993]
Hello.  I am using an iPad to run Hero Lab and cannot see any of the spells from Tasha's.  I'm using the 5e Community Pack v3.2 (updated 2021-04-18).  I'm a retired s/w dev and could possibly work with the XML or JSON code to add the listings, but I don't know where those files are located on the iPad (used the MS stack and I'm not an Apple guy).  I'm entirely open to the possibility that this is user error of some sort, but various attempts at uninstalling and re-installing the Community Pack hasn't helped any, to date.  FWIW, I have not installed HL on another system.  Thanks for your help.

**Comment by BlackRose-XIII** [comment]
Have you checked your source settings? You may not have TCoE content enabled by default.

**Comment by Sidthiel** [comment]
Thanks for the quick reply.  

Proper question. Hopefully this is the appropriate response.  🙂

**Comment by Fenris447** [comment]
Right now, you have to enable the Variant Class Features (there’s a source for “Always Show Tasha’s Variants” that enables this), then select your class’s expanded spell list feature to see the Tasha’s spells. In the next update, I’ll be setting them up to automatically show up whenever you just select the TCOE source.

**Comment by Sidthiel** [comment]
Hi, Fenris.

I hope you are doing well.

That did the trick.  I figured it was something I’d missed.  I had enabled the “Always Show Tasha’s Variants” before, but did not take the next step of enabling the expanded spell list feature (doh!).

Thanks for the prompt answers and help,

jd 

Sent from Mail for Windows 10

**Comment by Fenris447** [comment]
I've updated the code to add these spells to the class spell lists whenever the TCOE source is selected. So now it'll function just like XGTE and SCAG spells.
