### ISSUE TITLE
Interaction between Hexblade's "Hex Warrior" feature and Pact of the Blade

### ISSUE THREAD

**Issue by BlackRose-XIII** [Sklore/HL_DD_5e_Colab#996]
This is something that has bothered me mildly for a while, but I'm not sure it can even be done without just using an adjustment (which is already available)

Hex Warrior states that any Pact of the Blade weapon uses Charisma instead of Str/Dex. If possible, we should add a line to Pact of the Blade that checks if warlock subclass is Hexblade, and if yes, change the selected weapon's Attack+Damage stat to Charisma.

If this isn't possible in Hero Lab for whatever reason, please let me know and close this request. I just wanted to put it out there for those of you who understand the code better than I do.

**Comment by Fenris447** [comment]
So according to the code, it does do this in one way or another. But it’s not how I would have done it, and it looks like you have to select your Pact weapon using this feature. I should be able to have it instead automatically apply to the selected Pact weapon.

**Comment by BlackRose-XIII** [comment]
Yeah, that's my issue with the current implementation, because it doesn't allow for selecting 2 different weapons, which the Pact of the Blade Hexblade can do, allowing for Charisma-based dual wielding, or having 2 Magical weapons both using Charisma.

**Comment by Fenris447** [comment]
Donezo. It now applies CHA to Pact weapons automatically. I also changed it to automatically apply the CHA bonus as optional. IE if your STR/DEX is higher, it will apply, without any need to switch the ability on and off. Just choose your weapon from the drop-down and you're good to go.
