### ISSUE TITLE
Class Features referencing other classes' spell list missing newer spells

### ISSUE THREAD

**Issue by BlackRose-XIII** [Sklore/HL_DD_5e_Colab#997]
I think this may only be the spells from Tasha's, but essentially things like Warlock's Mystic Arcanum or Arcana domains Arcane Mastery don't show all the spells that are available because the spells aren't on the appropriate class's spell list by default.

**Comment by Fenris447** [comment]
For the most part, I took this into account for the Class Feature Variants “Expanded Spell Lists” feature. But the next release will have classes added to all the Tasha’s spells, so this won’t be a problem any more anyway.
