### ISSUE TITLE
Fire elemental bonus to attack

### ISSUE THREAD

**Issue by Dragon5e** [Sklore/HL_DD_5e_Colab#998]
I posted in the forum but Fenris447 directed me to here. anyways the fire elemental need fixing. After looking at air elemental I decide to check on Fire. Well so far so good hey wait this Touch attack. As far as I can tell 5e do not have touch for ac. Seem to indicate range only. After looking at multiple sites https://www.dndbeyond.com/monsters/fire-elemental. The 2 bonus need to be removed. But hey I got an answer that attacks can be dex only so air elemental get that dex slams. This is the fire ele stats.

Touch. Melee Weapon Attack: +6 to hit, reach 5 ft., one target. Hit: 10 (2d6 + 3) fire damage. If the target is a creature or a flammable object, it ignites. Until a creature takes an action to douse the fire, the target takes 5 (1d10) fire damage at the start of each of its turns.

**Comment by Dragon5e** [comment]
[custom.txt](https://github.com/Sklore/HL_DD_5e_Colab/files/6683230/custom.txt)

**Comment by Fenris447** [comment]
Closing this issue as it will be addressed alongisde a bunch of other incorrect SRD monster stats. See #1029.
